from pathlib import Path
import json, hashlib, subprocess
from orchestration.adapter import codex_runtime as cr, config
base=Path('coordination/design/BATCH-c2a2b6'); task='TASK-20260908-ab0e84'; original=base/f'reviews/{task}/runtime-session-receipt.json'; result=json.loads(original.read_text()); body=result['runtime_session_receipt']; oldhash=hashlib.sha256(original.read_bytes()).hexdigest(); assert body['verification']['failures']==['state_row_missing']; assert body['launch']['exit_code']==0 and body['launch']['probe_output_matches'] and body['launch']['thread_started_event_count']==1
cfg=config.load(); resolution=cr._strict_resolution(cfg=cfg,policy='review-adversarial',role='validator',backend='openai',effort=None,independent_session=True); assert resolution.resolved_model_id=='gpt-5.6-sol' and resolution.reasoning_effort=='xhigh'; sid=body['identity']['independent_session_id']; db=Path('/Users/adamburan/.codex/state_5.sqlite'); row=cr._query_state_row(db,sid); rollout,rel=cr._resolve_rollout(db,row['rollout_path']); session,sh,turn,th=cr._parse_rollout(rollout)
cfg.assert_inference_target_allowed(row['model'],row['model_provider'],session.get('model_provider'),turn['model'],context='existing native session completion'); assert cr._sha256_file(Path(body['launch']['safe_argv'][0]))==body['runtime']['codex_binary_sha256']
start=cr._now(); proc=subprocess.run(['python3','tools/check_runtime_bindings.py'],capture_output=True,check=True); end=cr._now(); now=cr._now(); fail=cr._cross_checks(receipt=result,request_model=body['requested']['model'],request_effort=body['requested']['reasoning_effort'],request_workdir=Path(body['requested']['workdir']),thread_id=sid,thread_time=None,row=row,session=session,turn=turn,cli_version=body['runtime']['cli_version'],launch_start=cr._parse_timestamp(body['launch']['started_at']),launch_end=cr._parse_timestamp(body['launch']['ended_at']),binding_start=start,binding_end=end,recorded_at=now,expected_provider='openai'); assert not fail,fail
publicrow=dict(row); publicrow['rollout_path']=rel; body['observed'].update(state_row_allowlist=publicrow,state_row_sha256=cr._sha256_bytes(cr._canonical_json(row)),session_meta_sha256=sh,turn_context_sha256=th,rollout_relative_path=rel,rollout_path_sha256=cr._path_sha256(rollout)); body['runtime']['provider']=row['model_provider']; body['identity']['recorded_at']=cr._iso(now); body['verification'].update(status='verified',runtime_resolution_verified=True,failures=[],runtime_bindings_check={'exit_code':proc.returncode,'stdout_sha256':cr._sha256_bytes(proc.stdout),'stderr_sha256':cr._sha256_bytes(proc.stderr),'started_at':cr._iso(start),'ended_at':cr._iso(end)})
body['continuation']={'kind':'same_session_delayed_state_completion','original_receipt':str(original),'original_receipt_sha256':oldhash,'original_failure':'state_row_missing','new_model_session_launched':False,'same_session_id':sid,'procedure_deviation':'Initial CLI process succeeded but its SQLite row was not immediately visible. Re-polled only the same thread and completed strict policy, model, effort, provider, source, cwd, sandbox, identity, state/rollout timestamp and runtime-binding checks. Original failure receipt stays byte-identical.','timestamp_boundary':'The optional original thread.started timestamp is not retained in the saved receipt and is not reasserted. Actual state/session/turn timestamps passed the original launch interval checks.','script_sha256':hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),'verification_scope':'exact_existing_codex_session_only; no backend catalog or scientific validation'}
out=base/f'runtime-rechecks/{task}/completion.json'; out.parent.mkdir(parents=True,exist_ok=True); assert not out.exists(); assert cr._privacy_invariant(result,state_db=db,receipt_path=out,rollout_path=rollout); cr._write_exclusive(out,result); assert hashlib.sha256(original.read_bytes()).hexdigest()==oldhash
print(json.dumps({'completion_receipt':str(out),'session_id':sid,'model':row['model'],'effort':row['reasoning_effort'],'provider':row['model_provider'],'all_metadata_checks':True,'runtime_bindings_pass':True}))
