"""Subgroup membership and cofactor clearing from the O-module structure of E(F_q).

Setting.  E/F_q ordinary, #E(F_q) = h*r with r prime, r not dividing h, G the
subgroup of order r.  The handed-in theorem is Lenstra's ("Complex
multiplication structure of elliptic curves", J. Number Theory 56 (1996)):
if End(E) = O then E(F_q) is isomorphic to O/(pi - 1)O as an O-module, pi
the Frobenius.  It is used here as a hypothesis and checked on points (every
prediction below is tested against [r]Q and [h]Q, and the size of
E(F_q)[ell] it predicts for each small ell | h is compared with an exact
count of rational ell-torsion points from the ell-division polynomial).

What follows from it, with I = (pi - 1)O = rr * J, rr the prime of norm r
that contains pi - 1 and J the cofactor part (rr + J = O since r does not
divide h):

* for any beta in O, multiplication by beta on O/I has kernel of order
  [O : beta*O + I] (Dedekind domain: |ker| = |O/I| / |image| and the image
  is (beta*O + I)/I).  ``element_index`` computes that index exactly as the
  gcd of the 2x2 minors of {beta, beta*omega, pi-1, (pi-1)*omega};
* **membership.**  If beta is in rr and [O : beta*O + I] = r then ker(beta)
  on E(F_q) is exactly G (it contains G and has r elements), so Q in G iff
  beta(Q) = O.  The only ideal between I and O of index r is rr (an ideal of
  norm r dividing rr*J with r not dividing N(J)), so the index condition is
  both necessary and sufficient; ``gcd(N(beta)/r, h) = 1`` is a sufficient
  shortcut for it, not a necessary one;
* **cofactor clearing.**  If [O : beta*O + I] = h then beta*O + I = J (again
  the only ideal of that index between I and O), so beta(E(F_q)) =
  J/I, which is the r-torsion G: beta maps E(F_q) ONTO G and its fibres are
  cosets of ker(beta).  On G it acts as the scalar c = beta mod rr, so
  beta(Q) = [c/h mod r]([h]Q) for every Q in E(F_q);
* the least positive rational integer in J is the exponent of the cofactor
  group O/J, i.e. the smallest integer "effective cofactor".

Short elements are found by LLL (``lattice.lll``) on the Z-bases of rr (the
GLV relation lattice {(c0, c1) : c0 + c1*lambda = 0 mod r}) and of J (from
(pi - 1) * conj(rr) / r), in coordinates c0 + c1*alpha with alpha the cheap
endomorphism actually evaluated (a unit, or a chain built by ``explicit``).
Costs are the cross-curve sweep's formula counts (``curvesweep``: the curve's
own doubling, add-2007-bl/madd-2007-bl, interleaved width-w NAF, the
optimised chain evaluator) applied to the exact digits of the fixed scalars:
**modelled**, not timed.

    python -m harness.endosweep.subgroup --out-dir research/endosweep_subgroup_20261008
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import random
import time
from dataclasses import dataclass, field
from math import gcd, isqrt, log2

from . import chainsweep as CS
from . import curvesweep as CV
from . import explicit as EX
from . import lattice as LA
from . import quadorder as QO
from .toyverify import Composite, Curve, Isomorphism, prime_nth_roots

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
ARKWORKS_JSON = os.path.join(ROOT, "research", "endosweep_curves_20261006", "arkworks", "curves.json")
INPUTS_JSON = os.path.join(ROOT, "research", "endosweep_subgroup_20261008", "inputs.json")

# BLS12-381 G1 endomorphism constant and parameter, transcribed from
# arkworks-rs/curves@e2d16a27 bls12_381/src/curves/g1.rs (sha256 3e22b089...,
# the hash recorded in research/endosweep_curves_20261006/arkworks/curves.json):
# "endomorphism_p(x,y) = (BETA * x, y)", and from bls12_381/src/curves/mod.rs:
# X = 0xd201000000010000, X_IS_NEGATIVE = true.
BLS12_381_BETA = 793479390729215512621379701633421447060886740281060493010456487427281649075476305620758731620350
BLS12_381_U = -0xd201000000010000


# ---------------------------------------------------------------------------
# exact algebra in O = Z[omega]
# ---------------------------------------------------------------------------

def element_index(D: int, gens) -> int:
    """[O : sum g*O] for elements g = (a, b) = a + b*omega (0 if not full rank).

    The ideal generated by the g is the Z-span of {g, g*omega}; its index in
    Z^2 is the gcd of all 2x2 minors of those vectors.
    """
    vecs = []
    for g in gens:
        vecs.append(tuple(g))
        vecs.append(QO.multiply(D, tuple(g), (0, 1)))
    det = 0
    for i in range(len(vecs)):
        for j in range(i + 1, len(vecs)):
            det = gcd(det, vecs[i][0] * vecs[j][1] - vecs[i][1] * vecs[j][0])
    return det


def kernel_order(D: int, beta, pim1) -> int:
    """|ker beta| on E(F_q) = O/(pi - 1), by Lenstra's module structure."""
    return element_index(D, [beta, pim1])


def frobenius_element(D: int, q: int, t: int, f: int, lam_omega: int, r: int) -> tuple[int, int]:
    """pi = (t - f*tau)/2 +- f*omega, the sign that acts as 1 on G (where omega acts as lam_omega)."""
    tau = D % 2
    out = []
    for s in (f, -f):
        if (t - s * tau) % 2:
            continue
        a, b = (t - s * tau) // 2, s
        assert QO.norm(D, a, b) == q and QO.trace(D, a, b) == t
        if (a - 1 + b * lam_omega) % r == 0:
            out.append((a, b))
    if len(out) != 1:
        raise ValueError(f"Frobenius sign not pinned by the action on G ({len(out)} candidates)")
    return out[0]


def smith_invariants(basis) -> tuple[int, int]:
    """(d1, d2), d1 | d2, with Z^2 / span(basis) = Z/d1 x Z/d2."""
    (a, b), (c, d) = basis
    d1 = gcd(gcd(a, b), gcd(c, d))
    det = abs(a * d - b * c)
    return d1, det // d1


@dataclass
class Alpha:
    """The evaluated endomorphism alpha = s + b*omega (b = +-1), acting on G as lam."""
    s: int
    b: int
    lam: int
    cost: dict                       # {"M", "S", "M_eq"} of one evaluation
    label: str

    def to_omega(self, c0: int, c1: int) -> tuple[int, int]:
        return c0 + c1 * self.s, c1 * self.b

    def from_omega(self, a: int, b: int) -> tuple[int, int]:
        if b % self.b:
            raise ValueError("not in Z[alpha]")
        c1 = b // self.b
        return a - c1 * self.s, c1


@dataclass
class ModuleStructure:
    D: int
    q: int
    r: int
    h: int
    t: int
    f: int
    lam_omega: int
    pi: tuple[int, int]
    rr_basis: list[list[int]]          # LLL-reduced, alpha coordinates
    J_basis: list[list[int]]           # LLL-reduced, alpha coordinates
    cofactor_invariants: tuple[int, int]
    effective_cofactor: int            # least positive integer in J
    checks: dict = field(default_factory=dict)

    @property
    def pim1(self) -> tuple[int, int]:
        return self.pi[0] - 1, self.pi[1]


def module_structure(D: int, q: int, r: int, h: int, alpha: Alpha) -> ModuleStructure:
    t = q + 1 - h * r
    Dfrob = t * t - 4 * q
    if Dfrob % D:
        raise ValueError("t^2 - 4q is not a multiple of D")
    f2 = Dfrob // D
    f = isqrt(f2)
    if f * f != f2:
        raise ValueError("t^2 - 4q is not D times a square")
    if h % r == 0:
        raise ValueError("r divides h: the r-part is not O/rr")
    lam_omega = (alpha.lam - alpha.s) * alpha.b % r          # b = +-1
    tau, nw = QO.omega_trace_norm(D)
    assert (lam_omega * lam_omega - tau * lam_omega + nw) % r == 0, "lambda is not an eigenvalue of omega"
    pi = frobenius_element(D, q, t, f, lam_omega, r)
    pim1 = (pi[0] - 1, pi[1])
    # rr = r*O + (omega - lam_omega)*O; J = (pi - 1) * conj(rr) / r
    rr_w = [(r, 0), ((-lam_omega) % r, 1)]
    assert element_index(D, rr_w) == r
    J_w = []
    for g in rr_w:
        x = QO.multiply(D, pim1, QO.conjugate(D, *g))
        assert x[0] % r == 0 and x[1] % r == 0
        J_w.append((x[0] // r, x[1] // r))
    assert element_index(D, J_w) == h, "J does not have index h"
    assert element_index(D, J_w + [pim1]) == h, "pi - 1 is not in J"
    rr_a = LA.lll([list(alpha.from_omega(*g)) for g in rr_w])
    J_a = LA.lll([list(alpha.from_omega(*g)) for g in J_w])
    rr_a.sort(key=LA.l2_norm_sq)
    J_a.sort(key=LA.l2_norm_sq)
    inv = smith_invariants(J_w)
    # least positive integer in J: the generator of J cap Z = the exponent of O/J
    (a1, b1), (a2, b2) = J_w
    eff = abs(a1 * b2 - a2 * b1) // gcd(b1, b2)
    assert inv[1] == eff
    return ModuleStructure(D, q, r, h, t, f, lam_omega, pi, rr_a, J_a, inv, eff)


@dataclass
class Candidate:
    c0: int
    c1: int
    kernel: int                         # |ker| on E(F_q), Lenstra
    norm: int
    height_bits: int
    eigenvalue: int                     # action on G
    gcd_shortcut: bool                  # gcd(N/r, h) = 1 (membership) / N in the clearing sense


def short_elements(M: ModuleStructure, alpha: Alpha, which: str, *, box: int = 4) -> list[Candidate]:
    """Every c1*b1 + c2*b2 (|c_i| <= box) of the reduced basis that is a valid test.

    ``which = "membership"``: in rr with |ker| = r.  ``which = "clearing"``:
    |ker| = h, i.e. beta*O + (pi - 1) = J, so beta maps E(F_q) onto G.
    Sorted by height (max |c0|, |c1|) in alpha coordinates.
    """
    basis = M.rr_basis if which == "membership" else M.J_basis
    want = M.r if which == "membership" else M.h
    seen, out = set(), []
    for i in range(-box, box + 1):
        for j in range(-box, box + 1):
            c0 = i * basis[0][0] + j * basis[1][0]
            c1 = i * basis[0][1] + j * basis[1][1]
            if (c0, c1) == (0, 0) or (-c0, -c1) in seen:
                continue
            seen.add((c0, c1))
            w = alpha.to_omega(c0, c1)
            k = kernel_order(M.D, w, M.pim1)
            if k != want:
                continue
            N = QO.norm(M.D, *w)
            if which == "membership":
                sc = N % M.r == 0 and gcd(N // M.r, M.h) == 1
            else:
                sc = gcd(N, M.r) == 1
            out.append(Candidate(c0, c1, k, N, max(abs(c0), abs(c1)).bit_length(),
                                 (c0 + c1 * alpha.lam) % M.r, sc))
    out.sort(key=lambda c: (max(abs(c.c0), abs(c.c1)), abs(c.c0) + abs(c.c1)))
    return out


# ---------------------------------------------------------------------------
# operation counts (curvesweep's formulas on fixed scalars)
# ---------------------------------------------------------------------------

def scalar_ops(ar: CV.Arith, k: int, widths=(2, 3, 4, 5, 6, 7)) -> dict:
    """Best width-w NAF [k]Q, M_eq = M + S, over widths and affine/Jacobian tables."""
    k = abs(k)
    best = None
    for table in ("affine", "jacobian"):
        for w in widths:
            if k == 0:
                continue
            M, S = CV.baseline_ops(ar, k, w, table)
            if best is None or M + S < best["M_eq"]:
                best = {"M": M, "S": S, "M_eq": M + S, "w": w, "table": table, "bits": k.bit_length()}
    return best or {"M": 0, "S": 0, "M_eq": 0, "w": None, "table": None, "bits": 0}


def msm_ops(ar: CV.Arith, c0: int, c1: int, chain: dict, widths=(2, 3, 4, 5, 6, 7)) -> dict:
    """[c0]Q + [c1]alpha(Q): interleaved width-w NAF with two tables plus one alpha evaluation."""
    if c1 == 0:
        return scalar_ops(ar, c0, widths)
    if c0 == 0:
        s = scalar_ops(ar, c1, widths)
        return {**s, "M": s["M"] + chain["M"], "S": s["S"] + chain["S"],
                "M_eq": s["M_eq"] + chain["M_eq"]}
    best = None
    for table in ("affine", "jacobian"):
        for w in widths:
            M, S = CV.glv_ops(ar, c0, c1, w, table, chain)
            if best is None or M + S < best["M_eq"]:
                best = {"M": M, "S": S, "M_eq": M + S, "w": w, "table": table,
                        "bits": max(abs(c0), abs(c1)).bit_length()}
    return best


def legendre_ops(p: int) -> dict:
    """A Legendre symbol by Fermat exponentiation to (p-1)/2 (square-and-multiply)."""
    e = (p - 1) // 2
    S, M = e.bit_length() - 1, bin(e).count("1") - 1
    return {"M": M, "S": S, "M_eq": M + S}


# ---------------------------------------------------------------------------
# endomorphisms on points
# ---------------------------------------------------------------------------

def chain_map(E: Curve, res: EX.ChainResult):
    """The built chain as a callable on F_q-points (None = the point at infinity)."""
    maps, cur = [], E
    for ell, hp in zip(res.steps, res.kernel_polys):
        iso = EX.KernelIsogeny(cur, hp, ell)
        maps.append(iso)
        cur = iso.codomain
    back = Isomorphism(cur, res.isomorphism_u)
    if (back.codomain.a, back.codomain.b) != (E.a, E.b):
        raise AssertionError("the isomorphism does not return to E")
    maps.append(back)
    return Composite(maps)


def unit_map_j0(E: Curve, beta: int):
    p = E.p
    return lambda P: None if P is None else (beta * P[0] % p, P[1])


def apply_element(E: Curve, phi, c0: int, c1: int, Q):
    return E.add(E.mul(c0, Q), E.mul(c1, phi(Q)) if c1 else None)


def random_point(E: Curve, rng: random.Random):
    while True:
        x = rng.randrange(E.p)
        rhs = (x * x * x + E.a * x + E.b) % E.p
        if rhs == 0:
            return (x, 0)
        ys = prime_nth_roots(rhs, 2, E.p)
        if ys:
            return (x, ys[rng.randrange(len(ys))])


def check_on_points(E: Curve, phi, r: int, h: int, mem: Candidate, clr: Candidate, eff: int,
                    *, npoints: int, nother: int, small_primes, seed: int) -> dict:
    """Both tests against the definition, on random and constructed points.

    Truth: Q in G iff [r]Q = O.  Clearing: beta(Q) = [c/h]([h]Q) with c the
    action of beta on G; since [h]Q is always in G and c/h is a unit mod r,
    this says beta(Q) is in G and is O exactly when Q has no G-component.
    The integer effective cofactor gets the same check.
    """
    rng = random.Random(seed)
    N = h * r
    assert clr.eigenvalue % r and eff % r, "a clearing map must be nonzero on G"
    ratio = clr.eigenvalue * pow(h, -1, r) % r
    eratio = eff * pow(h, -1, r) % r
    stats: dict[str, dict] = {}

    def record(kind, Q, full):
        s = stats.setdefault(kind, {"points": 0, "members": 0, "membership_errors": 0,
                                    "clearing_errors": 0, "effective_cofactor_errors": 0})
        s["points"] += 1
        truth = E.mul(r, Q) is None
        s["members"] += int(truth)
        if (apply_element(E, phi, mem.c0, mem.c1, Q) is None) != truth:
            s["membership_errors"] += 1
        if full:
            hQ = E.mul(h, Q)
            # [h]Q lies in G for every Q, so R = [c/h]([h]Q) with c/h != 0 mod r
            # says at once that R is in G and that R = O iff [h]Q = O.
            R = apply_element(E, phi, clr.c0, clr.c1, Q)
            s["clearing_errors"] += int(R != E.mul(ratio, hQ))
            Re = E.mul(eff, Q)
            s["effective_cofactor_errors"] += int(Re != E.mul(eratio, hQ))

    for _ in range(npoints):
        record("random", random_point(E, rng), True)
    for _ in range(nother):
        record("member [h]R", E.mul(h, random_point(E, rng)), True)
    for _ in range(nother):
        record("cofactor-only [r]R", E.mul(r, random_point(E, rng)), True)
    for _ in range(nother):
        A = E.mul(h, random_point(E, rng))
        B = E.mul(r, random_point(E, rng))
        record("mixed [h]R + [r]S", E.add(A, B), True)
    for ell in small_primes:
        v, m = 0, N
        while m % ell == 0:
            v, m = v + 1, m // ell
        found = 0
        for _ in range(64):
            T = E.mul(m, random_point(E, rng))            # the ell-Sylow component
            while T is not None and E.mul(ell, T) is not None:
                T = E.mul(ell, T)                           # down to order ell
            if T is not None:
                record(f"order {ell}", T, True)
                found += 1
                if found == 3:
                    break
    record("identity", None, True)
    total = {k: sum(s[k] for s in stats.values())
             for k in ("points", "members", "membership_errors", "clearing_errors", "effective_cofactor_errors")}
    return {"by_kind": stats, "total": total}


def torsion_count_check(E: Curve, D: int, pim1, ell: int) -> dict:
    """#E(F_q)[ell] from the ell-division polynomial vs [O : ell*O + (pi - 1)O]."""
    import flint  # type: ignore
    p = E.p
    ctx = flint.fmpz_mod_poly_ctx(p)
    if ell == 2:
        roots = ctx([E.b % p, E.a % p, 0, 1]).roots()
        count = 1 + len(roots)
    else:
        f = EX.division_polynomials_flint(p, E.a, E.b, ell)[ell]
        count = 1
        for x, _ in ctx(f).roots():
            x = int(x)
            rhs = (x ** 3 + E.a * x + E.b) % p
            if rhs == 0 or pow(rhs, (p - 1) // 2, p) == 1:
                count += 1 if rhs == 0 else 2
    pred = element_index(D, [(ell, 0), pim1])
    return {"ell": ell, "counted": count, "predicted": pred, "agree": count == pred}


# ---------------------------------------------------------------------------
# one curve
# ---------------------------------------------------------------------------

def trial_primes(h: int, bound: int = 1 << 16) -> list[int]:
    out, m, d = [], h, 2
    while d < bound and d * d <= m:
        if m % d == 0:
            out.append(d)
            while m % d == 0:
                m //= d
        d += 1
    if 1 < m < bound:
        out.append(m)
    return out


def analyse(name: str, E: Curve, r: int, h: int, D: int, alpha: Alpha, phi, *,
            npoints: int, nother: int, seed: int, box: int = 4) -> dict:
    t0 = time.time()
    M = module_structure(D, E.p, r, h, alpha)
    ar = CV.arithmetic(E.p, E.a)
    mem_all = short_elements(M, alpha, "membership", box=box)
    clr_all = short_elements(M, alpha, "clearing", box=box)
    if not mem_all or not clr_all:
        raise RuntimeError("no valid element in the search box")

    def costed(c: Candidate) -> dict:
        ops = msm_ops(ar, c.c0, c.c1, alpha.cost)
        return {"c0": str(c.c0), "c1": str(c.c1), "height_bits": c.height_bits, "norm": str(c.norm),
                "kernel_order_on_E(F_q)": str(c.kernel), "eigenvalue_on_G": hex(c.eigenvalue),
                "gcd_shortcut_holds": c.gcd_shortcut, "ops": ops}

    mem = min(mem_all[:12], key=lambda c: msm_ops(ar, c.c0, c.c1, alpha.cost)["M_eq"])
    clr = min(clr_all[:12], key=lambda c: msm_ops(ar, c.c0, c.c1, alpha.cost)["M_eq"])
    small = trial_primes(h)
    pts = check_on_points(E, phi, r, h, mem, clr, M.effective_cofactor, npoints=npoints, nother=nother,
                          small_primes=small, seed=seed)
    tors = [torsion_count_check(E, D, M.pim1, ell) for ell in small if ell <= 64]
    base_r = scalar_ops(ar, r)
    base_h = scalar_ops(ar, h)
    eff_ops = scalar_ops(ar, M.effective_cofactor)
    mem_ops = msm_ops(ar, mem.c0, mem.c1, alpha.cost)
    clr_ops = msm_ops(ar, clr.c0, clr.c1, alpha.cost)
    half_r, half_h = log2(r) / 2, log2(h) / 2
    return {
        "curve": name, "p_bits": E.p.bit_length(), "r": hex(r), "r_bits": r.bit_length(), "h": hex(h),
        "h_bits": h.bit_length(), "D": D, "conductor_f": hex(M.f), "trace": hex(M.t),
        "arithmetic": ar.note, "alpha": {"label": alpha.label, "s": alpha.s, "b": alpha.b,
                                         "eigenvalue_on_G": hex(alpha.lam), "cost": alpha.cost},
        "frobenius_in_O": [str(M.pi[0]), str(M.pi[1])],
        "cofactor_group_invariants": [str(x) for x in M.cofactor_invariants],
        "effective_cofactor": hex(M.effective_cofactor),
        "effective_cofactor_bits": M.effective_cofactor.bit_length(),
        "small_primes_of_h": small,
        "torsion_checks": tors,
        "rr_basis_bits": [max(abs(x) for x in v).bit_length() for v in M.rr_basis],
        "J_basis_bits": [max(abs(x) for x in v).bit_length() for v in M.J_basis],
        "membership": {"chosen": costed(mem), "valid_in_box": len(mem_all),
                       "half_bits": round(half_r, 2), "excess_bits": round(mem.height_bits - half_r, 2),
                       "shortest_valid": costed(mem_all[0])},
        "clearing": {"chosen": costed(clr), "valid_in_box": len(clr_all),
                     "half_bits": round(half_h, 2), "excess_bits": round(clr.height_bits - half_h, 2),
                     "shortest_valid": costed(clr_all[0]),
                     "relation_to_h": f"beta(Q) = [{hex(clr.eigenvalue * pow(h, -1, r) % r)}]([h]Q)"},
        "costs_M_eq": {
            "[r]Q": base_r, "beta_membership": mem_ops,
            "[h]Q": base_h, "[effective cofactor]Q": eff_ops, "beta_clearing": clr_ops,
            "ratio_membership": round(base_r["M_eq"] / mem_ops["M_eq"], 3),
            "ratio_clearing_vs_h": round(base_h["M_eq"] / clr_ops["M_eq"], 3),
            "ratio_clearing_vs_effective": round(eff_ops["M_eq"] / clr_ops["M_eq"], 3),
        },
        "points": pts,
        "elapsed_s": round(time.time() - t0, 1),
    }


# ---------------------------------------------------------------------------
# curves
# ---------------------------------------------------------------------------

def _arkworks(name: str, path: str = ARKWORKS_JSON) -> dict:
    with open(path) as fh:
        d = json.load(fh)
    c = next(c for c in d["curves"] if c["name"] == name)
    return {"p": int(c["field"]["p"], 16), "a": int(c["params"]["a"]["raw"], 16),
            "b": int(c["params"]["b"]["raw"], 16), "n": int(c["order"], 16), "h": int(c["cofactor"], 16)}


def j0_unit(E: Curve, r: int, beta: int, P) -> Alpha:
    """phi(x, y) = (beta x, y) as an element of Z[omega] (omega = zeta_6): phi = omega - 1."""
    lam = next(l for l in ((-1 + s) * pow(2, -1, r) % r for s in _sqrts(-3, r))
               if E.mul(l, P) == (beta * P[0] % E.p, P[1]))
    return Alpha(-1, 1, lam, CV.chain_ops((), "optimised"), "zeta_3: (x, y) -> (beta x, y)")


def _sqrts(a: int, n: int) -> list[int]:
    from sympy.ntheory import sqrt_mod
    s = sqrt_mod(a % n, n)
    return [s, (-s) % n]


def chain_alpha(E: Curve, r: int, h: int, D: int, element, order, label: str):
    root = QO.omega_eigenvalues(D, r)[0]
    res = EX.build_chain_endomorphism(E.p, E.a, E.b, r, h, D, tuple(element), steps=list(order),
                                      conjugates=False, omega_root=root)
    if not res.found:
        raise RuntimeError(f"{label}: chain not built: {res.note}")
    s, b = res.matched_element
    if abs(b) != 1:
        raise RuntimeError("alpha must be s +- omega for Z[alpha] = O")
    ops = CV.chain_ops(tuple(order), "optimised")
    return Alpha(s, b, res.eigenvalue, ops, label), chain_map(E, res), res


def bls12_381_control(npoints: int, nother: int, seed: int) -> dict:
    c = _arkworks("bls12_381")
    E = Curve(c["p"], c["a"], c["b"])
    P = EX.point_of_order(E, c["n"], c["h"], 3)
    alpha = j0_unit(E, c["n"], BLS12_381_BETA, P)
    phi = unit_map_j0(E, BLS12_381_BETA)
    out = analyse("BLS12-381 G1", E, c["n"], c["h"], -3, alpha, phi, npoints=npoints, nother=nother, seed=seed)
    M = module_structure(-3, c["p"], c["n"], c["h"], alpha)
    out["control"] = control_summary(M, alpha, out, BLS12_381_U)
    return out


def control_summary(M: ModuleStructure, alpha: Alpha, out: dict, u: int) -> dict:
    """Compare what the module derivation found with the known BLS12 identities.

    Known (arkworks bls12_381 g1.rs at the pinned commit, quoting ePrint
    2021/1130 Section 6 and ePrint 2019/403 Section 5): G1 membership is
    "endomorphism_p(P) == -[X^2]P" and cofactor clearing multiplies by 1 - X.
    """
    r, D = M.r, M.D
    J_w = [alpha.to_omega(*v) for v in M.J_basis]
    rr_w = [alpha.to_omega(*v) for v in M.rr_basis]
    beta = alpha.to_omega(u * u, 1)                      # u^2 + phi
    mem = out["membership"]["chosen"]
    short = out["membership"]["shortest_valid"]
    sw = alpha.to_omega(int(short["c0"]), int(short["c1"]))
    return {
        "phi_eigenvalue_is_minus_u2": alpha.lam == (-u * u) % r,
        "r_equals_u4_minus_u2_plus_1": r == u ** 4 - u ** 2 + 1,
        "h_equals_(u-1)^2/3": M.h == (u - 1) ** 2 // 3,
        "u2_plus_phi_in_rr": element_index(D, rr_w + [beta]) == r,
        "norm_of_u2_plus_phi_equals_r": QO.norm(D, *beta) == r,
        "kernel_of_u2_plus_phi_on_E(F_p)": str(kernel_order(D, beta, M.pim1)),
        "cheapest_valid_membership_element": [mem["c0"], mem["c1"]],
        "cheapest_is_+-(u2_plus_phi)": (int(mem["c0"]), int(mem["c1"])) in ((u * u, 1), (-u * u, -1)),
        "shortest_by_height_valid_element": [short["c0"], short["c1"]],
        "shortest_is_a_unit_multiple_of_u2_plus_phi": QO.norm(D, *sw) == r and any(
            QO.multiply(D, beta, w) in (sw, (-sw[0], -sw[1])) for w in QO.units(D)),
        "1_minus_u_in_J": element_index(D, J_w + [(1 - u, 0)]) == M.h,
        "1_minus_u_not_in_rr": (1 - u) % r != 0,
        "effective_cofactor_equals_|1-u|": M.effective_cofactor == abs(1 - u),
        "cofactor_group": f"Z/{M.cofactor_invariants[0]} x Z/{M.cofactor_invariants[1]}",
    }


def residue_test_bandersnatch(E: Curve, r: int, h: int, D: int, pim1, nonmembers: int, seed: int) -> dict:
    """Q in G iff Q in 2E(F_p) when E(F_p)[2^oo] = Z/2 x Z/2: two Legendre symbols."""
    import flint  # type: ignore
    p = E.p
    two = element_index(D, [(2, 0), pim1])
    four = element_index(D, [(4, 0), pim1])
    out = {"#E(F_p)[2] predicted": two, "#E(F_p)[4] predicted": four}
    roots = sorted(int(x) for x, _ in flint.fmpz_mod_poly_ctx(p)([E.b % p, E.a % p, 0, 1]).roots())
    out["rational_2_torsion_roots"] = len(roots)
    if not (h == 4 and two == 4 and len(roots) == 3):
        out["applicable"] = False
        return out
    out["applicable"] = True
    e1, e2 = roots[0], roots[1]

    def qr(z):
        return z % p != 0 and pow(z, (p - 1) // 2, p) == 1

    def residue_member(Q):
        if Q is None:
            return True
        if Q[1] == 0:
            return False
        return qr(Q[0] - e1) and qr(Q[0] - e2)

    rng = random.Random(seed)
    errs = pts = mem = 0
    for i in range(nonmembers):
        R = random_point(E, rng)
        for Q in (R, E.mul(h, R), E.mul(r, R), E.add(E.mul(h, R), E.mul(r, random_point(E, rng)))):
            truth = E.mul(r, Q) is None
            pts += 1
            mem += int(truth)
            errs += int(residue_member(Q) != truth)
    out.update({"points": pts, "members": mem, "errors": errs, "ops": {
        "two_legendre_symbols": {k: 2 * v for k, v in legendre_ops(p).items()}}})
    return out


def run(*, npoints: int = 1000, nother: int = 200, seed: int = 20261008, inputs: str = INPUTS_JSON,
        progress=print) -> dict:
    results = {}
    progress("BLS12-381 G1 (positive control)")
    results["BLS12-381 G1"] = bls12_381_control(npoints=max(npoints // 4, 50), nother=max(nother // 4, 20), seed=seed)

    progress("CP6-782 G1: building 4 + omega as 7.3.5")
    c = _arkworks("cp6_782")
    E = Curve(c["p"], c["a"], c["b"])
    alpha, phi, res = chain_alpha(E, c["n"], c["h"], -339, (4, 1), (7, 3, 5), "4 + omega as 7.3.5 (chain)")
    results["CP6-782 G1"] = analyse("CP6-782 G1", E, c["n"], c["h"], -339, alpha, phi,
                                    npoints=npoints, nother=nother, seed=seed)

    progress("Bandersnatch: building sqrt(-2) as one 2-isogeny")
    c = _arkworks("ed_on_bls12_381_bandersnatch")
    E = Curve(c["p"], c["a"], c["b"])
    alpha, phi, res = chain_alpha(E, c["n"], c["h"], -8, (0, 1), (2,), "sqrt(-2) as one 2-isogeny (chain)")
    out = analyse("Bandersnatch (short Weierstrass model)", E, c["n"], c["h"], -8, alpha, phi,
                  npoints=max(npoints // 4, 50), nother=max(nother // 4, 20), seed=seed)
    M = module_structure(-8, E.p, c["n"], c["h"], alpha)
    out["residue_test"] = residue_test_bandersnatch(E, c["n"], c["h"], -8, M.pim1, 50, seed)
    results["Bandersnatch"] = out

    with open(inputs) as fh:
        inp = json.load(fh)
    m = inp["curves"]["mnt1"]
    progress("mnt1: building omega as one 5-isogeny")
    E = Curve(int(m["p"], 16), int(m["a"], 16) % int(m["p"], 16), int(m["b"], 16))
    n, h = int(m["n"], 16), int(m["h"], 16)
    alpha, phi, res = chain_alpha(E, n, h, -19, (0, 1), (5,), "omega as one 5-isogeny (chain)")
    results["mnt1"] = analyse("mnt1", E, n, h, -19, alpha, phi, npoints=max(npoints // 4, 50),
                              nother=max(nother // 4, 20), seed=seed)
    return {"results": results, "chain_curve_cofactors": inp["chain_curve_cofactors"],
            "inputs_sources": inp["sources"], "npoints": npoints, "nother": nother, "seed": seed}


# ---------------------------------------------------------------------------
# report
# ---------------------------------------------------------------------------

def _fmt(x) -> str:
    return f"{x:,}".replace(",", " ") if isinstance(x, int) else str(x)


def markdown(out: dict) -> str:
    R = out["results"]
    L = ["# Subgroup membership and cofactor clearing from the O-module structure of E(F_q)", "",
         "Generated by `python -m harness.endosweep.subgroup`.  Costs are **modelled** (curvesweep's formula "
         "counts on the exact width-w NAF digits of the fixed scalars, best width and table, M_eq = M + S); "
         "correctness is **measured** on points.", ""]
    L += ["## Costs (M_eq, modelled)", "",
          "| curve | h bits | [r]Q | beta membership (bits) | ratio | [h]Q | [e]Q, e = exponent of cofactor group (bits) | beta clearing (bits) | ratio vs [h] | ratio vs [e] |",
          "|:--|--:|--:|:--|--:|--:|:--|:--|--:|--:|"]
    for name, o in R.items():
        c = o["costs_M_eq"]
        mem, clr = o["membership"]["chosen"], o["clearing"]["chosen"]
        L.append(f"| {name} | {o['h_bits']} | {c['[r]Q']['M_eq']} | {c['beta_membership']['M_eq']} ({mem['height_bits']}) | "
                 f"{c['ratio_membership']} | {c['[h]Q']['M_eq']} | "
                 f"{c['[effective cofactor]Q']['M_eq']} ({o['effective_cofactor_bits']}) | {c['beta_clearing']['M_eq']} "
                 f"({clr['height_bits']}) | {c['ratio_clearing_vs_h']} | {c['ratio_clearing_vs_effective']} |")
    L += ["", "## Short elements (LLL)", "",
          "| curve | alpha | log2(r)/2 | membership beta = c0 + c1 alpha | bits | excess | log2(h)/2 | clearing beta | bits | excess |",
          "|:--|:--|--:|:--|--:|--:|--:|:--|--:|--:|"]
    for name, o in R.items():
        m, c = o["membership"], o["clearing"]
        L.append(f"| {name} | {o['alpha']['label']} | {m['half_bits']} | {m['chosen']['c0']} + {m['chosen']['c1']} alpha | "
                 f"{m['chosen']['height_bits']} | {m['excess_bits']} | {c['half_bits']} | {c['chosen']['c0']} + "
                 f"{c['chosen']['c1']} alpha | {c['chosen']['height_bits']} | {c['excess_bits']} |")
    L += ["", "## Checks on points (measured)", "",
          "| curve | kind | points | members | membership errors | clearing errors | effective-cofactor errors |",
          "|:--|:--|--:|--:|--:|--:|--:|"]
    for name, o in R.items():
        for kind, s in o["points"]["by_kind"].items():
            L.append(f"| {name} | {kind} | {s['points']} | {s['members']} | {s['membership_errors']} | "
                     f"{s['clearing_errors']} | {s['effective_cofactor_errors']} |")
    L += ["", "## Module predictions vs counted torsion", "",
          "| curve | ell | #E(F_q)[ell] counted (division polynomial) | [O : ell O + (pi-1) O] | agree |",
          "|:--|--:|--:|--:|:--|"]
    for name, o in R.items():
        for t in o["torsion_checks"]:
            L.append(f"| {name} | {t['ell']} | {t['counted']} | {t['predicted']} | {t['agree']} |")
    L += ["", "## Structure", ""]
    for name, o in R.items():
        inv = o["cofactor_group_invariants"]
        L.append(f"* **{name}**: D = {o['D']}, cofactor group O/J = Z/{inv[0]} x Z/{inv[1]}; "
                 f"clearing relation {o['clearing']['relation_to_h']}; small primes of h: {o['small_primes_of_h']}.")
    ctl = R["BLS12-381 G1"].get("control")
    if ctl:
        L += ["", "## BLS12-381 positive control", ""]
        for k, v in ctl.items():
            L.append(f"* `{k}`: {v}")
    b = R.get("Bandersnatch", {}).get("residue_test")
    if b:
        L += ["", "## Bandersnatch residue test", ""]
        for k, v in b.items():
            L.append(f"* `{k}`: {v}")
    L += ["", "## Cofactors of the 17 chain curves", "", "| curve | h | h bits |", "|:--|--:|--:|"]
    for name, hh in out["chain_curve_cofactors"].items():
        L.append(f"| {name} | {hh if int(hh, 16) < 1 << 64 else hh[:18] + '...'} | {int(hh, 16).bit_length()} |")
    return "\n".join(L) + "\n"


def sha256_file(path: str) -> str:
    with open(path, "rb") as fh:
        return hashlib.sha256(fh.read()).hexdigest()


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="membership tests and cofactor clearing from the O-module structure")
    ap.add_argument("--out-dir", required=True)
    ap.add_argument("--points", type=int, default=1000)
    ap.add_argument("--other", type=int, default=200)
    ap.add_argument("--seed", type=int, default=20261008)
    ap.add_argument("--inputs", default=INPUTS_JSON)
    args = ap.parse_args(argv)
    t0 = time.time()
    out = run(npoints=args.points, nother=args.other, seed=args.seed, inputs=args.inputs)
    try:
        import flint  # type: ignore
        fl = flint.__version__
    except ImportError:
        fl = None
    out["provenance"] = {"python_flint": fl, "arkworks_json_sha256": sha256_file(ARKWORKS_JSON),
                         "inputs_json_sha256": sha256_file(args.inputs), "elapsed_s": round(time.time() - t0, 1)}
    os.makedirs(args.out_dir, exist_ok=True)
    jp = os.path.join(args.out_dir, "subgroup.json")
    with open(jp, "w") as fh:
        json.dump(out, fh, indent=1, sort_keys=False)
        fh.write("\n")
    with open(os.path.join(args.out_dir, "subgroup.md"), "w") as fh:
        fh.write(markdown(out))
    with open(os.path.join(args.out_dir, "SHA256SUMS"), "w") as fh:
        for name in ("inputs.json", "subgroup.json"):
            fp = os.path.join(args.out_dir, name)
            if os.path.exists(fp):
                fh.write(f"{sha256_file(fp)}  {name}\n")
    print(f"wrote {jp} in {time.time() - t0:.0f} s")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
