"""Toy-scale EXPLICIT verification of what the sweeper models.

The sweeper reasons about eigenvalues, heights and lattices.  This module
builds the actual rational maps on small curves and checks, by evaluating
them on points, that

1. the unit automorphism zeta_3 on a j = 0 curve acts on the prime-order
   subgroup as one of the two roots the sweeper predicts;
2. a degree-7 endomorphism 2 + omega of Z[zeta_6], built by Velu's formulas
   from the rational 7-torsion and an isomorphism back to the curve, is an
   endomorphism with the predicted eigenvalue a + b*lambda_omega;
3. iterating it j times (an isogeny-cycle "pump") gives the eigenvalue
   lambda^j and the height the sweeper computes with ``quadorder.power``;
4. on a curve with CM by the class-number-3 order Z[(1+sqrt(-23))/2], the
   closed walk of three 2-isogenies is an endomorphism of degree 8 whose
   eigenvalue matches 1 + omega (the generator of the first principal power
   of a prime above 2) -- i.e. ``smallest_principal_power`` describes a
   real map;
5. the 4-dimensional decomposition {1, u, alpha, u*alpha} reconstructs k*P
   from explicit endomorphism images for random k, with every coefficient
   within the lattice's Babai bound;
6. affine operation counts of a plain double-and-add versus the pump are
   recorded (toy affine formulas; the cost model in ``costmodel.py`` uses
   projective counts and is NOT calibrated from these numbers).

Everything is deterministic (fixed seeds) and prints a JSON-able record.
"""
from __future__ import annotations

import json
import random
from dataclasses import dataclass

from sympy import isprime, nextprime
from sympy.ntheory import sqrt_mod
from sympy.ntheory.residue_ntheory import nthroot_mod

from . import lattice as LA
from . import quadorder as QO


# ---------------------------------------------------------------------------
# counted affine arithmetic
# ---------------------------------------------------------------------------

@dataclass
class Counter:
    p: int
    M: int = 0
    S: int = 0
    I: int = 0

    def mul(self, a, b):
        self.M += 1
        return a * b % self.p

    def sqr(self, a):
        self.S += 1
        return a * a % self.p

    def inv(self, a):
        self.I += 1
        return pow(a % self.p, -1, self.p)

    def snapshot(self):
        return {"M": self.M, "S": self.S, "I": self.I}

    def reset(self):
        self.M = self.S = self.I = 0


class Curve:
    """y^2 = x^3 + a x + b over F_p, affine, with counted field operations."""

    def __init__(self, p: int, a: int, b: int, F: Counter | None = None):
        self.p, self.a, self.b = p, a % p, b % p
        self.F = F or Counter(p)
        if (4 * self.a ** 3 + 27 * self.b ** 2) % p == 0:
            raise ValueError("singular")

    def on_curve(self, P):
        if P is None:
            return True
        x, y = P
        return (y * y - x * x * x - self.a * x - self.b) % self.p == 0

    def j(self):
        p, a, b = self.p, self.a, self.b
        num = 1728 * 4 * a ** 3
        den = (4 * a ** 3 + 27 * b ** 2) % p
        return num * pow(den, -1, p) % p

    def neg(self, P):
        return None if P is None else (P[0], (-P[1]) % self.p)

    def add(self, P, Q):
        F, p = self.F, self.p
        if P is None:
            return Q
        if Q is None:
            return P
        x1, y1 = P
        x2, y2 = Q
        if x1 == x2:
            if (y1 + y2) % p == 0:
                return None
            lam = F.mul((3 * F.sqr(x1) + self.a) % p, F.inv(2 * y1))
        else:
            lam = F.mul((y2 - y1) % p, F.inv(x2 - x1))
        x3 = (F.sqr(lam) - x1 - x2) % p
        y3 = (F.mul(lam, (x1 - x3) % p) - y1) % p
        return (x3, y3)

    def mul(self, k, P):
        if k < 0:
            return self.mul(-k, self.neg(P))
        R, Q = None, P
        while k:
            if k & 1:
                R = self.add(R, Q)
            Q = self.add(Q, Q)
            k >>= 1
        return R

    def lift_x(self, x):
        rhs = (x * x * x + self.a * x + self.b) % self.p
        y = sqrt_mod(rhs, self.p)
        return None if y is None else (x, int(y))

    def point(self, seed: int):
        rng = random.Random(seed)
        while True:
            P = self.lift_x(rng.randrange(1, self.p))
            if P is not None:
                return P


# ---------------------------------------------------------------------------
# Velu for odd prime kernels and for 2-torsion kernels (counted)
# ---------------------------------------------------------------------------

class VeluMap:
    """E -> E' with kernel generated by K (order ell).  Evaluates with counting."""

    def __init__(self, E: Curve, K, ell: int):
        self.E, self.ell = E, ell
        p, a, b = E.p, E.a, E.b
        self.terms = []     # (xq, vq, uq)
        v = w = 0
        if ell == 2:
            xq, yq = K
            assert yq == 0
            gx = (3 * xq * xq + a) % p
            vq, uq = gx, 0
            self.terms.append((xq, vq, uq))
            v, w = vq, (uq + xq * vq) % p
        else:
            Q = K
            for _ in range((ell - 1) // 2):
                xq, yq = Q
                gx = (3 * xq * xq + a) % p
                gy = (-2 * yq) % p
                vq = 2 * gx % p
                uq = gy * gy % p
                self.terms.append((xq, vq, uq))
                v = (v + vq) % p
                w = (w + uq + xq * vq) % p
                Q = E.add(Q, K)
        self.codomain = Curve(p, (a - 5 * v) % p, (b - 7 * w) % p, E.F)

    def __call__(self, P):
        if P is None:
            return None
        F, p = self.E.F, self.E.p
        x, y = P
        X, Y = x, y
        for (xq, vq, uq) in self.terms:
            if (x - xq) % p == 0:
                return None
            d = F.inv(x - xq)
            d2 = F.sqr(d)
            X = (X + F.mul(vq, d) + F.mul(uq, d2)) % p
            yd2 = F.mul(y, d2)
            Y = (Y - 2 * F.mul(uq, F.mul(yd2, d)) - F.mul(vq, yd2)) % p
        return (X, Y)


class Isomorphism:
    """(x, y) -> (u^2 x, u^3 y) from y^2 = x^3 + a x + b to y^2 = x^3 + a u^4 x + b u^6."""

    def __init__(self, E: Curve, u: int):
        self.E, self.u = E, u % E.p
        p = E.p
        self.u2, self.u3 = self.u * self.u % p, self.u ** 3 % p
        self.codomain = Curve(p, E.a * self.u ** 4 % p, E.b * self.u ** 6 % p, E.F)

    def __call__(self, P):
        if P is None:
            return None
        return (self.E.F.mul(self.u2, P[0]), self.E.F.mul(self.u3, P[1]))


def isomorphism_to(E1: Curve, E2: Curve):
    """An F_p-isomorphism E1 -> E2 (same j), or None if they are twists."""
    p = E1.p
    if E1.a == 0 and E2.a == 0:
        ratio = E2.b * pow(E1.b, -1, p) % p
        for u in nthroot_mod(ratio, 6, p, all_roots=True) or []:
            iso = Isomorphism(E1, int(u))
            if (iso.codomain.a, iso.codomain.b) == (E2.a, E2.b):
                return iso
        return None
    if E1.a and E2.a and E1.b and E2.b:
        r = E2.b * pow(E1.b, -1, p) * E1.a * pow(E2.a, -1, p) % p
        u = sqrt_mod(r, p)
        if u is None:
            return None
        for cand in (int(u), (-int(u)) % p):
            iso = Isomorphism(E1, cand)
            if (iso.codomain.a, iso.codomain.b) == (E2.a, E2.b):
                return iso
    return None


class Composite:
    def __init__(self, maps):
        self.maps = maps

    def __call__(self, P):
        for m in self.maps:
            P = m(P)
        return P


# ---------------------------------------------------------------------------
# toy curve constructions
# ---------------------------------------------------------------------------

def _two_torsion_points(E: Curve):
    from sympy import Poly, symbols
    x = symbols("x")
    roots = Poly(x ** 3 + E.a * x + E.b, x, modulus=E.p).ground_roots()
    return [(int(r) % E.p, 0) for r in roots]


def j0_curve_with_7_torsion(bits: int, seed: int = 1):
    """A curve y^2 = x^3 + b over F_p, p = 1 mod 3, with #E = 7 * c * n, n prime.

    The six twists of j = 0 have traces +-A, +-(A+3B)/2, +-(A-3B)/2 where
    4p = A^2 + 3B^2; we pick p, then the twist, by testing group orders.
    """
    rng = random.Random(seed)
    while True:
        p = nextprime(rng.randrange(1 << (bits - 1), 1 << bits))
        if p % 3 != 1:
            continue
        el = QO.cornacchia_element(-3, p)
        if el is None:
            continue
        A, B = 2 * el.a + el.b, el.b             # 4p = A^2 + 3B^2
        traces = set()
        for s1 in (1, -1):
            traces.add(s1 * A)
            if (A + 3 * B) % 2 == 0:
                traces.add(s1 * (A + 3 * B) // 2)
            if (A - 3 * B) % 2 == 0:
                traces.add(s1 * (A - 3 * B) // 2)
        cands = [(t, p + 1 - t) for t in traces if (p + 1 - t) % 7 == 0]
        good = []
        for t, N in cands:
            m = N // 7
            while m % 2 == 0:
                m //= 2
            while m % 3 == 0:
                m //= 3
            if isprime(m) and m > 4 * (p ** 0.5) and m > 1000:
                good.append((t, N, m))
        if not good:
            continue
        for b in range(1, 200):
            E = Curve(p, 0, b)
            P = E.point(seed)
            for t, N, n in good:
                if E.mul(N, P) is None and E.mul(N // n, P) is not None:
                    return E, N, n, t


HILBERT_CLASS_POLY_M23 = [1, 3491750, -5151296875, 12771880859375]   # H_{-23}(x), degree 3


def cm23_curve(bits: int, seed: int = 1):
    """A curve with CM by the maximal order of Q(sqrt(-23)) (h = 3) over F_p.

    Roots of the Hilbert class polynomial H_{-23} mod p give the three
    j-invariants of the 2-isogeny 3-cycle; 4p = A^2 + 23 B^2 gives the trace.
    The class polynomial is verified, not trusted: the trace found by testing
    the group order must satisfy t^2 - 4p = -23 f^2.
    """
    from sympy import Poly, symbols
    x = symbols("x")
    rng = random.Random(seed)
    while True:
        p = nextprime(rng.randrange(1 << (bits - 1), 1 << bits))
        el = QO.cornacchia_element(-23, p)
        if el is None:
            continue
        A = 2 * el.a + el.b
        roots = Poly(sum(c * x ** (3 - i) for i, c in enumerate(HILBERT_CLASS_POLY_M23)), x,
                     modulus=p).ground_roots()
        js = [int(r) % p for r in roots]
        if len(js) != 3:
            continue
        for t in (A, -A):
            N = p + 1 - t
            m = N
            for q in (2, 2, 2, 3):
                if m % q == 0:
                    m //= q
            if not (isprime(m) and m > 4 * p ** 0.5 and m > 1000):
                continue
            n = m
            j0 = js[0]
            k = j0 * pow((1728 - j0) % p, -1, p) % p
            a0, b0 = 3 * k % p, 2 * k % p
            for tw in range(1, 50):
                E = Curve(p, a0 * tw ** 2 % p, b0 * tw ** 3 % p)
                P = E.point(seed)
                if E.mul(N, P) is None and E.mul(N // n, P) is not None:
                    assert (t * t - 4 * p) % 23 == 0
                    f2 = (4 * p - t * t) // 23
                    f = int(round(f2 ** 0.5))
                    assert f * f == f2, "trace does not match CM by -23: class polynomial wrong?"
                    return E, N, n, t, js


# ---------------------------------------------------------------------------
# the verification runs
# ---------------------------------------------------------------------------

def eigenvalue_of(E: Curve, phi, P, n: int, candidates: list[int]) -> int | None:
    """Which candidate scalar c satisfies phi(P) = c*P?  (P of prime order n.)"""
    img = phi(P)
    for c in candidates:
        if E.mul(c % n, P) == img:
            return c % n
    return None


def _orbit_candidates(D: int, el: QO.RingElement, lam_w: int, n: int) -> dict[int, tuple[int, int]]:
    cands = {}
    for base in ((el.a, el.b), QO.conjugate(D, el.a, el.b)):
        for u in QO.units(D):
            a_, b_ = QO.multiply(D, base, u)
            cands[QO.eigenvalue(D, a_, b_, lam_w, n)] = (a_, b_)
    return cands


def verify_j0_pump(bits: int = 26, seed: int = 3, pump_power: int | None = None) -> dict:
    E, N, n, t = j0_curve_with_7_torsion(bits, seed)
    p = E.p
    F = E.F
    rec = {"p": p, "b": E.b, "order": N, "n": n, "trace": t, "checks": []}
    cof = N // n
    P = None
    s = seed
    while P is None or E.mul(n, P) is not None:
        s += 1
        P = E.mul(cof, E.point(s))
    # 1. zeta_3: (x, y) -> (beta x, y)
    beta = next(int(r) for r in nthroot_mod(1, 3, p, all_roots=True) if int(r) != 1)
    zeta = lambda Q: None if Q is None else (F.mul(beta, Q[0]), Q[1])  # noqa: E731
    lam_w_roots = QO.omega_eigenvalues(-3, n)          # eigenvalues of omega = zeta_6
    zeta3_roots = [(r - 1) % n for r in lam_w_roots]   # zeta_3 = omega - 1
    lam_z = eigenvalue_of(E, zeta, P, n, zeta3_roots)
    rec["checks"].append({"zeta_3 eigenvalue predicted": lam_z is not None, "lambda_zeta3": lam_z})
    assert lam_z is not None
    lam_w = (lam_z + 1) % n
    # 2. degree-7 endomorphism 2 + omega from the rational 7-torsion
    K = None
    s = 0
    while K is None:
        s += 1
        K = E.mul(N // 7, E.point(100 + s))
    assert E.mul(7, K) is None
    velu = VeluMap(E, K, 7)
    E2 = velu.codomain
    assert E2.j() == E.j() == 0, "codomain of the 7-kernel is not j=0"
    iso = isomorphism_to(E2, E)
    assert iso is not None, "codomain is the twist, not the curve itself"
    alpha = Composite([velu, iso])
    cands = _orbit_candidates(-3, QO.RingElement(-3, 2, 1), lam_w, n)
    lam_a = eigenvalue_of(E, alpha, P, n, list(cands))
    rec["checks"].append({"degree-7 endomorphism eigenvalue matches a+b*lambda_omega": lam_a is not None,
                          "element": cands.get(lam_a), "lambda_alpha": lam_a})
    assert lam_a is not None
    a_, b_ = cands[lam_a]
    # 3. pump: alpha^j with height about n^(1/4)
    bits_n = n.bit_length() - 1
    if pump_power is None:
        pump_power = max(1, round(bits_n / 4 / 1.4))
    j = pump_power
    aj, bj = QO.power(-3, (a_, b_), j)
    pump = Composite([alpha] * j)
    lam_pump_pred = QO.eigenvalue(-3, aj, bj, lam_w, n)
    F.reset()
    img = pump(P)
    pump_ops = F.snapshot()
    ok = E.mul(lam_pump_pred, P) == img
    rec["checks"].append({"alpha^j eigenvalue = predicted": ok, "j": j, "height": QO.height(aj, bj),
                          "predicted_height_bits": QO.height(aj, bj).bit_length(), "n_bits": bits_n,
                          "affine_ops_pump": pump_ops})
    assert ok
    # 5. 4-dim decomposition {1, zeta, alpha^j, zeta*alpha^j}
    gens = [1, lam_z, lam_pump_pred, lam_z * lam_pump_pred % n]
    red = LA.reduce(gens, n)
    cb = LA.coefficient_bits(red, samples=16, seed=seed)
    rng = random.Random(seed + 7)
    worst = 0
    images = [P, zeta(P), img, zeta(img)]
    for _ in range(8):
        k = rng.randrange(1, n)
        ks = red.decompose(k)
        worst = max(worst, max(abs(v) for v in ks))
        lhs = E.mul(k, P)
        rhs = None
        for ki, Qi in zip(ks, images):
            rhs = E.add(rhs, E.mul(ki, Qi))
        assert lhs == rhs, "4-dim decomposition with explicit maps failed"
    rec["checks"].append({"4-dim decomposition reconstructs k*P (8 random k)": True,
                          "max_coeff_bits": worst.bit_length(), "babai_bound_bits": cb["bound_bits"],
                          "balanced_bits": cb["balanced_bits"], "basis_inf_norm_bits": cb["basis_inf_norm_bits"]})
    # 6. op counts: plain double-and-add of a full scalar vs the pump
    F.reset()
    E.mul(rng.randrange(1, n), P)
    rec["affine_ops_double_and_add_full_scalar"] = F.snapshot()
    rec["affine_ops_pump"] = pump_ops
    return rec


def verify_cm23_cycle(bits: int = 26, seed: int = 5) -> dict:
    E, N, n, t, js = cm23_curve(bits, seed)
    p = E.p
    rec = {"p": p, "a": E.a, "b": E.b, "order": N, "n": n, "trace": t, "j_cycle": js, "checks": []}
    cof = N // n
    s = seed
    P = None
    while P is None or E.mul(n, P) is not None:
        s += 1
        P = E.mul(cof, E.point(s))
    jset = set(js)
    paths = []

    def walk(cur: Curve, maps, prev_j, depth):
        if depth == 3:
            if cur.j() == E.j():
                paths.append(list(maps))
            return
        for T2 in _two_torsion_points(cur):
            v = VeluMap(cur, T2, 2)
            cj = v.codomain.j()
            if cj not in jset or cj == prev_j or cj == cur.j():
                continue
            walk(v.codomain, maps + [v], cur.j(), depth + 1)

    walk(E, [], None, 0)
    assert paths, "no closed 3-walk found: class polynomial or cycle logic wrong"
    found = None
    beta = QO.smallest_principal_power(-23, 2)        # 1 + omega, norm 8, class order 3
    assert beta is not None and beta.norm == 8
    lam_w_roots = QO.omega_eigenvalues(-23, n)
    for path in paths:
        last = path[-1].codomain
        iso = isomorphism_to(last, E)
        if iso is None:
            continue
        phi = Composite(path + [iso])
        for lam_w in lam_w_roots:
            cands = _orbit_candidates(-23, beta, lam_w, n)
            lam = eigenvalue_of(E, phi, P, n, list(cands))
            if lam is not None:
                found = (path, lam, cands[lam], lam_w)
                break
        if found:
            break
    rec["checks"].append({"2-isogeny 3-cycle is an endomorphism with eigenvalue of 1+omega (or conjugate/unit)":
                          found is not None,
                          "element": found[2] if found else None, "lambda": found[1] if found else None,
                          "paths_found": len(paths)})
    assert found is not None
    path, lam, (a_, b_), lam_w = found
    j = 3
    aj, bj = QO.power(-23, (a_, b_), j)
    phi = Composite(path + [isomorphism_to(path[-1].codomain, E)])
    pump = Composite([phi] * j)
    pred = QO.eigenvalue(-23, aj, bj, lam_w, n)
    ok = E.mul(pred, P) == pump(P)
    rec["checks"].append({"cycle^3 eigenvalue = predicted": ok, "height_of_cycle^3": QO.height(aj, bj),
                          "degree": 8 ** j})
    assert ok
    red = LA.reduce([1, lam], n)
    cb = LA.coefficient_bits(red, samples=16, seed=seed)
    rec["checks"].append({"GLV-2 with the degree-8 cycle endomorphism": True,
                          "coeff_bits_bound": cb["bound_bits"], "balanced_bits": cb["balanced_bits"]})
    return rec


def main(argv=None) -> int:
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("--bits", type=int, default=26)
    ap.add_argument("--out", default=None)
    args = ap.parse_args(argv)
    out = {"j0_pump": verify_j0_pump(args.bits), "cm23_cycle": verify_cm23_cycle(args.bits)}
    txt = json.dumps(out, indent=1, default=str)
    if args.out:
        with open(args.out, "w") as f:
            f.write(txt)
    print(txt)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
