import json
from collections import Counter
IN = '/Volumes/Volume/crypto-autoresearcher/inputs'
with open(f'{IN}/ledger_inventory_20260724.json') as f:
    inv = json.load(f)

FAM_SUM = {
 'ECFG': "Index-calculus relation-surface program on toy prime-field ECDLP: Evans functional graphs (k -> x(kB)), public source/selector/collector surfaces for low-term relations, factor columns/packets on order-11779 and similar toy targets, rank and certificate accounting against an explicit Pollard-rho operation ledger. Spanning hypotheses (ECFG-H), observations (ECFG-P), negative results (ECFG-NR), restricted theorems (ECFG-RT), interrupted-run audits (ECFG-IR), and mixed results (ECFG-MX) across both the main and index-calculus ledgers; mechanism vocabulary centers on source generation, selectors, holdouts, rank, certificates, and rho ratios.",
 'TRANSFER': "Non-generic transfer/decomposition channel search: corresponding objects (Kummer surfaces and quartics, genus-2/3/4 Jacobians, Pryms of cyclic covers, split abelian surfaces E x E with Hermitian gluings, incidence covers, Weil restrictions) are constructed to expose a hidden factor base, relation source, or descent channel for the original prime-field subgroup. Includes the F5F0-F5F10 normalized-incidence-cover chain (projector theorems, exact Weil counts, target-multiplicity-zero negatives), the K0/K1P0-K1P10F PO96N Kummer-lattice chain (nodes, NS saturation, (1,2)-polarizations, elliptic embeddings, quotient-field materialization), and the TRANSFER-H0xx hypothesis spine; every positive is toy/model-bound with factor-base, relation, descent, and algorithm gates explicitly false unless charged.",
 'ISO': "Isogeny-orientation recovery program: ascending-volcano self-pairings, Kani/BHLS two-dimensional diamonds, oriented (quadratic-order) ideals as Kani auxiliaries, balanced-primary sign-free Kummer-row identification (beta>4d), double-orientation Schur selectors, Bockstein-Weil local leakage, repeated-prime divided-orientation compact evaluation, PEARL/SCALLOP implementation and transcript audits, and the POKE-4D norm-fiber enumeration. Sub-prefixes: ISO-AR (ascending-recovery hypotheses/positives/negatives), ISO-SP (self-pairing), ISO-CW (cost-weighted isogeny atlas), ISO-PK (product-Kummer), ISO-RM (rational maps), ISO-BP/ISO-BPI (balanced-primary), ISO-IKD (ideal Kani diamond), ISO-ONK (oriented norm Kani), ISO-DO (double orientation), ISO-BWL (Bockstein-Weil), ISO-RPDO (repeated-prime divided orientation), ISO-PEARL, ISO-P4D (POKE-4D), ISO-BRK (breakthrough triage), ISO-XW (novelty crosswalk), ISO-GATE (manuscript gate).",
 'OFQ': "Open-frontier question bullets from both ledgers' 'Open frontier questions' sections, including named idea-generation candidates (RT-1476-SUBRES-A1 backward-3-sum eliminant exponent, RT-1472-CYCLEMAT-A2 graphic-matroid cycle enrichment, RITT-B3/BAR-RITT-D3 functional decomposition of division polynomials, ISOWALK-C1 Ramanujan isogeny-walk collisions, MODHECKE-B1/ZILBERPINK-C2 modular-Hecke and Zilber-Pink routes) and the TRANSFER-H036/H038 hard goals; [x] items are resolved bullets preserved with their scoped outcomes.",
 'SHA': "SHA-1 differential-path compression work: disturbance-support basin allocation (w2_w3, w1_w3_w5, w3_w5, w1_w5), seed rotation, and exact verifier-recomputed compression paths; a self-contained side line unrelated to ECDLP.",
 'PO-transfer': "The 2026-06-10 non-generic transfer/decomposition channel sieve (PO-transfer-001..007): same-field isogeny-class invariance (closed), quadratic-twist positive control (P-224 twist 2^58.55 vs base 2^111.83), bielliptic norm-interpolation relation source (BNIT), Plucker incidence gate, trace-quotient restricted theorem, and (3,3)-split cofiber hypergraph; every tested algorithm lost to rho by measured factors (178x..115587x).",
 'H': "Index-calculus ledger hypothesis rows without hyphenated IDs (H325-H329): order-11779 packet free-column [6,7] residual-supply and source-generation pivots after the P1085 packet baseline.",
 'NR': "Three no-prefix negative rows (NR-1078 etc.) in the index-calculus ledger on selector/top-k source-pool exhaustion for remaining columns [6,7].",
 'RT': "Named open-frontier candidates RT-1476-SUBRES-A1 (serial-S3 backward-3-sum eliminant degree exponent beta<3/10 for sub-rho m=5 membership IC) and RT-1472-CYCLEMAT-A2 (2-large-prime graphic-matroid cycle-basis enrichment delta>1/4 at L=q^{1/5}).",
 'P': "Single no-hyphen observation row P1085 (index-calculus ledger): P1083 verified column-7 relation integrated into the order-11779 packet, rank 14->15, free columns [6,7,16]->[6,16].",
 'RITT': "Named open-frontier candidate RITT-B3 / BAR-RITT-D3: functional (Ritt) indecomposability of division polynomials f_m beyond Pohlig-Hellman-trivial factors, certified via Lattes-decomposition census.",
 'MODHECKE': "Named open-frontier candidate MODHECKE-B1 / ZILBERPINK-C2: modular/Hecke and Zilber-Pink special-subvariety routes; genuinely open with no literature refutation; require Theory-Agent formalization before experiment.",
 'ISOWALK': "Named open-frontier candidate ISOWALK-C1: non-backtracking Ramanujan isogeny-walk collision search beating the birthday bound (exponent<1/2) versus spectral-gap constant improvement only.",
}

inv['family_summaries'] = FAM_SUM
inv['methodology_notes'] = [
 "Entries are ledger table rows keyed by first-cell ID from the two fresh ledger copies (main_research_ledger.md 2563 lines; index_calculus_ledger.md 720 lines), plus open-frontier bullets (OFQ-* positional IDs following the 20260719 convention; five named bullets keep their own IDs), plus seven PO-transfer-* entries from non_generic_transfer_search_20260610.md.",
 "Semantic fields (representation, exploited_structure, factor_base, relation_shape, relation_generation, compression, linear_algebra_object, target_descent, cost_bottleneck) are deterministic keyword-tag extractions over the full row text; mechanism is a tag prefix plus a claim gist. They are fingerprints for search/grouping, not hand-verified per-row readings (except the 71 new and ~9 changed entries listed in data_quality_caveats, which are hand-authored).",
 "dominant_vocabulary uses case-insensitive word-boundary counts over both ledgers plus the transfer report with leading row-ID cells stripped, to avoid counting each row's own ID; merged variants (e.g. 'factor base' covers 'factor-base').",
 "closed_territory collects every entry whose outcome is negative-flavored (negative sections, NEGATIVE RESULT status cells, NR-family IDs, resolved-negative OFQ bullets); obstruction fields lead with 'QUANT:' measurement fragments when the row text contains them (1029/1269 rows carry quantitative content; the rest state qualitative scope only).",
 "open_frontier collects all unchecked ledger bullets verbatim plus next-action branches of hypothesis-status rows (66 questions + 328 branches).",
 "The 20260719 inventory was used as a checklist: every prior ID was verified against the fresh ledgers; 66 main + 5 IC new rows were fully processed; 54 rows with changed text were re-extracted (9 key ones hand-verified); the old-copy diff (research_ledger_main.md) was cross-checked and found to be a stale snapshot (it lacks TRANSFER-H036..H038 and the ISO tail sections present since 2026-07-20).",
]
inv['data_quality_caveats'] = [
 "Hand-authored semantic fingerprints: the 66 new main-ledger IDs + 5 new IC IDs (H325-H329) + changed TRANSFER-H011/H035/H036, ISO-NR-ONK-001, ISO-NR-IKD-012, ISO-RT-IKD-013; all other entries carry heuristic keyword fingerprints whose tag granularity varies.",
 "ECFG-P227 appears twice in the IC ledger (kept as ECFG-P227 and ECFG-P227#2); all other IDs are unique.",
 "IC-ledger rows ECFG-P286..ECFG-P1513 (87 rows) sit under the '## Baselines' header as dated continuation tables without their own section headers; their 'section' field says 'Baselines' but they are really continuation evidence tables.",
 "Terse rows: some early IC rows (e.g. ECFG-001..ECFG-0xx) are one-line hypothesis/status rows with owner+next cells only; they lack evidence cells, so quantitative obstruction fields fall back to the claim gist (240/1269 closed items have no QUANT fragment).",
 "OFQ positional IDs (OFQ-*) shift whenever bullets are added/removed; they are stable only within this snapshot. Five named bullets additionally appear under their own IDs (RT-*, RITT-*, ISOWALK-C1, MODHECKE-B1 / ZILBERPINK-C2).",
 "bibliography.json (10 literature citations) is metadata, not a ledger; it is not inventoried as entries. The literature map and baselines tables inside the ledgers are section content, not ID rows, and are summarized in family summaries instead.",
 "Multi-line cells containing literal '|' inside backticks (21 main rows, 2 IC rows) split into >5 raw cells; claim/status/next extraction tolerates this but a few mechanism gists may truncate mid-cell.",
 "ISO-NR-DO-021 preserves a retraction (custody failure): its algebraic counts stand but the geometric interpretation is withdrawn; ISO-RT-IKD-013/IJD-style theorems are marked NOVELTY-UNVERIFIED by the ledger itself.",
]
with open(f'{IN}/ledger_inventory_20260724.json', 'w') as f:
    json.dump(inv, f, indent=1)
print('top-level keys:', list(inv.keys()))
print('entry_count:', inv['entry_count'], 'actual:', len(inv['entries']))
