
default(parisizemax, 2000000000);
p = 2^64 - 2^32 + 1; q = p^5;
print("P=", p);
print("P_MOD_7=", p % 7);
print("KRONECKER_MINUS7_P=", kronecker(-7, p));
EA = ellinit([-35, 98], p);
print("EA_J=", lift(EA.j)); print("MINUS3375_MOD_P=", (-3375) % p);
print("EA_DISC_NONZERO=", EA.disc != 0);
print("EA_CARD_FP=", ellcard(EA)); print("P_PLUS_1=", p + 1);
print("EA_SUPERSINGULAR_FP=", ellissupersingular(EA));
z = ffgen(Mod(1,p)*(x^5-3), 'z);
print("Z5M3_IRREDUCIBLE=", polisirreducible(Mod(1,p)*(x^5-3)));
EA5 = ellinit([-35 + 0*z, 98 + 0*z]);
t0 = getwalltime(); r = iferr(alarm(300, ellcard(EA5)), E, E); print("EA_CARD_FP5=", r); print("EA_CARD_FP5_MS=", getwalltime() - t0);
print("EA_CARD_FP5_EQ_Q_PLUS_1=", r == q + 1);
print("EA_SUPERSINGULAR_FP5=", ellissupersingular(EA5));
EB = ellinit([3, 8], p); NB1 = ellcard(EB); print("EB_CARD_FP=", NB1);
EB5 = ellinit([3 + 0*z, 8 + 0*z]);
t0 = getwalltime(); rb = iferr(alarm(300, ellcard(EB5)), E, E); print("EB_CARD_FP5=", rb); print("EB_CARD_FP5_MS=", getwalltime() - t0);
t1 = p + 1 - NB1; tt = vector(6); tt[1] = 2; tt[2] = t1; for(k = 3, 6, tt[k] = t1*tt[k-1] - p*tt[k-2]);
print("EB_CARD_FP5_BY_FROBENIUS_RECURSION=", q + 1 - tt[6]);
print("EB_FP_DIVIDES_FP5=", if(type(rb) == "t_INT", rb % NB1 == 0, "n/a"));
print("EB_T1=", t1); print("EB_T1SQ_MINUS_4P=", t1^2 - 4*p); print("EB_CORE_T1SQ_M4P=", core(t1^2 - 4*p));
print("P_PLUS_1_FACTOR=", factor(p + 1));
phi = p^4 - p^3 + p^2 - p + 1; print("PHI10=", phi); print("PHI10_BITS=", #binary(phi)); print("PHI10_ISPSEUDOPRIME=", ispseudoprime(phi));
t0 = getwalltime(); fphi = iferr(alarm(300, factor(phi)), E, E); print("PHI10_FACTOR=", fphi); print("PHI10_FACTOR_MS=", getwalltime() - t0);
Emas = ellinit([3, 8*z^4]); jm = Emas.j; print("J_MAS_IN_FP=", jm^p == jm);
Egf = ellinit([263*z - 4/3, 16/27 - 2*263*z/3]); jg = Egf.j; print("J_GF_IN_FP=", jg^p == jg);
