"""EXP-INSTR-85b102 amendment v2: CTRL-VALUESHUFFLE.

NEW MODULE, NEW FUNCTIONS ONLY. Nothing in `harness/run_blocknull.py` and
nothing in the eleven functions frozen by version 1 (`_targets`,
`targets_uniform`, `permutation_null`, `binomial_null_verdict`,
`exact_null_verdict`, `decomposition_rate_m2`, `decomposition_rate_m3`,
`liftable_density`, `factor_base_fixed_size`, `factor_base_window`,
`two_torsion_x_count`) is modified here. They are IMPORTED and CALLED;
`frozen_function_diff.txt` is the receipt, regenerated by this run.

WHAT THIS CONTROL IS. The null object of the same shape as the version-1
N ladder: same curves, same (trace, N), same class sizes, same block
partitions -- only the per-curve functional VALUES are permuted, uniformly at
random across the whole pool, independently per functional per replicate. It
separates two live explanations of the 50-of-144 type-A residue that the
committed data cannot separate, because the committed data holds exactly one
realization of the values:

    (i)  a pure artifact of N-band blocking geometry acting on an ARBITRARY
         value multiset; or
    (ii) something specific to the m = 3 sum-set family, which reverses in
         8 of 8 cells at both primes under both statistics.

The deciding quantity is where the observed residue count falls in the
shuffled null. That quantity did not exist when the decision rule was frozen
in experiments/EXP-INSTR-85b102/amendments/v2.yaml.

NO PERMUTATION STUDY. B is not a parameter of this control. The entire ladder
ratio sequence is recomputed from `closed_form_null_mean` alone, which is
exact whenever every class lies inside one block -- automatic on the N ladder
because N = p + 1 - t is injective in the trace, so an N band never splits a
class. This is why the control costs CPU-minutes rather than CPU-hours.

SCOPE. Tier TOY. p in {4001, 6007}. Instrument characterisation only: no
ECDLP attack, no discrete logarithm, no relation collection, no solver, no
cost or exponent claim. sota_delta is zero on every axis. A `p > 0.05` result
means NO STRUCTURE DETECTED AT 200 REPLICATES, never "no structure exists":
the resolution floor is 1/201 = 0.00498 and the design's power against a small
effect is not characterised.

This module INTERPRETS NOTHING. It emits the terminal state defined by the
frozen decision rule and the numbers that determine it.
"""
from __future__ import annotations

import csv
import hashlib
import json
import os
import statistics as pystats
import time
from dataclasses import dataclass, field

import numpy as np

from . import run_blocknull as rb
from .run_blocknull import (closed_form_null_mean, classes_within_blocks,
                            functional_keys, statistic_unweighted,
                            statistic_weighted)

# --------------------------------------------------------------------------
# frozen declarations, read from experiments/EXP-INSTR-85b102/amendments/v2.yaml
# --------------------------------------------------------------------------

EXPERIMENT_ID = "EXP-INSTR-85b102"
RUN_AREA = "INSTR"
CONTROL_ID = "CTRL-VALUESHUFFLE"
AMENDMENT = "experiments/EXP-INSTR-85b102/amendments/v2.yaml"
AMENDMENT_VERSION = 2
DOMAIN = "EXP-INSTR-85b102/v2/CTRL-VALUESHUFFLE"

# parameters_frozen
REPLICATES = 200
SEEDS = (20260807, 20260808, 11235813)
POOLS = ("POOL_A", "POOL_B", "POOL_C", "POOL_D")
SOURCE_RUNS = {
    "POOL_A": "RUN-INSTR-85b102-poolA-c",
    "POOL_B": "RUN-INSTR-85b102-poolB-b",
    "POOL_C": "RUN-INSTR-85b102-poolC",
    "POOL_D": "RUN-INSTR-85b102-poolD",
}

# budget (amendment v2)
WALL_CLOCK_LIMIT_S = 3600
MEMORY_LIMIT_GB = 4

# definitions_frozen.residue_count -- READ FROM COMMITTED VERSION-1 ARTIFACTS
# BEFORE ANY REPLICATE, and frozen in the approved amendment. SR-B1 compares
# the re-derivation against THIS number and never the reverse.
FROZEN_OBSERVED_RESIDUE = 50
FROZEN_DENOMINATOR_FULL = 144
FROZEN_DENOMINATOR_COMPARABLE = 138          # denominator_note, Coordinator recount
# item 3f of RT-20260807-743198, per pool
FROZEN_OBSERVED_RESIDUE_BY_POOL = {"POOL_A": 10, "POOL_B": 10,
                                   "POOL_C": 16, "POOL_D": 14}
# B3: the per-functional residue indicator for the m = 3 sum-set family
M3_FAMILY = ("sumset_m3", "sumset_eff_m3")
FROZEN_OBSERVED_M3 = {"sumset_m3": 8, "sumset_eff_m3": 8}
M3_CELLS = 8                                  # 4 pools x 2 statistics

# The verdict rule, restated verbatim from harness/run_blocknull.py:1552:
#     rises = all(b >= a - 1e-12 for a, b in zip(vals, vals[1:]))
# Restated rather than imported because it is an inline expression in the
# frozen v1 emitter, not a callable. This is the same independent
# re-implementation RT-20260807-743198 and CORR-20260807-732541 used, and the
# reproduction gate checks it against the committed booleans.
VERDICT_TOLERANCE = 1e-12

N_LADDER = rb.N_LADDER

CERTIFICATE_NOTE = (
    "certificate.kind: none, EXPLICITLY. This control computes no discrete "
    "logarithm and collects no relation, so there is no solve or relation "
    "claim to certify (docs/claims-and-verification.md). Its reproduction "
    "gate, its per-replicate geometry-invariance assertions and its "
    "closed-form applicability assertions are internal consistency checks, "
    "not certificates, and are reported as such.")

ASYMMETRY_DECLARED = (
    "state_1 (CONTROLLED_NULL) is a POSITIVE finding about the INSTRUMENT and "
    "state_2 (STRUCTURE_PRESENT) is NOT a finding about mathematics. Neither "
    "outcome supports any GOAL-ENDO-001 hypothesis. A `p > 0.05` result means "
    "NO STRUCTURE DETECTED AT 200 REPLICATES, never 'no structure exists': "
    "the resolution floor is 1/201 = 0.004975 and the design's power against "
    "a small effect is not characterised.")


def _repo() -> str:
    return os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def _sha(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


# --------------------------------------------------------------------------
# seeding
# --------------------------------------------------------------------------


def derive_shuffle_seed(replicate: int, pool: str, functional: str) -> int:
    """Big-endian SHA-256 of the declared payload, reduced mod 2^64.

        payload = DOMAIN | "SHUFFLE" | pool | functional | replicate
                  | seed0 | seed1 | seed2

    IMPLEMENTATION DECISION, RECORDED BECAUSE THE CONTRACT DOES NOT FIX IT.
    `parameters_frozen.seeds` names three seeds and `parameters_frozen.
    replicates` names 200; the amendment does not say how the three map onto
    the replicates. This derivation consumes ALL THREE for EVERY draw, so no
    seed is favoured, no replicate shares a stream with another, and a third
    party reproduces any single shuffle from (replicate, pool, functional)
    alone. It mirrors `run_blocknull.derive_seed`, which is the convention
    already committed for this experiment. Any other mapping is a different
    (and equally legal) reading of an under-specified field; this one is
    stated here so the difference is visible rather than silent.
    """
    payload = (f"{DOMAIN}|SHUFFLE|{pool}|{functional}|{replicate}"
               f"|{SEEDS[0]}|{SEEDS[1]}|{SEEDS[2]}")
    return int.from_bytes(hashlib.sha256(payload.encode("ascii")).digest(),
                          "big") % (1 << 64)


# --------------------------------------------------------------------------
# pool views, read from COMMITTED version-1 artifacts only
# --------------------------------------------------------------------------


@dataclass
class PoolView:
    """One frozen pool, reconstructed from its committed run directory.

    Nothing here is re-enumerated or re-measured: `per_curve.csv` supplies the
    curves, their traces and every functional value; `rung_table.json`
    supplies the block partition of each rung. (trace, N), the class sizes and
    the block assignment are READ, never recomputed from a curve.
    """
    name: str
    p: int
    run_id: str
    n: int
    keys: list
    traces_by_curve: list
    class_traces: list                       # class index -> trace
    class_N: list                            # class index -> N (group order)
    class_sizes: list
    labels: np.ndarray = field(repr=False)
    values: dict = field(repr=False)
    blocks: dict = field(repr=False)         # rung -> np.ndarray of block ids
    degenerate: dict = field(default_factory=dict)
    delta_max: dict = field(default_factory=dict)
    n_blocks: dict = field(default_factory=dict)

    @property
    def K(self) -> int:
        return len(self.class_traces)

    @property
    def non_degenerate_ladder(self) -> list:
        return [r for r in N_LADDER if not self.degenerate[r]]


def _run_dir(run_id: str) -> str:
    return os.path.join(_repo(), "experiments", EXPERIMENT_ID, "runs", run_id)


def load_pool_view(pool: str, run_id: str) -> PoolView:
    base = _run_dir(run_id)
    with open(os.path.join(base, "per_curve.csv"), encoding="utf-8") as fh:
        rows = list(csv.reader(fh))
    header, body = rows[0], rows[1:]
    p = int(body[0][0])
    keys = functional_keys(p)
    fixed = ["p", "a", "b", "j", "trace", "order", "aut_order", "fb_m2",
             "fb_m3", "n_targets", "hits_m2", "hits_m3"]
    if header[:12] != fixed:
        raise RuntimeError(f"{run_id}: unexpected per_curve.csv prefix "
                           f"{header[:12]}")
    if header[12:12 + len(keys)] != keys:
        raise RuntimeError(f"{run_id}: unexpected functional columns "
                           f"{header[12:12 + len(keys)]}")

    traces = [int(r[4]) for r in body]
    orders = [int(r[5]) for r in body]
    class_traces: list = []
    for t in traces:
        if t not in class_traces:
            class_traces.append(t)
    index_of = {t: i for i, t in enumerate(class_traces)}
    labels = np.array([index_of[t] for t in traces], dtype=np.int64)
    class_sizes = [int((labels == i).sum()) for i in range(len(class_traces))]
    class_N = []
    for i, t in enumerate(class_traces):
        Ns = {orders[j] for j in range(len(traces)) if traces[j] == t}
        if len(Ns) != 1:
            raise RuntimeError(f"{run_id}: class t={t} carries several N {Ns}")
        class_N.append(int(Ns.pop()))

    values = {k: np.array([float(r[12 + i]) for r in body], dtype=np.float64)
              for i, k in enumerate(keys)}

    with open(os.path.join(base, "rung_table.json"), encoding="utf-8") as fh:
        rt = json.load(fh)[pool]
    blocks, degen, dmax, nblk = {}, {}, {}, {}
    for rung in rb.RUNGS:
        comp = rt[rung]["block_composition_by_trace"]
        blk_of_trace = {}
        for bid, ts in comp.items():
            for t in ts:
                blk_of_trace[int(t)] = int(bid)
        blocks[rung] = np.array([blk_of_trace[t] for t in traces],
                                dtype=np.int64)
        degen[rung] = bool(rt[rung]["degenerate"])
        dmax[rung] = int(rt[rung]["delta_max_N"])
        nblk[rung] = int(rt[rung]["n_blocks"])

    return PoolView(name=pool, p=p, run_id=run_id, n=len(body), keys=keys,
                    traces_by_curve=traces, class_traces=class_traces,
                    class_N=class_N, class_sizes=class_sizes, labels=labels,
                    values=values, blocks=blocks, degenerate=degen,
                    delta_max=dmax, n_blocks=nblk)


def geometry_fingerprint(view: PoolView) -> dict:
    """The bits the shuffle MUST NOT touch, hashed.

    (trace, N) per class, the class sizes, the per-curve class label and the
    per-curve block id at every rung. Recomputed and compared after every
    single replicate: `state_0_INVALID` fires when any of these moves.
    """
    trace_N = ";".join(f"{t}:{N}" for t, N in
                       zip(view.class_traces, view.class_N))
    sizes = ";".join(str(s) for s in view.class_sizes)
    labels = ",".join(str(int(x)) for x in view.labels)
    blocks = {r: _sha(",".join(str(int(x)) for x in view.blocks[r]))
              for r in rb.RUNGS}
    return {
        "trace_N_pairs": trace_N,
        "trace_N_sha256": _sha(trace_N),
        "class_sizes_sha256": _sha(sizes),
        "labels_sha256": _sha(labels),
        "block_assignment_sha256_by_rung": blocks,
        "n_curves": view.n,
        "n_classes": view.K,
    }


def value_multiset_fingerprint(values: dict) -> dict:
    """sha256 of each functional's SORTED value vector.

    Preserved exactly by a permutation; any change means the shuffle did more
    than permute.
    """
    out = {}
    for k, v in values.items():
        s = np.sort(np.asarray(v, dtype=np.float64))
        out[k] = _sha(",".join(repr(float(x)) for x in s))
    return out


# --------------------------------------------------------------------------
# the frozen verdict rule and the type-A residue
# --------------------------------------------------------------------------


def verdict_rises(vals: list) -> bool:
    """harness/run_blocknull.py:1552, restated. NOTE THE VACUOUS TRUE.

    `all()` over an empty or one-element list is True, so a cell with fewer
    than two defined R values scores MONOTONE RISE on no data. That defect is
    OBJ-3 of RT-20260807-743198 and is recorded, NOT repaired, here: the
    amendment states in `what_this_amendment_does_not_do` that fixing it is a
    separate amendment. `n_comparisons` is reported beside every verdict so a
    vacuous pass is visible.
    """
    return all(b >= a - VERDICT_TOLERANCE for a, b in zip(vals, vals[1:]))


def ladder_cells(view: PoolView, values: dict) -> dict:
    """Every (functional, statistic) cell's ladder, from the closed form alone.

    R(rung) = T_obs / E[T_pi | rung] with E[T_pi | rung] the EXACT closed-form
    null mean. T_obs does not depend on the rung, so the whole sequence is one
    fixed numerator over the ladder's denominators.

    The type-A residue indicator is the frozen verdict rule applied to the
    NON-DEGENERATE rungs only, which removes every type-B reversal by
    construction (item 3f of RT-20260807-743198, and `definitions_frozen` of
    the amendment).
    """
    out = {}
    nd = view.non_degenerate_ladder
    for k in view.keys:
        v = values[k]
        t_w = statistic_weighted(v, view.labels)
        t_u = statistic_unweighted(v, view.labels)
        cf = {}
        for rung in N_LADDER:
            cf[rung] = (closed_form_null_mean(v, view.labels,
                                              view.blocks[rung], "weighted"),
                        closed_form_null_mean(v, view.labels,
                                              view.blocks[rung], "unweighted"))
        for si, (stat, T) in enumerate((("weighted", t_w),
                                        ("unweighted", t_u))):
            R = {}
            for rung in N_LADDER:
                m = cf[rung][si]
                R[rung] = (None if m is None or m == 0.0 or
                           (isinstance(m, float) and np.isnan(m))
                           else T / m)
            vals_nd = [R[r] for r in nd if R[r] is not None]
            vals_all = [R[r] for r in N_LADDER if R[r] is not None]
            rises = verdict_rises(vals_nd)
            out[f"{k}|{stat}"] = {
                "T_obs": T,
                "closed_form_null_mean": {r: cf[r][si] for r in N_LADDER},
                "R": R,
                "non_degenerate_rungs": list(nd),
                "n_comparisons": max(0, len(vals_nd) - 1),
                "type_A_residue": (not rises),
                "vacuous": len(vals_nd) < 2,
                "comparable": bool(vals_all),
                "closed_form_applicable": all(
                    cf[r][si] is not None for r in N_LADDER),
            }
    return out


def residue_summary(cells_by_pool: dict) -> dict:
    """Counts over the 144-cell frame, plus the per-functional breakdown."""
    total = 0
    comparable = 0
    full = 0
    vacuous = 0
    per_pool = {}
    per_functional: dict = {}
    bitmap_keys: list = []
    bitmap: list = []
    for pool in POOLS:
        cells = cells_by_pool[pool]
        r = sum(1 for c in cells.values() if c["type_A_residue"])
        cmp_ = sum(1 for c in cells.values() if c["comparable"])
        vac = sum(1 for c in cells.values() if c["vacuous"])
        per_pool[pool] = {"residue": r, "cells": len(cells),
                          "comparable": cmp_, "vacuous": vac}
        total += r
        comparable += cmp_
        full += len(cells)
        vacuous += vac
        for ck in sorted(cells):
            fkey = ck.split("|")[0]
            per_functional.setdefault(fkey, {"residue": 0, "cells": 0})
            per_functional[fkey]["cells"] += 1
            per_functional[fkey]["residue"] += int(cells[ck]["type_A_residue"])
            bitmap_keys.append(f"{pool}|{ck}")
            bitmap.append("1" if cells[ck]["type_A_residue"] else "0")
    return {
        "residue_count": total,
        "cells_full": full,
        "cells_comparable": comparable,
        "cells_vacuous_in_residue_construction": vacuous,
        "by_pool": per_pool,
        "by_functional": per_functional,
        "m3_family": {k: per_functional.get(k, {}).get("residue")
                      for k in M3_FAMILY},
        "cell_bitmap": "".join(bitmap),
        "cell_bitmap_keys_sha256": _sha(";".join(bitmap_keys)),
    }


# --------------------------------------------------------------------------
# SR-B1: the reproduction gate. BLOCKING, AND IT RUNS FIRST.
# --------------------------------------------------------------------------


def committed_residue(pool: str, run_id: str, ratio_field: str) -> dict:
    """The residue re-derived from a committed results.json ratio field."""
    with open(os.path.join(_run_dir(run_id), "results.json"),
              encoding="utf-8") as fh:
        L = json.load(fh)["ladder"]
    B = L["B"]
    residue = 0
    comparable = 0
    vacuous = 0
    cells = 0
    verdict_agrees = 0
    verdict_checked = 0
    per_functional: dict = {}
    for fkey in L["functionals"]:
        for stat in ("weighted", "unweighted"):
            cells += 1
            seq = [L["cells"][f"{pool}|{fkey}|{r}|{stat}|B{B}"]
                   for r in N_LADDER]
            nd = [c for c in seq if not c["degenerate"]]
            vals_nd = [c[ratio_field] for c in nd if c[ratio_field] is not None]
            vals_all = [c[ratio_field] for c in seq
                        if c[ratio_field] is not None]
            if vals_all:
                comparable += 1
            if len(vals_nd) < 2:
                vacuous += 1
            is_res = not verdict_rises(vals_nd)
            residue += int(is_res)
            per_functional.setdefault(fkey, {"residue": 0, "cells": 0})
            per_functional[fkey]["cells"] += 1
            per_functional[fkey]["residue"] += int(is_res)
            # cross-check the restated rule against the committed boolean on
            # the FULL ladder (the v1 verdict, not the residue construction)
            if ratio_field == "variance_ratio_R_empirical":
                verdict_checked += 1
                mine = verdict_rises(vals_all)
                theirs = L["monotonicity"][f"{fkey}|{stat}"][
                    "ratio_rises_monotonically_along_N_ladder"]
                verdict_agrees += int(mine == theirs)
    return {"residue": residue, "cells": cells, "comparable": comparable,
            "vacuous": vacuous, "by_functional": per_functional,
            "restated_rule_agrees_with_committed_boolean":
                (None if not verdict_checked
                 else f"{verdict_agrees}/{verdict_checked}")}


def reproduction_gate(views: dict) -> dict:
    """SR-B1. Three independent derivations of the OBSERVED residue count.

      D1  committed `variance_ratio_R_empirical`  (the v1 Monte-Carlo ratio)
      D2  committed `variance_ratio_R_closed_form` (exact, zero MC error)
      D3  RECOMPUTED end-to-end from `per_curve.csv` + `rung_table.json`
          through this module's own pipeline -- the identity replicate of the
          shuffle, and the only derivation that certifies the null is measured
          by the same instrument as the observed value.

    THE GATE PASSES ONLY IF ALL THREE RETURN 50. On failure the run STOPS,
    reports both numbers, and adjusts nothing: the frozen 50 is never moved to
    match a re-derivation.
    """
    d1 = {p: committed_residue(p, SOURCE_RUNS[p], "variance_ratio_R_empirical")
          for p in POOLS}
    d2 = {p: committed_residue(p, SOURCE_RUNS[p],
                               "variance_ratio_R_closed_form") for p in POOLS}
    d3_cells = {p: ladder_cells(views[p], views[p].values) for p in POOLS}
    d3 = residue_summary(d3_cells)

    tot1 = sum(v["residue"] for v in d1.values())
    tot2 = sum(v["residue"] for v in d2.values())
    tot3 = d3["residue_count"]

    # degeneracy must be a SUFFIX of the N ladder, or the residue construction
    # would compare rungs that are not adjacent in the ladder.
    suffix_ok = {}
    for p in POOLS:
        flags = [views[p].degenerate[r] for r in N_LADDER]
        suffix_ok[p] = flags == sorted(flags)          # False... then True...

    per_pool_ok = all(
        d1[p]["residue"] == d2[p]["residue"] == d3["by_pool"][p]["residue"]
        == FROZEN_OBSERVED_RESIDUE_BY_POOL[p] for p in POOLS)

    m3_ok = all(d3["m3_family"][k] == FROZEN_OBSERVED_M3[k] for k in M3_FAMILY)

    passed = bool(tot1 == tot2 == tot3 == FROZEN_OBSERVED_RESIDUE
                  and per_pool_ok and all(suffix_ok.values()))

    return {
        "rule": "SR-B1 REPRODUCTION GATE, BLOCKING, RUNS FIRST",
        "frozen_observed_residue_count": FROZEN_OBSERVED_RESIDUE,
        "frozen_observed_by_pool": FROZEN_OBSERVED_RESIDUE_BY_POOL,
        "derivations": {
            "D1_committed_empirical_ratio": {
                "total": tot1,
                "by_pool": {p: d1[p]["residue"] for p in POOLS},
                "comparable_cells": sum(d1[p]["comparable"] for p in POOLS),
                "full_cells": sum(d1[p]["cells"] for p in POOLS),
                "restated_rule_vs_committed_boolean":
                    {p: d1[p]["restated_rule_agrees_with_committed_boolean"]
                     for p in POOLS}},
            "D2_committed_closed_form_ratio": {
                "total": tot2,
                "by_pool": {p: d2[p]["residue"] for p in POOLS},
                "comparable_cells": sum(d2[p]["comparable"] for p in POOLS),
                "full_cells": sum(d2[p]["cells"] for p in POOLS)},
            "D3_recomputed_from_per_curve_csv": {
                "total": tot3,
                "by_pool": {p: d3["by_pool"][p]["residue"] for p in POOLS},
                "comparable_cells": d3["cells_comparable"],
                "full_cells": d3["cells_full"],
                "note": "the identity replicate: same code path the shuffled "
                        "replicates use, with no permutation applied"},
        },
        "denominators": {
            "full_cells": FROZEN_DENOMINATOR_FULL,
            "comparable_cells": FROZEN_DENOMINATOR_COMPARABLE,
            "reproduced_full_cells": d3["cells_full"],
            "reproduced_comparable_cells": d3["cells_comparable"],
            "residue_against_full": f"{tot3}/{d3['cells_full']}",
            "residue_against_comparable": f"{tot3}/{d3['cells_comparable']}",
            "which_the_decision_rule_used": (
                "THE COUNT, over the full 144-cell frame. The frozen "
                "statistic is a COUNT and the null is drawn over the same "
                "144-cell frame, so the denominator does not enter the "
                "p-value at all. 50 reproduces under BOTH denominators "
                "because the six-cell difference is cells with no defined R "
                "at any rung, which cannot be in the residue under either. "
                "Both fractions are reported."),
        },
        "degeneracy_is_a_ladder_suffix": suffix_ok,
        "m3_family_observed": d3["m3_family"],
        "m3_family_frozen": FROZEN_OBSERVED_M3,
        "m3_family_reproduced": m3_ok,
        "observed_cells": d3,
        "gate": "PASS" if passed else "FAIL",
        "on_failure": (
            "STOP. Report the discrepancy as the deliverable, report BOTH "
            "numbers, and do NOT adjust the frozen 50 to match the "
            "re-derivation."),
    }


# --------------------------------------------------------------------------
# the shuffled null
# --------------------------------------------------------------------------


def shuffled_values(view: PoolView, replicate: int) -> dict:
    """One replicate's values: each functional permuted independently.

    Uniform over the symmetric group on the WHOLE POOL, per functional, per
    replicate. Nothing else moves: labels, blocks, class sizes and (trace, N)
    are the view's, untouched.
    """
    out = {}
    for k in view.keys:
        rng = np.random.default_rng(derive_shuffle_seed(replicate, view.name, k))
        out[k] = view.values[k][rng.permutation(view.n)]
    return out


def replicate_invariants(view: PoolView, values: dict, base_geo: dict,
                         base_multiset: dict) -> dict:
    """Every `state_0_INVALID` trigger, asserted PER REPLICATE, not assumed."""
    geo = geometry_fingerprint(view)
    ms = value_multiset_fingerprint(values)
    applicability = {r: bool(classes_within_blocks(view.labels,
                                                  view.blocks[r]))
                     for r in N_LADDER}
    return {
        "trace_N_unchanged": geo["trace_N_sha256"] == base_geo["trace_N_sha256"],
        "class_sizes_unchanged":
            geo["class_sizes_sha256"] == base_geo["class_sizes_sha256"],
        "labels_unchanged": geo["labels_sha256"] == base_geo["labels_sha256"],
        "block_assignment_unchanged": (
            geo["block_assignment_sha256_by_rung"]
            == base_geo["block_assignment_sha256_by_rung"]),
        "value_multiset_preserved": ms == base_multiset,
        "closed_form_exact_at_every_ladder_rung": all(applicability.values()),
        "applicability_by_rung": applicability,
    }


def run_null(views: dict, replicates: int, deadline: float | None,
             checkpoint_path: str | None = None, say=None) -> dict:
    """`replicates` shuffled realizations of the whole 144-cell frame."""
    base_geo = {p: geometry_fingerprint(views[p]) for p in POOLS}
    base_ms = {p: value_multiset_fingerprint(views[p].values) for p in POOLS}
    records: list = []
    violations: list = []
    ckpt = open(checkpoint_path, "w", encoding="utf-8") if checkpoint_path else None
    t0 = time.time()
    try:
        for rep in range(replicates):
            if deadline is not None and time.time() > deadline:
                return {"aborted": True, "reason": "wall-clock budget exhausted",
                        "replicates_completed": len(records),
                        "records": records, "violations": violations}
            cells_by_pool = {}
            inv_by_pool = {}
            for pool in POOLS:
                view = views[pool]
                vals = shuffled_values(view, rep)
                inv = replicate_invariants(view, vals, base_geo[pool],
                                           base_ms[pool])
                inv_by_pool[pool] = inv
                if not all(v for k, v in inv.items()
                           if k != "applicability_by_rung"):
                    violations.append({"replicate": rep, "pool": pool,
                                       "invariants": inv})
                cells_by_pool[pool] = ladder_cells(view, vals)
            summ = residue_summary(cells_by_pool)
            rec = {
                "replicate": rep,
                "residue_count": summ["residue_count"],
                "cells_full": summ["cells_full"],
                "cells_comparable": summ["cells_comparable"],
                "cells_vacuous": summ["cells_vacuous_in_residue_construction"],
                "by_pool": {p: summ["by_pool"][p]["residue"] for p in POOLS},
                "m3_family": summ["m3_family"],
                "by_functional": {k: v["residue"]
                                  for k, v in summ["by_functional"].items()},
                "cell_bitmap": summ["cell_bitmap"],
                "invariants_all_hold": all(
                    all(v for k, v in inv.items() if k != "applicability_by_rung")
                    for inv in inv_by_pool.values()),
            }
            records.append(rec)
            if ckpt:
                ckpt.write(json.dumps(rec, sort_keys=True) + "\n")
                ckpt.flush()
            if say and (rep + 1) % 20 == 0:
                say(f"   replicate {rep + 1}/{replicates} "
                    f"residue={rec['residue_count']} "
                    f"elapsed={time.time() - t0:.1f}s")
    finally:
        if ckpt:
            ckpt.close()
    return {"aborted": False, "replicates_completed": len(records),
            "records": records, "violations": violations,
            "wall_seconds": round(time.time() - t0, 3)}


# --------------------------------------------------------------------------
# the frozen decision rule
# --------------------------------------------------------------------------


def two_sided_empirical_p(observed: float, null: list) -> dict:
    """frozen_decision_rule.statistic, verbatim.

        p = (1 + #{replicates at least as extreme}) / (1 + n_replicates)

    with extremeness measured as |x - median(null)|. Counts and half-integer
    medians are exactly representable in float64, so the >= comparison is
    exact.
    """
    med = pystats.median(null) if null else float("nan")
    obs_ext = abs(observed - med)
    at_least = sum(1 for x in null if abs(x - med) >= obs_ext)
    n = len(null)
    return {
        "median_of_null": med,
        "observed": observed,
        "observed_extremeness_abs_dev_from_median": obs_ext,
        "n_replicates": n,
        "replicates_at_least_as_extreme": at_least,
        "p_value_two_sided": (1 + at_least) / (1 + n) if n else None,
        "resolution_floor": 1.0 / (1 + n) if n else None,
        "formula": "(1 + #{|x - median| >= |obs - median|}) / (1 + n)",
    }


def null_distribution_summary(values: list) -> dict:
    if not values:
        return {"n": 0}
    s = sorted(values)
    n = len(s)

    def q(f):
        # nearest-rank order statistic; no interpolation, so every reported
        # quantile is an actually-observed replicate value
        return s[min(n - 1, max(0, int(round(f * (n - 1)))))]

    return {
        "n": n, "min": s[0], "q05": q(0.05), "q25": q(0.25),
        "median": pystats.median(s), "q75": q(0.75), "q95": q(0.95),
        "max": s[-1],
        "mean": sum(s) / n,
        "sd": (pystats.stdev(s) if n > 1 else 0.0),
        "histogram": {str(v): s.count(v) for v in sorted(set(s))},
        "quantile_rule": "nearest-rank order statistic, no interpolation",
    }


def decide(gate: dict, null: dict, observed_residue: int,
           observed_m3: dict) -> dict:
    """Emit the terminal state. FROM INSIDE THE CODE, per the frozen rule."""
    invalid_reasons = []
    if gate["gate"] != "PASS":
        invalid_reasons.append(
            "SR-B1 reproduction gate FAILED: the observed type-A residue "
            f"count re-derived from committed version-1 artifacts is "
            f"D1={gate['derivations']['D1_committed_empirical_ratio']['total']}, "
            f"D2={gate['derivations']['D2_committed_closed_form_ratio']['total']}, "
            f"D3={gate['derivations']['D3_recomputed_from_per_curve_csv']['total']}, "
            f"against the frozen {FROZEN_OBSERVED_RESIDUE}.")
    if null.get("aborted"):
        invalid_reasons.append(f"null aborted: {null.get('reason')}")
    if null.get("violations"):
        v = null["violations"][0]
        invalid_reasons.append(
            f"{len(null['violations'])} replicate(s) altered the frozen "
            f"geometry or the value multiset; first at replicate "
            f"{v['replicate']} pool {v['pool']}")
    bad_applic = [r["replicate"] for r in null.get("records", [])
                  if not r["invariants_all_hold"]]
    if bad_applic:
        invalid_reasons.append(
            f"closed form lost `exact` applicability at replicates "
            f"{bad_applic[:5]}")
    n_done = null.get("replicates_completed", 0)
    if not invalid_reasons and n_done != REPLICATES:
        invalid_reasons.append(
            f"{n_done} replicates completed against the frozen {REPLICATES}")

    counts = [r["residue_count"] for r in null.get("records", [])]
    stat = two_sided_empirical_p(observed_residue, counts) if counts else None

    m3 = {}
    for k in M3_FAMILY:
        nullk = [r["m3_family"][k] for r in null.get("records", [])]
        m3[k] = {
            "observed": observed_m3[k],
            "cells": M3_CELLS,
            "null": null_distribution_summary(nullk),
            "two_sided": two_sided_empirical_p(observed_m3[k], nullk)
                         if nullk else None,
            "one_sided_upper_count_ge_observed":
                sum(1 for x in nullk if x >= observed_m3[k]),
            "one_sided_upper_p":
                ((1 + sum(1 for x in nullk if x >= observed_m3[k]))
                 / (1 + len(nullk))) if nullk else None,
            "p_value_note": (
                "The amendment's frozen p-value formula is stated for the "
                "residue COUNT. The same two-sided formula is applied here "
                "for consistency and the one-sided upper-tail count is "
                "reported beside it. THIS QUANTITY DOES NOT ENTER THE "
                "TERMINAL STATE, which the frozen rule keys to the residue "
                "count alone."),
        }

    if invalid_reasons:
        state = "state_0_INVALID"
        terminal = "INVALID"
        meaning = "Not evidence. Returns with the concrete defect."
    elif stat["p_value_two_sided"] > 0.05:
        state = "state_1_CONTROLLED_NULL"
        terminal = "CONTROLLED_NULL"
        meaning = (
            "p > 0.05. The residue is a pure artifact of N-band blocking "
            "geometry acting on an arbitrary value multiset, with NO "
            "ARITHMETIC CONTENT. Consequence: the contract's "
            "`what_non_decay_means` clause must be restricted to functionals "
            "with a declared minimum association to N, and every reading in "
            "this campaign that treats a non-rising R as an unnamed-nuisance "
            "tell must be re-read against that restriction.")
    else:
        state = "state_2_STRUCTURE_PRESENT"
        terminal = "STRUCTURE_PRESENT"
        meaning = (
            "p <= 0.05. The reversal pattern depends on WHICH curve carries "
            "which value, not merely on the blocking geometry. IT REMAINS AN "
            "INSTRUMENT FINDING AT TOY SCALE and licenses no claim about "
            "isogeny-class structure or ECDLP cost.")

    return {
        "control": CONTROL_ID,
        "experiment_id": EXPERIMENT_ID,
        "amendment": AMENDMENT,
        "frozen_decision_rule_statistic": (
            "Two-sided empirical p-value of the observed type-A residue count "
            "in the shuffled null, computed as (1 + #{replicates at least as "
            "extreme}) / (1 + n_replicates), extremeness measured as "
            "|x - median(null)|."),
        "terminal_state": terminal,
        "state_id": state,
        "state_meaning_as_frozen": meaning,
        "invalid_reasons": invalid_reasons,
        "observed_residue_count": observed_residue,
        "observed_residue_against_full_denominator":
            f"{observed_residue}/{FROZEN_DENOMINATOR_FULL}",
        "observed_residue_against_comparable_denominator":
            f"{observed_residue}/{FROZEN_DENOMINATOR_COMPARABLE}",
        "denominator_used_by_the_decision_rule":
            gate["denominators"]["which_the_decision_rule_used"],
        "reproduction_gate": gate["gate"],
        "null_distribution": null_distribution_summary(counts),
        "decision_statistic": stat,
        "m3_family_indicator": m3,
        "asymmetry_declared": ASYMMETRY_DECLARED,
        "evidence_strength_cap": (
            "Any evidence record arising from this control is capped at "
            "`preliminary` and `claim_tier: toy` regardless of outcome. Under "
            "AGENTS.md rule 12 the contradiction between a validated "
            "execution report and an independent review already requires "
            "further independent review before ANY evidence record is written "
            "from this line of work."),
        "scope": ("Tier TOY. p in {4001, 6007}. Instrument characterisation "
                  "only. No ECDLP claim either way. sota_delta zero on every "
                  "axis."),
        "emitted_by": "harness/ctrl_valueshuffle.py::decide",
    }


# --------------------------------------------------------------------------
# budget guards
# --------------------------------------------------------------------------


def cap_memory() -> dict:
    import resource
    try:
        soft, hard = resource.getrlimit(resource.RLIMIT_AS)
        want = MEMORY_LIMIT_GB * 1024 ** 3
        resource.setrlimit(resource.RLIMIT_AS,
                           (want, hard if hard != resource.RLIM_INFINITY
                            else want))
        return {"rlimit_as_bytes": want, "applied": True,
                "previous_soft": soft}
    except Exception as exc:                              # pragma: no cover
        return {"applied": False, "error": f"{type(exc).__name__}: {exc}"}


# --------------------------------------------------------------------------
# emission
# --------------------------------------------------------------------------


def _emit(run_suffix: str, metrics: dict, raw: dict, stdout: str,
          command: str, started: float, finished: float, status: str,
          valid: bool, invalid_reason=None) -> str:
    from .runner import RunResult, write_run
    return write_run(EXPERIMENT_ID, RUN_AREA, RunResult(
        run_suffix=run_suffix, curve_id=raw.get("curve_id", "n/a"),
        seed=SEEDS[0], parameters=raw.get("parameters", {}),
        metrics=metrics, certificate={"kind": "none"},
        valid=valid, invalid_reason=invalid_reason,
        stdout=stdout, stderr="", raw=raw),
        status=status, command=command, started=started, finished=finished)


def _dump(run_id: str, name: str, obj, text: bool = False) -> None:
    path = os.path.join(_run_dir(run_id), name)
    with open(path, "w", encoding="utf-8") as f:
        if text:
            f.write(obj)
        else:
            json.dump(obj, f, indent=2, sort_keys=True, default=str)


def main(argv=None) -> int:
    import argparse
    ap = argparse.ArgumentParser(
        description="CTRL-VALUESHUFFLE (EXP-INSTR-85b102 amendment v2)")
    ap.add_argument("--stage", required=True, choices=("gate", "control"))
    ap.add_argument("--replicates", type=int, default=REPLICATES)
    ap.add_argument("--suffix", required=True)
    ap.add_argument("--max-seconds", type=int, default=WALL_CLOCK_LIMIT_S)
    ap.add_argument("--base-ref", default="HEAD")
    ap.add_argument("--context-ref", default="origin/main")
    ap.add_argument("--checkpoint", default=None)
    args = ap.parse_args(argv)

    started = time.time()
    deadline = started + args.max_seconds
    mem = cap_memory()
    log: list = []

    def say(msg: str) -> None:
        log.append(msg)
        print(msg, flush=True)

    say(f"{CONTROL_ID} -- {EXPERIMENT_ID} amendment v{AMENDMENT_VERSION}")
    say(f"contract: {AMENDMENT}")
    say(f"stage={args.stage} replicates={args.replicates} "
        f"seeds={list(SEEDS)} max_seconds={args.max_seconds} "
        f"memory_cap={mem}")
    say("")

    say("0. FROZEN-FUNCTION RECEIPT (CTRL-FROZEN-DIFF, regenerated)")
    diff_text, diff_rep = rb.frozen_function_report(args.base_ref,
                                                    args.context_ref)
    say(f"   verdict: {diff_rep['verdict']}")
    say("")

    say("1. LOADING THE FOUR OPERATIVE POOLS FROM COMMITTED ARTIFACTS")
    views = {}
    for pool in POOLS:
        v = load_pool_view(pool, SOURCE_RUNS[pool])
        views[pool] = v
        say(f"   {pool:7s} run={SOURCE_RUNS[pool]:28s} p={v.p} n={v.n} "
            f"K={v.K} non-degenerate N-ladder rungs="
            f"{v.non_degenerate_ladder}")
    say("")

    say("2. SR-B1 REPRODUCTION GATE (BLOCKING, RUNS FIRST)")
    gate = reproduction_gate(views)
    for name, d in gate["derivations"].items():
        say(f"   {name:34s} total={d['total']:3d} by_pool={d['by_pool']} "
            f"comparable={d['comparable_cells']} full={d['full_cells']}")
    say(f"   frozen observed value: {FROZEN_OBSERVED_RESIDUE} of "
        f"{FROZEN_DENOMINATOR_FULL}  (comparable denominator "
        f"{FROZEN_DENOMINATOR_COMPARABLE})")
    say(f"   m = 3 family observed: {gate['m3_family_observed']} "
        f"(frozen {FROZEN_OBSERVED_M3}, reproduced="
        f"{gate['m3_family_reproduced']})")
    say(f"   restated verdict rule vs committed booleans: "
        f"{gate['derivations']['D1_committed_empirical_ratio']['restated_rule_vs_committed_boolean']}")
    say(f"   degeneracy is a ladder suffix: "
        f"{gate['degeneracy_is_a_ladder_suffix']}")
    say(f"   GATE: {gate['gate']}")
    say("")

    null = {"aborted": False, "replicates_completed": 0, "records": [],
            "violations": []}
    if gate["gate"] != "PASS":
        say("   GATE FAILED -- STOPPING BEFORE ANY REPLICATE IS DRAWN.")
        say("   The frozen 50 is NOT adjusted. Both numbers are reported.")
    elif args.stage == "control":
        say(f"3. SHUFFLED NULL: {args.replicates} replicates, "
            f"closed form only, no permutation study")
        null = run_null(views, args.replicates, deadline,
                        checkpoint_path=args.checkpoint, say=say)
        say(f"   replicates completed: {null['replicates_completed']}")
        say(f"   geometry/multiset violations: {len(null['violations'])}")
        say("")
    else:
        say("3. SHUFFLED NULL: NOT RUN AT THIS STAGE (--stage gate)")
        say("")

    observed_summary = gate["observed_cells"]
    decision = None
    if args.stage == "control":
        decision = decide(gate, null, observed_summary["residue_count"],
                          observed_summary["m3_family"])
        say("4. FROZEN DECISION RULE")
        say(f"   null: {json.dumps(decision['null_distribution']['histogram'])}")
        say(f"   null median={decision['null_distribution']['median']} "
            f"mean={decision['null_distribution']['mean']:.3f} "
            f"sd={decision['null_distribution']['sd']:.3f} "
            f"min={decision['null_distribution']['min']} "
            f"max={decision['null_distribution']['max']}")
        st = decision["decision_statistic"]
        say(f"   observed={st['observed']} |obs-median|="
            f"{st['observed_extremeness_abs_dev_from_median']} "
            f"at_least_as_extreme={st['replicates_at_least_as_extreme']}/"
            f"{st['n_replicates']}")
        say(f"   two-sided empirical p = {st['p_value_two_sided']:.6f} "
            f"(resolution floor {st['resolution_floor']:.6f})")
        for k in M3_FAMILY:
            m = decision["m3_family_indicator"][k]
            say(f"   {k:16s} observed {m['observed']}/{M3_CELLS} "
                f"null median={m['null']['median']} max={m['null']['max']} "
                f"two-sided p={m['two_sided']['p_value_two_sided']:.6f} "
                f"one-sided upper p={m['one_sided_upper_p']:.6f}")
        say("")
        say(f"   TERMINAL STATE: {decision['terminal_state']} "
            f"({decision['state_id']})")
        if decision["invalid_reasons"]:
            for r in decision["invalid_reasons"]:
                say(f"     invalid_reason: {r}")
        say("")

    finished = time.time()
    import resource as _res
    ru = _res.getrusage(_res.RUSAGE_SELF)
    cpu = round(ru.ru_utime + ru.ru_stime, 3)

    status = "completed"
    valid = True
    invalid_reason = None
    if null.get("aborted"):
        status = "failed_infrastructure"
        valid = False
        invalid_reason = (f"wall-clock budget of {args.max_seconds}s exhausted "
                          f"after {null['replicates_completed']} replicates; "
                          f"partial artifacts retained. Infrastructure "
                          f"failure, NEVER negative evidence "
                          f"(AGENTS.md rule 5).")
    elif decision is not None and decision["terminal_state"] == "INVALID":
        valid = False
        invalid_reason = "; ".join(decision["invalid_reasons"])
    elif gate["gate"] != "PASS":
        valid = False
        invalid_reason = ("SR-B1 reproduction gate FAILED; no replicate was "
                          "drawn and the discrepancy is the deliverable")

    metrics = {
        "control": CONTROL_ID,
        "stage": args.stage,
        "amendment": AMENDMENT,
        "reproduction_gate": gate["gate"],
        "observed_type_A_residue_count": observed_summary["residue_count"],
        "observed_residue_against_full_denominator":
            f"{observed_summary['residue_count']}/{observed_summary['cells_full']}",
        "observed_residue_against_comparable_denominator":
            f"{observed_summary['residue_count']}/{observed_summary['cells_comparable']}",
        "frozen_observed_residue_count": FROZEN_OBSERVED_RESIDUE,
        "observed_by_pool": {p: observed_summary["by_pool"][p]["residue"]
                             for p in POOLS},
        "observed_m3_family": observed_summary["m3_family"],
        "replicates_declared": args.replicates,
        "replicates_completed": null["replicates_completed"],
        "geometry_violations": len(null["violations"]),
        "terminal_state": (decision["terminal_state"] if decision
                           else "NOT EVALUATED AT THIS STAGE"),
        "two_sided_p_value": (decision["decision_statistic"]["p_value_two_sided"]
                              if decision and decision["decision_statistic"]
                              else None),
        "null_median": (decision["null_distribution"]["median"]
                        if decision else None),
        "frozen_function_diff_verdict": diff_rep["verdict"],
        "wall_seconds": round(finished - started, 3),
        "cpu_seconds": cpu,
        "peak_rss_bytes": ru.ru_maxrss * 1024,
        "certificate_note": CERTIFICATE_NOTE,
        "scope": ("Tier TOY. Instrument characterisation only. No ECDLP "
                  "claim, no cost or exponent claim, sota_delta zero."),
    }
    raw = {
        "control": CONTROL_ID,
        "curve_id": "n/a (control on four frozen pools; no curve is "
                    "re-enumerated and no functional is re-measured)",
        "parameters": {
            "amendment": AMENDMENT,
            "stage": args.stage,
            "replicates_declared": args.replicates,
            "seeds": list(SEEDS),
            "seed_derivation": ("SHA-256(DOMAIN|SHUFFLE|pool|functional|"
                                "replicate|seed0|seed1|seed2) mod 2^64"),
            "pools": list(POOLS),
            "source_runs": SOURCE_RUNS,
            "permutation_study": "NONE -- closed form only, B is not a "
                                 "parameter of this control",
            "verdict_tolerance": VERDICT_TOLERANCE,
            "max_seconds": args.max_seconds,
            "memory_cap": mem,
            "base_ref": args.base_ref,
            "context_ref": args.context_ref,
        },
        "reproduction_gate": gate,
        "null": {k: v for k, v in null.items() if k != "records"},
        "null_records": null["records"],
        "decision": decision,
        "frozen_function_diff": diff_rep,
        "pool_views": {
            p: {"run_id": views[p].run_id, "p": views[p].p, "n": views[p].n,
                "K": views[p].K, "class_traces": views[p].class_traces,
                "class_N": views[p].class_N,
                "class_sizes": views[p].class_sizes,
                "functionals": views[p].keys,
                "degenerate_by_rung": views[p].degenerate,
                "delta_max_by_rung": views[p].delta_max,
                "geometry_fingerprint": geometry_fingerprint(views[p]),
                "value_multiset_fingerprint":
                    value_multiset_fingerprint(views[p].values)}
            for p in POOLS},
    }
    cmd = (f"python3 -m harness.ctrl_valueshuffle --stage {args.stage} "
           f"--replicates {args.replicates} --suffix {args.suffix} "
           f"--max-seconds {args.max_seconds}")
    run_id = _emit(args.suffix, metrics, raw, "\n".join(log) + "\n", cmd,
                   started, finished, status, valid=valid,
                   invalid_reason=invalid_reason)
    print(f"wrote {run_id}", flush=True)

    _dump(run_id, "reproduction-gate.json", gate)
    _dump(run_id, "frozen_function_diff.txt", diff_text, text=True)
    _dump(run_id, "frozen_function_diff.json", diff_rep)
    if args.stage == "control":
        _dump(run_id, "valueshuffle-null.json", {
            "control": CONTROL_ID,
            "replicates_declared": args.replicates,
            "replicates_completed": null["replicates_completed"],
            "aborted": null.get("aborted"),
            "wall_seconds": null.get("wall_seconds"),
            "seeds": list(SEEDS),
            "seed_derivation": ("SHA-256(DOMAIN|SHUFFLE|pool|functional|"
                                "replicate|seed0|seed1|seed2) mod 2^64"),
            "permutation_study": "NONE",
            "residue_count_null": null_distribution_summary(
                [r["residue_count"] for r in null["records"]]),
            "comparable_cells_per_replicate": null_distribution_summary(
                [r["cells_comparable"] for r in null["records"]]),
            "vacuous_cells_per_replicate": null_distribution_summary(
                [r["cells_vacuous"] for r in null["records"]]),
            "by_pool_null": {
                p: null_distribution_summary([r["by_pool"][p]
                                              for r in null["records"]])
                for p in POOLS},
            "m3_family_null": {
                k: null_distribution_summary([r["m3_family"][k]
                                              for r in null["records"]])
                for k in M3_FAMILY},
            "per_functional_null_mean_residue": _per_functional_null(null),
            "geometry_violations": null["violations"],
            "records": null["records"],
        })
        _dump(run_id, "decision-rule-evaluation.json", decision)
    return 0


def _per_functional_null(null: dict) -> dict:
    out: dict = {}
    for rec in null.get("records", []):
        for k, v in rec["by_functional"].items():
            out.setdefault(k, []).append(v)
    return {k: {"mean": sum(v) / len(v), "min": min(v), "max": max(v),
                "n_replicates": len(v)} for k, v in out.items()}


if __name__ == "__main__":                                # pragma: no cover
    raise SystemExit(main())
