import json,os
D=os.path.dirname(os.path.abspath(__file__)); p=os.path.join(D,'RESULTS.json'); R=json.load(open(p))
R["findings"]=[
 {"id":"F1","label":"measured","segment":"1 and 2",
  "statement":"With the hint bytes taken from the TRUE key schedule, both constructions reproduce BATCH-001 exactly on this binary: 16 of 16 diagonals across 4 true-hint runs (TRUE6, TRUE7 at seed 90001 under contention; TRUE6-S2, TRUE7-S2 at seed 90031 uncontended) have exactly ONE surviving byte and it is the CORRECT byte. r=7 survivors 8034b976 in both runs, identical to BATCH-001 attack7_out.json; r=6 survivors fd,41,fd,7a matching attack6b_out.json rk_last."},
 {"id":"F2","label":"measured","segment":"1 and 2",
  "statement":"With ALL THREE hint bytes per diagonal taken from an INDEPENDENT WRONG key, the filter admits NO survivor. Across 44 diagonals from 11 completed trials (11 distinct secrets.token_hex(16) keys, 11 distinct seeds, 6 at r=6 plus 2 at r=7 uncontended in segment 2, 2 at r=6 plus 1 at r=7 in segment 1) the survivor-count histogram is {0: 44}. Zero unique survivors; the true byte appears nowhere in any survivor set; the wrong key's own corresponding byte appears nowhere either."},
 {"id":"F3","label":"measured, PRIORITY 1 OF THE RESUMED SEGMENT","segment":"2",
  "statement":"THE PARTIAL-HINT ARM. With only 1 of the 3 hint bytes per diagonal wrong (4 trials, r=6 and r=7) and with 2 of 3 wrong (3 trials, r=6 and r=7), the filter again admits NO survivor: 28 diagonals, histogram {0: 28}, zero unique survivors, true byte nowhere in any survivor set. A single false hint byte is enough to empty the candidate set.",
  "what_this_settles":"The filter is NOT insensitive to individual hint bytes. It requires EVERY hint byte to be correct. The alternative the coordinator named -- that a 1-of-3-wrong hint might still yield a unique correct survivor, which would have made the isolation weaker than 'needs the true hint' -- IS NOT WHAT WAS MEASURED, at 4 trials at 1-of-3 and 3 trials at 2-of-3."},
 {"id":"F4","label":"interpretation, stated in the strongest honest form the measurement supports","segment":"1 and 2",
  "statement":"HYPOTHESIS (B) -- that the filter admits exactly one survivor per diagonal for structural reasons and was correct in BATCH-001 only because the hint it was handed was correct -- IS REFUTED BY THIS MEASUREMENT. A false hint does not produce a different unique survivor; it produces NO survivor, and this holds whether 1, 2, or 3 of the 3 hint bytes per diagonal are false. The uniqueness BATCH-001 observed is therefore not an artefact of the survivor test, and the r=6 and r=7 constructions are consistent with hypothesis (A): hint-assisted isolation of the CORRECT byte, contingent on every supplied hint byte being correct.",
  "revision_from_segment_1":"The segment-1 version of this finding carried the caveat that all-wrong hints yielding zero survivors was consistent BOTH with 'the filter needs every hint byte' and with 'the filter is insensitive to some hint bytes'. The segment-2 partial-hint arm removes that ambiguity in favour of the first reading. No segment-1 number was changed; the interpretation was extended by new measurement.",
  "limits_of_this_statement":["One target key throughout.","11 all-wrong trials, 7 partial trials, 4 true-hint trials. All diagonals in every wrong or partial trial read exactly 0; no borderline case was observed, so no distributional claim about near-miss hints beyond 1-of-3 and 2-of-3 is made.","This says nothing about whether the constructions are USEFUL: r=6 remains dominated (see carried_forward) and r=7 remains not a key recovery.","Toy tier. Nothing here bears on full-round or deployed AES, and no comparison to published cryptanalysis is made in either direction."]},
 {"id":"F5","label":"measured, secondary","segment":"1 and 2","measured_values_only":True,
  "statement":"The separation is not visible in the bulk survivor count. Surviving (k3,k4) pairs summed over all 16 (diagonal,row) cells, per structure: TRUE6 [4066,32], TRUE7 [4066,32], TRUE6-S2 [4115,29], TRUE7-S2 [4115,29]; all-wrong WRONG6-01 [4108,16], WRONG6-02 [4177,21], WRONG7-02 [4003,11], WRONG6-B01 [4039,17], WRONG6-B02 [4083,8], WRONG6-B03 [4181,18], WRONG6-B04 [4035,9], WRONG6-B05 [4156,16], WRONG6-B06 [4019,18], WRONG7-B01 [4010,17], WRONG7-B02 [4084,17]; partial PART6-1of3-A [4080,8], PART6-1of3-B [4117,16], PART7-1of3-A [4116,15], PART7-1of3-B [4039,13], PART6-2of3-A [4200,23], PART6-2of3-B [3954,12], PART7-2of3-A [4084,11]. After one structure all arms sit near 4000-4200; after two, true arms retain 29-32 pairs and false arms 8-23. The decisive difference is the four-row consistency test, which the true byte passes by construction and which no false candidate passed in any measured diagonal. One structure is not decisive; two are."}]
R["incompleteness_and_dropped_work"]={
 "halted_on_budget":True,
 "segment_1":{"binding_stop_utc":"2026-08-02T17:56:47Z","halted_on_stamp":True,
   "shortfall":"3 of 8 required all-wrong trials completed; partial-hint arm never started.",
   "cause":"machine contention from concurrently scheduled producer tasks (coordinator-acknowledged scheduling error), not a defect of the object under test.",
   "failed_or_truncated_runs":[
     {"item":"WRONG6-03,04,05,06,07","status":"resource_exhaustion / budget truncation","detail":"Launched concurrently at 1 thread each at 17:31:54Z under load average 12. All five hit their 1150 s timeout (exit status 124) at 17:46 having completed only structure 0 of 2, so no per-diagonal verdict exists. NOT negative mathematical evidence; excluded from every distribution. Their first-structure bulk counts (4047, 4085, 3964, 4107, 4291) are recorded but carry no verdict."},
     {"item":"WRONG7-01","status":"operator/infrastructure termination","detail":"Started 17:29:19Z. At 17:31:20Z the executor killed its driver's GNU timeout wrapper while re-planning; timeout forwarded SIGTERM to the child, which died with 0 bytes of output. An executor protocol deviation, recorded and not repaired. Relaunched as WRONG7-02, which completed and is reported."}]},
 "segment_2":{"binding_stop_utc":"2026-08-02T18:40:12Z","halted_on_stamp":True,
   "completed":"All priority-1 partial-hint runs, 8 further all-wrong runs, and a matched uncontended true-hint pair. No segment-2 run failed, timed out, or was terminated.",
   "not_run":[{"item":"a third and fourth 2-of-3-wrong trial at r=7 (PART7-2of3-B), and all-wrong trials beyond 11","status":"NOT RUN","detail":"queued behind the completed work; the driver's budget check skipped nothing before the clock, and the remaining items were simply not queued deep enough to matter. The 2-of-3 arm at r=7 has 1 trial, the thinnest cell in the design."},
     {"item":"second target key","status":"NOT RUN","detail":"outside the frozen preregistration."}]},
 "totals":{"all_wrong_trials_completed":11,"all_wrong_trials_required_by_card":8,
   "partial_1of3_trials_completed":4,"partial_2of3_trials_completed":3,"true_hint_trials_completed":4,
   "runs_that_produced_no_verdict":6},
 "checks_that_did_not_run":[
  {"check":"adapter model probe","reason":"no resolvable adapter under this harness; model_verified false"},
  {"check":"independent re-verification certificate","reason":"certificate.kind is none: this is a pure measurement of survivor counts and claims no solve and no relation. The true-hint arms reproduce BATCH-001's certified bytes but this task mints no new certificate."},
  {"check":"cost re-measurement of the r=6 attack against exhaustive search","reason":"not in scope; BATCH-001's numbers are carried forward as BATCH-001 measurements. Segment-1 wall times were taken under contention and are not offered as cost measurements; segment-2 wall times are uncontended but were not taken under BATCH-001's measurement protocol and are likewise not offered as cost measurements."}]}
json.dump(R,open(p,'w'),indent=1); print("bytes",os.path.getsize(p))
