"""Emit a Rust constants module from exported chain-constant JSON files.

    python3 research/endosweep_20261005/emit_rust_constants.py \
        research/endosweep_20261005/cryptopro_b_chain_5_5_7.constants.json [more.json ...] > out.rs

Each JSON (from export_chain_constants.py) becomes one `pub const CHAIN_<NAME>: Chain`.
Field elements are emitted as little-endian u64 limb arrays of the CANONICAL
value (not Montgomery form); the consumer converts once at startup.
"""
from __future__ import annotations

import hashlib
import json
import sys


def limbs(hexstr: str) -> str:
    v = int(hexstr, 16)
    out = []
    for _ in range(4):
        out.append(f"0x{v & ((1 << 64) - 1):016X}")
        v >>= 64
    assert v == 0
    return "[" + ", ".join(out) + "]"


def main(paths: list[str]) -> int:
    print("//! Chain-endomorphism constants for GOST CryptoPro-B, generated by")
    print("//! research/endosweep_20261005/emit_rust_constants.py (crypto-autoresearcher) from")
    for pth in paths:
        h = hashlib.sha256(open(pth, "rb").read()).hexdigest()
        print(f"//!   {pth.split('/')[-1]}  sha256 {h}")
    print("//! Every field element is a canonical little-endian [u64; 4] value (NOT Montgomery form).")
    print("//! Polynomials are listed low-degree first. Do not edit by hand.")
    print("#![allow(clippy::unreadable_literal)]")
    print()
    print("pub struct ChainStep {")
    print("    pub ell: u32,")
    print("    pub domain_a: [u64; 4],")
    print("    pub domain_b: [u64; 4],")
    print("    pub codomain_a: [u64; 4],")
    print("    pub codomain_b: [u64; 4],")
    print("    /// monic kernel polynomial psi, degree (ell-1)/2, low first")
    print("    pub psi: &'static [[u64; 4]],")
    print("    /// numerator of the x-map: x' = N(x)/psi(x)^2, degree ell, low first")
    print("    pub n: &'static [[u64; 4]],")
    print("    /// numerator of the y-map: y' = y * M(x)/psi(x)^3, degree (3 ell - 3)/2, low first")
    print("    pub m: &'static [[u64; 4]],")
    print("}")
    print()
    print("pub struct TestVector {")
    print("    pub p: [[u64; 4]; 2],")
    print("    pub phi_p: [[u64; 4]; 2],")
    print("    pub k: [u64; 4],")
    print("    /// decomposition k = k1 + k2 * lambda (mod n); sign and magnitude")
    print("    pub k1_neg: bool,")
    print("    pub k1: [u64; 4],")
    print("    pub k2_neg: bool,")
    print("    pub k2: [u64; 4],")
    print("    pub k_p: [[u64; 4]; 2],")
    print("}")
    print()
    print("pub struct Chain {")
    print("    pub name: &'static str,")
    print("    pub degree: u64,")
    print("    pub steps: &'static [ChainStep],")
    print("    /// final isomorphism (x, y) -> (u^2 x, u^3 y) back to the curve")
    print("    pub iso_u: [u64; 4],")
    print("    /// eigenvalue lambda mod n of the composite on the prime-order subgroup")
    print("    pub lambda: [u64; 4],")
    print("    /// LLL-reduced basis of {(v1, v2): v1 + v2 lambda = 0 mod n}, rows (v1, v2) as signed decimal strings")
    print("    pub glv_basis: [[&'static str; 2]; 2],")
    print("    pub babai_bound_bits: u32,")
    print("    pub vectors: &'static [TestVector],")
    print("}")
    print()
    first = json.load(open(paths[0]))
    print(f"pub const P_HEX: &str = \"{first['p']}\";")
    print(f"pub const A_HEX: &str = \"{first['a']}\";")
    print(f"pub const B_HEX: &str = \"{first['b']}\";")
    print(f"pub const N_HEX: &str = \"{first['n']}\";")
    print(f"pub const P: [u64; 4] = {limbs(first['p'])};")
    print(f"pub const A: [u64; 4] = {limbs(first['a'])};")
    print(f"pub const B: [u64; 4] = {limbs(first['b'])};")
    print(f"pub const N: [u64; 4] = {limbs(first['n'])};")
    print()
    names = []
    for pth in paths:
        d = json.load(open(pth))
        tag = "_".join(str(s["ell"]) for s in d["steps"])
        name = f"CHAIN_{tag}"
        names.append(name)
        for k in ("p", "a", "b", "n"):
            assert d[k] == first[k]
        print(f"pub const {name}: Chain = Chain {{")
        print(f"    name: \"GOST CryptoPro-B chain {' * '.join(str(s['ell']) for s in d['steps'])} (element {d['element'][0]} + {d['element'][1]} w, degree {d['degree']})\",")
        print(f"    degree: {d['degree']},")
        print("    steps: &[")
        for s in d["steps"]:
            print("        ChainStep {")
            print(f"            ell: {s['ell']},")
            print(f"            domain_a: {limbs(s['domain']['a'])},")
            print(f"            domain_b: {limbs(s['domain']['b'])},")
            print(f"            codomain_a: {limbs(s['codomain']['a'])},")
            print(f"            codomain_b: {limbs(s['codomain']['b'])},")
            for key, fld in (("kernel_poly_low_first", "psi"), ("N_low_first", "n"), ("M_low_first", "m")):
                print(f"            {fld}: &[")
                for c in s[key]:
                    print(f"                {limbs(c)},")
                print("            ],")
            print("        },")
        print("    ],")
        print(f"    iso_u: {limbs(d['isomorphism_u'])},")
        print(f"    lambda: {limbs(d['eigenvalue'])},")
        gb = d["glv_basis"]
        print(f"    glv_basis: [[\"{gb[0][0]}\", \"{gb[0][1]}\"], [\"{gb[1][0]}\", \"{gb[1][1]}\"]],")
        print(f"    babai_bound_bits: {d['babai_bound_bits']},")
        print("    vectors: &[")
        for v in d["test_vectors"]:
            k1, k2 = int(v["k1"]), int(v["k2"])
            print("        TestVector {")
            print(f"            p: [{limbs(v['P'][0])}, {limbs(v['P'][1])}],")
            print(f"            phi_p: [{limbs(v['phiP'][0])}, {limbs(v['phiP'][1])}],")
            print(f"            k: {limbs(v['k'])},")
            print(f"            k1_neg: {'true' if k1 < 0 else 'false'}, k1: {limbs(hex(abs(k1)))},")
            print(f"            k2_neg: {'true' if k2 < 0 else 'false'}, k2: {limbs(hex(abs(k2)))},")
            print(f"            k_p: [{limbs(v['kP'][0])}, {limbs(v['kP'][1])}],")
            print("        },")
        print("    ],")
        print("};")
        print()
    print(f"pub const CHAINS: &[&Chain] = &[{', '.join('&' + n for n in names)}];")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
