"""Render the headline tables of the endomorphism-ring sweep from sweep/sweep.json.

Run from the repository root:

    python3 research/endosweep_20261005/make_tables.py > research/endosweep_20261005/TABLES.md

Every number in TABLES.md is read from the JSON the sweeper wrote; nothing
is typed in by hand.
"""
from __future__ import annotations

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SWEEP = os.path.join(HERE, "sweep", "sweep.json")


def main() -> int:
    with open(SWEEP) as f:
        data = json.load(f)
    opts = data["options"]
    results = data["results"]
    out: list[str] = []
    out.append("# Sweep tables (generated by make_tables.py from sweep/sweep.json)\n")
    out.append(f"Options: discriminant scan bound {opts['disc_bound']}, single-isogeny degree <= "
               f"{opts['small_norm_max']}, pump primes {opts['pump_primes']}, max dimension {opts['max_dim']}, "
               f"{opts['lattice_samples']} random scalars per lattice, affine tables = {opts['affine_tables']}.\n")

    # ---- Table 1: certificate and best configuration per target ----------
    out.append("## 1. Per-target certificate and best configuration\n")
    out.append("| target | family | n bits | CM discriminant | h(D) | min non-scalar degree | best | total M | generic M | speedup | literature |")
    out.append("|---|---|---|---|---|---|---|---|---|---|---|")
    for r in results:
        best = r["configs"][0]
        if r["cm_discriminant"] is not None:
            disc = str(r["cm_discriminant"])
            mind = str(r["min_nonscalar_degree"])
        elif r["frobenius_discriminant_bits"]:
            disc = f"|D_K| > {opts['disc_bound']} (certified)"
            mind = f">= {opts['disc_bound'] // 4}"
        else:
            disc, mind = "n/a (declared generators)", ""
        hcl = "" if r["class_number"] is None else str(r["class_number"])
        out.append(f"| {r['name']} | {r['family']} | {r['n_bits']} | {disc} | {hcl} | {mind} | {best['label']} | "
                   f"{best['cost_M']:.0f} | {r['generic_cost_M']:.0f} | {best['speedup_vs_generic']:.2f}x | {best['known_as']} |")
    out.append("")

    # ---- Table 2: paid pumps vs the configuration they try to beat ------
    out.append("## 2. Isogeny-cycle pumps against the best pump-free configuration\n")
    out.append("The pump's price per bit of height is 2*cost(ell-step)/log2(ell) field multiplications; "
               "the doubling it replaces costs DBL_M. A pump can only win if its price per bit is below DBL_M, "
               "and even then it must also pay for the extra precomputed tables.\n")
    out.append("| target | DBL M | cheapest pump (ell, cycle length, M/bit) | best pump config | dim | coeff bits | pump total M | best pump-free config | total M | pump outcome |")
    out.append("|---|---|---|---|---|---|---|---|---|---|")
    for r in results:
        if not r["pumps"]:
            continue
        pumps = sorted(r["pumps"], key=lambda p: p["cost_per_height_bit_M"])
        cp = pumps[0]
        pump_cfgs = [c for c in r["configs"] if c["label"].startswith("pump")]
        free_cfgs = [c for c in r["configs"] if not c["label"].startswith("pump")]
        if not pump_cfgs:
            continue
        pb = pump_cfgs[0]
        fb = free_cfgs[0]
        dbl = pb["cost_breakdown"].get("DBL_M")
        delta = (pb["cost_M"] - fb["cost_M"]) / fb["cost_M"] * 100
        verdict = f"loses by {delta:.1f}%" if delta > 0 else f"wins by {-delta:.1f}%"
        out.append(f"| {r['name']} | {dbl} | ({cp['ell']}, {cp['cycle_length']}, {cp['cost_per_height_bit_M']:.1f}) | "
                   f"{pb['label']} | {pb['dim']} | {pb['coeff_bits_bound']}/{pb['coeff_bits_empirical']} | {pb['cost_M']:.0f} | "
                   f"{fb['label']} | {fb['cost_M']:.0f} | {verdict} |")
    out.append("")

    # ---- Table 3: free pumps (Frobenius-type generators) ------------------
    out.append("## 3. Frobenius-type (free) generators: dimension versus coefficient size\n")
    out.append("| target | config | dim | coeff bits bound/emp/ideal | reduced-basis inf-norm bits | total M | speedup | literature |")
    out.append("|---|---|---|---|---|---|---|---|")
    for r in results:
        if not any(c["label"].startswith(("frob", "2-dim")) for c in r["configs"]):
            continue
        for c in r["configs"]:
            if c["label"].startswith(("frob", "2-dim", "GLV-2", "generic")):
                out.append(f"| {r['name']} | {c['label']} | {c['dim']} | {c['coeff_bits_bound']}/{c['coeff_bits_empirical']}/"
                           f"{c['balanced_bits']:.1f} | {c['basis_inf_norm_bits']} | {c['cost_M']:.0f} | "
                           f"{c['speedup_vs_generic']:.2f}x | {c['known_as']} |")
    out.append("")

    # ---- Table 4: which configurations carry no literature label ---------
    out.append("## 4. Configurations with no literature match, best instance per target\n")
    out.append("| target | config | dim | coeff bits | total M | best known config | its M | gap |")
    out.append("|---|---|---|---|---|---|---|---|")
    for r in results:
        novel = [c for c in r["configs"] if c["known_as"].startswith("no literature match")]
        known = [c for c in r["configs"] if not c["known_as"].startswith("no literature match")]
        if not novel or not known:
            continue
        nb, kb = novel[0], known[0]
        gap = (nb["cost_M"] - kb["cost_M"]) / kb["cost_M"] * 100
        out.append(f"| {r['name']} | {nb['label']} | {nb['dim']} | {nb['coeff_bits_bound']}/{nb['coeff_bits_empirical']} | "
                   f"{nb['cost_M']:.0f} | {kb['label']} | {kb['cost_M']:.0f} | {gap:+.1f}% |")
    out.append("")
    sys.stdout.write("\n".join(out))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
