#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
od1_gate701c_v2.py
==================

TASK-20260801-801, GOAL-AES-001 BATCH-003.

Two computations, in one self-contained script depending on nothing outside
the Python standard library:

  PHASE `graph`  -- OD-1.  Exact all-pairs BFS on the directed 1020-node
      (lambda, k) graph of verify_derivation.py claim C11: nodes (lambda, k)
      for lambda in GF(2^8)^* and k in {0,1,2,3}; edges
      (lambda, k) -> (lambda * M[j][k], j) for every j in {0,1,2,3}, with M the
      AES MixColumns circulant of first row (02,03,01,01).  Reports the full
      eccentricity distribution, the DIAMETER, the radius and a realizing pair
      on the forward graph AND on the reverse graph, re-confirms strong
      connectivity independently of C11 (Kosaraju, plus the forward/reverse
      reachability counts), and additionally analyses the 2-STEP graph G^2,
      which is the object the OD-1 extension argument actually needs (each
      graph edge of the extension costs TWO interfaces; see the report).

  PHASE `construction` -- GATE-701-C v2 construction validation, run and
      recorded BEFORE the gate itself.  Builds the three GF(2^4) matrices,
      and for each one checks: entries all nonzero (or not), invertibility,
      the multiplicative subgroup generated by the entries and its order, and
      the strongly-connected-component structure of the induced (lambda, k)
      graph over GF(2^4).  This is construction validation of the null
      objects, not outcome selection: it inspects the MATRICES, never the
      gate reading.

  PHASE `gate` -- GATE-701-C v2 itself.  For each of the three matrices and
      for every one of the 65535 nonzero Delta in GF(2^4)^4, computes the
      GF(2)-dimension of the smallest GF(2)-subspace containing
      Delta_i * m_i (i = least index with Delta_i != 0) and closed under the
      four GF(2)-linear maps T_j(u) = u_j * m_j, where m_j is column j of the
      matrix.  Reports the full dimension histogram per matrix.

DETERMINISM.  There is NO randomness anywhere in this script.  Every
computation is exhaustive over a finite set, in a fixed enumeration order, and
the output is byte-identical on re-execution.  No seed is required and none is
used; `seeds: {}` in the results file records exactly that, rather than
inventing one.

SUPERSESSION.  This file SUPERSEDES the GATE-701-C specification in
coordination/goals/GOAL-AES-001/batches/BATCH-002/tasks/TASK-20260731-701/
candidate_report.yaml (falsification_gate, null_object_control.null_2) and the
validator-authored gate701c.py described in TASK-20260731-705
derivation_and_ideation_review.md section 7.4.  It does NOT modify either.
Every BATCH-001 and BATCH-002 artifact is immutable and is left exactly as
committed.

SCOPE.  Nothing in this script is a cryptanalytic claim about AES.  It is
derivation-level computation about the algebra of AES components and about a
scaled-down GF(2^4) analogue.  It asserts NOTHING about AES at any round
count, is not a distinguisher, and is not a barrier statement about AES
security.

inference:
  policy: executor-implementation
  requested_policy: executor-implementation
  resolved_model_id: claude-opus-5
  fallback_used: true
  fallback_reason: >-
    Structural.  Under this Claude Code harness the
    orchestration/model-policies.yaml policy aliases cannot be resolved by
    subagent frontmatter (CLAUDE.md, "Model policy note"); all subagents run
    `model: inherit`.  The requested policy is recorded and the resolved model
    is recorded; no silent substitution.
  model_verified: false        # `python3 -m orchestration.adapter doctor --probe` NOT run
  reasoning_effort: unrecorded
  independent_session: false
  standing_basis: inference-amendment commit 0137a051eb5828789eb267fa83c8278086578d4c
  provenance_basis: protocol-amendment-GOAL-AES-001-002 (comment-block stanza +
    artifact_provenance digest list in od1_gate701c_results.json)

Usage:
    python3 od1_gate701c_v2.py --phase graph
    python3 od1_gate701c_v2.py --phase construction
    python3 od1_gate701c_v2.py --phase gate
    python3 od1_gate701c_v2.py --phase all        # graph + construction + gate

Each phase writes a JSON object to stdout after a human-readable log on
stderr, so the phases can be captured separately and merged into the manifest.
"""

from __future__ import annotations

import argparse
import collections
import json
import sys
import time
from typing import Dict, List, Sequence, Tuple

# ===========================================================================
# GF(2^8) -- for the OD-1 graph phase.  Reference multiplication only; no
# tables are trusted.
# ===========================================================================

MOD8 = 0x11B  # x^8 + x^4 + x^3 + x + 1


def gmul8(a: int, b: int) -> int:
    a &= 0xFF
    b &= 0xFF
    r = 0
    while b:
        if b & 1:
            r ^= a
        b >>= 1
        a <<= 1
        if a & 0x100:
            a ^= MOD8
    return r & 0xFF


# AES MixColumns, circulant with first row (02,03,01,01); M[i][j] = c[(j-i)%4].
M8 = (
    (0x02, 0x03, 0x01, 0x01),
    (0x01, 0x02, 0x03, 0x01),
    (0x01, 0x01, 0x02, 0x03),
    (0x03, 0x01, 0x01, 0x02),
)

# ===========================================================================
# GF(2^4) -- for the gate phase.  Modulus x^4 + x + 1 (primitive), matching
# the TASK-20260731-705 validator's gate701c.py as described in section 7.4.
# ===========================================================================

MOD4 = 0x13  # x^4 + x + 1


def gmul4(a: int, b: int) -> int:
    a &= 0xF
    b &= 0xF
    r = 0
    while b:
        if b & 1:
            r ^= a
        b >>= 1
        a <<= 1
        if a & 0x10:
            a ^= MOD4
    return r & 0xF


def circulant(first_row: Sequence[int]) -> Tuple[Tuple[int, ...], ...]:
    """M[i][j] = first_row[(j - i) mod 4], the same convention as the AES
    MixColumns matrix hard-coded above."""
    c = list(first_row)
    return tuple(tuple(c[(j - i) % 4] for j in range(4)) for i in range(4))


def rank_gf(mat, mul, inv_of) -> int:
    """Gauss-Jordan rank over a field with the supplied multiplication."""
    m = [list(row) for row in mat]
    n = len(m)
    row = 0
    for col in range(n):
        piv = None
        for r in range(row, n):
            if m[r][col]:
                piv = r
                break
        if piv is None:
            continue
        m[row], m[piv] = m[piv], m[row]
        iv = inv_of(m[row][col])
        m[row] = [mul(iv, x) for x in m[row]]
        for r in range(n):
            if r != row and m[r][col]:
                f = m[r][col]
                m[r] = [x ^ mul(f, y) for x, y in zip(m[r], m[row])]
        row += 1
    return row


def inv4(a: int) -> int:
    for x in range(1, 16):
        if gmul4(a, x) == 1:
            return x
    raise ZeroDivisionError(a)


def inv8(a: int) -> int:
    for x in range(1, 256):
        if gmul8(a, x) == 1:
            return x
    raise ZeroDivisionError(a)


def subgroup_generated(gens, mul, order_of_group: int) -> List[int]:
    """Multiplicative subgroup generated by a set of nonzero field elements."""
    seen = {1}
    stack = [1]
    while stack:
        x = stack.pop()
        for g in gens:
            if g == 0:
                continue
            y = mul(x, g)
            if y not in seen:
                seen.add(y)
                stack.append(y)
    return sorted(seen)


# ===========================================================================
# The (lambda, k) graph, over an arbitrary field size.
# ===========================================================================

def build_lambda_k_graph(mat, mul, q: int):
    """Nodes (lambda, k), lambda in {1..q-1}, k in 0..3.
    Edges (lambda,k) -> (lambda*mat[j][k], j) for every j.
    An edge whose target scalar is 0 (possible only if mat has a zero entry)
    leaves the node set and is DROPPED, which is recorded explicitly."""
    nodes = [(lam, k) for lam in range(1, q) for k in range(4)]
    index = {n: i for i, n in enumerate(nodes)}
    fwd: List[List[int]] = [[] for _ in nodes]
    rev: List[List[int]] = [[] for _ in nodes]
    dropped = 0
    for (lam, k) in nodes:
        u = index[(lam, k)]
        for j in range(4):
            t = mul(lam, mat[j][k])
            if t == 0:
                dropped += 1
                continue
            v = index[(t, j)]
            fwd[u].append(v)
            rev[v].append(u)
    return nodes, index, fwd, rev, dropped


def bfs_dist(adj: List[List[int]], src: int) -> List[int]:
    n = len(adj)
    dist = [-1] * n
    dist[src] = 0
    dq = collections.deque([src])
    while dq:
        u = dq.popleft()
        du = dist[u] + 1
        for v in adj[u]:
            if dist[v] < 0:
                dist[v] = du
                dq.append(v)
    return dist


def all_pairs_stats(adj: List[List[int]], nodes) -> Dict:
    n = len(adj)
    ecc = [0] * n
    diameter = -1
    realizing = None
    unreachable_pairs = 0
    for s in range(n):
        d = bfs_dist(adj, s)
        mx, arg = -1, None
        for t in range(n):
            if d[t] < 0:
                unreachable_pairs += 1
                continue
            if d[t] > mx:
                mx, arg = d[t], t
        ecc[s] = mx
        if mx > diameter:
            diameter = mx
            realizing = (nodes[s], nodes[arg], mx)
    dist_hist = collections.Counter(ecc)
    return {
        "n_nodes": n,
        "diameter": diameter,
        "radius": min(ecc),
        "eccentricity_distribution": {str(k): v for k, v in sorted(dist_hist.items())},
        "realizing_pair_at_diameter": {
            "source": {"lambda": hex(realizing[0][0]), "k": realizing[0][1]},
            "target": {"lambda": hex(realizing[1][0]), "k": realizing[1][1]},
            "distance": realizing[2],
        },
        "ordered_pairs_with_no_path": unreachable_pairs,
    }


def scc_kosaraju(fwd: List[List[int]], rev: List[List[int]]) -> List[List[int]]:
    n = len(fwd)
    visited = [False] * n
    order: List[int] = []
    for s in range(n):
        if visited[s]:
            continue
        stack = [(s, 0)]
        visited[s] = True
        while stack:
            u, i = stack.pop()
            if i < len(fwd[u]):
                stack.append((u, i + 1))
                v = fwd[u][i]
                if not visited[v]:
                    visited[v] = True
                    stack.append((v, 0))
            else:
                order.append(u)
    comp = [-1] * n
    comps: List[List[int]] = []
    for s in reversed(order):
        if comp[s] >= 0:
            continue
        cid = len(comps)
        cur = [s]
        comp[s] = cid
        stack = [s]
        while stack:
            u = stack.pop()
            for v in rev[u]:
                if comp[v] < 0:
                    comp[v] = cid
                    cur.append(v)
                    stack.append(v)
        comps.append(cur)
    return comps


# ===========================================================================
# PHASE `graph`: OD-1
# ===========================================================================

def phase_graph() -> Dict:
    t0 = time.time()
    nodes, index, fwd, rev, dropped = build_lambda_k_graph(M8, gmul8, 256)
    assert dropped == 0, "AES M has no zero entry; no edge may be dropped"

    fwd_stats = all_pairs_stats(fwd, nodes)
    rev_stats = all_pairs_stats(rev, nodes)

    # Independent re-confirmation of strong connectivity, three ways:
    #  (i) single-source forward and reverse reachability from (0x01, k=0);
    #  (ii) Kosaraju SCC decomposition;
    #  (iii) implied by the all-pairs BFS above (no unreachable ordered pair).
    d0 = bfs_dist(fwd, index[(1, 0)])
    r0 = bfs_dist(rev, index[(1, 0)])
    comps = scc_kosaraju(fwd, rev)

    # ---- 2-step graph G^2.  The OD-1 extension consumes TWO interfaces per
    # graph edge (Step 1 at one interface, Step 2's upgrade at the next), so
    # the object it needs is walks of EVEN length.
    g2: List[List[int]] = []
    for u in range(len(nodes)):
        s = set()
        for v in fwd[u]:
            s.update(fwd[v])
        g2.append(sorted(s))
    self_loops_g2 = sum(1 for u in range(len(nodes)) if u in set(g2[u]))
    g2_rev: List[List[int]] = [[] for _ in nodes]
    for u in range(len(nodes)):
        for v in g2[u]:
            g2_rev[v].append(u)
    g2_stats = all_pairs_stats(g2, nodes)
    g2_comps = scc_kosaraju(g2, g2_rev)

    # ---- n_star: the quantity the extension proposition actually uses.
    # A collision Delta of pi^(0) with least nonzero coordinate index i and
    # value mu = Delta_i yields GLOBAL invariance of pi^(2) at the four nodes
    # S0(mu, i) = {(mu * M[k][i], k) : k = 0..3}.  Each further pair of
    # interfaces advances every held node by one G^2 step.  n_star is the
    # worst case, over all 1020 possible (mu, i), of the number of G^2 steps
    # needed for S0 to cover ALL 1020 nodes.
    n_star = -1
    n_star_witness = None
    per_start = {}
    for (mu, i) in nodes:
        s0 = [index[(gmul8(mu, M8[k][i]), k)] for k in range(4)]
        dist = [-1] * len(nodes)
        dq = collections.deque()
        for u in set(s0):
            dist[u] = 0
            dq.append(u)
        while dq:
            u = dq.popleft()
            du = dist[u] + 1
            for v in g2[u]:
                if dist[v] < 0:
                    dist[v] = du
                    dq.append(v)
        m = max(dist)
        per_start[(mu, i)] = m
        if m > n_star:
            n_star = m
            n_star_witness = (mu, i)
    n_star_hist = collections.Counter(per_start.values())

    return {
        "phase": "graph",
        "object": "directed (lambda,k) graph of verify_derivation.py claim C11",
        "field": "GF(2^8), modulus 0x11B",
        "matrix": "AES MixColumns circulant, first row (02,03,01,01)",
        "node_count": len(nodes),
        "edges_dropped_to_zero_scalar": dropped,
        "forward_graph": fwd_stats,
        "reverse_graph": rev_stats,
        "strong_connectivity_recheck": {
            "forward_reachable_from_0x01_k0": sum(1 for x in d0 if x >= 0),
            "reverse_reachable_from_0x01_k0": sum(1 for x in r0 if x >= 0),
            "kosaraju_scc_count": len(comps),
            "largest_scc_size": max(len(c) for c in comps),
            "strongly_connected": len(comps) == 1,
            "independent_of_C11": True,
        },
        "two_step_graph_G2": {
            "note": "edges of G2 are walks of length exactly 2 in G",
            "nodes_with_self_loop": self_loops_g2,
            "scc_count": len(g2_comps),
            "strongly_connected": len(g2_comps) == 1,
            **g2_stats,
        },
        "n_star": {
            "definition": "max over the 1020 possible (mu,i) of the number of "
                          "G2-steps for S0(mu,i) = {(mu*M[k][i], k) : k=0..3} "
                          "to cover all 1020 nodes",
            "value": n_star,
            "witness_mu_i": {"mu": hex(n_star_witness[0]), "i": n_star_witness[1]},
            "distribution": {str(k): v for k, v in sorted(n_star_hist.items())},
        },
        "wall_clock_seconds": round(time.time() - t0, 3),
    }


# ===========================================================================
# PHASE `construction`: GATE-701-C v2 null construction validation
# ===========================================================================

# The three matrices, fixed here BEFORE the gate is run.
#
# target : AES-shaped GF(2^4) analogue, circulant first row (02,03,01,01).
# null_1 : the identity interface (ShiftRows + AddRoundKey, no MixColumns).
#          Unchanged from the BATCH-002 specification; it is the sensitivity
#          anchor, not the Step-3 negation.
# null_2 : REDESIGNED.  Selection rule, fixed a priori and stated in the
#          report before measurement:
#            (1) H := the order-3 subgroup of GF(2^4)^* , i.e. GF(4)^* , the
#                multiplicative group of the subfield GF(4) < GF(2^4).  It is
#                proper (3 | 15, 3 != 15).  It is chosen among the two proper
#                nontrivial subgroups (orders 3 and 5) on the STRUCTURAL
#                ground that it is the only one that is the multiplicative
#                group of a subfield, which is what makes the predicted stall
#                hand-checkable -- the same standard the gate imposes on
#                null_1 ("sensitivity is demonstrated, not assumed").
#            (2) Among 4x4 circulants with all entries in H, enumerate first
#                rows alpha^(5*e) for e in {0,1,2}^4 in lexicographic order of
#                (e0,e1,e2,e3) and take the FIRST invertible one.
#          That rule is deterministic and yields exactly ONE candidate, which
#          is then verified and run once.
TARGET_FIRST_ROW = (0x2, 0x3, 0x1, 0x1)


def _alpha_pow4(e: int) -> int:
    x = 1
    for _ in range(e % 15):
        x = gmul4(x, 0x2)
    return x


def select_null2() -> Dict:
    """Executes the a-priori selection rule and records the whole enumeration."""
    H = sorted({_alpha_pow4(5 * t) for t in range(3)})
    trace = []
    chosen = None
    for e0 in range(3):
        for e1 in range(3):
            for e2 in range(3):
                for e3 in range(3):
                    row = tuple(_alpha_pow4(5 * e) for e in (e0, e1, e2, e3))
                    mat = circulant(row)
                    rk = rank_gf(mat, gmul4, inv4)
                    trace.append({
                        "exponent_tuple": [e0, e1, e2, e3],
                        "first_row": [hex(x) for x in row],
                        "rank": rk,
                        "invertible": rk == 4,
                    })
                    if rk == 4 and chosen is None:
                        chosen = row
                    if chosen is not None:
                        return {
                            "subgroup_H": [hex(x) for x in H],
                            "subgroup_order": len(H),
                            "group_order": 15,
                            "proper": len(H) < 15,
                            "enumeration_trace_until_first_invertible": trace,
                            "selected_first_row": [hex(x) for x in chosen],
                        }
    raise RuntimeError("no invertible circulant over H -- would itself be the finding")


def matrix_facts(name: str, mat) -> Dict:
    entries = [mat[i][j] for i in range(4) for j in range(4)]
    gens = sorted({e for e in entries if e != 0})
    sub = subgroup_generated(gens, gmul4, 15) if gens else [1]
    rk = rank_gf(mat, gmul4, inv4)
    nodes, index, fwd, rev, dropped = build_lambda_k_graph(mat, gmul4, 16)
    comps = scc_kosaraju(fwd, rev)
    sizes = collections.Counter(len(c) for c in comps)
    # component structure described by the lambda-cosets they occupy
    comp_lambda_sets = []
    for c in sorted(comps, key=len, reverse=True)[:6]:
        lams = sorted({nodes[u][0] for u in c})
        comp_lambda_sets.append({
            "size": len(c),
            "lambdas": [hex(x) for x in lams],
            "indices_k": sorted({nodes[u][1] for u in c}),
        })
    return {
        "name": name,
        "matrix_rows": [[hex(x) for x in row] for row in mat],
        "all_entries_nonzero": all(e != 0 for e in entries),
        "distinct_entries": [hex(x) for x in sorted(set(entries))],
        "rank_over_GF(2^4)": rk,
        "invertible": rk == 4,
        "subgroup_generated_by_entries": [hex(x) for x in sub],
        "subgroup_order": len(sub),
        "subgroup_is_proper": len(sub) < 15,
        "lambda_k_graph_over_GF(2^4)": {
            "node_count": len(nodes),
            "edges_dropped_to_zero_scalar": dropped,
            "scc_count": len(comps),
            "strongly_connected": len(comps) == 1,
            "scc_size_histogram": {str(k): v for k, v in sorted(sizes.items())},
            "largest_components": comp_lambda_sets,
        },
    }


def build_matrices() -> Tuple[Dict, Dict]:
    sel = select_null2()
    mats = {
        "target": circulant(TARGET_FIRST_ROW),
        "null_1": tuple(tuple(1 if i == j else 0 for j in range(4)) for i in range(4)),
        "null_2": circulant([int(x, 16) for x in sel["selected_first_row"]]),
    }
    return mats, sel


def phase_construction() -> Dict:
    t0 = time.time()
    mats, sel = build_matrices()
    facts = {name: matrix_facts(name, m) for name, m in mats.items()}
    return {
        "phase": "construction",
        "field": "GF(2^4), modulus 0x13 (x^4+x+1), alpha=0x2 primitive",
        "null_2_selection": sel,
        "matrices": facts,
        "wall_clock_seconds": round(time.time() - t0, 3),
    }


# ===========================================================================
# PHASE `gate`: GATE-701-C v2
# ===========================================================================

def closure_dimension(delta: int, cols: List[List[int]]) -> int:
    """delta is a 16-bit packed vector of four GF(2^4) nibbles, nibble i at
    bits 4i..4i+3.  cols[j] is column j of the matrix as a list of 4 nibbles.

    Returns the GF(2)-dimension of the smallest GF(2)-subspace of GF(2^4)^4
    containing v0 = Delta_i * m_i (i the least index with Delta_i != 0) and
    closed under the four maps T_j(u) = u_j * m_j.  Each T_j is GF(2)-LINEAR
    (coordinate extraction is GF(2)-linear and w -> w * m_j is GF(2)-linear),
    so closing on a spanning set suffices."""
    i = 0
    while ((delta >> (4 * i)) & 0xF) == 0:
        i += 1
    lam = (delta >> (4 * i)) & 0xF
    v0 = 0
    for r in range(4):
        v0 |= gmul4(lam, cols[i][r]) << (4 * r)

    basis: List[int] = []          # row-echelon basis of 16-bit words
    pivots: List[int] = []

    def add(v: int) -> bool:
        for p, b in zip(pivots, basis):
            if v >> p & 1:
                v ^= b
        if v == 0:
            return False
        p = v.bit_length() - 1
        basis.append(v)
        pivots.append(p)
        # keep sorted by pivot descending for a stable reduction order
        order = sorted(range(len(basis)), key=lambda t: -pivots[t])
        basis[:] = [basis[t] for t in order]
        pivots[:] = [pivots[t] for t in order]
        return True

    work = []
    if add(v0):
        work.append(v0)
    while work:
        u = work.pop()
        for j in range(4):
            uj = (u >> (4 * j)) & 0xF
            if uj == 0:
                continue
            w = 0
            for r in range(4):
                w |= gmul4(uj, cols[j][r]) << (4 * r)
            if w and add(w):
                work.append(w)
    return len(basis)


def phase_gate() -> Dict:
    mats, sel = build_matrices()
    results = {}
    for name in ("target", "null_1", "null_2"):
        mat = mats[name]
        cols = [[mat[r][j] for r in range(4)] for j in range(4)]
        t0 = time.time()
        hist = collections.Counter()
        for delta in range(1, 1 << 16):
            hist[closure_dimension(delta, cols)] += 1
        el = time.time() - t0
        results[name] = {
            "matrix_rows": [[hex(x) for x in row] for row in mat],
            "deltas_tested": (1 << 16) - 1,
            "dimension_histogram": {str(k): v for k, v in sorted(hist.items())},
            "count_reaching_dim_16": hist.get(16, 0),
            "max_dimension": max(hist),
            "min_dimension": min(hist),
            "wall_clock_seconds": round(el, 3),
        }
    return {"phase": "gate", "per_matrix": results}


# ===========================================================================

def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--phase", choices=["graph", "construction", "gate", "all"],
                    required=True)
    args = ap.parse_args()
    out = {}
    if args.phase in ("graph", "all"):
        sys.stderr.write("[phase graph] all-pairs BFS on 1020 nodes ...\n")
        out["graph"] = phase_graph()
    if args.phase in ("construction", "all"):
        sys.stderr.write("[phase construction] null construction validation ...\n")
        out["construction"] = phase_construction()
    if args.phase in ("gate", "all"):
        sys.stderr.write("[phase gate] 3 x 65535 closures ...\n")
        out["gate"] = phase_gate()
    json.dump(out, sys.stdout, indent=1, sort_keys=False)
    sys.stdout.write("\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
