#!/usr/bin/env python3
"""
Assemble the three declared deliverables.

EVERY frontier value is READ FROM the frozen file at run time and its sha256 is
recomputed here.  No frontier number is transcribed into this file, into the
report template, or into any comparison; the report is generated from what is
read.  (CORRECTION-predeclared-target-values.md: hand-transcription put two of
three pre-declared incumbents wrong in the previous batch.)

The heights of the reported candidates are RECOMPUTED FROM THEIR MINIMAL
a-INVARIANTS ALONE, in pure Python with no PARI, and compared with the value
PARI produced.  Their ranks are RE-CERTIFIED here by a second, separate
invocation of exact_certify.py on the exhibited points.  And every reported
curve_key is checked against the frozen ICARM snapshot so that a board curve
cannot be rediscovered and reported as new.

usage: build_deliverables.py TASKDIR
"""
import hashlib
import json
import math
import os
import statistics as st
import sys
from fractions import Fraction as F

import exact_certify as ec
import measure

REPO = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                    *(['..'] * 8)))
FRONTIER = os.path.join(REPO, 'coordination/goals/GOAL-ECQ-002/baseline/'
                              'frontier_20260823.json')
SNAPSHOT = os.path.join(REPO, 'coordination/goals/GOAL-ECQ-002/baseline/'
                              'icarm_database_20260823.json')

INTERMEDIATE_BENCHMARK = 79.329   # from H-ECQ-8b600d intermediate_benchmark.value
INTERMEDIATE_BENCHMARK_SOURCE = ('H-ECQ-8b600d intermediate_benchmark.value '
                                 '(board #1, best construction-class curve at '
                                 'rank 12); NOT a frontier-file value')


def sha256(path):
    h = hashlib.sha256()
    with open(path, 'rb') as f:
        for b in iter(lambda: f.read(1 << 16), b''):
            h.update(b)
    return h.hexdigest()


def c4c6_from_ainvs(ai):
    """c4, c6 from a-invariants, pure Python -- INDEPENDENT of PARI."""
    a1, a2, a3, a4, a6 = [int(x) for x in ai]
    b2 = a1 * a1 + 4 * a2
    b4 = 2 * a4 + a1 * a3
    b6 = a3 * a3 + 4 * a6
    c4 = b2 * b2 - 24 * b4
    c6 = -b2 ** 3 + 36 * b2 * b4 - 216 * b6
    return c4, c6


def naive_height_from_ainvs(ai):
    c4, c6 = c4c6_from_ainvs(ai)
    return math.log(max(abs(c4) ** 3, c6 * c6)), c4, c6


def matched_null(nulls):
    """Compare the ladder rungs at MATCHED coefficient content.

    The rungs are generated by different parameter draws, so their P2
    distributions differ; comparing raw medians would confound rank with size.
    Here every rung is restricted to the log-P2 window they all cover, and the
    comparison is reported inside that window only, with the per-rung
    regression of envelope on log P2 alongside.
    """
    if not nulls:
        return None
    rungs = nulls['rungs']
    per = {}
    for k, rows in rungs.items():
        per[k] = [(math.log(float(r['content_P2'])),
                   r['measured_envelope_min_naive_height'])
                  for r in rows if float(r['content_P2']) > 0]
    lo = max(min(x for x, _ in v) for v in per.values() if v)
    hi = min(max(x for x, _ in v) for v in per.values() if v)
    out = {'log_content_P2_window': [lo, hi],
           'window_rule': 'the intersection of the four rungs\' log-P2 ranges',
           'rungs': {}}
    for k, v in per.items():
        w = [(x, y) for x, y in v if lo <= x <= hi]
        if not w:
            out['rungs'][k] = {'n_in_window': 0}
            continue
        ys = [y for _, y in w]
        out['rungs'][k] = {
            'n_in_window': len(w),
            'n_rational_sections': 2 * int(k[1:]),
            'min_envelope_in_window': min(ys),
            'median_envelope_in_window': st.median(ys),
            'mean_envelope_in_window': st.fmean(ys),
            'fit_in_window': measure.fit([x for x, _ in w], ys),
        }
    return out


def load(p):
    return json.load(open(p)) if os.path.exists(p) else None


def main(taskdir):
    res = os.path.join(taskdir, 'results')
    frontier = json.load(open(FRONTIER))
    fr_sha = sha256(FRONTIER)
    snap = json.load(open(SNAPSHOT))
    snap_sha = sha256(SNAPSHOT)
    board_keys = {c['curve_key'] for c in snap['curves']}
    board_ainvs = {tuple(str(x) for x in c['ainvs']) for c in snap['curves']}

    scan = load(os.path.join(res, 'tuple_envelope_scan_admissible.json'))
    scan_more = [load(os.path.join(res, n)) for n in
                 ('tuple_envelope_scan_largespread.json',
                  'tuple_envelope_scan_spread57_74.json')]
    scan_more = [x for x in scan_more if x]
    nulls = load(os.path.join(res, 'null_ladder.json'))
    searches = [load(os.path.join(res, n)) for n in
                ('rank_search.json', 'rank_search_ceiling12.json',
                 'rank_search_largespread.json')]
    searches = [s for s in searches if s]
    certs = load(os.path.join(res, 'certified_candidates.json'))

    fams = list(scan['families'])
    seen = {f['family'] for f in fams}
    for sc in scan_more:
        for f in sc['families']:
            if f['family'] not in seen:
                fams.append(f)
                seen.add(f['family'])

    # ---------------- deliverable 1 -----------------------------------
    def arm(f, which, key):
        t = f.get('two_arm_fit') or {}
        return (t.get(which) or {}).get(key)

    rows = []
    for f in fams:
        s = f.get('surface') or {}
        rows.append({
            'family': f['family'],
            'tuple': f['tuple'],
            'stratum': f.get('stratum'),
            'content_P2': f['content_P2'],
            'log_content_P2': math.log(float(f['content_P2']))
                              if float(f['content_P2']) > 0 else None,
            'deg_x_r': f['deg_x_r'],
            'n_rational_sections': f['n_sections'],
            'measured_envelope_min_naive_height':
                f['measured_envelope_min_naive_height'],
            'envelope_argmin_t': f['envelope_argmin_t'],
            'median_naive_height': f['median_naive_height'],
            'flat_arm_intercept': arm(f, 'flat_arm', 'intercept'),
            'flat_arm_slope': arm(f, 'flat_arm', 'slope'),
            'flat_arm_r_squared': arm(f, 'flat_arm', 'r_squared'),
            'steep_arm_intercept': arm(f, 'steep_arm', 'intercept'),
            'steep_arm_slope': arm(f, 'steep_arm', 'slope'),
            'steep_arm_r_squared': arm(f, 'steep_arm', 'r_squared'),
            'crossover_log_param_size':
                (f.get('two_arm_fit') or {}).get('crossover_log_param_size'),
            'surface_degree_d': s.get('surface_degree_d'),
            'forced_large_t_slope_12d': s.get('forced_large_t_slope_12d'),
            'sum_m_v_minus_1': s.get('sum_m_v_minus_1'),
            'shioda_tate_ceiling_own_fibre_configuration':
                s.get('shioda_tate_ceiling'),
            'generic_K3_bound_not_used': s.get('generic_K3_bound_NOT_USED'),
            'fibre_types': [(x['type'], x['deg']) for x in s.get('fibres', [])],
        })
    rows.sort(key=lambda r: r['measured_envelope_min_naive_height'])

    env = [r['measured_envelope_min_naive_height'] for r in rows]
    lx = [r['log_content_P2'] for r in rows if r['log_content_P2'] is not None]
    ly = [r['measured_envelope_min_naive_height'] for r in rows
          if r['log_content_P2'] is not None]
    steep = [r['steep_arm_slope'] for r in rows if r['steep_arm_slope'] is not None]
    flat = [r['flat_arm_slope'] for r in rows if r['flat_arm_slope'] is not None]
    by_ceiling = {}
    for r in rows:
        c = r['shioda_tate_ceiling_own_fibre_configuration']
        by_ceiling.setdefault(str(c), []).append(
            r['measured_envelope_min_naive_height'])

    d1 = {
        'what': 'per-tuple measured envelope of minimal-model naive height, '
                'both arms fitted separately, plus each family\'s own surface '
                'degree and Shioda-Tate ceiling; and the required null ladder',
        'task_id': 'TASK-20260823-416e78',
        'hypothesis_id': 'H-ECQ-8b600d',
        'batch_id': 'BATCH-541940',
        'goal_id': 'GOAL-ECQ-002',
        't_box': measure.T_BOX_DESC,
        'frontier_file_read_at_run_time': {
            'path': os.path.relpath(FRONTIER, REPO),
            'sha256_recomputed_now': fr_sha,
            'retrieved_at_utc': frontier['retrieved_at_utc'],
            'sha256_of_snapshot_field': frontier['sha256_of_snapshot'],
            'snapshot_sha256_recomputed_now': snap_sha,
            'snapshot_matches_hypothesis_frozen_sha': (
                snap_sha == frontier['sha256_of_snapshot']),
        },
        'admissibility': {
            'condition': 'deg_x r = 4 (genus-1 quartic).  NOT automatic.',
            'main_scan': scan['admissibility'],
            'further_scans': [x['admissibility'] for x in scan_more],
            'observed_in_the_superseded_unfiltered_scan':
                'RUN-ECQTUP-416e78-002 measured 10694 arbitrary tuples; 127 '
                '(1.2%) were admissible.  That run is invalid_measurement: it '
                'silently truncated the other 98.8%, which are genus-2 '
                'quintics, to quartics.',
        },
        'envelope_vs_tuple': {
            'n_families': len(rows),
            'min_envelope': min(env), 'max_envelope': max(env),
            'median_envelope': st.median(env),
            'spread_max_minus_min': max(env) - min(env),
            'envelope_vs_log_content_P2_fit': measure.fit(lx, ly),
            'by_own_shioda_tate_ceiling': {
                k: {'n': len(v), 'min': min(v), 'median': st.median(v),
                    'max': max(v)}
                for k, v in sorted(by_ceiling.items(),
                                   key=lambda kv: (kv[0] == 'None', kv[0]))},
        },
        'two_arm_law': {
            'steep_arm_slope_median': st.median(steep) if steep else None,
            'steep_arm_slope_iqr': ([st.quantiles(steep, n=4)[0],
                                     st.quantiles(steep, n=4)[2]]
                                    if len(steep) > 4 else None),
            'flat_arm_slope_median': st.median(flat) if flat else None,
            'forced_12d_for_d_equals_2': 24,
            'note': 'the two arms are fitted INDEPENDENTLY with a free '
                    'breakpoint; no single line is fitted across the vertex',
        },
        'null_ladder': (nulls or {}).get('rung_summary'),
        'null_ladder_matched_on_content': matched_null(nulls),
        'null_ladder_certified': (nulls or {}).get('certified_at_envelope_argmin'),
        'null_ladder_generation': (nulls or {}).get('generation'),
        'families': rows,
    }
    json.dump(d1, open(os.path.join(taskdir, 'tuple_envelope_scan.json'), 'w'),
              indent=1)

    # ---------------- deliverable 2 -----------------------------------
    fibres = []
    for s in searches:
        for r in s.get('fibres', []):
            if 'certified_rank_lower_bound' in r:
                fibres.append(r)
    if certs:
        for f in certs['families']:
            for c in f['fibres']:
                if 'certified_rank_lower_bound' in c:
                    fibres.append({
                        'family': f['family'], 'tuple': f['tuple'],
                        't': c['t'],
                        'minimal_a_invariants': c['minimal_a_invariants'],
                        'naive_height': c['naive_height'],
                        'curve_key': c['curve_key'],
                        'certified_rank_lower_bound':
                            c['certified_rank_lower_bound'],
                        'points': c['points_on_minimal_model'],
                        'shioda_tate_ceiling': f['shioda_tate_ceiling'],
                        'content_P2': f['content_P2'],
                    })
    best = {}
    for r in fibres:
        k = r['curve_key']
        if k not in best or r['certified_rank_lower_bound'] > \
                best[k]['certified_rank_lower_bound']:
            best[k] = r
    fibres = list(best.values())

    pareto = {}
    for k in range(1, 16):
        c = [r for r in fibres if r['certified_rank_lower_bound'] >= k]
        if c:
            pareto[str(k)] = min(c, key=lambda r: r['naive_height'])

    records = []
    for k in sorted(pareto, key=int):
        r = pareto[k]
        ai = [int(x) for x in r['minimal_a_invariants']]
        h_ind, c4, c6 = naive_height_from_ainvs(ai)
        pts = [[str(F(x)), str(F(y))] for x, y in r['points']]
        recert = ec.certify(ai, pts, max_prime=8000, max_good_primes=200,
                            l_candidates=(2, 3, 5, 7, 11, 13, 17, 19))
        onc = all(ec.on_curve(ec.Qfield(), [F(a) for a in ai],
                              (F(x), F(y))) for x, y in pts)
        key = '%d:%d' % (c4, c6)
        records.append({
            'rank_threshold_it_is_best_at': int(k),
            'family': r['family'], 'tuple': r.get('tuple'), 't': r['t'],
            'ainvs': [str(a) for a in ai],
            'curve_key': key,
            'curve_key_agrees_with_pari': key == r['curve_key'],
            'rank_lower_bound': recert['certified_rank_lower_bound'],
            'rank_lower_bound_agrees_with_search_stage':
                recert['certified_rank_lower_bound'] ==
                r['certified_rank_lower_bound'],
            'naive_height': h_ind,
            'naive_height_reported_by_pari_stage': r['naive_height'],
            'naive_height_recomputed_from_ainvs_alone_no_pari': h_ind,
            'naive_height_agreement_abs': abs(h_ind - r['naive_height']),
            'c4': str(c4), 'c6': str(c6),
            'discriminant': str(ec.discriminant(ai)),
            'all_points_exactly_on_minimal_model': onc,
            'n_points_exhibited': len(pts),
            'points': pts,
            'independent_point_indices':
                (recert.get('independence') or {}).get(
                    'independent_point_indices'),
            'independence_l': (recert.get('independence') or {}).get('l'),
            'torsion_bound': recert.get('torsion_bound'),
            'shioda_tate_ceiling_of_its_family': r.get('shioda_tate_ceiling'),
            'already_on_the_frozen_icarm_board': key in board_keys
                                                 or tuple(str(a) for a in ai)
                                                 in board_ainvs,
            'provenance': {
                'construction': "Mestre's q(x) -> p = q(x-T)q(x+T) = g^2 - r, "
                                'y^2 = r(x,T), sections at x = a_i +- T',
                'rank_certified_by': 'exact_certify.py (exact, stdlib only), '
                                     're-run here independently of the search',
                'points_found_by': 'the twelve construction sections, plus '
                                   'PARI ellrank used ONLY as a point search',
                'not_submitted_to_icarm': True,
            },
        })

    cell = {}
    for k in sorted(frontier['frontier_by_rank_threshold'], key=int):
        fr = frontier['frontier_by_rank_threshold'][k]
        inc = fr['min_naive_height']['value']
        mine = pareto.get(k)
        cell[k] = {
            'frozen_frontier_min_naive_height_READ_AT_RUN_TIME': inc,
            'frozen_frontier_curve_id': fr['min_naive_height']['curve_id'],
            'frozen_frontier_submitter': fr['min_naive_height']['submitter'],
            'our_best_certified_naive_height': mine['naive_height'] if mine else None,
            'our_best_family': mine['family'] if mine else None,
            'delta_ours_minus_frontier': (mine['naive_height'] - inc)
                                         if mine else None,
            'cell_taken': bool(mine and mine['naive_height'] < inc),
        }

    d2 = {
        'what': 'best (certified rank, naive height) curves, ICARM record '
                'format.  NOTHING WAS SUBMITTED TO THE ICARM ENDPOINT.',
        'task_id': 'TASK-20260823-416e78',
        'frontier_file_read_at_run_time': d1['frontier_file_read_at_run_time'],
        'n_distinct_certified_curves': len(fibres),
        'predeclared_cell': {
            'rank_threshold': 12,
            'metric': 'naive_height',
            'incumbent_read_at_run_time':
                frontier['frontier_by_rank_threshold']['12']['min_naive_height'],
        },
        'intermediate_benchmark': {
            'value': INTERMEDIATE_BENCHMARK,
            'source': INTERMEDIATE_BENCHMARK_SOURCE,
            'our_best_at_certified_rank_12':
                pareto['12']['naive_height'] if '12' in pareto else None,
            'beaten': bool('12' in pareto
                           and pareto['12']['naive_height'] < INTERMEDIATE_BENCHMARK),
        },
        'per_rank_threshold_vs_frozen_frontier': cell,
        'records': records,
    }
    json.dump(d2, open(os.path.join(taskdir, 'best_candidates.json'), 'w'),
              indent=1)

    print('deliverables written; %d families, %d distinct certified curves'
          % (len(rows), len(fibres)))
    for k in sorted(cell, key=int):
        c = cell[k]
        if c['our_best_certified_naive_height'] is None:
            continue
        print('r>=%-3s frontier %10.4f   ours %10.4f   delta %+9.4f  taken=%s'
              % (k, c['frozen_frontier_min_naive_height_READ_AT_RUN_TIME'],
                 c['our_best_certified_naive_height'],
                 c['delta_ours_minus_frontier'], c['cell_taken']))
    return 0


if __name__ == '__main__':
    sys.exit(main(os.path.abspath(sys.argv[1])))
