"""BR-1 ambiguity register, written BEFORE the pass over the blind inputs.
Each entry: the clause, the readings considered, the reading chosen, why, and
what it can affect. None was resolved by reading any producer artifact."""

AMBIGUITIES = [
    {
        "id": "AMB-1",
        "clause": "task card Q6: 'a_k as a 17-bit integer' (spec object.fixed_schedule_replay: e_k(r) = a_{k,0} + <a_k, r>)",
        "readings": ["bit j of the integer = coefficient of r_j (the M_D(E^j) block), LSB = r_0",
                     "bit order reversed (MSB = r_0)"],
        "chosen": "bit j = coefficient of r_j",
        "why": "matches the spec's own encodings: field element bit j = coefficient of t^j, and r_j = coefficient of t^j in x_R, so <a_k, r> = parity(a_k & x_R)",
        "affects": "only the integer values listed for a_k in Q6; K_exact, K_rank and the increases-rank flags are invariant under a fixed bit permutation",
    },
    {
        "id": "AMB-2",
        "clause": "spec object.zero_reduction_set: 'The leading-column set of that basis must equal the pivot column set'",
        "readings": ["leading column = the FIRST nonzero column in the declared (descending degrevlex) column order, i.e. smallest column index",
                     "leading column = the last nonzero column (largest index)"],
        "chosen": "smallest column index",
        "why": "the column pass processes columns in increasing index, so its pivot rows form an echelon basis whose leads are the smallest nonzero index; only this reading makes the spec's C-PASS equality a theorem. Z_D itself (span membership) does not depend on the reading",
        "affects": "only the C-PASS consistency check, not Z_D, |Z_D| or any trace",
    },
    {
        "id": "AMB-3",
        "clause": "spec object.zero_reduction_set: 'Z_D = {i : row i of M_D lies in the span of rows 0..i-1}' together with 'Zero rows are RETAINED'",
        "readings": ["a zero row lies in every span (including the span of the empty set), so every zero row, including row 0 if zero, is in Z_D",
                     "zero rows are excluded from Z_D"],
        "chosen": "zero rows are in Z_D",
        "why": "forced by the definition of span; the spec's identity |Z_D| = R_D - rank_D also requires it",
        "affects": "Z_D and T_set only if M_4 has zero rows; the per-instance count zero_rows_in_M4 is recorded so the effect is visible",
    },
    {
        "id": "AMB-4",
        "clause": "spec object.curve: 'Draw (A, B) from seed S_curve (B != 0)' with seeds.generator numpy.random.Generator(numpy.random.PCG64(seed))",
        "readings": ["R1: two scalar calls A = integers(0, 2^17), B = integers(0, 2^17), reject B = 0",
                     "R2: A = integers(0, 2^17), B = integers(1, 2^17)",
                     "R3: (A, B) = integers(0, 2^17, size=2), reject B = 0",
                     "other call patterns (dtype, endpoint, B before A) not tried"],
        "chosen": "R1 as primary; R2 and R3 also computed and reported; all three declared before any draw",
        "why": "the clause fixes the stream but not the call pattern, and numpy's bounded-integer draws consume the stream differently for scalar and vector calls. The card calls a mismatch a finding about determinacy",
        "affects": "Q7 only (optional)",
    },
    {
        "id": "AMB-5",
        "clause": "spec object.fixed_schedule_replay: 'replaying the op log once on M_D(E^0) and on each M_D(E^j)'",
        "readings": ["M_D(E^j) = the Macaulay construction applied to the 17 rows of E^j read as Boolean polynomials (the construction is F_2-linear in the equations)"],
        "chosen": "as stated",
        "why": "no other reading is coherent; linearity M_D(E(r)) = M_D(E^0) + sum_j r_j M_D(E^j) is CHECKED on every instance",
        "affects": "Q6",
    },
    {
        "id": "AMB-6",
        "clause": "spec object.descended_system: 'the 17 x 172 coefficient matrix' E(r)",
        "readings": ["the order of E(r)'s 172 columns is not specified"],
        "chosen": "E(r) is held as the map monomial -> 17-bit coefficient word; no column order is needed",
        "why": "no requested quantity depends on E(r)'s internal column order; M_D uses its own declared column order",
        "affects": "nothing requested",
    },
    {
        "id": "AMB-7",
        "clause": "task card Q3: match flags '(equal content)' at T_ops",
        "readings": ["compare full T_ops content for every pair", "compare by sha256 and confirm content when hashes are equal"],
        "chosen": "sha256 comparison, with content re-derived and compared whenever hashes are equal",
        "why": "the spec compares traces by hash and, on equal hashes, by content. Different hashes imply different canonical encodings and so different content",
        "affects": "none in outcome; the confirmations are listed",
    },
    {
        "id": "AMB-8",
        "clause": "task card Q5: 'count / n, with the Clopper-Pearson 95% interval'",
        "readings": ["two-sided equal-tailed exact interval (alpha/2 = 0.025 per tail); n = non-degenerate unsatisfiable targets of the 100-target subsample under THIS task's classification"],
        "chosen": "as stated",
        "why": "standard definition; the card says 'reference YOU classify unsatisfiable'",
        "affects": "Q5 interval endpoints",
    },
    {
        "id": "AMB-9",
        "clause": "spec: D in {3, 4}; card and blind inputs: D = [4]",
        "readings": ["compute D = 4 only, as the card's Q1-Q6 require"],
        "chosen": "D = 4 for every quantity; D = 3 only in the fixture-dimension self-test",
        "why": "scope of the card",
        "affects": "nothing requested",
    },
]
