"""Readings chosen where the specification text admits more than one reading
(BR-1, BR-3). Written BEFORE the real pass, from the specification text alone;
no producer code, engine code or note was consulted to choose any of them.
Each entry: clause, readings considered, the one chosen, why.
"""

AMBIGUITIES = [
    {
        "id": "AMB-01",
        "clause": "EXP-CERTBIN-ddfe75 fresh_arms.N-CONV.drawn_part: bits = g.integers(0, 2, size=|S_L|) (one call per attempt)",
        "readings": ["numpy defaults (dtype=int64, endpoint=False)", "dtype=uint8 / bool", "endpoint=True with high=1"],
        "chosen": "numpy defaults: g.integers(0, 2, size=len(S_L)) exactly as written, dtype int64, endpoint False",
        "why": "The call is written out; any other dtype or endpoint is an addition to the text. The dtype changes stream consumption, so this reading is load-bearing for Q0.",
    },
    {
        "id": "AMB-02",
        "clause": "N-CONV drawn_part 'placed on S_L'; object.union_support 'S_L ... in row-major order (k ascending, then column ascending)'",
        "readings": ["bits[i] -> i-th position of S_L in the stated row-major order", "column-major placement"],
        "chosen": "bits[i] -> S_L[i], S_L listed row-major (k ascending, then column ascending)",
        "why": "The order is stated in object.union_support; placement in that order is the direct reading.",
    },
    {
        "id": "AMB-03",
        "clause": "N-CONV kept_part 'Qpart(x_R) on quadratic columns, exactly as in E_S3(x_R)'; 'All other columns 0..18 are zero'",
        "readings": ["quadratic columns 19..171 copied from my E_S3(x_R); columns 0..18 = drawn bits on S_L, zero off S_L"],
        "chosen": "as stated",
        "why": "Single reading; recorded for completeness. E_S3(x_R) has no entry outside U at any of the 144 slots (checked), so the identity comparison is well posed.",
    },
    {
        "id": "AMB-04",
        "clause": "N-CONV identity_rejection: 'a draw equal to E_S3(x_R) is rejected'",
        "readings": ["the whole 17 x 172 drawn system equals E_S3(x_R)", "only the drawn bits equal E_S3's bits on S_L"],
        "chosen": "whole-system equality",
        "why": "The two readings coincide because the quadratic part is copied from E_S3(x_R) and E_S3(x_R) is zero off U; recorded for completeness.",
    },
    {
        "id": "AMB-05",
        "clause": "keep_rule: 'duplicate of an already-kept system of the same arm by E_sha256'",
        "readings": ["sha256 of an unspecified byte encoding of E (not defined in the texts I may read)", "exact equality of the 17 x 172 matrix"],
        "chosen": "exact equality of the 17 x 172 matrix (implemented as sha256 of my own canonical uint8 row-major bytes, used only as a set key); compared against every kept system of the arm, earlier slots and the same slot's filled role",
        "why": "Any collision-free hash of a canonical encoding of E decides duplication identically to content equality; the E_sha256 encoding itself is only defined in files I may not read.",
    },
    {
        "id": "AMB-06",
        "clause": "keep_rule: 'Each attempt makes one draw, applies the arm's rejections ..., then computes s' versus BR-4 's ... for every drawn system of Q0'",
        "readings": ["s computed only for non-rejected draws", "s computed for every draw"],
        "chosen": "s is computed and logged for every draw (BR-4); a rejected draw's s never affects role assignment",
        "why": "Computing s consumes no randomness, so the stream and the kept systems are identical under both readings; BR-4 asks for s on every drawn system.",
    },
    {
        "id": "AMB-07",
        "clause": "keep_rule role handling: attempts a = 0, 1, ... up to 255; first s = 0 draw -> unsatisfiable; first s >= 1 -> satisfiable control; 'Other draws are discarded'; 'If attempt 255 passes with a role unfilled, that role is EXHAUSTED(cap)'",
        "readings": ["at most 256 attempts (a = 0..255); a draw whose role is already filled is 'discarded'"],
        "chosen": "as stated; the slot stops as soon as both roles are filled",
        "why": "Direct reading. A draw of an already-filled role is logged 'discarded'; a rejected draw is logged 'rejected' with its reason.",
    },
    {
        "id": "AMB-08",
        "clause": "instance_record: solutions 'as 18-bit integers'; exhaustive evaluation over all 2^18 assignments",
        "readings": ["bit i of the integer = v_i", "bit 17 - i = v_i"],
        "chosen": "bit i = v_i (so x_1 = u & 0x1FF and x_2 = (u >> 9) & 0x1FF as field elements)",
        "why": "The same LSB-first convention as the E_layout hex and the field encoding. Only solution listings depend on it; s does not.",
    },
    {
        "id": "AMB-09",
        "clause": "BR-3 row-hex: '17 rows, bit j = column j, lowercase hex without prefix'",
        "readings": ["no zero padding", "zero-padded to 43 hex digits"],
        "chosen": "no zero padding (Python format(x, 'x'))",
        "why": "Padding is not specified; the integer value is unambiguous either way.",
    },
    {
        "id": "AMB-10",
        "clause": "N-CONVL: bits placed 'on the constant positions of S_L'; 'A draw equal to B's own bits is rejected (identity), and so is the all-zero draw'",
        "readings": ["drawn vector compared with (bit k of B) for k in the constant positions of S_L, in S_L order", "compared with the full 17-bit B"],
        "chosen": "compared with B's bits at the constant positions of S_L (in S_L order); b' = sum of drawn bit i * t^{k_i}; constant entries off S_L are zero (they are zero in E_S3 as well); columns 1..171 copied from E_S3(x_R)",
        "why": "The draw only has |S_L cap column 0| bits, so equality can only be taken on those positions. Q0-opt only.",
    },
    {
        "id": "AMB-11",
        "clause": "N-CONV17 and N-ELL144: no identity_rejection is stated",
        "readings": ["no identity rejection (duplicates only)", "some implied identity"],
        "chosen": "duplicates only",
        "why": "The keep_rule lists rejections per arm; none is given for these arms. Q0-opt only.",
    },
    {
        "id": "AMB-12",
        "clause": "N-ELL144 draw_rule: 'M = zeros(17 * 172); M[Upos] = g.integers(0, 2, size=Upos.size), with Upos = flatnonzero(U) row-major; then c = int(g.integers(0, 2)); rows 0..15 are kept; row 16 is replaced by v_0 + v_9 + c'",
        "readings": ["U = the full 17 x 172 union support (quadratic columns included), two generator calls per attempt, row 16 replaced entirely"],
        "chosen": "as stated",
        "why": "Direct reading. Q0-opt only.",
    },
    {
        "id": "AMB-13",
        "clause": "EXP-CERTBIN-e94b27 mutant_closure_W_D: 'stop at the first i with dim W^(i+1) = dim W^(i)'; BR-2 'reaches its fixpoint at iteration index >= 2'; Q3 'the fixpoint index'",
        "readings": ["fixpoint index = that first i (W^(i) is the fixpoint)", "fixpoint index = i + 1 (the last iteration computed)"],
        "chosen": "fixpoint_index = the first i with dim W^(i+1) = dim W^(i); 'dims' lists dim W^(0), ..., dim W^(i+1), the last entry repeating the previous one",
        "why": "W^(i) is the least fixpoint; W^(i+1) is only the confirming iteration. Both readings are recoverable from 'dims'.",
    },
    {
        "id": "AMB-14",
        "clause": "rc_b and Q5 'the label'",
        "readings": ["labels exist only for steps (1) and (3)"],
        "chosen": "'not applicable (kernel dim d)' (step 1), 'REFUTED-AT-DEGREE-2' / 'ELL-TRIVIAL' (step 3), and 'SUBSTITUTED' for systems that go through steps (4)-(5)",
        "why": "Step (4) names no label; 'SUBSTITUTED' is my name for it.",
    },
    {
        "id": "AMB-15",
        "clause": "rc_b (1) 'left kernel of the 17 x 153 quadratic-column submatrix'; (2) ell = sum_k c_k f_k",
        "readings": ["c in F_2^17 with c^T Q = 0, c_k multiplying f_k (row k)"],
        "chosen": "as stated; c reported as a list of 17 bits indexed by k",
        "why": "Direct reading.",
    },
    {
        "id": "AMB-16",
        "clause": "rc_b (4)-(5): substitution and R'_D",
        "readings": ["v_{j*} := (ell + v_{j*}) including ell's constant; remaining variables relabelled ascending 0..16; R'_D built with the M_D conventions in 17 variables and 17 equations"],
        "chosen": "as stated; R'_3 is 306 x 834 and R'_4 2618 x 3214 (fixture, checked)",
        "why": "Direct reading; the fixture dimensions confirm the row/column sets.",
    },
    {
        "id": "AMB-17",
        "clause": "Q1: 'with a wdag-v1 (BR-6) for each one refuted'",
        "readings": ["refuted = 1 in rowspace(M_4) (Q1 computes M_4 only)", "refuted = 1 in W_4 (would require W_4 on the replay systems)"],
        "chosen": "refuted = 1 in rowspace(M_4); the certificate is the one-node rows-only wdag of BR-6. W_4 is not computed on replay systems.",
        "why": "Q1 lists only M_4 quantities; W_4 is required on the pool (Q3), not on the replay.",
    },
    {
        "id": "AMB-18",
        "clause": "Q2 'P is the rank of the projection of rowspace(M_4) onto the span of degree-4 monomials'; derived_per_instance P = rank M_4 - dims_by_deg(M_4)[3]",
        "readings": ["the two definitions (they are equal by linear algebra)"],
        "chosen": "both computed; they must agree (asserted per system)",
        "why": "A cross-check at no cost.",
    },
    {
        "id": "AMB-19",
        "clause": "BR-4: pool systems 'that you can identify as S_3 descents at a slot's x_R (by matching your own E_S3)'",
        "readings": ["exact equality with my E_S3(x_R) at some slot", "also systems equal to an S_3 descent with another curve constant"],
        "chosen": "BR-4's second route is applied to exact matches. Supplementary, not required: where the quadratic and linear parts equal E_S3 at a slot but the constant differs, oracle A is also run with the system's own constant b' and reported separately.",
        "why": "The clause names matching my own E_S3; the supplementary route costs nothing and is labelled.",
    },
    {
        "id": "AMB-20",
        "clause": "certificate_format wdag-v1: poly(i) = sum rows + sum_{(j,c)} v_j * poly(c); recommended construction 'Collapse each of those 19 groups into one node'",
        "readings": ["the W^(i-1) group becomes its own node", "the W^(i-1) group is inlined into the parent"],
        "chosen": "inlined: a node has no un-multiplied child term, so the W^(i-1) component w of a decomposition y = w + sum_j v_j g_j contributes its own rows and prods to the parent node; each g_j becomes a child node. The same j may appear more than once in a node's prods (a sum).",
        "why": "The format's poly has no term 'plus poly(c)'; the recommended construction is declared not binding and the verifier 'does not care how'.",
    },
    {
        "id": "AMB-21",
        "clause": "wdag-v1 validity rule (a) 'every child id c is less than i'",
        "readings": ["only the ordering condition", "ordering plus existence and distinct ids"],
        "chosen": "my checker also requires distinct integer ids, existing children, header D = 4 and nv = 18, j in 0..17, and an existing output node (reported as rule 'format' or 'a')",
        "why": "A stricter checker cannot accept anything the literal rules reject.",
    },
    {
        "id": "AMB-22",
        "clause": "object.union_support 'on the curve of curve.json'",
        "readings": ["A, B from curve.json (a file under a must_not_read run directory)", "A, B from blind-inputs.json"],
        "chosen": "A = 97044, B = 126251 from blind-inputs.json, which equal the values stated in the specification texts (claim_tier_and_scope)",
        "why": "curve.json is under experiments/EXP-CERTBIN-4e92d7/runs/, which I may not read. Only B enters E_S3; A enters the point-addition self-test.",
    },
    {
        "id": "AMB-23",
        "clause": "xr144 slots 'Slot 0..143 carries (source set, idx, x_R)'",
        "readings": ["the blind-inputs 'slots' table (slot, x_R)"],
        "chosen": "x_R by slot from blind-inputs.json; source set and idx are not given and not needed for any required quantity",
        "why": "The card names the slots table as the xr144 order of x_R.",
    },
]
