#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""VAL TASK-20260812-55056b probe D -- cross-check the lead's COMMITTED per-cell
numbers against the Validator's independent re-derivation.

Reads:
  * the lead's committed results_gvar2.json (at snapshot 3aac83fd8), and
  * rederive_gvar2.json -- but only for the summary; the per-cell comparison
    recomputes the Validator's own values in-process from probe C's module, so
    the comparison is re-derived value vs producer value, per cell, per route.

Reports, per (family, candidate, route): the number of cells whose s_c, m_c,
D_c and VERDICT agree, and the maximum absolute and relative deviation in s_c.
A DEFECT IN THE GENERATION of a number is invisible to arithmetic on that
number, so this probe compares against values generated by a separate
implementation rather than re-adding the producer's own.

Run from the repository root.
"""
import importlib.util
import json
import math
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
LEAD = ("coordination/goals/GOAL-MLKEM-005/batches/BATCH-4ed139/tasks/"
        "TASK-20260812-56b9da/results_gvar2.json")

spec = importlib.util.spec_from_file_location(
    "rederive", os.path.join(HERE, "probe_gvar2_rederive.py"))
RD = importlib.util.module_from_spec(spec)
sys.modules["rederive"] = RD
spec.loader.exec_module(RD)

# lead route labels -> mine
RMAP = {"R0_closed_form": "R0", "R1_slogdet": "R1", "R2_QR_of_BT": "R2",
        "R3_slogdet_of_UB": "R3", "R4_gram_half_slogdet": "R4",
        "R5_slogdet_of_BH_ambient_isometry": "R5"}


def main():
    lead = json.load(open(LEAD))
    prof = lead["per_cell_profiles"]
    print("lead per_cell_profiles blocks:", len(prof))
    V = {f: RD.collect(f)[0] for f in RD.FAMILIES}

    rows = []
    total_cells = 0
    total_sd_agree = 0
    total_verdict_agree = 0
    worst_abs = 0.0
    worst_rel = 0.0
    worst_where = None
    agree_g = 0
    total_g = 0
    for block, body in sorted(prof.items()):
        # block keys are "candidate|route|family"
        parts = block.split("|")
        if len(parts) != 3:
            continue
        cand, lroute, fam = parts
        if lroute not in RMAP or fam not in ("F0", "F1"):
            continue
        if cand not in ("X_null", "rdet", "V_evade"):
            continue
        rt = RMAP[lroute]
        mine = RD.var_s(RD.cellvals(V[fam], fam, cand, rt))
        fib = RD.FIBRE_OF[fam][0]
        minef = RD.var_f(RD.cellvals(V[fib], fib, cand, rt))
        cells = body.get("per_cell", {})
        n = agree_sd = agree_v = 0
        for ckey, crec in cells.items():
            lat, b = ckey.rsplit("_b", 1)
            key = (lat, int(b))
            if key not in mine:
                continue
            n += 1
            m = mine[key]
            ls, ms = crec["VAR_S"].get("s_c"), m["s"]
            if ls is not None:
                dd = abs(ls - ms)
                r = dd / max(abs(ls), abs(ms)) if max(abs(ls), abs(ms)) else 0.0
                if ls == ms:
                    agree_sd += 1
                if r > worst_rel:
                    worst_rel, worst_abs, worst_where = r, dd, f"{block}/{ckey}"
            if crec["VAR_S"].get("VAR_S") == m["VAR_S"]:
                agree_v += 1
            total_g += 1
            if crec.get("G_VAR2") == RD.gvar2(m, minef[key]):
                agree_g += 1
        rows.append((block, n, agree_sd, agree_v))
        total_cells += n
        total_sd_agree += agree_sd
        total_verdict_agree += agree_v
    print(f"\n{'block':44s} {'cells':>6s} {'s_c BIT-EQUAL':>14s} "
          f"{'VAR_S agree':>12s}")
    for b, n, a, v in rows:
        flag = "" if (a == n and v == n) else "   <<< CHECK"
        print(f"{b:44s} {n:6d} {a:14d} {v:12d}{flag}")
    print(f"\nTOTAL per-cell s_c values compared : {total_cells}")
    print(f"  bit-identical to the producer's  : {total_sd_agree}")
    print(f"  VAR_S verdict agreeing           : {total_verdict_agree}")
    print(f"  worst relative s_c deviation     : {worst_rel:.3e} "
          f"at {worst_where}")
    print(f"  G-VAR2 per-cell verdicts compared: {total_g}, agreeing: {agree_g}")

    # ---- headline scalars the report states, re-derived
    print("\n--- HEADLINE SCALARS ---")
    f0 = lead["FIXTURE_F0"]
    f1 = lead["FIXTURE_F1"]
    print("lead FIXTURE_F0 verdict:", f0.get("VERDICT"))
    print("lead FIXTURE_F1 verdict:", f1.get("VERDICT"))
    print("lead TERMINATION:", json.dumps(lead["TERMINATION"])[:400])
    print("lead peak_rss_mb:", lead.get("peak_rss_mb"),
          " wall_clock_seconds:", lead.get("wall_clock_seconds"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
