"""Emit validation-report.yaml for TASK-20260904-42b33a."""
import hashlib
import json
import os

BASE = ("/home/user/crypto-autoresearcher/coordination/reviews/pfdr-battery-20260904/"
        "reviews/TASK-20260904-42b33a/")
REL = "coordination/reviews/pfdr-battery-20260904/reviews/TASK-20260904-42b33a/"


def sha(p):
    h = hashlib.sha256()
    with open(p, "rb") as f:
        for b in iter(lambda: f.read(1 << 16), b""):
            h.update(b)
    return h.hexdigest()


arts = []
for root, dirs, files in os.walk(BASE):
    dirs[:] = [d for d in dirs if d != "__pycache__"]
    for fn in sorted(files):
        p = os.path.join(root, fn)
        rel = REL + os.path.relpath(p, BASE)
        arts.append((rel, sha(p)))
arts = sorted(arts)

d = json.load(open(BASE + "tables/rederivation_results.json"))
pb = json.load(open(BASE + "tables/phaseb_checks.json"))
fits = d["fits"]


def ci(k):
    f = fits[k]
    return f"slope {f['slope']:.4f}, 95% t-interval [{f['ci95'][0]:.4f}, {f['ci95'][1]:.4f}], n={f['n']}, df={f['df']}"


run_status = {r: (v["checks"]["status"], v["checks"]["wall_seconds"],
                  v["checks"]["closure_py_sha256"][:8])
              for r, v in sorted(pb["runs"].items())}

L = []
w = L.append
w("validation_report:")
w("  id: VAL-20260904-42b33a")
w("  task_id: TASK-20260904-42b33a")
w("  experiment_id: EXP-PFDR-cbdefb")
w("  hypothesis_id: H-PFDR-c88f14")
w("  question_id: RQ-PFDR-ae2fba")
w("  recorded_at: '2026-09-04'")
w("  reviewer_role: validator")
w("  snapshot_under_review:")
w("    branch: claude/degree-regularity-polynomial-systems-pssesi")
w("    head_commit: 6468b25ed8a959602fb8a877633989fd21f0f96b")
w("    run_package_commit: a3a81e33  # 'runs(EXP-PFDR-cbdefb): twenty-three completed_valid runs'")
w("    working_tree_clean_for_the_package_under_review: true")
w("    note: >-")
w("      The 23 run directories and every producer artifact are present in the")
w("      committed snapshot, not working-tree-only. The only uncommitted paths in")
w("      the tree are other reviewers' report directories, which I did not read.")
w("")
w("  scope_of_this_report: >-")
w("    Joints V1, V2, V3, V4 of review_plan in TASK-20260904-42b33a, and nothing")
w("    else. This is not a verdict on the claim under review: joints R0-R5 and the")
w("    proves-too-much control belong to TASK-20260904-3a2ff5 and are invisible to")
w("    me by construction. A passed/incomplete verdict here concerns the")
w("    admissibility of the receipt, never the meaning of the measurement, and it")
w("    supports no ECDLP claim, no speedup and no promotion.")
w("")

w("  run_ids:   # all 23, terminal status as read from the manifests")
for r, (st, wall, ch) in run_status.items():
    w(f"    - {{run_id: {r}, status: {st}, wall_seconds: {wall}, closure_py_sha256_prefix: {ch}}}")
w("")

w("  phase_boundary:")
w("    phase_A_started_utc: '2026-09-04T02:19:55Z'   # session start / first tool call")
w("    phase_A_ended_utc: '2026-09-04T02:34:03Z'")
w("    rederivation_yaml_sha256_at_boundary: "
  "04a55734c74b6c1d9941de34ad886149864b47acc1bb0a6700ecdf825c31bc2c")
w("    boundary_record: " + REL + "logs/phase-boundary.txt")
w("    statement: >-")
w("      Every number in rederivation.yaml was computed and written before any")
w("      manifest, sidecar, package hash file or producer artifact of EXP-PFDR-cbdefb")
w("      or EXP-PFDR-5726af was opened. In phase A I did not open even the permitted")
w("      run.inputs.parameters blocks: the derivation used only the parameters")
w("      transcribed in the handoff's review_plan.blind_rederivation.parameters, which")
w("      is the strongest available blind posture and is what scripts/params.py")
w("      contains. Two supplementary convention-variant computations (reading 2b at")
w("      s = 4, 5 and the literal polynomial ring at s = 3) finished after the values")
w("      above were fixed but before phase B; they are my own computations from the")
w("      same statement and read no producer artifact.")
w("")

w("  artifact_checks:")
w("    - check: 'seven-file run package present in all 23 run directories'")
w("      method: 'directory listing against the required set (manifest.yaml, command.txt, environment.json, stdout.log, stderr.log, raw-result.json, package-sha256.json)'")
w("      result: pass")
w("      detail: '23/23 complete; no extra files in any run directory'")
w("    - check: 'package-sha256.json sidecar hashes recompute'")
w("      method: 'sha256 of each declared file recomputed; raw-result.json and stdout.log were HASHED, never opened (blind_from)'")
w("      result: pass")
w("      detail: '138 declared hashes over 23 runs (6 per run, including manifest.yaml); 0 mismatches'")
w("    - check: 'manifest status / revision / dirty tree'")
w("      method: 'strict YAML parse of all 23 manifests'")
w("      result: pass")
w("      detail: 'all 23 status completed_valid, result.valid true, invalid_reason null; code.commit 3029ff1466011c8a8b93e8614ebe3dc1201e08e1 on all 23; code.dirty false on all 23; source.all_pinned true; source.modified empty'")
w("    - check: 'command.txt equals manifest code.command'")
w("      result: pass")
w("      detail: '23/23 identical'")
w("    - check: 'the two closure.py versions'")
w("      method: 'read run.code.source.files pins from every manifest; hashed the tree copy; searched every reachable commit for the other blob'")
w("      result: FAIL (retention)")
w("      detail: >-")
w("        Exactly two versions are pinned, as the plan expected, but the partition is")
w("        not the one the plan expected and one version is not retained:")
w("        74e659bb2546e79c9e9ec4e7e4adb1922345f2387ee64f42d62616645b8bd8e6 on THREE")
w("        runs (RUN-PFDR-cbdefb-fixture, -s1-slice, -dff-agreement, all started")
w("        21:53 UTC) and 63475db53f5d34859d638327a7082834da0b81209059d0b871bab5b4e32cfb98")
w("        on the other TWENTY (from 22:08:31 UTC on, i.e. every ladder cell, every")
w("        equal-d^s cell and both m = 3 cells). The tree copy hashes to 63475db5;")
w("        `git log --all` shows closure.py entering history exactly once, in a3a81e33,")
w("        with content 63475db5; a scan of `git rev-list --all` finds NO reachable")
w("        commit containing 74e659bb. The earlier version is retained nowhere.")
w("    - check: 'run_cbdefb.py pin'")
w("      result: pass")
w("      detail: 'one version, 5d1e71b906f0039a60d6758b9d5560a14d5395618553cab2a7e8e8c5b6e71c3d, on all 23 runs; equals the tree copy'")
w("    - check: 'closure-convention hash binding'")
w("      method: 'sha256 of experiments/EXP-PFDR-cbdefb/stage1-closure-convention.md computed with a hashing tool; THE FILE WAS NOT OPENED'")
w("      result: pass")
w("      detail: 'all 23 manifests declare 99190ce39524669056e818bcbc510c9699baf2beabdafaddf2c2663ae93f6437 in both inputs.parameters.closure_convention.sha256 and inputs.parameters.closure_convention_sha256; the file hashes to exactly that; one convention_id string on all 23'")
w("    - check: 'shared meter pinning (invalidation rule 2)'")
w("      method: 'recomputed the 14 pinned meter file hashes from the tree and compared them with the table in harness/macaulay_fp/VALIDATION.md'")
w("      result: pass")
w("      detail: '14/14 match the tree AND 13/13 non-self entries match VALIDATION.md; meter_commit 2d2083e59edab14fe4ac4a42d777b1aa5be867b8; VALIDATION.md records the p = 2 known answer (section 5) and the planted-syzygy control (section 7) in the same lineage'")
w("    - check: 'manifest schema against the minimum manifest of docs/evidence-and-reproducibility.md'")
w("      result: partial")
w("      detail: >-")
w("        Every top-level block is present (id, experiment_id, status, code, inference,")
w("        environment, inputs, timing, resources, result) with certificate.kind /")
w("        .verified / .verifier filled. run.inference is an abbreviated 5-field block")
w("        on all 23 runs and omits 10 template fields (canonical_policy, backend,")
w("        provider, model_provenance, model_verified, requested_reasoning_effort,")
w("        fallback_reason, degraded_requirements, independent_session, config_digest),")
w("        and it names the LEGACY alias 'executor-terra' where the handoff wrote")
w("        'executor-implementation'. The missing content is not absent from the run:")
w("        it is recorded under inputs.parameters.session_inference, which carries")
w("        requested_policy executor-implementation, requested_reasoning_effort medium,")
w("        runtime_reported_model claude-fable-5-1, model_verified false with a note")
w("        that the adapter binding (claude-sonnet-5) and the runtime-reported model")
w("        differ, degraded false, independent_session true, no_bedrock true, and")
w("        fallback_used 'unknown' (a disclosure, not a false boolean). Recorded as a")
w("        schema deviation, not as missing evidence.")
w("    - check: 'stderr empty; timing source; resources'")
w("      result: pass")
w("      detail: 'stderr.log is 0 bytes on all 23; timing.timing_source = wrapper on all 23; peak_rss_bytes and cpu_seconds present on all 23'")
w("    - check: 'budget and run-count caps'")
w("      result: pass")
w("      detail: >-")
w("        23 runs of the contract's maximum 48. Total wall 6853.34 s, total cpu")
w("        6852.21 s = 1.90 h against total_cpu_hours 48 (handoff envelope 172800 s).")
w("        Largest single run 1150.06 s against wall_clock_seconds_per_run 7200. Budget")
w("        block identical on all 23 (7200 / wall_guard 6600 / 8 GB / 1 worker /")
w("        blas_threads 1). not_computed_wall_guard = 0 and not_plantable_draws = 0 in")
w("        every ladder cell.")
w("    - check: 'engine policy and the dense exactness bound'")
w("      result: pass")
w("      detail: >-")
w("        engine_policy identical on all 23: sparse_column_limit 256,")
w("        certificate_column_limit 1024, dense_exactness_bound 'p^2 (ncols + 1) < 2^53'.")
w("        At the binding case p = 65537 with the recorded 968 columns the bound is")
w("        65537^2 x 969 = 4161950319561 < 2^53 = 9007199254740992, a margin of 2164x;")
w("        it also holds at the 1024-column cap. Verified arithmetically; no violation.")
w("")

w("  metric_recomputations:")
w("    - metric: '(d_ff, d_lf) per (s, instance) under the HKY V_{F,D} closure, D_max = 7'")
w("      method: 'BLIND re-derivation from the definition alone with my own exact linear algebra; harness/macaulay_fp not imported; no producer artifact read'")
w("      systems: 48   # 12 declared instances x s in {2,3,4,5}")
w("      recomputed: '(5,5) at s=2 on 12/12; (5,5) at s=3 on 12/12; (6,6) at s=4 on 12/12; (6,6) at s=5 on 12/12'")
w("      producer_recorded: '(5,5), (5,5), (6,6), (6,6) as the single distinct pair in every cell of the 15 ladder manifests (40 Semaev draws each)'")
w("      agreement: exact")
w("      extra: 'exactly one fall degree per system on all 48 (d_lf = d_ff); 0 right-censored under my own certificate; V_{F,d_ff} equals the full ideal cap I(Z) n B_{<=d_ff} on all 48'")
w(f"    - metric: 'OLS slope of d_lf on s over s = 2..5, per draw'")
w(f"      recomputed: '{ci('d_lf_per_draw')}, residual variance {fits['d_lf_per_draw']['residual_variance']:.6f}'")
w("      note: 'my 48 draws; the producer fitted 480 draws of the same four values'")
w(f"    - metric: 'OLS slope of d_lf on s over s = 2..5, per (s, p) cell mean'")
w(f"      recomputed: '{ci('d_lf_per_cell')}'")
w(f"    - metric: 'OLS slope of d_lf on s over s = 2..5, per s mean (independent units)'")
w(f"      recomputed: '{ci('d_lf_per_s')}'")
w("      note: >-")
w("        This is the only aggregation whose units are independent: within-cell")
w("        variance is exactly 0 (every draw in every cell returns the same integer),")
w("        so the four s-values 5, 5, 6, 6 are the whole dataset.")
w("    - metric: \"contract's three-outcome rule\"")
w("      recomputed: >-")
w("        UNRESOLVED on all three aggregations. Outcome I needs the interval to")
w("        contain 1 and exclude 0.5: per-draw and per-cell contain neither 1 nor 0;")
w("        per-s contains 1 but does not exclude 0.5. Outcome III needs the interval")
w("        to contain 0 and exclude 0.25 AND four consecutive s uncensored with one")
w("        common d_lf: the longest such run is 2 (s = 2,3 at 5 and s = 4,5 at 6), so")
w("        the flat clause fails on the integers themselves at every aggregation.")
w("    - metric: \"HEUR-002 falsifier statistic ('the d_lf interval excludes 0')\"")
w("      recomputed: 'TRUE on the per-draw fit [0.3406, 0.4594] and on the per-cell fit [0.2591, 0.5409]; FALSE on the per-s fit [-0.2085, 1.0085]'")
w("      note: >-")
w("        Reported as a recomputation, not as a judgement. Whether the statistic is a")
w("        valid instrument is joint R1, which I do not own. What I can say from my own")
w("        numbers: the statistic's truth value is decided entirely by which")
w("        aggregation is used, and the aggregation with independent units is the one")
w("        on which it is false.")
w("    - metric: 'analytic reproduction of the producer-reported n = 480 fit'")
w("      method: 'OLS of the step (5,5,6,6) each replicated 120 times, computed from the shape alone'")
w("      recomputed: 'slope 0.400000, residual variance 0.0502092, se 0.0091478, t_.975,478 = 1.964939, ci [0.382025, 0.417975]'")
w("      note: >-")
w("        Matches the execution report's quoted [0.3820, 0.4180] and residual_variance")
w("        0.0502 as quoted in the task card. This is an analytic check of the")
w("        arithmetic, not a validation of the fit's units, and it was computed from")
w("        the step shape rather than from any producer file.")
w("")

w("  control_checks:")
w("    - control: CTRL-DFF-AGREEMENT")
w("      blocking: true")
w("      result: pass_with_caveat")
w("      detail: >-")
w("        RUN-PFDR-cbdefb-dff-agreement records 24 rows (curve seeds 1101-1103 x")
w("        targets 1-2 x s = 2..5 at p = 4099), P1_all_agree true, same_instance_all")
w("        true, disagreements [], 0 censored, and per s closure_d_ff = graded_5726af =")
w("        closure_d_lf = 5, 5, 6, 6. The four sibling EXP-PFDR-5726af manifests")
w("        independently record semaev_d_ff_values as 12 copies of 5, 5, 6, 6 with")
w("        spread 1 and P1_all_semaev_d_ff_equal_frozen true, at D_max 6, 7, 8, 9. The")
w("        cbdefb manifest pins each sibling's raw-result.json by sha256 and all four")
w("        recompute (files hashed, never opened).")
w("      caveat: 'this control ran under closure.py 74e659bb, which is retained nowhere; every ladder cell ran under 63475db5'")
w("    - control: 'CTRL-DFF-AGREEMENT, independent re-derivation (my own code)'")
w("      result: pass")
w("      detail: >-")
w("        On the instance named in the plan (5726af curve seed 1101, target 1,")
w("        p = 4099, a = 527, b = 72, x_R = 2374) my blind closure returns (5,5), (5,5),")
w("        (6,6), (6,6) at s = 2..5, certified uncensored. The curve is non-singular")
w("        with j = 892 and on-curve window x = {1,2,3}, matching the 5726af manifest's")
w("        CTRL-S2-HAND-FIXTURE record exactly, and x_R = 2374 = x((1,555) + (3,1574)).")
w("        So the agreement control's numbers are reproduced by code that never saw the")
w("        producer's implementation.")
w("    - control: 'CTRL-ITERATION-COUNT (fall with iteration count 1)'")
w("      result: pass_at_s_ge_2")
w("      detail: >-")
w("        fall_with_iteration_count_1 = 0 on every arm in all twelve s >= 2 ladder")
w("        cells; min_iteration_count_at_falls on the Semaev arm is 3, 5, 6, 8 at")
w("        s = 2..5. At s = 1 the tell fires with min count 1 on 40/40 Semaev draws,")
w("        40/40 non-curve draws and 30, 50 and 85 of the 200 NULL-1 draws at")
w("        p = 4099, 65537 and 16411; NULL-2 is unaffected there (min count 2, 0")
w("        flagged). My own closure needs")
w("        1 + productive rounds = 2, 4, 4, 5 at s = 2..5, i.e. >= 2 at every claimed")
w("        fall, so the control's floor is met under an independent implementation")
w("        too. The count difference is explained by multiplier granularity (see")
w("        limitations), not by a different fixed point.")
w("    - control: 'cross-engine coverage (sparse vs dense)'")
w("      result: recorded")
w("      detail: >-")
w("        s = 1..4 cells: engine sparse, cross_checked 40/40 on the Semaev arm,")
w("        cross_check_agree_all true. s = 5 cells: engine dense, cross_checked 1/40.")
w("        So 39 of 40 Semaev draws in each s = 5 cell, and 117 of 120 across the three")
w("        primes, rest on the dense engine alone. engine_cross_check_all_agree is true")
w("        in all 15 cells.")
w("    - control: 'null and nearby arms as recorded (not my joints; tabulated for the composition)'")
w("      result: recorded")
w("      detail: >-")
w("        NULL-1/NULL-2 d_lf = 3, 5, 6, 7 at s = 1..4 with band offsets 0, 1, 1, 1,")
w("        and at s = 5 all 200 NULL-1 and 5 NULL-2 draws are right_censored with no")
w("        fall in (4, 7]. NULL-3 has no fall at s = 2 (5 draws, no_fall_in_window 5,")
w("        right_censored 0 -- consistent with D_max >= n + 1 there) and matches the")
w("        Semaev pair at s = 3, 4, 5 (null3_minus_semaev_dff and _dlf both [0]). The")
w("        non-curve cubic reproduces the Semaev pair in every one of the 15 cells.")
w("        P1_closure_dff_equals_graded_dff_all_semaev is true in all 15.")
w("    - control: 'instance validity of the declared 12-instance subsample (my own arithmetic)'")
w("      result: pass")
w("      detail: >-")
w("        12/12 curves non-singular (4a^3 + 27b^2 != 0) with a, b != 0 and j not in")
w("        {0, 1728}; 12/12 have at least two on-curve x in the planting window [0,4)")
w("        (four curves have three, two have two); 12/12 x_R equals x(P_1 + P_2) for an")
w("        exhibited pair of window points with signs; and for every (instance, s) the")
w("        digit solution set of S~ is non-empty and lies inside the window.")
w("")

w("  joints:")
w("    - joint: 'V1 blind re-derivation of (d_ff, d_lf) under the HKY closure on the declared subsample and the slope over s = 2..5'")
w("      result: holds")
w("      attack_executed: >-")
w("        Implemented the quantity from its statement with my own code: S~ =")
w("        S_3(ell_1, ell_2, x_R) built from the formula given, the field equations,")
w("        and V_{F,D} for D = 0..7 computed to a fixed point by exact linear algebra")
w("        mod p. Ran all 48 systems. Executed the literal polynomial-ring reading in")
w("        R = F_p[a] with the field equations adjoined at s = 2 (12/12 instances) and")
w("        s = 3 (1 instance) and proved the general equivalence with the squarefree")
w("        computation used at s = 4, 5. Fitted d_lf on s per draw, per (s,p) cell and")
w("        per s with 95 percent t-intervals, and evaluated the contract's rule on each.")
w("      deciding_fact: >-")
w("        Every one of the 48 systems gives exactly (5,5), (5,5), (6,6), (6,6) at")
w("        s = 2..5 with a single fall degree, uncensored under my own certificate.")
w("        No breaking artifact exists: no (s, instance) departs from the pattern and")
w("        no system has more than one fall degree. The slope is 0.4 on all three")
w("        aggregations; the interval is [0.3406, 0.4594] per draw, [0.2591, 0.5409]")
w("        per cell and [-0.2085, 1.0085] on the four independent s-points, and the")
w("        contract's label is UNRESOLVED on all three.")
w("      qualification: >-")
w("        The quantity is CONVENTION-DEPENDENT and I can bound how much. A third")
w("        reading -- the quotient ring with the condition deg_B(h v) <= D instead of")
w("        deg(h) + deg_B(v) <= D, i.e. allowing degree-D elements to be multiplied")
w("        because idempotency keeps the product's reduced degree at D -- gives the")
w("        ladder 4, 5, 5, 6 and a four-point slope of 0.6 instead of 0.4. It is NOT")
w("        the reading the plan designates, and it is NOT the plan's named reduced-ring")
w("        variant (which multiplies only elements of degree <= D-1 and is the reading")
w("        I proved equivalent to the literal one). The producer's convention_id string")
w("        in all 23 manifests -- 'cumulative-Macaulay W0 + V_{F,D-1}; fallen x")
w("        variables to fixed point; reduced degree; fall iff dim(V_D cap B_{<=D-1}) >")
w("        dim V_{D-1}' -- describes the designated reading, not the third one:")
w("        multiplying FALLEN elements (degree <= D-1) by VARIABLES is exactly the")
w("        constraint I implemented, seeding with V_{F,D-1} is a no-op by monotonicity,")
w("        and the fall test is identical. So the agreement is on the intended object.")
w("    - joint: 'V2 run-set validity, manifest schema and pinning, the two closure.py hashes, the convention hash binding, seeds'")
w("      result: breaks")
w("      attack_executed: >-")
w("        Checked all 23 run directories for the seven files, recomputed every sidecar")
w("        hash, parsed every manifest strictly, compared status / commit / dirty /")
w("        pinned source hashes / seeds / D_max / plant_window / engine_policy / budget /")
w("        timing source / stderr size / session inference, recomputed the convention")
w("        hash without opening the file, recomputed the 14 meter hashes against")
w("        VALIDATION.md, verified the dense exactness bound arithmetically, counted")
w("        runs and wall time against the caps, and searched git history for both")
w("        closure.py blobs.")
w("      deciding_fact: >-")
w("        Nothing on the plan's breaking-artifact list fires: no hash mismatch, no")
w("        third closure.py version, the convention hash matches the file, the seed")
w("        sets are the contract's (3101-3108 x 1-5 with null seeds 7, 11, 13, 17, 19")
w("        in the 15 ladder cells; 1101-1103 x 1-2 in the dff-agreement run; 3101-3103")
w("        for the equal-d^s and m = 3 cells), D_max is 7 and plant_window 4 wherever")
w("        the contract says so, and the exactness bound holds with a 2164x margin at")
w("        p = 65537 and 968 columns. The joint nonetheless BREAKS on a fact the plan")
w("        did not anticipate: closure.py 74e659bb -- the version that produced")
w("        RUN-PFDR-cbdefb-fixture, -s1-slice and -dff-agreement, i.e. all three")
w("        blocking instrument controls in their Stage-1 form -- exists in NO reachable")
w("        commit and not in the tree. Those three receipts pin a file that no longer")
w("        exists, so they cannot be re-run, and the plan's own disposition for this")
w("        joint ('a disclosed change whose metric-neutrality only the red team, who")
w("        may read the file, can judge') is not executable by anyone.")
w("      scope_of_the_break: >-")
w("        The 20 runs that produced EVERY number in the ladder, the equal-d^s cells")
w("        and the m = 3 cells are pinned to 63475db5, which is committed in a3a81e33")
w("        and hashes identically in the tree; those receipts are reproducible. The")
w("        break is confined to the three Stage-1 control runs, and it is partly")
w("        mitigated: the s = 1 floor was re-measured under 63475db5 in the three")
w("        m2-s1 ladder cells, and the closure-vs-graded d_ff identity (P1) is")
w("        recomputed inside all 15 ladder cells under 63475db5. What is unmitigated")
w("        is the comparison against EXP-PFDR-5726af's recorded values, which exists")
w("        only under the lost version -- and which my own independent re-derivation")
w("        of the (1101, 1) instance reproduces.")
w("    - joint: 'V3 instance and certificate checks on the declared subsample and the distinct-instance count'")
w("      result: holds")
w("      attack_executed: >-")
w("        Rebuilt each of the 12 declared instances with my own F_p and elliptic-curve")
w("        arithmetic (Tonelli-Shanks for p = 65537): discriminant, j-invariant,")
w("        on-curve x in [0,4), all window points with both signs, every x(P_1 + P_2)")
w("        over ordered pairs including doublings, and the digit solution set of S~ at")
w("        each s by a subset transform.")
w("      deciding_fact: >-")
w("        No breaking artifact: every declared x_R is a window-pair sum with an")
w("        exhibited witness, every curve is non-singular with generic j, and every")
w("        digit solution lies in the window. The distinct-system bound: a curve")
w("        contributes at most as many distinct generator systems as it has reachable")
w("        x(P_1 + P_2), which is 9 for the four curves with three on-curve window x")
w("        and 4 for the two curves (both at p = 16411) with two. A curve of the second")
w("        kind cannot supply 5 distinct targets, so at least one duplicate per such")
w("        curve is FORCED -- which is exactly the plan's declared duplicate at")
w("        p = 16411 curve 3101 (target seeds 2 and 3 share x_R = 4634). A cell")
w("        therefore holds at most 8 x 9 = 72 and at least 8 x 4 = 32 distinct systems")
w("        among its 40 draws, so the distinct-system count alone does not collapse")
w("        n = 40 by much.")
w("      stronger_replication_finding: >-")
w("        The binding replication fact is not the distinct-system count but the")
w("        observable's variance: (d_ff, d_lf) is the SAME integer pair on all 12")
w("        instances at each s, across two curves, two targets and three primes, and")
w("        the manifests record a single distinct pair among all 40 draws of every")
w("        cell. Within-cell variance is exactly 0. The 480 draws behind the reported")
w("        fit are therefore 4 numbers, and the per-draw standard error shrinks as")
w("        1/sqrt(480) for no statistical reason. Evaluating the reported statistic on")
w("        independent units is joint R1's business; the zero-variance fact is mine and")
w("        I record it as measured.")
w("      unexpected_observation: >-")
w("        Three of the twelve declared instances have a DEGENERATE decomposition: the")
w("        only digit solution is diagonal, ell_1 = ell_2, so x_R = x(2P) rather than")
w("        x(P_1 + P_2) for distinct points -- p = 65537 curve 3101 target 1 gives")
w("        (0,0), target 2 gives (1,1), and curve 3102 target 2 gives (3,3). These are")
w("        legitimate window pairs and the pair (d_ff, d_lf) is unaffected, but a")
w("        quarter of the subsample carries a doubling rather than a genuine")
w("        two-summand decomposition and the solution set has size 1 rather than 2.")
w("        Recorded as an unexpected observation under AGENTS.md rule 8.")
w("      limitation: >-")
w("        The manifests do not record per-draw (a, b, x_R); those live in")
w("        raw-result.json, which is blind_from for me. I therefore could not compare")
w("        the plan's transcribed triples with a producer artifact. What I could")
w("        establish is internal validity, which is nearly as strong: a mis-transcribed")
w("        x_R would fail the window-pair-sum test except with probability about 9/p.")
w("    - joint: 'V4 CTRL-DFF-AGREEMENT and cross-engine coverage from the manifests'")
w("      result: holds")
w("      attack_executed: >-")
w("        Read the dff-agreement manifest and the four EXP-PFDR-5726af cell manifests,")
w("        verified the pinned sibling raw-result.json hashes by hashing (not opening),")
w("        tabulated engine / cross_checked / cross_check_agree_all / censoring /")
w("        iteration counts / P1 per cell per arm from the 15 ladder manifests, and")
w("        re-derived the (1101, 1) agreement instance with my own closure.")
w("      deciding_fact: >-")
w("        No breaking artifact: no dff-agreement row disagrees with 5726af's recorded")
w("        value (24/24, disagreements empty, same_instance_all true), no censored")
w("        Semaev draw exists anywhere on the ladder (right_censored 0 and")
w("        no_fall_in_window 0 in all 15 cells), and no cell has a false cross-check")
w("        flag. 5726af's own manifests record 5, 5, 6, 6, and my independent closure")
w("        returns 5, 5, 6, 6 on the same instance.")
w("      limitation: >-")
w("        Cross-engine coverage is 40/40 at s <= 4 and 1/40 at s = 5, so 117 of the")
w("        120 s = 5 Semaev draws rest on the dense engine alone. That engine is not")
w("        the validated meter: harness/macaulay_fp/VALIDATION.md states 'no floating")
w("        point anywhere in a rank', so the dense float64 path lives in closure.py and")
w("        its correctness rests on the declared exactness bound rather than on the")
w("        meter's test suite. The bound holds at the recorded sizes; the code that")
w("        applies it is outside my read set.")
w("")

w("  heuristic_validation_checks:")
w("    - check: 'pre-registered prediction'")
w("      result: pass")
w("      detail: >-")
w("        The frozen contract (specification.yaml, approved 2026-09-03, DEC-20260903-93862f)")
w("        pre-registers d_ff = 5, 5, 6, 6 at s = 2..5, the null band c in {0,1,2}, the")
w("        three-outcome rule and the joint-label reconciliation, before any run. My")
w("        blind re-derivation reproduces the d_ff prediction exactly on 48 systems.")
w("        The prediction was not fitted after the data.")
w("    - check: 'sample integrity (sizes, seeds, procedure in the manifest)'")
w("      result: pass")
w("      detail: 'seeds, curve/target/null seed sets, window, D_max, per-cell draw counts (40 Semaev, 200 NULL-1, 5 NULL-2, 5 NULL-3, 40 non-curve) are all in the manifests and match the contract'")
w("    - check: 'correspondence validity'")
w("      result: not_applicable")
w("      detail: 'no correspondence or substitute sampler is used; all systems are computed directly at the tested primes'")
w("    - check: 'scale binding'")
w("      result: pass_with_limitation")
w("      detail: >-")
w("        The contract labels the tier toy (p <= 2^16, s <= 5, <= 1024 columns) and")
w("        states that no transfer in s is claimed. My re-derivation is at exactly that")
w("        scale and carries no transfer either. The measured law d_ff = d_lf =")
w("        4 + floor(s/2) is a statement about s in {2,3,4,5} only: four points at")
w("        resolution 0.25.")
w("    - check: \"HEUR-001 band, where testable\"")
w("      result: recorded")
w("      detail: 'null band offsets 0, 1, 1, 1 at s = 1..4 (inside {0,1,2}); at s = 5 all null draws are right-censored by D_max = 7, so the top cell of the null is not testable'")
w("    - check: \"HEUR-002 falsifier statistic\"")
w("      result: aggregation_dependent")
w("      detail: 'see metric_recomputations; true per draw and per cell, false on the four independent s-points'")
w("")
w("  cost_model_checks:")
w("    - check: 'concrete cost table present in this experiment'")
w("      result: not_applicable")
w("      detail: >-")
w("        EXP-PFDR-cbdefb produces no cost table; the cost consequences of a measured")
w("        D_0(s) belong to EXP-PFDR-c04716 / H-PFDR-06fd60 and are outside this")
w("        experiment and outside my joints. I record only the datum they would need:")
w("        my own closure reaches the full ideal cap at D = 4 + floor(s/2) on every one")
w("        of the 48 systems, so the solving degree measured here GROWS with s and is")
w("        6 already at s = 4, 5. Any cost statement that assumes a constant D_0 <= 6")
w("        must state what it does at s >= 6, which this ladder does not test.")
w("    - check: 'resource records present per run'")
w("      result: pass")
w("      detail: 'peak_rss_bytes and cpu_seconds in all 23 manifests; per-cell pre-flight column counts, dense-equivalent byte bounds and the 50000-column / 4 GiB caps recorded and within contract in every ladder cell'")
w("")
w("  proof_architecture_checks:")
w("    - check: 'baseline fixture reproduces exactly'")
w("      result: pass_at_the_ladder_level")
w("      detail: >-")
w("        The inherited d_ff law (H-PFDR-4148b8 / IDEA-20260903-e1e38b: 5, 5, 6, 6) is")
w("        reproduced exactly by an independent implementation on 48 systems and by the")
w("        dff-agreement control against EXP-PFDR-5726af. The known-answer fixture run")
w("        itself is one of the three runs whose code is not retained (see V2).")
w("    - check: 'quantifier fidelity'")
w("      result: pass")
w("      detail: >-")
w("        Nothing I computed licenses 'there exists D_0 for all s'. What is measured is")
w("        'for all cells of the declared ladder, the pair and the fitted slope', which")
w("        is what H-PFDR-c88f14's proof_search_map.quantifier_order says is claimed.")
w("    - check: 'ceiling and nearby control'")
w("      result: recorded")
w("      detail: 'the non-curve cubic reproduces the Semaev pair in all 15 cells; the interpretation of that is joint R4, not mine'")
w("")

w("  verdict: incomplete")
w("  verdict_rationale: >-")
w("    The load-bearing quantity is confirmed. An implementation that never saw the")
w("    producer's code, notes or report reproduces (d_ff, d_lf) = (5,5), (5,5), (6,6),")
w("    (6,6) on all 48 systems of the declared subsample, reproduces the")
w("    CTRL-DFF-AGREEMENT instance, and obtains the same slope 0.4; the run set is")
w("    schema-complete, hash-consistent, correctly seeded, within budget, and its")
w("    convention hash and meter pinning bind. The receipt is nevertheless INCOMPLETE")
w("    rather than passed, for one reason that cannot be repaired: three of the 23")
w("    runs -- the known-answer fixture, the s = 1 baseline slice and the")
w("    d_ff-agreement control, i.e. all three blocking instrument controls in their")
w("    Stage-1 form -- pin a closure.py version that is retained in no commit and no")
w("    working tree. A pin to a blob nobody has is not retention, those three runs")
w("    cannot be re-run, and no reviewer can judge whether the change between the two")
w("    versions was metric-neutral. Per docs/evidence-and-reproducibility.md a missing")
w("    reproduction-package element is incomplete evidence, not invalid evidence: I")
w("    found no wrong number anywhere, and the numbers the controls were meant to")
w("    guard are independently confirmed by this re-derivation, which is why the")
w("    verdict is incomplete and not failed. Admissibility of the 20 measurement runs")
w("    is not in question. This verdict is about the receipt only. It supports no")
w("    ECDLP claim, demonstrates no speedup, and authorises no promotion or status")
w("    change.")
w("")

w("  limitations:")
w("    - >-")
w("      I own four joints of ten. Joints R0-R5 and the proves-too-much control are")
w("      invisible to me by construction, and nothing here is a verdict on the claim.")
w("    - >-")
w("      closure.py 74e659bb is retained nowhere, so the metric-neutrality of the")
w("      disclosed code change cannot be established by me or by any later reviewer.")
w("      The remedy is not a re-read: it is a re-run of the three Stage-1 controls")
w("      under the retained version 63475db5, which would cost about 13 minutes")
w("      (dff-agreement was 762 s, the other two under 25 s).")
w("    - >-")
w("      117 of the 120 s = 5 Semaev draws rest on the dense float64 engine with no")
w("      second engine agreeing. The engine's exactness bound is declared and I")
w("      verified it holds arithmetically at p = 65537 with 968 columns (margin 2164x),")
w("      but the code implementing it is in blind_from and the validated meter")
w("      explicitly contains no floating point in a rank. My own independent")
w("      computation at s = 5 used a different exact method and agrees on all 12")
w("      instances, which is the strongest cross-check available to me.")
w("    - >-")
w("      The quantity is convention-dependent at the level that matters: a defensible")
w("      third reading of 'closed under multiplication' in the quotient ring moves the")
w("      ladder from 5, 5, 6, 6 to 4, 5, 5, 6 and the slope from 0.4 to 0.6. My")
w("      primary reading is the one the plan designates, and the manifests'")
w("      convention_id string describes that same reading, but the frozen convention")
w("      document itself is load-bearing for every number in the package and I did not")
w("      open it (only hashed it).")
w("    - >-")
w("      My subsample is 12 of the 120 draws per cell (2 curves of 8, 2 targets of 5,")
w("      all three primes). Because the manifests record a single distinct pair per")
w("      cell, agreement on my 12 implies agreement with every recorded draw; but I")
w("      verified 12 instances, not 120, and only the Semaev arm.")
w("    - >-")
w("      Pass counts are not comparable between implementations without stating the")
w("      multiplier granularity. The producer's convention multiplies fallen elements")
w("      by VARIABLES; mine multiplies them by ALL monomials of the admissible degree.")
w("      Both reach the same fixed point (iterating single variables generates every")
w("      admissible monomial multiple, since the intermediate degrees stay within the")
w("      bound), but the producer's counts are necessarily larger: their")
w("      min_iteration_count_at_falls is 3, 5, 6, 8 at s = 2..5 against my 2, 4, 4, 5.")
w("      Any comparison of iteration counts across the two must say which convention it")
w("      is using; CTRL-ITERATION-COUNT's floor of 2 is met under both.")
w("    - >-")
w("      run.inference in all 23 manifests is an abbreviated block missing 10 template")
w("      fields and naming the legacy policy alias; the content is present under")
w("      inputs.parameters.session_inference. Disclosed as a schema deviation.")
w("    - >-")
w("      Three of my twelve instances carry a doubling (ell_1 = ell_2) rather than a")
w("      two-summand decomposition.")
w("    - >-")
w("      Everything here is at the contract's declared toy scale: p <= 2^16, s <= 5,")
w("      at most 968 columns, four points on the s-axis at resolution 0.25. No")
w("      statement about larger s or about any cryptographic parameter follows.")
w("")

w("  inference:")
w("    requested_policy: review-adversarial")
w("    canonical_policy: review-adversarial")
w("    requested_reasoning_effort: xhigh")
w("    reasoning_effort: xhigh")
w("    backend: anthropic")
w("    provider: anthropic")
w("    resolved_model_id: claude-opus-5")
w("    model_provenance: runtime-reported")
w("    model_verified: false")
w("    model_verified_note: >-")
w("      `python3 -m orchestration.adapter resolve --role validator --independent-session`")
w("      returns 'review-adversarial -> anthropic:claude-opus-5 (effort=xhigh)', which")
w("      agrees with the model identifier this session reports (claude-opus-5). I did")
w("      not run `doctor --probe`, and identifier agreement is not a probe, so")
w("      model_verified stays false.")
w("    fallback_used: false")
w("    fallback_reason: null")
w("    degraded_requirements: []")
w("    independent_session: true")
w("    no_bedrock: true")
w("")

w("  artifact_paths:")
for rel, h in arts:
    if rel.endswith("validation-report.yaml"):
        continue
    w(f"    - {{path: {rel}, sha256: {h}}}")
w("    - {path: " + REL + "validation-report.yaml, sha256: null}  # self; hashed by the archive receipt")
w("")

w("  records_modified: none")
w("  commits_made: none")
w("  write_scope_respected: true")
w("")

w("review_attestation:")
w("  task_id: TASK-20260904-42b33a")
w("  joints_owned:   # copied verbatim from review_plan.joints")
w("    - 'V1 blind re-derivation of (d_ff, d_lf) under the HKY closure on the declared subsample and the slope over s = 2..5'")
w("    - 'V2 run-set validity, manifest schema and pinning, the two closure.py hashes, the convention hash binding, seeds'")
w("    - 'V3 instance and certificate checks on the declared subsample and the distinct-instance count'")
w("    - 'V4 CTRL-DFF-AGREEMENT and cross-engine coverage from the manifests'")
w("  per_joint_result:")
w("    V1: holds")
w("    V2: breaks")
w("    V3: holds")
w("    V4: holds")
w("  sources_read:")
w("    phase_A:")
w("      - ledger/handoffs/TASK-20260904-42b33a.yaml")
w("      - agents/validator.md")
w("      - AGENTS.md")
w("      - CLAUDE.md")
w("      - docs/evidence-and-reproducibility.md")
w("      - knowledge/literature/KN-LIT-7607.md")
w("      - experiments/EXP-PFDR-cbdefb/specification.yaml")
w("      - ledger/hypotheses/H-PFDR-c88f14.yaml")
w("    phase_B:")
w("      - experiments/EXP-PFDR-cbdefb/runs/*/manifest.yaml   # all 23, in full")
w("      - experiments/EXP-PFDR-cbdefb/runs/*/command.txt      # all 23")
w("      - experiments/EXP-PFDR-cbdefb/runs/*/environment.json # all 23")
w("      - experiments/EXP-PFDR-cbdefb/runs/*/package-sha256.json  # all 23")
w("      - experiments/EXP-PFDR-cbdefb/runs/*/stderr.log       # sizes only (all 0 bytes)")
w("      - experiments/EXP-PFDR-5726af/runs/RUN-PFDR-5726af-m2-s2-gate/manifest.yaml")
w("      - experiments/EXP-PFDR-5726af/runs/RUN-PFDR-5726af-m2-s3/manifest.yaml")
w("      - experiments/EXP-PFDR-5726af/runs/RUN-PFDR-5726af-m2-s4/manifest.yaml")
w("      - experiments/EXP-PFDR-5726af/runs/RUN-PFDR-5726af-m2-s5/manifest.yaml")
w("      - harness/macaulay_fp/VALIDATION.md   # sections 1-3 (deliverable table, test results, port note)")
w("      - ledger/handoffs/TASK-20260903-6745ea.yaml   # header, budget, inference, write_scope")
w("      - ledger/decisions/DEC-20260903-93862f.yaml   # grep for target_ids / EXP-PFDR-cbdefb only")
w("      - templates/research-records.md   # review_attestation and archive blocks")
w("      - tools/allocate_id.py   # prefix table, to confirm VAL-* is unregistered")
w("  hashed_but_not_opened:")
w("    - experiments/EXP-PFDR-cbdefb/stage1-closure-convention.md")
w("    - experiments/EXP-PFDR-cbdefb/closure.py")
w("    - experiments/EXP-PFDR-cbdefb/run_cbdefb.py")
w("    - experiments/EXP-PFDR-cbdefb/analyze.py")
w("    - experiments/EXP-PFDR-cbdefb/runs/*/raw-result.json")
w("    - experiments/EXP-PFDR-cbdefb/runs/*/stdout.log")
w("    - experiments/EXP-PFDR-5726af/runs/RUN-PFDR-5726af-m2-s{2-gate,3,4,5}/raw-result.json")
w("  not_read_declared_inputs:")
w("    - harness/macaulay_fp/*.py and tests/test_macaulay_fp.py were HASHED but their")
w("      source was not read; my closure and ranks are my own code and import nothing")
w("      from harness/.")
w("    - docs/claims-and-verification.md was not opened; no claim-tier question arose")
w("      that the handoff and AGENTS.md did not settle.")
w("  read_sibling_reports: false")
w("  read_sibling_reports_note: >-")
w("    One repository-wide grep with -l (filenames only) and one grep whose printed")
w("    matches all came from paths outside coordination/reviews/pfdr-battery-20260904/")
w("    returned the NAMES of sibling report files while I was checking VAL-* identifier")
w("    practice. No line of any sibling report was displayed and no sibling report was")
w("    opened. Disclosed rather than left implicit.")
w("  blind_from_respected: true")
w("  blind_from_respected_note: >-")
w("    No path in review_plan.blind_rederivation.blind_from was opened at any point,")
w("    in phase A or phase B. raw-result.json, stdout.log, closure.py, run_cbdefb.py,")
w("    analyze.py and stage1-closure-convention.md were passed to sha256 only, which")
w("    the handoff explicitly permits for the convention file and which is the same")
w("    operation for the others. The producer's convention_id string quoted in this")
w("    report was read from the MANIFESTS, which are not blind_from.")
w("  verdict: breaks   # for the four joints owned collectively, because V2 breaks;")
w("                    # V1, V3 and V4 hold, and V1 -- the load-bearing quantity --")
w("                    # holds exactly")
w("  id_allocation_provenance: >-")
w("    VAL-20260904-42b33a mirrors the task token, which is this repository's existing")
w("    practice for validation reports. VAL-* has no prefix registered in")
w("    tools/allocate_id.py, so no identifier was allocated; --check confirms the id is")
w("    well-formed-by-default and free (0 occurrences across 11107 identifier-bearing")
w("    paths). No other identifier was minted by this task.")
w("  yaml_parse_disclosure: >-")
w("    Emitted by scripts/write_report.py and round-tripped through yaml.safe_load")
w("    before delivery; no tabs, no duplicate keys, every prose value a folded or")
w("    quoted scalar.")

open(BASE + "validation-report.yaml", "w").write("\n".join(L) + "\n")
print("wrote validation-report.yaml;", len(arts), "artifacts hashed")
