#!/usr/bin/env python3
"""
Negative controls for the exact certifier (controls before belief).

A certifier that says "independent" to everything is worthless, so before any
of its outputs are used the same code is run against objects whose answer is
KNOWN: dependent point sets, off-curve points, and torsion points.  Pure
stdlib, no PARI.

  C1  P and 2P on a rank-1 curve       -> must certify 1, not 2
  C2  P, Q, P+Q on a rank-2 curve      -> must certify 2, not 3
  C3  a point with a typo'd y          -> must be rejected as off-curve
  C4  a torsion point                  -> must be rejected as torsion
  C5  the true generators of a rank-2 curve -> must certify 2

usage: python3 selftest_certifier.py [out.json]
"""
import json
import sys
from fractions import Fraction as F

from exact_certify import Qfield, add, mul, certify


def controls():
    K = Qfield()
    out = []

    # C1: 389a1 has rank 2 with generators (-1,1) and (0,-1); use only one and
    # its double on the rank-1 curve 37a1 y^2+y=x^3-x, generator (0,0).
    ai37 = [0, 0, 1, -1, 0]
    aiF = [F(a) for a in ai37]
    P = (F(0), F(0))
    P2 = mul(K, aiF, 2, P)
    c = certify(ai37, [[str(P[0]), str(P[1])], [str(P2[0]), str(P2[1])]])
    out.append({'control': 'C1 P and 2P on 37a1 (true rank 1)',
                'expected_certified': 1,
                'certified': c['certified_rank_lower_bound'],
                'pass': c['certified_rank_lower_bound'] == 1})

    # C2: 389a1, y^2 + y = x^3 + x^2 - 2x, rank 2, generators (-1,1), (0,-1)
    ai389 = [0, 1, 1, -2, 0]
    aiF = [F(a) for a in ai389]
    A = (F(-1), F(1))
    B = (F(0), F(-1))
    C = add(K, aiF, A, B)
    pts = [[str(A[0]), str(A[1])], [str(B[0]), str(B[1])], [str(C[0]), str(C[1])]]
    c = certify(ai389, pts)
    out.append({'control': 'C2 P, Q, P+Q on 389a1 (true rank 2)',
                'expected_certified': 2,
                'certified': c['certified_rank_lower_bound'],
                'pass': c['certified_rank_lower_bound'] == 2})

    # C5: the two true generators alone
    c = certify(ai389, pts[:2])
    out.append({'control': 'C5 generators of 389a1',
                'expected_certified': 2,
                'certified': c['certified_rank_lower_bound'],
                'pass': c['certified_rank_lower_bound'] == 2})

    # C3: off-curve point
    c = certify(ai389, [['-1', '2'], ['0', '-1']])
    out.append({'control': 'C3 off-curve point (typo in y)',
                'expected_certified': 1,
                'certified': c['certified_rank_lower_bound'],
                'off_curve_failures': c['on_curve_failures'],
                'pass': c['on_curve_failures'] == [0]
                        and c['certified_rank_lower_bound'] == 1})

    # C4: torsion point. 11a1: y^2 + y = x^3 - x^2 - 10x - 20, rank 0,
    # torsion Z/5 generated by (5,5).
    ai11 = [0, -1, 1, -10, -20]
    c = certify(ai11, [['5', '5']])
    out.append({'control': 'C4 torsion point (5,5) on 11a1 (rank 0)',
                'expected_certified': 0,
                'certified': c['certified_rank_lower_bound'],
                'torsion_rejected': c['torsion_points_rejected'],
                'pass': c['certified_rank_lower_bound'] == 0
                        and c['torsion_points_rejected'] == [0]})
    return out


if __name__ == '__main__':
    rows = controls()
    for r in rows:
        print('%-45s expected %s got %s  %s'
              % (r['control'], r['expected_certified'], r['certified'],
                 'PASS' if r['pass'] else 'FAIL'))
    allpass = all(r['pass'] for r in rows)
    if len(sys.argv) > 1:
        json.dump({'controls': rows, 'all_pass': allpass},
                  open(sys.argv[1], 'w'), indent=1)
    print('ALL CONTROLS PASS' if allpass else 'CONTROL FAILURE')
    sys.exit(0 if allpass else 1)
