#!/usr/bin/env python3
"""Generate/check thin adapters; optionally diagnose additional discovery roots."""
from __future__ import annotations
import argparse
from pathlib import Path
import re

PLUGIN_NAME = "crypto-autoresearcher-harness"
NAME = "run"
CANONICAL = f"plugins/{PLUGIN_NAME}/skills/{NAME}/SKILL.md"
ADAPTERS = {
    f".agents/skills/{NAME}/SKILL.md": NAME,
    f".claude/skills/{NAME}/SKILL.md": NAME,
}
RETIRED_ADAPTERS = (
    ".agents/skills/crypto-autoresearcher-harness/SKILL.md",
    ".claude/skills/crypto-autoresearcher-harness/SKILL.md",
    ".claude/skills/launch-research-harness/SKILL.md",
    ".claude/skills/coordinate-research-goal/SKILL.md",
    ".claude/skills/run-experiment/SKILL.md",
)


def render(name: str) -> str:
    return f"""---
name: {name}
description: Run existing experiments and report their outputs. Use for run, run experiments, run the harness, or a named experiment, task, goal, or existing experiment command.
---
<!-- Generated by plugins/{PLUGIN_NAME}/scripts/entrypoints.py; edit the canonical skill. -->

# Run

Read `{CANONICAL}` from this checkout and execute the requested experiments.

Keep this an execution task: launch existing programs, show progress, preserve
outputs, and report results. Do not add an agent-led protocol/schema validation
phase, preparation workflow, or review cycle. Built-in runner checks still apply.

The same run skill is used by Codex and OpenCode, Claude Code, and the plugin.
"""


def check(repo: Path) -> list[str]:
    problems = []
    canonical = repo / CANONICAL
    if not canonical.is_file():
        problems.append(f"missing canonical skill: {canonical}")
    for relative, name in ADAPTERS.items():
        path = repo / relative
        if not path.is_file() or path.read_text() != render(name):
            problems.append(f"adapter drift: {relative}")
    for relative in RETIRED_ADAPTERS:
        if (repo / relative).exists():
            problems.append(f"retired execution skill is still discoverable: {relative}")
    for path in (repo / f"plugins/{PLUGIN_NAME}/skills").rglob("SKILL.md"):
        if path != canonical:
            problems.append(f"extra plugin skill: {path.relative_to(repo)}")
    return problems


def discover(repo: Path, roots: list[Path]) -> list[str]:
    # Only inspect explicitly supplied roots; never read user credentials/config.
    found = {(repo / f".agents/skills/{NAME}/SKILL.md").resolve()}
    for root in roots:
        if not root.is_dir():
            raise ValueError(f"skill root does not exist: {root}")
        for path in root.rglob("SKILL.md"):
            body = path.read_text(encoding="utf-8")
            if re.search(r"(?m)^name:\s*" + re.escape(NAME) + r"\s*$", body):
                found.add(path.resolve())
    return sorted(str(path) for path in found)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", required=True, type=Path)
    action = parser.add_mutually_exclusive_group(required=True)
    action.add_argument("--check", action="store_true")
    action.add_argument("--write", action="store_true")
    parser.add_argument("--skill-root", type=Path, action="append", default=[])
    args = parser.parse_args()
    repo = args.repo.resolve()
    if not (repo / CANONICAL).is_file():
        parser.error("repo does not contain the canonical harness skill")
    if args.write:
        for relative, name in ADAPTERS.items():
            path = repo / relative
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(render(name))
    problems = check(repo)
    for problem in problems:
        print("FAIL: " + problem)
    try:
        candidates = discover(repo, args.skill_root)
    except (OSError, ValueError) as error:
        print(f"FAIL: discovery inspection: {error}")
        return 2
    if len(candidates) > 1:
        print("WARNING: multiple run discovery candidates; this is a filesystem")
        print("inventory, not the host's enabled-skill list. Check the host's skill")
        print("selector and disable the redundant installed copy if both are enabled.")
        for candidate in candidates:
            print("  " + candidate)
    if not problems:
        print("OK: run is the single execution skill across repository and plugin adapters.")
    return 1 if problems else 0


if __name__ == "__main__":
    raise SystemExit(main())
