#!/usr/bin/env python3
"""Generate/check thin adapters; optionally diagnose additional discovery roots."""
from __future__ import annotations
import argparse
from pathlib import Path
import re

NAME = "crypto-autoresearcher-harness"
CANONICAL = f"plugins/{NAME}/skills/{NAME}/SKILL.md"
ADAPTERS = {
    f".agents/skills/{NAME}/SKILL.md": (NAME, None),
    f".claude/skills/{NAME}/SKILL.md": (NAME, None),
    ".claude/skills/launch-research-harness/SKILL.md": ("launch-research-harness", "portfolio"),
    ".claude/skills/coordinate-research-goal/SKILL.md": ("coordinate-research-goal", "goal"),
}


def render(name: str, mode: str | None) -> str:
    description = (
        "Run or inspect the Crypto Autoresearcher harness, continue a GOAL-*, "
        "generate ideas, design experiments, or keep the research portfolio running."
        if mode is None else
        f"Compatibility alias for crypto-autoresearcher-harness in {mode} mode. "
        "Use the canonical harness skill for new requests."
    )
    routing = (
        "Select the mode from the user's request using the canonical mode table."
        if mode is None else
        f"Default to **{mode}** mode; an explicitly named goal or narrower user "
        "scope takes precedence. Do not expand the user's scope."
    )
    return f"""---
name: {name}
description: {description}
---
<!-- Generated by plugins/{NAME}/scripts/entrypoints.py; edit the canonical skill. -->

# Crypto Autoresearcher Harness

Read `{CANONICAL}` from the resolved Git checkout before any action.
{routing}

Follow its shared references for the full lifecycle, continuation, progress
reporting and stopping conditions. All authority stays with AGENTS.md and the
repository's role, dispatcher and archive contracts.

This adapter works across repository-native Codex and OpenCode discovery.
Legacy Claude commands delegate to the same procedure. Do not maintain a
second lifecycle here.
"""


def check(repo: Path) -> list[str]:
    problems = []
    canonical = repo / CANONICAL
    if not canonical.is_file():
        problems.append(f"missing canonical skill: {canonical}")
    for relative, (name, mode) in ADAPTERS.items():
        path = repo / relative
        if not path.is_file() or path.read_text() != render(name, mode):
            problems.append(f"adapter drift: {relative}")
    for name in ("lifecycle.md", "intake.md", "progress.md"):
        if not (canonical.parent / "references" / name).is_file():
            problems.append(f"missing shared reference: {name}")
    return problems


def discover(repo: Path, roots: list[Path]) -> list[str]:
    # Only inspect explicitly supplied roots; never read user credentials/config.
    found = {(repo / f".agents/skills/{NAME}/SKILL.md").resolve()}
    for root in roots:
        if not root.is_dir():
            raise ValueError(f"skill root does not exist: {root}")
        for path in root.rglob("SKILL.md"):
            body = path.read_text(encoding="utf-8")
            if re.search(r"(?m)^name:\s*" + re.escape(NAME) + r"\s*$", body):
                found.add(path.resolve())
    return sorted(str(path) for path in found)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", required=True, type=Path)
    action = parser.add_mutually_exclusive_group(required=True)
    action.add_argument("--check", action="store_true")
    action.add_argument("--write", action="store_true")
    parser.add_argument("--skill-root", type=Path, action="append", default=[])
    args = parser.parse_args()
    repo = args.repo.resolve()
    if not (repo / CANONICAL).is_file():
        parser.error("repo does not contain the canonical harness skill")
    if args.write:
        for relative, (name, mode) in ADAPTERS.items():
            path = repo / relative
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(render(name, mode))
    problems = check(repo)
    for problem in problems:
        print("FAIL: " + problem)
    try:
        candidates = discover(repo, args.skill_root)
    except (OSError, ValueError) as error:
        print(f"FAIL: discovery inspection: {error}")
        return 2
    if len(candidates) > 1:
        print("WARNING: multiple harness discovery candidates; this is a filesystem")
        print("inventory, not the host's enabled-skill list. Check the host's skill")
        print("selector and disable the redundant installed copy if both are enabled.")
        for candidate in candidates:
            print("  " + candidate)
    if not problems:
        print("OK: all repository entry points delegate to one shared lifecycle.")
    return 1 if problems else 0


if __name__ == "__main__":
    raise SystemExit(main())
