#!/usr/bin/env python3
"""PT-3(b) independent check: sympy's Groebner basis (modulus=2, grevlex, x1 > x2 > ..., field equations added as explicit generators)
for the PT-3(b) systems found through the evaluation kernel.  Compares the squarefree minimal leading monomials of the reduced GB with the
minimal elements of LM(I) from the evaluation kernel and prints the maximal size.  Shares no code with the closure."""
import sys, os, json, itertools, time
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import sympy
from sympy import symbols, groebner, Poly
from ref_closure import *

res = json.load(open(sys.argv[1]))
out = []
for case in res['PT-3b_GB_element_above_degree_4'][:int(sys.argv[3]) if len(sys.argv) > 3 else 3]:
    N = case['N']
    xs = symbols('x1:%d' % (N + 1))
    def tomonomial(m):
        t = sympy.Integer(1)
        for j in range(N):
            if (m >> j) & 1: t *= xs[j]
        return t
    gens = [sum(tomonomial(m) for m in g) for g in case['gens']]
    field = [x ** 2 + x for x in xs]
    t = time.time()
    G = groebner(gens + field, *xs, modulus=2, order='grevlex')
    dt = time.time() - t
    lms = []
    for g in G.exprs:
        P = Poly(g, *xs, modulus=2)
        lm = P.monoms(order='grevlex')[0]
        lms.append(lm)
    sqfree = []
    for lm in lms:
        if all(e <= 1 for e in lm):
            sqfree.append(sum(1 << j for j, e in enumerate(lm) if e))
    # minimal squarefree LMs of the whole LM ideal (generated by all lms): a squarefree m is a minimal generator iff it is in lms and no other lm divides it
    def divides(a, b): return all(x <= y for x, y in zip(a, b))
    mins = [lm for lm in lms if not any(lm2 != lm and divides(lm2, lm) for lm2 in lms)]
    mins_sq = sorted(sum(1 << j for j, e in enumerate(lm) if e) for lm in mins if all(e <= 1 for e in lm))
    # evaluation kernel route
    pts = points_of_system(N, [frozenset(g) for g in case['gens']])
    lmI, stdI = eval_kernel_lm(N, N, pts)
    mins_eval = sorted(m for m in lmI if not any(((m ^ (1 << j)) in lmI) for j in range(N) if (m >> j) & 1))
    ok = (mins_sq == mins_eval)
    out.append(dict(N=N, trial=case['trial'], sympy_seconds=round(dt, 2), gb_size=len(G.exprs), max_size_of_squarefree_min_LM_sympy=max(popcount(m) for m in mins_sq),
                    max_size_min_LM_evaluation_kernel=max(popcount(m) for m in mins_eval), minimal_LM_sets_equal=ok, V=case['V'],
                    n_std_via_sympy=None, closure_verdict_D4=case['closure_verdict_D4']))
    print(out[-1], flush=True)
json.dump(out, open(sys.argv[2], 'w'), indent=1)
