#!/usr/bin/env python3
"""
ref_closure.py -- PLAIN REFERENCE implementation of the closure quantity of TASK-20261004-095926,
written from the statement alone.  Small N only (about <= 22).

Representation: polynomial in B = F_2[x_1..x_N]/(x_i^2+x_i) = python frozenset of int bitmasks
(bit j-1 set iff x_j in the monomial); product of monomials = bitwise OR.

ORDER (statement): size first; among equal size m is LARGER than m' iff the LARGEST variable index in
m ^ m' belongs to m'.  With bit j-1 <-> x_j that is: larger  <=>  smaller integer bitmask.  Hence the
sort key  key(m) = (popcount(m), -m)  is increasing in the monomial order.   `order` argument allows
alternative graded orders for the W1(4) order-dependence experiment (deglex, random graded).

CLOSURE: literal fixed point.  Basis is an echelon dictionary LM -> polynomial (distinct leading monomials
so membership in the span = head reduction to 0).  One pass multiplies EVERY current basis element b by every
square-free monomial mu with 1 <= |mu| <= D - deg b (deg b = largest monomial size of b, equal to |LM b| for a
graded order), reduces and inserts the nonzero results; passes repeat until a full pass adds nothing.  At the
fixed point every current basis element's every allowed product lies in the span: W is closed and, being
generated by the generators through allowed products only, is the smallest such subspace.

Mutation switches (for the proves-too-much control PT-1) are explicit keyword arguments and default to the
unmutated closure.
"""
import itertools, sys, random, hashlib
from collections import defaultdict

popcount = lambda x: bin(x).count('1')


def key_degrevlex(m):
    return (popcount(m), -m)


def make_key_deglex(N):
    # graded lexicographic, x_1 largest variable: among equal size m > m' iff the SMALLEST index in the symmetric
    # difference belongs to m.  smallest index = lowest set bit of m^m'.
    def key(m):
        # increasing key with the order: compare by size then by (reversed bit string read from x_1)
        # m > m' iff lowest differing bit is in m.  Encode: key2 = bit-reversed mask as integer  (x_1 -> most significant)
        r = 0
        for j in range(N):
            r = (r << 1) | ((m >> j) & 1)
        return (popcount(m), r)
    return key


def make_key_random_graded(N, seed):
    rng = random.Random(seed)
    cache = {}
    def key(m):
        if m not in cache:
            cache[m] = rng.random()
        return (popcount(m), cache[m])
    return key


def all_monomials(N, dmax):
    out = []
    for s in range(dmax + 1):
        for c in itertools.combinations(range(N), s):
            m = 0
            for j in c: m |= 1 << j
            out.append(m)
    return out


def mult(mu, f):
    """product mu*f in B (mu a monomial bitmask), f a frozenset of monomial masks (kept for tests)."""
    res = set()
    for t in f:
        res ^= {t | mu}
    return frozenset(res)


class Space:
    """column space of all monomials of size <= D, ascending in the monomial order: bit position pos[m]; the
    leading monomial of a nonzero bitset is its highest set bit."""
    def __init__(self, N, D, key=key_degrevlex):
        self.N, self.D = N, D
        self.mons = sorted(all_monomials(N, D), key=key)
        self.pos = {m: i for i, m in enumerate(self.mons)}
        self.size = [popcount(m) for m in self.mons]
        self.mus = {s: [sum(1 << j for j in c) for c in itertools.combinations(range(N), s)] for s in range(D + 1)}

    def from_poly(self, f):
        x = 0
        for m in f:
            x ^= 1 << self.pos[m]
        return x

    def to_poly(self, x):
        out = set()
        while x:
            low = x & -x
            out.add(self.mons[low.bit_length() - 1])
            x ^= low
        return frozenset(out)

    def deg(self, x):
        return self.size[x.bit_length() - 1]

    def mulmu(self, mu, x):
        """mu * x for a bitset x all of whose monomials t satisfy |t|+|mu| <= D (budget respected by caller)."""
        res = 0
        pos, mons = self.pos, self.mons
        while x:
            low = x & -x
            t = mons[low.bit_length() - 1]
            res ^= 1 << pos[t | mu]
            x ^= low
        return res


class Closure:
    """reference closure; see module docstring.  elim = 'head' (dictionary head reduction, incremental) or
    'rref' (after each pass the whole row set is re-eliminated by plain Gauss-Jordan).  Products are generated by
    the SAME code for both (the PT-1 point)."""
    def __init__(self, gens, N, D=4, key=key_degrevlex, budget_shift=0, drop_last_batch=False,
                 only_new_lm=False, gens_only=False, elim='head', verbose=False, space=None, drop_last_chunk=0):
        self.N, self.D, self.key = N, D, key
        self.S = space if space is not None else Space(N, D, key)
        self.basis = {}               # highest-bit -> bitset (echelon, head-reduced)
        self.history = []
        self.verbose = verbose
        self.budget_shift, self.drop_last_batch = budget_shift, drop_last_batch
        self.only_new_lm, self.gens_only, self.elim = only_new_lm, gens_only, elim
        self.drop_last_chunk = drop_last_chunk      # PT-1(d) variant: flatten the pass's products, cut into chunks of this size, drop the LAST chunk
        self.gens = [self.S.from_poly(g) for g in gens if len(g)]
        self.passes = 0

    # ------------------------------------------------------------- elimination routines
    def reduce(self, x):
        b = self.basis
        while x:
            h = x.bit_length() - 1
            r = b.get(h)
            if r is None:
                return x, h
            x ^= r
        return 0, -1

    def insert(self, x):
        y, h = self.reduce(x)
        if not y:
            return False
        self.basis[h] = y
        return True

    def rref_all(self, rows):
        """Gauss-Jordan: returns {highest bit: row} fully reduced, built from scratch from `rows`."""
        piv = {}
        for x in rows:
            for h in sorted(piv, reverse=True):
                if (x >> h) & 1:
                    x ^= piv[h]
            if x:
                h = x.bit_length() - 1
                for h2 in list(piv):
                    if (piv[h2] >> h) & 1:
                        piv[h2] ^= x
                piv[h] = x
        return piv

    def add_rows(self, rows):
        added = 0
        if self.elim == 'head':
            for x in rows:
                if self.insert(x):
                    added += 1
        else:
            before = len(self.basis)
            self.basis = self.rref_all(list(self.basis.values()) + rows)
            added = len(self.basis) - before
        return added

    # ------------------------------------------------------------------------------ closure
    def products(self, h, b):
        S, D = self.S, self.D
        d = S.size[h]                      # = deg b for a graded order
        top = D - d - self.budget_shift
        out = []
        for s in range(1, top + 1):
            for mu in S.mus[s]:
                out.append(S.mulmu(mu, b))
        return out

    def run(self):
        S, D = self.S, self.D
        self.add_rows(list(self.gens))
        self.history.append(len(self.basis))
        if self.gens_only:
            rows = []
            for g in self.gens:
                d = S.deg(g)
                for s in range(1, D - d + 1 - self.budget_shift):
                    for mu in S.mus[s]:
                        rows.append(S.mulmu(mu, g))
            self.add_rows(rows)
            self.history.append(len(self.basis))
            return self
        done = set()
        while True:
            snapshot = sorted(self.basis.items())
            batches = []
            for h, b in snapshot:
                if self.only_new_lm and h in done:
                    continue
                bt = self.products(h, b)
                if bt:
                    batches.append(bt)       # a batch = all products of one row; rows without allowed products form no batch
                done.add(h)
            if self.drop_last_batch and batches:
                batches = batches[:-1]
            if self.drop_last_chunk and batches:
                flat = [x for bt in batches for x in bt]
                keep = flat[: ((len(flat) - 1) // self.drop_last_chunk) * self.drop_last_chunk]
                batches = [keep]
            added = 0
            for batch in batches:
                added += self.add_rows(batch)
            self.history.append(len(self.basis))
            self.passes += 1
            if self.verbose:
                print('pass', self.passes, 'rank', len(self.basis), 'added', added, file=sys.stderr)
            if not added:
                break
        return self

    # ------------------------------------- independent saturation verifier (the defining property)
    def saturated(self):
        S, D = self.S, self.D
        for h, b in list(self.basis.items()):
            d = S.size[h]
            for s in range(1, D - d + 1):
                for mu in S.mus[s]:
                    y, _ = self.reduce(S.mulmu(mu, b))
                    if y:
                        return False
        return True

    def contains_generators(self):
        return all(self.reduce(g)[0] == 0 for g in self.gens)

    def lm_set(self):
        return sorted(self.S.mons[h] for h in self.basis)

    def lm_counts(self):
        c = [0] * (self.D + 1)
        for h in self.basis:
            c[self.S.size[h]] += 1
        return c

    def polys(self):
        return [self.S.to_poly(b) for b in self.basis.values()]

    def contains_one(self):
        return 0 in self.lm_set()


def lm_hash(lms):
    s = ''.join('%d\n' % m for m in sorted(lms))
    return hashlib.sha256(s.encode()).hexdigest()


def count_std(N, lms):
    """number of square-free monomials (subsets of [N], all sizes) containing no member of lms as a subset.
    DFS over faces of the simplicial complex; exact."""
    lms = set(lms)
    if 0 in lms:
        return 0
    lm_list_by_size = defaultdict(set)
    for m in lms: lm_list_by_size[popcount(m)].add(m)
    # forbidden check for adding vertex v to face S (as list of elements): all subsets T of S, |T|<=3 -> {v} u T not in lms
    maxsz = max(lm_list_by_size) if lm_list_by_size else 0
    count = 0
    stack = [(0, -1, [])]   # (mask, last vertex, elements)
    while stack:
        mask, last, elems = stack.pop()
        count += 1
        for v in range(last + 1, N):
            vm = 1 << v
            ok = True
            # all T subset of elems with |T| <= maxsz-1 : T|v in lms?
            for sz in range(0, min(len(elems), maxsz - 1) + 1):
                if not ok: break
                bucket = lm_list_by_size.get(sz + 1)
                if not bucket: continue
                for T in itertools.combinations(elems, sz):
                    tm = vm
                    for e in T: tm |= 1 << e
                    if tm in bucket:
                        ok = False; break
            if ok:
                stack.append((mask | vm, v, elems + [v]))
    return count


# ------------------------------------------------------------------ ground truth by evaluation --------------
def points_of_system(N, gens):
    """exact V by brute force over all 2^N points (numpy)."""
    import numpy as np
    idx = np.arange(1 << N, dtype=np.uint64)
    ok = np.ones(1 << N, dtype=bool)
    for g in gens:
        val = np.zeros(1 << N, dtype=np.uint8)
        for m in g:
            if m == 0:
                val ^= 1
            else:
                val ^= ((idx & np.uint64(m)) == np.uint64(m)).astype(np.uint8)
        ok &= (val == 0)
    return [int(x) for x in np.nonzero(ok)[0]]


def eval_vec(m, pts):
    v = 0
    for i, a in enumerate(pts):
        if (m & a) == m:
            v |= 1 << i
    return v


def eval_kernel_lm(N, D, pts, key=key_degrevlex):
    """LM(I_{<=D}) for the ideal I of the point set pts, exactly, without any closure: m is a leading monomial
    of I iff its evaluation vector lies in the span of the evaluation vectors of all SMALLER monomials.
    returns (set of LM(I) of size <= D, set of standard monomials of size <= D)."""
    mons = sorted(all_monomials(N, D), key=key)
    basis = {}   # highest bit -> vec
    lms, std = set(), set()
    for m in mons:
        v = eval_vec(m, pts)
        while v:
            h = v.bit_length() - 1
            if h in basis:
                v ^= basis[h]
            else:
                basis[h] = v
                break
        if v:
            std.add(m)
        else:
            lms.add(m)
    return lms, std


def verdict(nstd, nV):
    return 'sufficient' if nstd == nV else ('insufficient' if nstd > nV else 'impossible')


def ground_truth(N, gens, D=4, key=key_degrevlex, pts=None):
    if pts is None:
        pts = points_of_system(N, gens)
    lmI, stdI = eval_kernel_lm(N, D, pts, key)
    return pts, lmI, stdI


if __name__ == '__main__':
    pass
