#!/usr/bin/env python3
"""PART B of EXP-ECQ-f5af06: search the FROZEN BOX for a 32nd independent point
on ICARM no. 302.

THIS IS A FALSIFICATION TEST OF THE BOARD'S OWN CLAIM, whose prior -- recorded in
the contract BEFORE any run existed -- is that NO SUCH POINT WILL BE FOUND. A null
is therefore not a discovery, not a surprise, and not a result about the curve.

THE TEST IS ASYMMETRIC. A hit would refute the board's own "BSD + GRH certified to
rank 31" claim. A MISS IS CONSISTENT WITH THE BOARD'S CLAIM AND EQUALLY CONSISTENT
WITH THE BOX BEING FAR TOO SMALL, and cannot distinguish the two. The only
sentence a miss licenses is: "no point of E(Q) outside the frozen box description
was found within the frozen box, at coverage n_B / N_B."

EXACT AND FLOATING-POINT-FREE throughout: squareness is decided by math.isqrt and
an integer equality, never by a floating-point square root.
"""
import argparse
import hashlib
import json
import os
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import common as C
from part_a import CERT_KW, REF, as_pt, pt_mul


def classify_hit(ai, known_points, hit, cert_kw):
    """Classify a discovered point against the known subgroup.

    A point Q with m*Q in the subgroup generated by the known points REDUCES THE
    INDEX of that subgroup and DOES NOT RAISE THE RANK. Reporting such a point as
    a rank increase would be a false record claim, so the decision is made by the
    exact certifier on the (known + 1)-point set and by nothing else.
    """
    n_known = len(known_points)
    combined = list(known_points) + [hit]
    c = C.EC.certify(ai, combined, **cert_kw)
    k = c["certified_rank_lower_bound"]
    if k >= n_known + 1:
        cls = "rank-increasing"
    elif k >= 1:
        cls = "index-reducing-or-dependent"
    else:
        cls = "uncertified"
    return cls, k, c


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--raw-out", required=True)
    ap.add_argument("--out", default=None)
    ap.add_argument("--cap-seconds", type=float, default=700.0)
    a = ap.parse_args()

    t_start = time.time()
    log = lambda s: (print(s), sys.stdout.flush())

    d = C.load_input()
    ai = [int(x) for x in d["ainvs"]]
    known = d["witness_points_xy_as_rationals"]
    box = C.FROZEN["part_b_box"]

    out = {
        "part": "B",
        "experiment_id": "EXP-ECQ-f5af06",
        "task_id": "TASK-20260824-261bb4",
        "question": ("Does a 32nd rational point exist on ICARM no. 302, independent of "
                     "the 31 known ones, inside the search box frozen in this contract?"),
        "prior_recorded_before_the_run": (
            "THE COORDINATOR'S PRIOR, RECORDED IN THE CONTRACT BEFORE ANY RUN EXISTED: "
            "NO SUCH POINT WILL BE FOUND. The board's own comment reads 'BSD + GRH "
            "certified to rank 31', and if that is accurate the rank IS EXACTLY 31 and "
            "no 32nd independent point exists at any height whatsoever. Independently of "
            "the board's claim, the 31 known points have x-numerators of about 33 "
            "decimal digits while the frozen box below reaches 7."),
        "asymmetry_of_the_test": (
            "A HIT would refute the board's own claim and would be a world record. A "
            "MISS is consistent with the board's claim AND equally consistent with the "
            "box being far too small, and CANNOT DISTINGUISH THE TWO. A miss supports NO "
            "statement of the form 'the rank is 31', 'the rank is not above 31', or 'no "
            "further points exist'."),
        "provenance_caveat": C.PROVENANCE_CAVEAT,
        "frozen_box_description_verbatim": box["description"],
        "floating_point_statement": (
            "NO FLOATING POINT ANYWHERE IN PART B. Squareness of D(x) is decided by "
            "math.isqrt on exact integers plus an integer equality; the group law and "
            "the classification are exact Fraction / integer arithmetic."),
        "observations": [],
        "deviations": [],
    }
    out["certifier_sha256"] = hashlib.sha256(open(C.CERTIFIER_PATH, "rb").read()).hexdigest()
    out["input_files"] = [
        {"path": "coordination/goals/GOAL-ECQ-2298dc/inputs/ICARM-302.json",
         "sha256": hashlib.sha256(open(C.INPUT_PATH, "rb").read()).hexdigest()},
        {"path": os.path.relpath(C.CERTIFIER_PATH, C.REPO), "sha256": out["certifier_sha256"]},
    ]

    # ---- DENOMINATOR FIRST.  Computed and recorded BEFORE any candidate is tested.
    log("== computing N_B BEFORE testing any candidate ==")
    N_B, per_w = C.box_denominator(box)
    out["N_B"] = N_B
    out["N_B_per_w"] = {str(k): v for k, v in per_w.items()}
    out["N_B_recorded_before_any_candidate_tested"] = True
    out["N_B_note"] = (
        "N_B is the exact count of admissible (u, w) pairs in the frozen box "
        "description, a fixed integer determined by the contract alone. It was computed "
        "and written here BEFORE the first candidate was tested and MAY NOT be "
        "recomputed, narrowed or widened afterwards. A budget shortfall is a smaller "
        "numerator over this unchanged denominator, never a redefined denominator.")
    log("   N_B = %d" % N_B)
    # flush the denominator to disk before testing anything
    json.dump(out, open(a.raw_out, "w"), indent=1)

    # ---- CTL-SATURATION-DISTINCTION, before the search ---------------------
    log("== CTL-SATURATION-DISTINCTION (constructed case, answer known) ==")
    r = REF["37a1"]
    P = as_pt(r["gens"][0])
    P2 = pt_mul(r["ainvs"], 2, P)
    known_sub = [[str(P2[0]), str(P2[1])]]          # the "known subgroup" is {2P}
    discovered = [str(P[0]), str(P[1])]             # the "discovered" point is P
    cls, k_sat, c_sat = classify_hit(r["ainvs"], known_sub, discovered, CERT_KW)
    sat = {
        "id": "CTL-SATURATION-DISTINCTION",
        "control": ("take a rank-1 curve with generator P, present the 'known subgroup' "
                    "as {2P}, and confirm that the classifier reports a discovered P as "
                    "INDEX-REDUCING rather than as rank-increasing"),
        "curve": "37a1", "source": r["source"], "ainvs": r["ainvs"],
        "known_subgroup_presented": known_sub,
        "discovered_point": discovered,
        "truth": ("P generates E(Q) modulo torsion and 2P generates an index-2 subgroup "
                  "of it; adjoining P to {2P} reduces the index from 2 to 1 and does NOT "
                  "raise the rank, which is 1 either way"),
        "pass_condition_declared_before_running":
            "classifier returns 'index-reducing-or-dependent' with certified rank lower "
            "bound 1; returning 'rank-increasing' is a FAIL and is exactly the shape of a "
            "false record claim",
        "classifier_output": cls,
        "certified_rank_lower_bound": k_sat,
        "outcome": "PASS" if (cls == "index-reducing-or-dependent" and k_sat == 1) else "FAIL",
        "certifier_errors": c_sat.get("errors"),
    }
    out["CTL_SATURATION_DISTINCTION"] = sat
    log("   -> %s (k=%d) : %s" % (cls, k_sat, sat["outcome"]))

    # ---- the search --------------------------------------------------------
    cap = a.cap_seconds
    deadline = t_start + cap - 20.0
    log("== searching the frozen box (cap %.0fs) ==" % cap)
    hits, n_B, exhausted, wall = C.search_box(ai, box, deadline, log=log)
    out["n_B"] = n_B
    out["box_exhausted"] = exhausted
    out["coverage"] = {
        "numerator_n_B": n_B, "denominator_N_B": N_B,
        "fraction": "%d / %d" % (n_B, N_B),
        "fraction_value": round(n_B / N_B, 9),
        "percent": round(100.0 * n_B / N_B, 6),
    }
    out["search_wall_clock_seconds"] = round(wall, 3)
    out["enumeration_order"] = ("w ascending from 1 to 30; within each w, |u| ascending "
                                "from 0, positive sign before negative. Deterministic, so "
                                "a time-truncated numerator is reproducible.")
    log("   tested %d / %d candidates (%.4f%%) in %.1fs; exhausted=%s; %d hits"
        % (n_B, N_B, 100.0 * n_B / N_B, wall, exhausted, len(hits)))

    # ---- classify every hit ------------------------------------------------
    classified = []
    rank_increasing = 0
    index_reducing = 0
    for h in hits:
        already = h in [list(x) for x in known] or h in known
        cls, kk, cc = classify_hit(d["ainvs"], known, h, CERT_KW)
        if cls == "rank-increasing":
            rank_increasing += 1
        else:
            index_reducing += 1
        classified.append({
            "x_exact": h[0], "y_exact": h[1],
            "already_among_the_31_known": already,
            "classification": cls,
            "certified_rank_lower_bound_of_32_point_set": kk,
            "certifier_output_that_decided_it": cc,
        })
        log("   HIT x=%s -> %s (k=%d)" % (h[0][:40], cls, kk))

    out["hits"] = classified
    out["n_hits"] = len(classified)
    out["n_rank_increasing"] = rank_increasing
    out["n_index_reducing_or_dependent"] = index_reducing
    out["known_points_not_in_box_note"] = (
        "The 31 known witness points have x-numerators of about 33 decimal digits and "
        "x-denominators as large as 3630906049, so NONE of them lies inside the frozen "
        "box (which reaches 7-digit numerators and w <= 30). A hit inside the box would "
        "therefore necessarily be a point not previously listed -- which is still not "
        "necessarily a rank increase, hence the classifier above.")

    if rank_increasing:
        out["branch_label"] = "B-POSITIVE"
    elif classified:
        out["branch_label"] = "B-INDEX-REDUCING"
    else:
        out["branch_label"] = "B-NULL"

    out["branch_defence"] = {
        "B-NULL": ("Pre-declared condition: no rank-increasing hit in the frozen box, "
                   "reported as n_B / N_B. Met iff n_rank_increasing == 0."),
        "observed": out["branch_label"],
        "statement_licensed": (
            "No point of E(Q) was found within the frozen box at coverage %d / %d. This "
            "is CONSISTENT WITH the board's rank-exactly-31 claim AND EQUALLY CONSISTENT "
            "WITH the box being far too small; it distinguishes neither and supports no "
            "statement about the rank of ICARM no. 302."
            % (n_B, N_B)) if out["branch_label"] == "B-NULL" else (
            "A hit was found; see hits[] for its exact coordinates and its "
            "classification. A hit is NOT automatically a 32nd independent point."),
    }
    out["certificates_to_reverify"] = [
        {"label": "PART B hit %d" % i, "a_invariants": [str(x) for x in ai],
         "points": known + [[h["x_exact"], h["y_exact"]]],
         "certified_rank_lower_bound": h["certified_rank_lower_bound_of_32_point_set"],
         "l": (h["certifier_output_that_decided_it"].get("independence") or {}).get("l"),
         "primes_used": (h["certifier_output_that_decided_it"].get("independence") or {}).get("primes_used"),
         "torsion_bound": h["certifier_output_that_decided_it"].get("torsion_bound"),
         "torsion_bound_primes": h["certifier_output_that_decided_it"].get("torsion_bound_primes")}
        for i, h in enumerate(classified) if h["classification"] == "rank-increasing"]

    out["protocol_certificate"] = {
        "kind": "independence_certificate" if rank_increasing else "none",
        "kind_reason": ("no hit was certified rank-increasing, so this is a PURE "
                        "MEASUREMENT RUN WITH NOTHING TO CERTIFY; the kind is stated "
                        "explicitly as `none` rather than left blank"
                        if not rank_increasing else
                        "a hit was certified rank-increasing over the 32-point set; the "
                        "six-clause claim bar of the contract applies IN FULL and nothing "
                        "is stated as a result before independent review-breakthrough"),
        "path": ("coordination/goals/GOAL-ECQ-2298dc/tasks/TASK-20260824-261bb4/"
                 "extension_search.json"),
    }
    out["parameters"] = {"box": box, "N_B": N_B, "cap_seconds": cap,
                         "certifier_search_bounds": {k: (list(v) if isinstance(v, tuple) else v)
                                                     for k, v in CERT_KW.items()}}
    out["metrics"] = {
        "part_b_N_B": N_B,
        "part_b_n_B": n_B,
        "part_b_coverage_fraction": round(n_B / N_B, 9),
        "part_b_box_exhausted": exhausted,
        "part_b_n_hits": len(classified),
        "part_b_n_rank_increasing": rank_increasing,
        "part_b_n_index_reducing_or_dependent": index_reducing,
        "part_b_wall_clock_seconds": round(wall, 3),
        "ctl_saturation_distinction": sat["outcome"],
        "total_wall_clock_seconds": round(time.time() - t_start, 3),
    }
    out["wall_clock_seconds"] = round(time.time() - t_start, 3)

    json.dump(out, open(a.raw_out, "w"), indent=1)
    if a.out:
        json.dump(out, open(a.out, "w"), indent=1)
    log("== part B done: branch %s, coverage %d / %d ==" % (out["branch_label"], n_B, N_B))
    return 0


if __name__ == "__main__":
    sys.exit(main())
