from pathlib import Path
import yaml
out=Path(__file__).parent
rows=[
 dict(id='IDEA-20260905-40aa90', title='Theta-coordinate Kummer representations with complete quotient-recovery accounting',
 claim='On matched small mathematical examples, a complete theta-coordinate relation description may reduce algebraic representation complexity after restoring quotient ambiguity, exceptional cases and recovery constraints. This is a falsifiable candidate, not an observed advantage.',
 mechanism='Theta coordinates expose structured identities and differential arithmetic. The question is whether that structure simplifies the complete relation locus rather than only arithmetic operations on its quotient.',
 assumptions=['Quotienting by negation identifies points but does not halve dimension or automatically halve the required variables.', 'A genus-2 Kummer surface is a quotient of a two-dimensional Jacobian; transfer to an elliptic-curve problem requires an explicit construction and separate cost accounting.', 'Every compared description must encode the same intended solutions, including signs and exceptional points.'],
 design='Establish equivalence of original and quotient relation descriptions on completely checkable small examples before comparing their full algebraic presentations. Count recovery constraints as part of the presentation. Parameters and budgets remain to be frozen by the Coordinator.',
 controls=['Baseline already exploiting negation symmetry.', 'Comparison including sign/difference information needed by differential arithmetic.', 'Exceptional-point and extraneous-solution checks.'],
 metrics=['equivalence_check', 'equation_count', 'variable_count', 'degrees', 'exceptional_components', 'recovery_constraints'],
 failure=['The complete presentation has no lower complexity than the symmetry-aware baseline in the tested scope.', 'An apparent reduction disappears when omitted recovery conditions are restored. A failed equivalence check invalidates the comparison.'],
 confounders=['Redundant baseline coordinates.', 'Omitted sign information.', 'Changing genus or field while attributing the difference to coordinates.'],
 observable='The quotient relation locus together with a complete recovery condition.',
 collision='Look for different original configurations with the same quotient data and check whether recovery distinguishes them.',
 baseline='The original relation description with negation symmetry already exploited.',
 ceiling='Equivalence and a scoped comparison of algebraic presentations; no general ECDLP cost or exponent claim.',
 nearby='A quotient presentation with recovery information deliberately omitted must fail equivalence.',
 deliverable='Representation-equivalence note listing preserved data, forgotten data, exceptional cases and recovery obligations.',
 refs=[('https://doi.org/10.1515/JMC.2007.012','Gaudry, Fast genus 2 arithmetic based on Theta functions: nearest arithmetic reference; differential arithmetic is not evidence of easier decomposition.')]),
 dict(id='IDEA-20260905-4dff7b', title='Edwards and Hessian model comparisons separating coordinate and point-set effects',
 claim='A model-dependent symmetry may simplify a complete relation presentation on small examples even after transporting the same mathematical point set and accounting for exceptional maps. No first-fall-degree or cost improvement is established.',
 mechanism='Alternative models expose different symmetries and equation sparsity. Separate a coordinate-only comparison from a model-adapted point-set comparison to identify the cause of any simplification.',
 assumptions=['Only models available over the declared field are comparable without additional transfer accounting.', 'Coordinate-only comparisons transport an identical point set.', 'Model-adapted point sets require explicit membership conditions and cardinality accounting.', 'First fall degree alone does not establish full solution cost.'],
 design='Prepare two small-example comparisons: identical point sets transported between available models, and separately declared model-adapted point sets. Compare complete equation presentations only after checking equivalence and map exceptions. Parameters and budgets require a later frozen contract.',
 controls=['Same point set transported between models.', 'Separate model-adapted point-set comparison.', 'Map denominators, excluded points and exceptional components included.', 'Full-system comparison alongside first-fall-degree diagnostics.'],
 metrics=['equivalence_check', 'equation_count', 'variable_count', 'degrees', 'sparsity', 'point_set_size', 'membership_constraints', 'exceptional_components'],
 failure=['A claimed coordinate-only effect disappears when the mathematical point set is held fixed.', 'Intermediate factorization does not simplify the complete relation locus.', 'The advantage depends on uncharged extension-field or exceptional-point handling.'],
 confounders=['Different point-set densities.', 'Special torsion or field assumptions.', 'Attributing a diagnostic degree fall to total complexity.'],
 observable='The complete relation locus and transported admissible point set.',
 collision='Check whether the model map identifies distinct admissible configurations or omits denominator-zero cases.',
 baseline='The same relation and mathematical point set in the original model.',
 ceiling='Model-, field- and point-set-specific algebraic comparison, without an exponent claim.',
 nearby='A comparison with unequal point sets must not be accepted as evidence of a coordinate-only improvement.',
 deliverable='Comparison matrix attributing each proposed simplification to coordinates, symmetry, point-set choice or missing constraints.',
 refs=[('https://www.math.auckland.ac.nz/~sgal018/Shishay.pdf','Nearest literature lead on binary Edwards summation polynomials and symmetry; binary-field observations do not establish a prime-field advantage.'), ('Diem attribution supplied by the user; exact work unresolved','The attribution that model choice matters for factor-base structure needs primary-source identification before use as support.')]),
 dict(id='IDEA-20260905-bf8898', title='Divisor embeddings and projective incidence with nonlinear admissibility controls',
 claim='A divisor-based projective representation may reveal useful structure in a relation locus that survives restoration of nonlinear divisor admissibility, rationality, multiplicity and recovery conditions. No algorithmic improvement is established.',
 mechanism='Express divisor data through a projective embedding and study the relation condition through linear systems and incidence geometry. Ask whether a geometric decomposition or rank condition simplifies the complete mathematical description.',
 assumptions=['Linearity of ambient constraints does not imply simplicity of finding admissible points on the embedded variety.', 'Every incidence solution used in a comparison must correspond to a valid original relation, with recovery and multiplicity accounted for.', 'The embedding, divisor membership and rationality conditions are part of the representation.'],
 design='Establish a correspondence between original relations and admissible incidence solutions on completely checkable small examples. Compare with the familiar geometric group-law baseline, then determine whether the full incidence description exposes structure after all constraints are restored. Freeze parameters and budgets separately before execution.',
 controls=['Exact baseline geometric expression of the group law.', 'Unrelated linear section with comparable dimensions.', 'Nearby object where the proposed structural simplification is known to fail.', 'Explicit recovery, rationality, multiplicity and extraneous-component checks.'],
 metrics=['correspondence_check', 'ambient_dimension', 'embedding_degree', 'membership_constraints', 'multiplicities', 'extraneous_components', 'recovery_constraints'],
 failure=['Nonlinear admissibility or recovery retains the original difficulty without a demonstrated simplification in the tested scope.', 'The proposed argument also accepts a nearby object on which its conclusion is false.', 'The correspondence loses valid relations or includes unrecoverable incidence solutions.'],
 confounders=['Ignoring the degree of the embedded variety.', 'Treating ambient linearity as computational tractability.', 'Rediscovering the baseline geometric group law.', 'Ignoring rationality or multiplicity.'],
 observable='Admissible incidence solutions together with their original-relation recovery data.',
 collision='Search for distinct divisor data with identical incidence observables and determine what distinguishes their recovery.',
 baseline='The existing geometric group-law and linear-equivalence description on the same small example.',
 ceiling='A structural equivalence or scoped representation simplification; no general tractability theorem.',
 nearby='A linear section whose ambient constraints hold but whose divisor admissibility fails must not certify a valid relation.',
 deliverable='Proof-search map and correspondence note covering baseline, collisions, quantifier order, method ceiling and nearby-object control.',
 refs=[]),
]
for r in rows:
    idea={
      'id':r['id'], 'question_id':'RQ-ECDLP-002', 'added':'2026-09-05', 'status':'proposed', 'approved_by':None,
      'title':r['title'], 'class':'representation', 'claim':r['claim'], 'mechanism':r['mechanism'], 'novelty_status':'unverified',
      'origin':{'kind':'user_supplied_idea', 'date':'2026-09-05', 'scope':'Publication of the three conversational drafts as separate proposal PRs.', 'related_open_pr':'https://github.com/aburan28/crypto-autoresearcher/pull/750', 'overlap_review':'Pending; the related PR describes broader representation ideation. No novelty or nonduplication conclusion.'},
      'citations':[{'ref':ref,'provenance':'recalled','claim':claim,'verified_by':None} for ref,claim in r['refs']],
      'citation_note':'Literature leads are conservatively marked recalled: this publication pass does not certify full primary-source review. They are pointers, not support.',
      'assumptions':r['assumptions'],
      'proof_search_map':{
         'bottleneck':'Distinguishing a simpler complete representation from complexity moved into hidden constraints.',
         'baseline_embedding':{'parameter_slice':r['baseline'],'reproduction_check':'Proposed exact equivalence check on small examples; no check has run.'},
         'observation_collision':{'observable':r['observable'],'distinct_preimage_search':r['collision']},
         'constructive_transforms':[{'transform':'representation_reduction','proposed_object':r['observable'],'predicted_gain':'A simpler complete algebraic presentation; magnitude unknown.'}],
         'quantifier_order':'Candidate existence claim: there exists a declared small example and representation with a strict measured simplification; for every solution used in that example, equivalence and recovery must hold. No universal family or scaling claim.',
         'method_ceiling':{'strongest_certifiable_claim':r['ceiling'],'nearby_object_control':r['nearby']},
         'proof_obligations':[{'claim':'Original and transformed admissible solutions correspond, including exceptions.','responsibility':'correctness'}, {'claim':'Comparison includes every defining, membership and recovery constraint.','responsibility':'size'}, {'claim':'Any later computational claim charges all stages and specifies transfer assumptions.','responsibility':'scope'}]},
      'predictions':[{'metric':'complete_presentation_complexity','direction':'lower','minimum_effect':'At least one predeclared measure strictly improves with other measures and tradeoffs disclosed; measures must be frozen before testing.'}, {'metric':'solution_correspondence','direction':'different','minimum_effect':'Exact agreement on all cases checked in the frozen small example, including exceptional cases.'}],
      'minimal_test':{'design':r['design'],'controls':r['controls'],'required_metrics':r['metrics']},
      'falsification_conditions':r['failure'], 'confounders':r['confounders'],
      'interpretation_limits':['Proposal only; no experiment, implementation, run, review, approval, or research-status promotion.', 'A scoped failed comparison does not close a research direction.', 'No live keys, deployed systems, or private-scalar recovery is part of this proposal.', 'Small-example observations do not justify an asymptotic or cryptographic-scale conclusion.', 'Infrastructure failures and timeouts are not mathematical evidence.'],
      'heuristic_assumptions':[], 'heuristic_note':'No distributional heuristic or asymptotic transfer assumption is asserted; any future such claim needs numbered assumptions and validation.',
      'target_complexity':{'time_exponent':'Unknown; no improvement claimed.', 'memory_exponent':'Unknown; no improvement claimed.', 'best_known':'Matched complete original representation; full algorithmic frontier comparison remains pending.', 'hidden_overhead':'Coordinate or embedding construction, membership, exceptional cases, recovery and any field transfer must be charged.', 'tradeoff_note':'Time, memory and data/query tradeoffs are unmeasured.'},
      'estimated_cost':{'implementation':'low','compute':'low','qualification':'Provisional expectation for a symbolic small-example intake check only; not an execution budget.'},
      'dominated_by':'unchecked', 'sota_delta':{'time':'Unmeasured; no numeric delta claimed.', 'memory':'Unmeasured; no numeric delta claimed.', 'data_queries':'Unmeasured; no numeric delta claimed.'},
      'frontier_check':{'status':'pending','note':'No unchecked null or quantitative frontier claim; Coordinator must complete overlap and Pareto review before ranking implementation.'},
      'recommended_priority':'medium', 'priority_rationale':'Provisional intake priority only; user interest in the incidence idea is recorded without claiming evidence-based superiority.',
      'first_deliverable':r['deliverable'], 'next_gate':'Coordinator overlap/frontier review followed by a separately frozen, unapproved experiment design; this record dispatches no work.'}
    (out/(r['id']+'.yaml')).write_text(yaml.safe_dump({'idea':idea},sort_keys=False,width=100))
print('\n'.join(r['id'] for r in rows))
