#!/usr/bin/env python3
"""Storage trim for the two large raw-result.json files (RUN-002, RUN-004).

Both searches are fully deterministic given the recorded seed and command, so
the full artifact is regenerable rather than lost.  This script rewrites the
raw result keeping ALL aggregate statistics verbatim (every trial counted,
nothing filtered by outcome) and the first `keep` curve records in search
order, and records the exact regeneration command in the file.

Every per-trial line remains in the run's stdout.log, which is NOT trimmed.

usage: trim_raw.py <raw-result.json> <keep> <regen-command-file>
"""
import json
import os
import sys


def main():
    path, keep, cmdfile = sys.argv[1], int(sys.argv[2]), sys.argv[3]
    d = json.load(open(path))
    size = os.path.getsize(path)
    cmd = open(cmdfile).read().strip()
    key = "curves" if "curves" in d else "results"
    n = len(d[key])
    d["_trim_note"] = (
        "Storage trim. Original file %d bytes with %d %s records; the first %d "
        "in search order are kept. ALL aggregate statistics above are verbatim "
        "and count every trial, including every failure. The run is "
        "deterministic given the recorded seed, so the full artifact is "
        "regenerated by the command in _regeneration_command. Per-trial lines "
        "for every trial remain in this run's untrimmed stdout.log."
        % (size, n, key, keep))
    d["_original_record_count"] = n
    d["_original_bytes"] = size
    d["_regeneration_command"] = cmd
    d[key] = d[key][:keep]
    json.dump(d, open(path, "w"), indent=1)
    print("trimmed %s: %d -> %d %s, %d -> %d bytes" % (
        path, n, len(d[key]), key, size, os.path.getsize(path)))


if __name__ == "__main__":
    main()
