#!/usr/bin/env python3
"""Generate each runtime's agent binding files from `orchestration/roles.yaml`.

A role's authority and tool surface are stated once, in runtime-neutral terms,
in `roles.yaml`; its behaviour is stated once, in prose, in `agents/<role>.md`.
Every runtime then needs the same facts restated in its own format. Restating
them by hand is how a harness ends up with a review role that is independent in
one runtime and not in another, with nothing failing.

So the binding files are generated, and `--check` makes drift a build error:

    python3 tools/generate_runtime_agents.py            # write the bindings
    python3 tools/generate_runtime_agents.py --check    # fail if any drifted
    python3 tools/generate_runtime_agents.py --diff     # show what would change

Two rules keep the generated files honest:

  * They never copy contract prose. A binding points at `AGENTS.md` and
    `agents/<role>.md` and stops. Prose cannot drift from a source it does not
    duplicate, and the role contract stays the one place behaviour is defined.

  * They never name a model. `model-policies.yaml` states what a role needs,
    `model-bindings.yaml` resolves that to an identifier per backend, and
    `python -m orchestration.adapter env` puts it in the runtime's environment.
    A model id hardcoded here would be a fourth answer to a question that
    already has three layers, and the one nothing validates.

`claude_code` is deliberately NOT generated: those bindings predate this script
and carry hand-written operating rules. `tools/check_runtime_bindings.py`
verifies them against the same table, which is the property that matters.

Exit status 0 = every generated binding is current, 1 = at least one drifted.
"""
from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from orchestration.role_registry import (  # noqa: E402
    REPO, effective_capabilities, load_roles, over_granted, parse_frontmatter,
    role_spec)

# Runtimes this script owns. A runtime absent here keeps hand-written bindings.
GENERATED_RUNTIMES = ("codex_cli", "opencode")

BANNER = "GENERATED by tools/generate_runtime_agents.py -- do not edit by hand."


def _description(role: str) -> str:
    """Reuse the Claude binding's description rather than inventing one.

    One human-written sentence per role already exists and is already reviewed.
    Copying it is not duplication of contract facts -- authority and tools come
    from roles.yaml -- it is reuse of a label, and it keeps the runtimes
    describing the same role in the same words.
    """
    frontmatter = parse_frontmatter(REPO / ".claude" / "agents" / f"{role}.md")
    return " ".join(str(frontmatter.get("description", "")).split())


def _contract_pointer(role: str, spec: dict[str, Any]) -> list[str]:
    return [
        f"You are the {role} of the crypto-autoresearcher program.",
        "",
        "Read these before acting and follow them exactly:",
        "  - AGENTS.md                 the binding inter-agent contract",
        f"  - {spec['contract']:<25} your full role contract",
        "",
        "This file grants your tool surface and nothing else. It deliberately",
        "carries no operating rules: they live in the contract above, so there",
        "is one place to change them and no second copy to drift.",
    ]


def _authority_notes(spec: dict[str, Any]) -> list[str]:
    authority = spec["authority"]
    lines = []
    if not authority.get("may_change_official_state"):
        lines.append(
            "You may not change official research state (hypothesis status, "
            "approvals, ledger records). Hand results to the Coordinator.")
    if not authority.get("may_execute_experiments"):
        lines.append("You may not execute experiments.")
    if authority.get("independent_of_producer"):
        lines.append(
            "You are an independent review role: run in a session separate "
            "from the producer of the artifact you are reviewing.")
    return lines


def _over_grant_warning(roles_doc: dict[str, Any], role: str,
                        runtime: str) -> list[str]:
    forced = set(over_granted(roles_doc, role, runtime))
    if not forced:
        return []
    lines: list[str] = []

    # Codex and OpenCode expose one primitive for both creating and modifying
    # files.  A role such as Idea Generator deliberately has ``write_files``
    # but not ``edit_files``: it may create its declared proposal artifacts,
    # but it must not rewrite existing records.  Saying "do not use
    # edit_files" is operationally impossible on these runtimes because it
    # also forbids the only way to create a file.  State the enforceable
    # boundary instead.
    declared = set(role_spec(roles_doc, role).get("capabilities") or [])
    coupled_write_edit = any(
        {"write_files", "edit_files"}.issubset(set(group))
        for group in (roles_doc.get("runtime_capability_coupling", {}).get(runtime, []) or [])
    )
    if ("edit_files" in forced and "write_files" in declared
            and coupled_write_edit):
        lines += [
            "",
            "IMPORTANT -- this runtime couples authorized file creation to its",
            "file-modification (`edit_files`) primitive. You may use that shared primitive only",
            "to create new files inside the task's declared write scope. Do not",
            "modify, replace, or delete any existing file.",
        ]
        forced.remove("edit_files")

    if forced:
        lines += [
            "",
            "IMPORTANT -- this runtime grants you capabilities your contract does",
            f"not: {', '.join(sorted(forced))}. The harness cannot withhold them "
            "here, so",
            "the restriction is yours to keep. Do not use them.",
        ]
    return lines


# --------------------------------------------------------------------------
# codex_cli
# --------------------------------------------------------------------------

def _codex_agent(roles_doc: dict[str, Any], role: str) -> str:
    spec = role_spec(roles_doc, role)
    capabilities = set(effective_capabilities(roles_doc, role, "codex_cli"))
    writes = {"write_files", "edit_files"} & capabilities
    sandbox = "workspace-write" if writes else "read-only"

    body = _contract_pointer(role, spec)
    notes = _authority_notes(spec)
    if notes:
        body += [""] + [f"- {note}" for note in notes]
    body += _over_grant_warning(roles_doc, role, "codex_cli")

    instructions = "\n".join(body)
    lines = [
        f"# {BANNER}",
        f"# Source: orchestration/roles.yaml -> roles.{role}",
        "#",
        "# Codex rejects unknown keys in an agent role file, so the tool",
        "# surface cannot be listed and is implied by `sandbox_mode` plus the",
        "# web-search toggle. `tools/check_runtime_bindings.py` reads it back",
        "# the same way it is written here.",
        "#",
        "# No `model` key on purpose: the model comes from the policy layer via",
        "# `python -m orchestration.adapter env`.",
        "",
        f'name = "{role}"',
        f'description = "{_description(role)}"',
        f'sandbox_mode = "{sandbox}"',
        "",
        'developer_instructions = """',
        instructions,
        '"""',
        "",
        "[tools]",
        f"web_search = {'true' if 'web_search' in capabilities else 'false'}",
        "",
    ]
    return "\n".join(lines)


def _codex_config(roles_doc: dict[str, Any]) -> str:
    lines = [
        f"# {BANNER}",
        "# Source: orchestration/roles.yaml",
        "#",
        "# Role registry for the Codex CLI. Each entry points at a role file",
        "# under .codex/agents/; those files carry the tool surface.",
        "",
        "[agents]",
        "# One thread per role in a dispatch batch, and no nesting: a subagent",
        "# spawning subagents would put work outside the batch the Coordinator",
        "# authorised.",
        "max_threads = 5",
        "max_depth = 1",
        "",
    ]
    for role, spec in roles_doc["roles"].items():
        # A role with no Codex binding gets no registry entry: policy-tier
        # variants exist only where a runtime can carry reasoning effort in its
        # agent format, and Codex role files reject unknown keys. Emitting the
        # entry anyway would point `config_file` at a file this script never
        # writes.
        if "codex_cli" not in (spec.get("runtime_bindings") or {}):
            continue
        lines += [
            f"[agents.{role}]",
            f'description = "{_description(role)}"',
            f'config_file = "./agents/{role}.toml"',
            "",
        ]
    return "\n".join(lines)


# --------------------------------------------------------------------------
# opencode
# --------------------------------------------------------------------------

# Every permission key the generated bindings state explicitly, and the
# capability each one belongs to. Stating all of them means a reader never has
# to know OpenCode's default to know what a role holds.
_OPENCODE_PERMISSIONS = (
    ("read", "read_files"),
    ("grep", "search_files"),
    ("glob", "search_files"),
    ("list", "search_files"),
    ("edit", "edit_files"),
    ("bash", "run_commands"),
    ("webfetch", "web_search"),
    ("websearch", "web_search"),
)


def _opencode_agent(roles_doc: dict[str, Any], role: str) -> str:
    spec = role_spec(roles_doc, role)
    capabilities = set(effective_capabilities(roles_doc, role, "opencode"))
    permissions = [
        f"  {key}: {'allow' if capability in capabilities else 'deny'}"
        for key, capability in _OPENCODE_PERMISSIONS
    ]

    body = _contract_pointer(role, spec)
    notes = _authority_notes(spec)
    if notes:
        body += [""] + [f"- {note}" for note in notes]
    body += _over_grant_warning(roles_doc, role, "opencode")

    lines = [
        "---",
        f"# {BANNER}",
        f"# Source: orchestration/roles.yaml -> roles.{role}",
        "# No `model` key on purpose: the model comes from the policy layer.",
        f"description: >-",
        f"  {_description(role)}",
        "mode: subagent",
        "temperature: 0.1",
        "permission:",
        *permissions,
        "  # A subagent never delegates: the Coordinator owns dispatch.",
        "  task:",
        '    "*": deny',
        "---",
        "",
        *body,
        "",
    ]
    return "\n".join(lines)


# --------------------------------------------------------------------------

def render(roles_doc: dict[str, Any]) -> dict[Path, str]:
    """Every file this script owns, mapped to its intended contents."""
    files: dict[Path, str] = {}
    roles = roles_doc["roles"]
    for role, spec in roles.items():
        bindings = spec.get("runtime_bindings") or {}
        for runtime in GENERATED_RUNTIMES:
            if runtime not in bindings:
                continue
            renderer = _codex_agent if runtime == "codex_cli" else _opencode_agent
            files[REPO / bindings[runtime]] = renderer(roles_doc, role)
    if any(runtime == "codex_cli"
           for spec in roles.values()
           for runtime in (spec.get("runtime_bindings") or {})):
        files[REPO / ".codex" / "config.toml"] = _codex_config(roles_doc)
    return files


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if any generated file is out of date")
    parser.add_argument("--diff", action="store_true",
                        help="print a unified diff of what would change")
    args = parser.parse_args()

    files = render(load_roles())
    stale: list[Path] = []
    for path, content in sorted(files.items()):
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        stale.append(path)
        if args.diff:
            print("".join(difflib.unified_diff(
                (current or "").splitlines(keepends=True),
                content.splitlines(keepends=True),
                fromfile=f"a/{path.relative_to(REPO)}",
                tofile=f"b/{path.relative_to(REPO)}")))

    if args.check or args.diff:
        if stale:
            print(f"{len(stale)} generated binding(s) out of date:")
            for path in stale:
                print(f"  - {path.relative_to(REPO)}")
            print("regenerate: python3 tools/generate_runtime_agents.py")
            return 1
        print(f"OK: {len(files)} generated binding(s) current")
        return 0

    for path, content in sorted(files.items()):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    print(f"wrote {len(files)} binding file(s):")
    for path in sorted(files):
        print(f"  - {path.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
