"""Per-curve ANF charge under three encodings, against the EV-ICPERF-784b25 budget.

Budget, l, R and rho come UNCHANGED from EXP-ICPERF-783e9e/impl (costmodel.py,
arity.py), so every row is priced on exactly the cell the original record used.
Only the size of the system that has to be written down changes.

  EXPANDED   : S_{m+1}(x_1..x_m, xR) descended in the m*l bits of x_1..x_m
               (the original record; reproduced here as a check)
  SYMMETRIZED: FPPR 2012 -- the symmetrized S~_{m+1}(e_1..e_m, xR) in auxiliary
               e_k bits (d_k of them) plus linking equations e_k = sigma_k(x)
  CHAINED    : Semaev 2015 -- S_3(x1,x2,u1), S_3(u1,x3,u2), .., S_3(u_{m-2},xm,xR)
               with m-2 auxiliary full-field unknowns u_i (n bits each)

Sizes are log2 of the number of distinct Boolean monomials that can occur.
Two upper bounds are given for the auxiliary encodings: DENSE, sum_{i<=D} C(v,i)
over all v unknowns (the original record's charge), and BLOCK, the exact size of
the monomial downset allowed by the measured Hamming-weight support (a product
of e_k^{a_k} can only produce block-k monomials of degree <= wt2(a_k)).
"""
import json, sys
from math import comb, log2
from itertools import product
from pathlib import Path
IMPL = Path(__file__).resolve().parents[2] / "experiments" / "EXP-ICPERF-783e9e" / "impl"
sys.path.insert(0, str(IMPL))
from arity import best_cell, boolean_degree, anf_log2_monomials, orbit_reduction  # noqa
from costmodel import charged_budget  # noqa

HERE = Path(__file__).resolve().parent
SUPPORT = {}
for f in sorted(HERE.glob("support_m*.json")):
    for k, v in json.load(open(f)).items():
        SUPPORT[int(k)] = v

def dense(v, D):
    return sum(comb(v, i) for i in range(min(D, v) + 1))

def block(d, W):
    """Size of the downset generated by weight vectors W, block sizes d."""
    caps = [max(w[k] for w in W) for k in range(len(d))]
    tot = 0
    for j in product(*[range(min(c, dk) + 1) for c, dk in zip(caps, d)]):
        if any(all(j[k] <= min(w[k], d[k]) for k in range(len(d))) for w in W):
            p = 1
            for k in range(len(d)): p *= comb(d[k], j[k])
            tot += p
    return tot

def e_dims(n, m, l, stable):
    # polynomial-basis V: e_k in span{1..t^{k(l-1)}}; stable V: charge the
    # whole field for k >= 2 (an upper bound; span(V^k) is not computed here)
    if stable:
        return [l] + [n] * (m - 1)
    return [min(n, k * (l - 1) + 1) for k in range(1, m + 1)]

def symmetrized(n, m, l, stable):
    s = SUPPORT[m]; d = e_dims(n, m, l, stable)
    W = [tuple(w) for w in s["maximal_weight_vectors"]]
    D_main = min(sum(max(min(w[k], d[k]) for w in W) for k in range(m)),
                 max(sum(min(w[k], d[k]) for k in range(m)) for w in W))
    D_main = max(sum(min(w[k], d[k]) for k in range(m)) for w in W)
    link_dense = dense(m * l, m)                      # sigma_k has degree k <= m
    main_dense = dense(sum(d), D_main)
    main_block = block(d, W)
    return dict(e_dims=d, aux_vars=sum(d), total_vars=m * l + sum(d),
                degree=max(D_main, m),
                log2_dense=log2(main_dense + link_dense),
                log2_block=log2(main_block + link_dense))

def chained(n, m, l):
    # S_3(a,b,c) = a^2b^2 + a^2c^2 + b^2c^2 + abc + a6: weight vectors (1,1,1)
    # (the abc term) dominates; block count for one link = (1+da)(1+db)(1+dc)
    # up to the degree-<=1-per-block structure, i.e. exactly prod (1 + d_i).
    dims = []
    u = n
    if m == 2:
        dims = [(l, l, 0)]
    else:
        dims = [(l, l, u)] + [(u, l, u)] * (m - 3) + [(u, l, 0)]
    blk = sum((1 + a) * (1 + b) * (1 + c) for a, b, c in dims)
    vars_ = m * l + (m - 2) * n
    return dict(aux_vars=(m - 2) * n, total_vars=vars_, degree=3 if m > 2 else 2,
                log2_dense=log2(dense(vars_, 3)), log2_block=log2(blk))

TARGETS = [(113, "SECG-adjacent"), (127, "Mersenne-degree"), (131, "ECC2K-130"),
           (163, "K-163 / B-163"), (233, "K-233 / B-233"), (239, "sect239"),
           (283, "K-283 / B-283"), (409, "K-409 / B-409"), (571, "K-571 / B-571")]

def main():
    rows = []
    for n, note in TARGETS:
        for use_frob in (True, False):
            for m in (3, 4, 5):
                if m not in SUPPORT: continue
                b = best_cell(2, n, m, use_frob)
                if b is None: continue
                l, R, budget = b["l"], b["R"], b["log2_budget"]
                stable = R > 1
                exp_anf = anf_log2_monomials(m * l, boolean_degree(m, l))
                sy = symmetrized(n, m, l, stable)
                ch = chained(n, m, l)
                rows.append(dict(
                    n=n, note=note, frobenius_arm=use_frob, m=m, l=l, R=R,
                    stable_V=stable, log2_budget=round(budget, 2),
                    expanded=dict(vars=m * l, degree=boolean_degree(m, l),
                                  log2_anf=round(exp_anf, 2),
                                  deficit=round(exp_anf - budget, 2)),
                    symmetrized=dict(sy, log2_dense=round(sy["log2_dense"], 2),
                                     log2_block=round(sy["log2_block"], 2),
                                     deficit_dense=round(sy["log2_dense"] - budget, 2),
                                     deficit_block=round(sy["log2_block"] - budget, 2),
                                     encoding_valid=not stable or True),
                    chained=dict(ch, log2_dense=round(ch["log2_dense"], 2),
                                 log2_block=round(ch["log2_block"], 2),
                                 deficit_dense=round(ch["log2_dense"] - budget, 2),
                                 deficit_block=round(ch["log2_block"] - budget, 2))))
    json.dump(rows, open(HERE / "anf_table.json", "w"), indent=1)
    # best arity per curve, per encoding, Frobenius arm on (as the original)
    summary = {}
    for n, note in TARGETS:
        rs = [r for r in rows if r["n"] == n and r["frobenius_arm"] and r["log2_budget"] > 0]
        if not rs: continue
        pick = lambda key: min(rs, key=key)
        e = pick(lambda r: r["expanded"]["deficit"])
        s = pick(lambda r: r["symmetrized"]["deficit_dense"])
        c = pick(lambda r: r["chained"]["deficit_block"])
        summary[n] = dict(note=note,
                          expanded=(e["m"], e["expanded"]["deficit"]),
                          symmetrized_dense=(s["m"], s["symmetrized"]["deficit_dense"]),
                          symmetrized_block=(s["m"], s["symmetrized"]["deficit_block"]),
                          chained_block=(c["m"], c["chained"]["deficit_block"]))
    json.dump(summary, open(HERE / "anf_summary.json", "w"), indent=1)
    print(f"{'n':>4} {'curve':<15} {'expanded':>14} {'symm dense':>14} {'symm block':>14} {'chained block':>14}")
    for n, s in summary.items():
        f = lambda t: f"m={t[0]} {t[1]:+7.1f}"
        print(f"{n:>4} {s['note']:<15} {f(s['expanded']):>14} {f(s['symmetrized_dense']):>14} {f(s['symmetrized_block']):>14} {f(s['chained_block']):>14}")

if __name__ == "__main__":
    main()
