#!/usr/bin/env python3
"""build_report.py -- writes validation_report.yaml for TASK-20261004-7d2fb6 (joints W4..W10). Numbers are read from the scratch outputs in this directory wherever they exist;
the prose is mine. Run last (after scripts/99_collect.sh); it hashes every other file of the write scope and writes the report, then re-parses it and checks the one-attestation rule."""
import os, sys, json, glob, hashlib, subprocess, collections, yaml

WS = os.environ["WS"]; SP = os.environ["SP"]; REPO = "/home/user/crypto-autoresearcher"
OUT = f"{WS}/outputs"; SCR = f"{OUT}/scratch_results"
def J(p): return json.load(open(p))
def JL(p): return [json.loads(l) for l in open(p) if l.strip()]
def sha(p): return hashlib.sha256(open(p, "rb").read()).hexdigest()
head = subprocess.run(["git", "-C", REPO, "rev-parse", "HEAD"], capture_output=True, text=True).stdout.strip()

# ---------------------------------------------------------------- data from the scratch outputs
w4z = {r["instance_id"]: r for r in J(f"{OUT}/w4_zeros.json")}
z44 = w4z["ch_n44_m2_t2_k22_low_B_ran_s20260913101_d5"]; z45 = w4z["ch_n45_m2_t2_k23_low_B_ran_s20260913101_d0"]
w4c = {s: J(f"{OUT}/w4_controls_{s}.json") for s in ("chained_n16_m2_t2_k8_d0", "null_n12_m2_t2_k9_d0", "chained_n20_m2_t2_k10_d3")}
w4b = J(f"{OUT}/w4_bulk_scale.json")
_k = [(s, r) for s in w4b if not s.startswith("window_") for r in w4b[s]["rows"] if r["nbad"] >= 0.5 * w4b[s]["rank_of_corrupted_call"]]
w4_half = {"settings": len(_k), "trials": sum(r["trials"] for _, r in _k), "flagged": sum(r["flagged_at_the_corrupted_call"] for _, r in _k),
           "out_min": min(v for _, r in _k for v in r["bad_output_rows_reported"]), "out_max": max(v for _, r in _k for v in r["bad_output_rows_reported"])}
_m = [(s, c) for s in w4c for c in w4c[s]["C_bulk"] if c["flagged_at_the_corrupted_call"] < c["trials"]]
w4_passes = "; ".join(f"{s.split('_m2')[0]} nbad {c['nbad']}: {c['trials'] - c['flagged_at_the_corrupted_call']}/{c['trials']} trials pass" for s, c in _m)
w6 = J(f"{OUT}/w6_table.json"); w6x = J(f"{OUT}/w6_crosschecks.json")
w8 = J(f"{OUT}/w8_table.json"); w8d = J(f"{OUT}/w8_duplicates.json"); w9 = J(f"{OUT}/w9_classes.json")
w10s = J(f"{OUT}/w10_sets.json"); w10a = J(f"{OUT}/w10_analysis.json"); w7c = J(f"{OUT}/w7_allcounts.json"); w7v = J(f"{OUT}/w7_codeversions.json")
w7i = J(f"{OUT}/w7_instances.json"); w7d = J(f"{OUT}/w7_drawrule.json")
xproc = JL(f"{SCR}/xproc.jsonl"); resume = JL(f"{SCR}/resume.jsonl"); dose = JL(f"{SCR}/dose.jsonl")

def campaign(files):
    rows = []
    for f in files: rows += JL(f"{SCR}/{f}")
    return rows
rows_all = campaign(["w5_orig.jsonl", "w5_bigN.jsonl", "w5_s32.jsonl", "w5_eq4.jsonl", "w5_eq4D7.jsonl", "w5_mut.jsonl"])
def agg(variants):
    c = collections.Counter(); insts = set()
    for r in rows_all:
        if r.get("variant") not in variants: continue
        c["runs"] += 1
        if r.get("rc") != 0: c["not_completed_at_cap"] += 1; continue
        c["completed"] += 1; insts.add(r["instance"])
        early = r["contains_one"] and r["rank"] < r["ncols"]
        if early: c["early_stop_partial_rank"] += 1
        differs = (not r["std_equal"]) or (not r["verdict_equal"]) or ((not r["rank_equal"] or not r["lm_equal_as_set"]) and not early)
        if "saturation_violations" in r and not early:
            c["saturation_checked"] += 1
            if r["saturation_violations"] > 0: differs = True; c["saturation_violations_gt0"] += 1
        if r.get("gens_not_in_span"): differs = True
        if differs: c["differs_from_reference"] += 1
    c["distinct_instances"] = len(insts)
    return dict(c)
unm = agg({"orig", "STRESS32"}); mut = {v: agg({v}) for v in ("MA", "MB", "MB_s32", "MC", "MD", "MD_s32", "MF", "MF_s32", "MG", "MH", "MH_s32")}
xp = collections.Counter()
for r in xproc:
    k = r["variant"]; xp[(k, "scenarios")] += 1; xp[(k, "producer_flags")] += bool(r["producer_procedure_flags"]); xp[(k, "independent_flags")] += bool(r["independent_checks_flag"])
xp_tab = {}
for (k, f), v in xp.items(): xp_tab.setdefault(k, {})[f] = v
xp_tot = {"scenarios": len(xproc), "producer_procedure_flags": sum(bool(r["producer_procedure_flags"]) for r in xproc),
          "independent_checks_flag": sum(bool(r["independent_checks_flag"]) for r in xproc),
          "scenarios_where_independent_checks_flag_but_producer_does_not": sum(1 for r in xproc if r["independent_checks_flag"] and not r["producer_procedure_flags"]),
          "of_which_verifier_violations_gt0": sum(1 for r in xproc if r["independent_checks_flag"] and r.get("verifier_violations", 0) > 0)}
ro = [r for r in resume if r["variant"] == "orig"]
res_tot = {"tests_orig": len(ro), "all_fields_equal": sum(1 for r in ro if r.get("all_equal")), "resumes_performed": sum((r["resumed_run"] or {}).get("resumed") or 0 for r in ro),
           "kills_inside_a_multiplier_list_mi_gt_0": sum(1 for r in ro for s in r["kill_states"] if "it" in s and s["mi"] > 0), "kills_total": sum(1 for r in ro for s in r["kill_states"] if "it" in s),
           "distinct_iteration_multiplier_states": sorted({(s["it"], s["md"]) for r in ro for s in r["kill_states"] if "it" in s}),
           "not_equal": [{"stem": r["stem"], "cap": r["cap"], "resume_cap": r["resume_cap"], "kills": r["kills_at_checkpoint_state"], "baseline_rank": r["baseline"]["rank"], "resumed_rank": r["resumed_run"]["rank"],
                          "std_equal": r["equal"]["std"], "contains_one_equal": r["equal"]["contains_one"], "lm_equal": r["equal"]["lm_sha256"]} for r in ro if not r.get("all_equal")],
           "ME_outcome_differs": [sum(1 for r in resume if r["variant"] == "ME" and not r.get("all_equal")), sum(1 for r in resume if r["variant"] == "ME")],
           "MI_outcome_differs": [sum(1 for r in resume if r["variant"] == "MI" and not r.get("all_equal")), sum(1 for r in resume if r["variant"] == "MI")]}
dr = [r for r in dose if r["P"] >= 0]
dose_tot = {"runs": len(dr), "outcome_changed": sum(r["outcome_changed"] for r in dr), "verifier_flags_among_changed": sum(1 for r in dr if r["outcome_changed"] and r.get("verifier_flags")),
            "producer_procedure_flags_among_changed": sum(1 for r in dr if r["outcome_changed"] and r.get("producer_procedure_flags")),
            "producer_procedure_flags_total": sum(bool(r.get("producer_procedure_flags")) for r in dr), "max_len_without_outcome_change": max(r["LEN"] for r in dr if not r["outcome_changed"]),
            "changed_cases": [{"stem": r["stem"], "iteration": r["iteration"], "P": r["P"], "LEN": r["LEN"], "products_in_iteration": r["nprod_in_iteration"]} for r in dr if r["outcome_changed"]]}
w7v_done = [r for r in w7v if r["rc"] == 0]

# files of the write scope (every file except this report)
files = {}
for p in sorted(glob.glob(f"{WS}/**", recursive=True)):
    if os.path.isfile(p) and os.path.basename(p) != "validation_report.yaml":
        files[os.path.relpath(p, REPO)] = sha(p)

binaries = {}
for label, p in (("my_m4ri_release-20240729_libm4ri.so (own build, make check 15/15)", f"{SP}/m4ri_prefix/lib/libm4ri-0.0.20240729.so"),
                 ("libclosure_orig.so (unmutated closure.c at HEAD fb50e265, my M4RI)", f"{SP}/work/build/libclosure_orig.so"),
                 ("libclosure_orig_evalcheck.so (-DECH_EVALCHECK)", f"{SP}/work/build/libclosure_orig_evalcheck.so"),
                 ("libcountm2.so (my build of count_m2.c)", f"{SP}/work/build/libcountm2.so"), ("libcountchain.so (my build of count_chain.c)", f"{SP}/work/build/libcountchain.so"),
                 ("refclos (my reference closure / verifier, g++ -O2)", f"{SP}/work/refclos"), ("vcount_ms (my independent zero counter)", f"{SP}/work/vcount_ms")):
    binaries[label] = sha(p)
for p in sorted(glob.glob(f"{SP}/work/mut/libclosure_*.so")):
    binaries["mutant " + os.path.basename(p)] = sha(p)
producer_lib = "/tmp/claude-0/-home-user/e1ee877e-40c0-526f-8ca6-a6aa5f9bf38e/scratchpad/m4ri-20240729/lib/libm4ri-0.0.20240729.so"
binaries["PRODUCER'S loaded M4RI (path recorded in every 5ed13e record; hashed in place, not part of any package)"] = sha(producer_lib)

# ---------------------------------------------------------------- the report
def finding(fid, grade, statement, evidence, reproduce=None):
    d = {"id": fid, "grade": grade, "statement": statement, "evidence": evidence}
    if reproduce: d["reproduce"] = reproduce
    return d
E = lambda *p: [f"coordination/goals/GOAL-SEMBIN-5078bc/reviews/TASK-20261004-7d2fb6/{x}" for x in p]

report = {"validation_report": {
 "id": "VAL-20261005-43997c",
 "id_note": "random 6-hex token; tools/allocate_id.py has no validation-report type (repo precedent: earlier GOAL-SEMBIN-5078bc validation reports)",
 "task_id": "TASK-20261004-7d2fb6",
 "role": "validator",
 "recorded_at": "2026-10-05",
 "goal_id": "GOAL-SEMBIN-5078bc", "batch_id": "BATCH-9d649f", "question_id": "RQ-SEMBIN-fa2e3f", "experiment_id": "EXP-SEMBIN-7e1371", "hypothesis_id": "H-SEMBIN-2d7708",
 "review_round": "REVIEW-SEMBIN-20261004-a47503 (as named in the card header; the plan file itself was not opened)",
 "run_ids": ["RUN-SEMBIN-5ed13e", "RUN-SEMBIN-9bb990"],
 "snapshot_read": {"branch": "claude/ecdlp-index-calculus-grobner-xwr62t", "head_commit": head,
                   "working_tree_clean_at_start": True,
                   "note": "Everything below was read from the committed tree at this HEAD. The 92 untracked instance files of RUN-SEMBIN-9bb990 are present on this host (they are the producer's); they were treated as hash-listed only: "
                           "I hashed them in place and regenerated every one of them from the generator; I did not open their contents."},
 "what_this_report_is_not": ("A verdict on the whole claim (the card forbids one) or on Q-A / Q-B as stated. One verdict per joint W4..W10 follows. Nothing here asserts Assumption 1, d_F4, any solver's degree of regularity, "
                              "n = 409 or 571, or the security of any curve, in either direction. No experiment run was made and no RUN id was minted: everything is scratch computation on small instances, "
                              "regeneration of instance files, mutants of COPIES of closure.c, and parsing/recomputation of the producer's records. An implementation or instrument failure is never a negative mathematical result."),
 "joint_verdicts": {"W4": "holds", "W5": "holds", "W6": "holds", "W7": "holds", "W8": "breaks", "W9": "breaks", "W10": "holds"},
 "verdict_reading_guide": ("'breaks' on W8 and W9 means that the card's pre-registered breaking artifact for that joint was found; in both cases it is narrow, none changes a verdict-bearing value of either run, and each is stated "
                            "with its reproducing command below. 'holds' on W5 means: no defect in the UNMUTATED closure.c and no statement-versus-code difference in the order or the budget, over the tested configurations (N <= 26, plus degree 6/7 at N = 12); "
                            "it is not a check of any N >= 40 closure, which this card forbade (see limitations)."),
 "joints": {},
}}
R = report["validation_report"]

# ============================================================== W4
R["joints"]["W4"] = {
 "verdict": "holds",
 "verdict_rationale": ("Holds for the claim as the card words it: witnesses are common zeros (VERIFIED), the check evaluates what is stated (VERIFIED, positive control), and no bulk-corruption mutant touching about as many rows as the defect observed on 0.0.20200125 (the check counted 0.478 and 0.490 of the output rows non-vanishing there, so at least that share was corrupted) passed (VERIFIED at N = 16..20, plus the real defect flagged in the package logs). "
                       "What I did find, and state as scope: smaller corruptions DO pass in a fraction of trials, most on a sparse witness, and the necessary-only control stays clean as predicted. If the Coordinator reads the card's 'a bulk-corruption mutant that the evalcheck passes' as any BULK mutant regardless of size, those passes meet it; I did not read it that way because the claim attacked is about a defect 'of the kind seen'."),
 "claim_as_attacked": ("That the -DECH_EVALCHECK build evaluates what the notes say (every input row and every output row of every elimination at a verified common zero); that the witness each cross-check used is a common zero of the .ms system; "
                       "and that a clean reading rules out a bulk out-of-ideal defect like the one seen on M4RI 0.0.20200125 but not out-of-ideal rows that vanish at the single witness."),
 "failed_attempts_to_break": [
   "Looked for a witness that is not a common zero: both witnesses violate 0 generators in my own evaluator and equal the first zero of count_m2's lister, which equals the set my independent counter finds.",
   "Looked for an evalcheck that does not evaluate what is stated: positive control (wrong witness) flags at the first elimination, and a correct witness reads in=0 out=0 for all three routines.",
   ("Looked for vacuity on a bulk defect (the card's breaking artifact: a bulk-corruption mutant that the evalcheck passes). Result, stated exactly: mutants DO pass when they corrupt few rows by single-bit flips "
    "(w4_controls part C, 12 trials per setting; the settings with at least one passing trial: " + w4_passes + "), and the passing is worst on the instance whose witness is sparse (null_n12, 5 ones in 18 coordinates, "
    "f = 0.77% of columns visible). The defect the claim is about is not of that size: in the notes' logs the check itself counted 66,598 of 139,204 and 68,559 of 139,898 output rows that do not vanish at the witness (0.478 and 0.490 of the rows), so at least that many rows were corrupted. Extended to that size "
    "(w4_bulk_scale: nbad >= 0.5 x the rank of the corrupted elimination single-bit flips, which touch at least about 39% of the rows before the silent re-echelonization; three instances) the evalcheck flagged " + f"{w4_half['flagged']}/{w4_half['trials']} trials ({w4_half['settings']} settings x 12; the out= counts it reported ranged from {w4_half['out_min']} to {w4_half['out_max']}: one flip need not leave one visible row after the re-echelonization)" + ", and "
    "the same evalcheck flagged the real defect at the window scale in the package's own logs (W9-1). So no mutant touching about as many rows as the observed defect passed, although single-bit flips are the least visible corruption per row. I read 'bulk out-of-ideal defect of the kind seen' as that size. Read as 'any "
    "BULK mutant, whatever its size', the mutants listed above are passing artifacts, and the claim as the notes word it ('necessary condition ... not a proof') is already consistent with them; the corrected wording below states the size dependence.")],
 "scope_finding_the_card_predicted": ("The check is necessary only and is a bulk-defect detector. It cannot see an out-of-ideal row that vanishes at the witness (necessary-only control below) and its per-bad-row detection probability for an isolated corruption is only "
                                       "the fraction of monomials equal to 1 at the witness (about 4.4% and 7.8% for a random degree-4 monomial, 5.0% and 8.5% over all columns, at the two window witnesses). It cannot see completeness at all."),
 "findings": [
  finding("W4-1", "VERIFIED", "Code reading of ech(), rows_not_vanishing() and the ECH_EVALCHECK branch (closure.c lines 197-233, 304-316): rows_not_vanishing(M, nrows) is run on the elimination INPUT (all rows) and rows_not_vanishing(M, r1) on the OUTPUT (rows < rank); a row is evaluated as the XOR over its set columns j of [col_mask_[j] subset of witness], i.e. its value in the Boolean ring at the Boolean point. The stderr line prints in= and out=; ech_mismatch_ counts calls with bin>0 or bout>0.",
          ["experiments/EXP-SEMBIN-7e1371/code/closure.c"]),
  finding("W4-2", "VERIFIED", f"Witnesses. xcheck.py takes the FIRST zero listed by count_m2.list_m2 (soundness_probe.solution_assignment: out[0], out[1], coordinates in the low-degree basis). The logs print only the count of violated generators (0) and the first 16 hex of the system hash; they do not name the witness. "
          f"Recomputed with the producer's own lister (my build of count_m2.c, sha256 equal to the manifest's libcountm2.so) and with my own zero finder (vcount_ms: affine-in-x2 solve per x1 on the Boolean polynomials parsed from the .ms, no field arithmetic): "
          f"n=44 draw 5 has {z44['my_count']} zeros {z44['lister_zeros']}; the witness xcheck.py used (implied) is {z44['lister_first_assignment_via_soundness_probe']} = lister index {z44['witness_index_in_lister_order']}. "
          f"n=45 draw 0 has {z45['my_count']} zeros {z45['lister_zeros']}; witness {z45['lister_first_assignment_via_soundness_probe']} = lister index {z45['witness_index_in_lister_order']}. "
          "All zeros of both instances violate 0 generators in my evaluator, and the lister's set equals my set. The same holds for all 12 window instances (exact |V| equal to the record's in 12/12; lister set equal to mine in 12/12).",
          E("outputs/w4_zeros.txt", "outputs/w4_zeros.json", "scripts/w4_zeros.py", "scripts/vcount_ms.c", "scripts/msparse.py"),
          "cd $SP/work && python3 $WS/scripts/w4_zeros.py   (after 00_env.sh, 02_build_libs.sh, 03_prodcopy.sh; builds vcount_ms with gcc -O2 scripts/vcount_ms.c)"),
  finding("W4-3", "VERIFIED", "Positive control (wrong witness) at small N on the evalcheck build of the UNMUTATED closure.c: a non-zero assignment violating 8 to 11 generators is flagged at the first elimination ('in=8 ... *** PRODUCTS ALREADY OUTSIDE THE IDEAL ***'), as the notes report for the 15-generator case at N=44 (that log is not in the package; I reproduced the kind of result, not the number). A correct witness reads in=0 out=0 at every call for all three routines (mzd_echelonize, PLUQ, Four Russians).",
          E("outputs/w4_controls_chained_n16_m2_t2_k8_d0.txt", "outputs/w4_controls_chained_n16_m2_t2_k8_d0.json", "scripts/w4_controls.py"),
          "python3 $WS/scripts/w4_controls.py chained_n16_m2_t2_k8_d0"),
  finding("W4-4", "VERIFIED", "Bulk-corruption mutant BULK (inside ech(), before the output accounting: one pseudo-random column flipped in each of nbad pseudo-random output rows, then silent re-echelonization), 12 trials per nbad, witness = first zero. Detection by the evalcheck at the corrupted call: "
          + "; ".join(f"{s}: " + ", ".join(f"nbad {c['nbad']}: {c['flagged_at_the_corrupted_call']}/12" for c in w4c[s]["C_bulk"]) for s in w4c) +
          ". Detection depends on how many monomials are 1 at the witness (witness popcount 7/16, 5/18, 12/20; fraction of degree-4 monomials equal to 1: 0.019, 0.0016, 0.102). For the two window witnesses (popcount 21/44 and 25/46) that fraction is 0.0441 and 0.0775.",
          E("outputs/w4_controls_chained_n16_m2_t2_k8_d0.json", "outputs/w4_controls_null_n12_m2_t2_k9_d0.json", "outputs/w4_controls_chained_n20_m2_t2_k10_d3.json", "scripts/make_mutants.py", "mutants/BULK.diff")),
  finding("W4-8", "VERIFIED (measurements at N = 16..20) + PLAUSIBLE (model at the window witnesses; no window-scale corruption run was made)",
          "Detection against corruption SIZE, extended to the size observed on M4RI 0.0.20200125 (BULK mutant, nbad up to 16,384 flips = 4.4 to 9.1 x the rows, 12 trials per setting; columns visible at the witness f = 0.77% / 3.9% / 12.8% on the three instances): "
          + "; ".join(f"{s.split('_m2')[0]} (rank {w4b[s]['rank_of_corrupted_call']}): " + ", ".join(f"nbad {r['nbad']} {r['flagged_at_the_corrupted_call']}/12" for r in w4b[s]["rows"]) for s in w4b if not s.startswith("window_"))
          + f". Settings with nbad >= 0.5 x rank: {w4_half['flagged']}/{w4_half['trials']} flagged. Measured rate against the model 1-(1-f)^nbad: at nbad = 512 on null_n12 the model gives 0.98 and 10/12 were flagged (the corruption is propagated by the re-echelonization, so the model is a rough guide, not a fit). "
          f"At the window witnesses (popcount 21 of 44 and 25 of 46; f = {w4b['window_n44_d5']['f']:.4f} and {w4b['window_n45_d0']['f']:.4f} over all columns) the model's miss probability for 16 / 128 / 1,024 bad rows is "
          + " / ".join(f"{w4b['window_n44_d5']['model_miss_probability'][k]:.3g}" for k in ('16', '128', '1024')) + " (n=44) and " + " / ".join(f"{w4b['window_n45_d0']['model_miss_probability'][k]:.3g}" for k in ('16', '128', '1024')) + " (n=45). "
          "Single-bit flips are the least visible corruption per bad row (a row replaced by a wrong combination would evaluate to 1 about half the time): PLAUSIBLE, not measured.",
          E("outputs/w4_bulk_scale.txt", "outputs/w4_bulk_scale.json", "scripts/w4_bulk_scale.py", "mutants/BULK.diff"),
          "cd $SP/work && python3 $WS/scripts/w4_bulk_scale.py null_n12_m2_t2_k9_d0 chained_n16_m2_t2_k8_d0 chained_n20_m2_t2_k10_d3   (after scripts/make_mutants.py; instances from 04_gen_instances.sh)"),
  finding("W4-5", "VERIFIED", "Necessary-only control (mutant INJ, inside ech(): after the elimination and before the evalcheck's output accounting, add the row p = (x_a + w_a)*mu, which vanishes at the witness w and not at a second zero w2 that differs in coordinate a). "
          "On null_n12 (insufficient base: std 4536, |V| = 67): evalcheck bad calls 0 and every call in=out=0, while rank changes 1986 -> 2604/2111/2002/1987 and std 4536 -> 2268/3896/4432/4528 for |mu| = 0/1/2/3; the verdict rule stays silent ('insufficient' throughout, std stays >= |V|); the final basis has 727/639/636/585 rows not vanishing at w2. "
          "On chained_n16 and chained_n20 (sufficient bases, |V| = 2) the evalcheck also stays clean (0 bad calls), rank rises by one, std falls from 2 to 1 and the verdict rule's own count check reports 'impossible' (std < |V|): there the exact count is a second line of defence the evalcheck lacks.",
          E("outputs/w4_controls_null_n12_m2_t2_k9_d0.txt", "outputs/w4_controls_chained_n16_m2_t2_k8_d0.txt", "outputs/w4_controls_chained_n20_m2_t2_k10_d3.txt", "mutants/INJ.diff")),
  finding("W4-6", "VERIFIED", "How many zeros each cross-checked instance has and which fraction the check used: n=44 draw 5: 4 zeros, 1 used (1/4); n=45 draw 0: 2 zeros, 1 used (1/2).", E("outputs/w4_zeros.json")),
  finding("W4-7", "VERIFIED (small N) + argument", "In the Boolean ring B = F_2[x]/(x_i^2+x_i) every ideal is the vanishing ideal of its zero set. Checked on the whole ideal I generated by the system (reference closure with D = N+1 and size-1 multipliers, i.e. all multiples): N=12: rank 4094 = 2^12 - |V| (|V| = 2); N=14: rank 16378 = 2^14 - |V| (|V| = 6). Consequence: a row lies in I iff it vanishes at ALL zeros, so for an instance with |V| = 2 or 4 an evaluation check at all zeros is not merely necessary but sufficient for 'W' is inside I'. It still would not give W inside the degree-capped closure (instances with |V| = 0 have no zero at all), and it says nothing about completeness. This is a suggestion, not a finding against the producer.",
          E("scripts/refclos.cpp", "scripts/w4_controls.py"), "MAXMU=1 refclos closure inst/chained_n12_m2_t2_k6_d0.sys 13 ref/x   (see outputs/scratch_results/ref_stats)"),
 ],
 "corrected_wording": ("NOTES.md already says the evaluation check is 'a necessary condition for soundness at one zero, not a proof'. Add: 'at 1 of 4 (resp. 1 of 2) zeros. Its power depends on how many rows are bad and how many columns are visible at the witness (a bad row is seen with probability about the fraction f of columns whose monomial equals 1 at the witness: 5.0% and 8.5% at the two window witnesses): it flagged every scratch trial in which at least half as many flips as output rows were injected (168 of 168) and flagged the real defect (66,598 / 68,559 non-vanishing rows) in the package logs, but corruption of a few hundred rows by single-bit flips passes in a fraction of trials on a sparse witness, and an out-of-ideal row that vanishes at the witness is never seen. It does not test completeness'."),
}

# ============================================================== W5
R["joints"]["W5"] = {
 "verdict": "holds",
 "verdict_rationale": ("Holds under the card's breaking-artifact definition: no disagreement of the UNMUTATED closure.c with my reference closure or saturation verifier on 127 completed runs, and no statement-versus-code difference in the order or the budget. Two verified differences that are NOT order or budget are reported and carry corrected wording: "
                       "S2 (early stop at the first batch that yields 1: the recorded rank and digest of one record, n=40 draw 0, are an intermediate batch-dependent state; I excepted the 7 early-stop runs from the rank/LM comparison for exactly this reason, which is a disagreement of the recorded rank with the statement's W_4 in those runs) and S3 (the verdict rule does not compare with |V| when 1 is in W). "
                       "If the Coordinator counts S2 as a 'defect in the unmutated closure.c', W5 would read breaks on rank/digest for that one record; the verdict-bearing values (N_std, verdict) are unaffected."),
 "claim_as_attacked": "That closure.c's product set is complete (every product mu*f with 1 <= |mu| <= D - deg f of every row that must be multiplied is formed exactly once and reaches the elimination, across batches, iterations, the single-level path, memory-driven splitting and resume) and that the card's statement of the closure equals what closure.c implements.",
 "closure_c_in_my_words": ("Columns: all squarefree monomials of size <= D, blocks by size descending, within a block ascending bitmask (Gosper), so column 0 is the largest monomial in the statement's ORDER and a reduced row's leading monomial is its first set column. "
   "Iteration 0 writes the generators as written, echelonizes (RREF) and installs the basis; every installed row is flagged new. Iteration i>=1: the rows flagged new (rows whose pivot column was not a pivot before, plus, in a later batch of the same iteration, rows whose pivot is flagged pivot_new_) are copied densely to NM; "
   "for each such row (in row order a) the multipliers are all squarefree monomials of size md = 1..D - popc(leading monomial) (ascending Gosper order; cursor (a, md, mi)); products are written (write_product: union, parity-cancel, column lookup) into S = [basis; batch], the batch size is re-derived before every batch from the live rank and the memory cap (batch_for; a floor of 1024 products below which the run stops 'unreached'), "
   "B_ is freed after the products are written (9096320e22), S is eliminated (PLUQ), the output is checked structurally and no old pivot may be lost, install_basis keeps the new/pivot_new_ flags, and ckpt_save writes the cursor and flags. The iteration ends when the cursor is exhausted; the closure ends when an iteration gives no new pivot, "
   "when every new row already has size D (n_prod = 0), when 1 becomes a pivot after a batch (early stop), or at the cap. The single-level path (max_iter = 1) multiplies the ORIGINAL generators, each by monomials up to D - (its own largest monomial size), in one iteration on top of the RREF of the generators. Resume reloads basis, flags, history and the cursor (a, md, mi) and the dense NM of the interrupted iteration."),
 "statement_versus_code": [
   {"id": "S1", "grade": "VERIFIED", "difference": "ORDER and BUDGET: none. The column layout reproduces the card's ORDER pairwise for N = 8..62 (column i is strictly larger than column i+1 under a literal implementation of the card's comparator), and the leading-monomial LISTS of the production closure equal those of my reference closure (written from the statement alone) on every completed unmutated run. Budget D - deg f with deg f = size of the leading monomial is what the product loops use.",
    "evidence": E("outputs/guards_test.txt", "scripts/guards_test.c", "scripts/refclos.cpp", "scripts/w5_campaign.py")},
   {"id": "S2", "grade": "VERIFIED", "difference": "EARLY STOP. When 1 enters the row space after a batch the closure stops (closure.c lines 904-910). The recorded rank, leading-monomial digest and leading-degree counts are then those of an intermediate subspace, not of W_D (which, containing 1, is the whole space of dimension = columns). The intermediate rank depends on the batch layout: on chained_n10_m3_t3_k4_d0 (|V| = 0) the same instance records rank 8774 at one memory cap and 8960 at another, against 9109 columns; the verdict and N_std = 0 are unaffected. In RUN-SEMBIN-5ed13e this changes the recorded rank/LM digest of exactly one record: n = 40 draw 0 (101,931 of 102,091, contains_one true, digest 8b168c1a...). The other four records with 1 in W (n=41 d0, n=42 d0 at D=2, n=43 d5, n=44 d0 at D=2) have rank = columns. Not a change of order or budget.",
    "evidence": E("outputs/scratch_results/w5_orig.jsonl", "outputs/w7_resume_note", ) if False else E("outputs/scratch_results/w5_orig.jsonl", "outputs/scratch_results/resume.jsonl", "outputs/w8_table.json")},
   {"id": "S3", "grade": "VERIFIED", "difference": "VERDICT RULE for 1 in W. The card's rule says 'impossible iff N_std < |V|'. closure_cert.closure_certificate takes a separate branch when 1 is in W: it sets verdict = sufficient and solutions = 0 without comparing with the caller-supplied |V|. Handed a deliberately wrong |V| = 5 on a solution-free instance it still returns sufficient (solutions 0, solutions_source 'caller_supplied'); the non-1 branch does return 'error' for std < |V|. (The 9bb990 NOTES describe this as a recording defect; closure_cert.py was not changed for 5ed13e.) For the five 5ed13e records with 1 in W the exact |V| is 0 (my independent counter agrees on all 12 instances and on all 60 draws), so no verdict is wrong; but for those five records the rule did not USE |V|, and the soundness of 1 in W_D rests on the elimination alone.",
    "evidence": E("outputs/w5_verdict_rule_poison.txt", "scripts/w5_verdict_rule_poison.py")},
   {"id": "S4", "grade": "VERIFIED (equality) / PLAUSIBLE (argument)", "difference": "Only 'new' rows are multiplied, each in the RREF version current at the start of its iteration, and each by sizes 1..D - size(LM). The statement closes under EVERY f in W. Equivalent because (a) the leading monomial of a sum of rows with distinct leading monomials is the largest of them, so deg f = max deg of the rows involved; (b) a later reduction only adds rows with later pivots (size <= deg), whose own budgets are at least as large; (c) closure under multipliers of size 1 with budget D - deg f already generates all larger multipliers (mutant MG, size-1 multipliers only, never changes an outcome in 27 runs). The argument is PLAUSIBLE (argued, not machine-checked); its prediction, equality of the production closure with the worklist reference closure (which multiplies every inserted vector, not just new rows), is VERIFIED in the campaign below.",
    "evidence": E("outputs/scratch_results/w5_orig.jsonl", "outputs/scratch_results/w5_mut.jsonl")},
   {"id": "S5", "grade": "VERIFIED", "difference": "SINGLE-LEVEL PATH. It is not the statement's W_D: it forms span(generators, mu*g for the ORIGINAL generators g, |mu| <= D - deg g) once. Its rank equals my independent Macaulay-matrix rank in 42/42 runs (7 instances, orig and lowered-batch-floor builds, three caps), and its recorded row count equals ngens + n_prod of the original generators.",
    "evidence": E("outputs/w5_singlelevel.txt", "scripts/w5_singlelevel.py")},
   {"id": "S6", "grade": "VERIFIED", "difference": "Monomial order tie-break is load-bearing for leading-monomial data and, in insufficient cases, for N_std: the same system with its variables reversed gives the same rank and a different LM set on all 8 instances tested and a different N_std on one (11312 against 11280); so an 'insufficient' count is relative to this order (x_1 largest). The comparison with the statement's order is therefore discriminating, and it passes.",
    "evidence": E("outputs/w5_order_control.txt", "scripts/w5_order_control.py")},
 ],
 "reference_and_verifier": {
   "reference_closure": "scripts/refclos.cpp, mode closure: written from the card's statement, ORDER implemented literally (largest variable index in the symmetric difference), hash-map column index, worklist over every inserted vector with non-reduced echelon, N_std by a SOS-DP over all 2^N subsets, nothing shared with closure.c.",
   "saturation_verifier": "refclos saturate: re-echelonizes the final basis rows with my own reducer, checks every generator reduces to 0 and that mu*r reduces to 0 for every echelon vector r and every mu with 1 <= |mu| <= D - deg(LM r). An unmutated final basis that fails would be a break; a final basis that passes and has the reference's rank equals W_D exactly (a closed space containing the generators contains W_D; equal rank forces equality).",
   "unmutated_totals": unm, "mutant_totals": mut},
 "mutants": [
   {"id": "MA", "what": "multiplier budget one lower", "detected_by_reference_and_verifier": True, "producer_procedure_flags": False, "note": "changes rank, std, LM and verdict in every run."},
   {"id": "MB", "what": "drop the pivot_new_ branch of install_basis", "detected_by_reference_and_verifier": "only when an iteration has several batches whose first batches add many pivots (lowered batch floor build, chained t=3 N=21: rank 6135 of 7544, std 1379 against |V| = 3, verdict sufficient -> insufficient); invisible at the production floor on every tested instance", "producer_procedure_flags": False,
    "note": "the branch is load-bearing: its removal produces a FALSE INSUFFICIENT, the polarity of the three window verdicts that depend on completeness."},
   {"id": "MC", "what": "multiply generators only (single-level product set run as a closure)", "detected_by_reference_and_verifier": "yes on the chained t=3 and eq.(4)-shaped instances; no on the quadratic ones where the single-level rank already equals the closure rank", "producer_procedure_flags": False},
   {"id": "MD", "what": "discard the last batch of products of every iteration", "detected_by_reference_and_verifier": True, "producer_procedure_flags": False, "note": "with one batch per iteration this discards every product (rank = rank of the generators)."},
   {"id": "ME", "what": "resume loses the partly processed row", "detected_by_reference_and_verifier": False, "producer_procedure_flags": False, "note": f"outcome unchanged in {res_tot['ME_outcome_differs'][1]} kill/resume tests: losing one row's remaining products is absorbed by redundancy at these sizes (see dose-response)."},
   {"id": "MF", "what": "cursor off-by-one: one product skipped at every full batch boundary", "detected_by_reference_and_verifier": False, "producer_procedure_flags": False, "note": "outcome unchanged (absorbed)."},
   {"id": "MG", "what": "only size-1 multipliers", "detected_by_reference_and_verifier": False, "producer_procedure_flags": False, "note": "equivalent mutant (S4)."},
   {"id": "MH", "what": "premature fixpoint: stop when < 5 new pivots", "detected_by_reference_and_verifier": False, "producer_procedure_flags": False, "note": "no outcome change at these sizes (the last productive iterations here add more than 5 pivots or none)."},
   {"id": "MI", "what": "resume forgets which rows/pivots were new", "detected_by_resume_harness": True, "note": f"outcome differs from the uninterrupted run in {res_tot['MI_outcome_differs'][0]} of {res_tot['MI_outcome_differs'][1]} tests (e.g. rank 6135 and std 1379 instead of 7544 and 3): a false insufficient."},
   {"id": "MJ", "what": "drop LEN consecutive products at position P of iteration IT (dose-response)", "result": dose_tot},
 ],
 "producer_cross_check_procedure_on_mutants": {
   "procedure": "the two-routine plus evalcheck procedure of crosscheck_n44_d5/xcheck.py: record run (default PLUQ, cap A) against a -DECH_EVALCHECK run with mzd_echelonize (method 0), cap B, witness a verified zero; flagged if rank/std/LM digest/profile differ or any call has in>0 or out>0. The mutant is applied to both builds.",
   "totals": xp_tot, "per_variant": xp_tab,
   "reading": ("The producer's procedure flagged none of the scenarios, including every one in which my reference and verifier flagged the record (MA, MB_s32, MC, MD, MD_s32): both routines eliminate the same under-filled matrices. This is the blind spot the notes state ('both routines share closure.c's product generation'), confirmed as EXPECTED and not by itself a break. "
               "The saturation verifier is the check that can see a missing product: it flagged every outcome-changing variant it was run on (N <= 24) and the reference flagged the N = 21 cases it could not saturate-check."),
   "evidence": E("outputs/scratch_results/xproc.jsonl", "outputs/scratch_results/xproc.log", "scripts/w5_xproc.py")},
 "dose_response_of_product_loss": {"result": dose_tot, "reading": ("A localized loss of products almost never changes the outcome: up to 15,000 consecutive products dropped leaves rank, std and LM list unchanged unless the block is essentially the whole iteration (all 2,176 products of null_n16 iteration 1; 15,000 of 15,204 products of chained_n9 iteration 3). When the outcome did change, the verifier flagged it (5 of 5) and the producer's procedure did not (0 of 5). "
                                      "So a missing-product defect that matters must remove almost an entire iteration or a structural class (MA, MB, MC, MD, MI above), and those are exactly what the verifier sees and the two-routine check does not."),
                         "evidence": E("outputs/scratch_results/dose.jsonl", "scripts/w5_singledrop.py", "scripts/run_doseresponse.sh", "scripts/run_doseresponse2.sh")},
 "guards": [
   {"id": "G1", "grade": "VERIFIED", "statement": "closure.c #included unmodified: ncols, per-block counts, strictly ascending masks, order, col_of2(col_mask_[j]) == j, col_of2 = -1 for popcount D+1 and for masks outside N, gen_masks_deg against an independent recursion, for N = 8, 12, 22, 28, 40, 44, 46, 50, 62 at D = 4 and N = 8, 12, 22, 28 at D = 7: all PASS; ncols at N = 40/44/46 is 102091/149986/179447, the columns of the records. write_product against a reference on 300 random inputs: PASS, dropped_terms_ = 0.", "evidence": E("outputs/guards_test.txt", "scripts/guards_test.c")},
   {"id": "G2", "grade": "VERIFIED", "statement": "grep of the six window lanes' stderr.log for 'closure: count mismatch': 0 occurrences. dropped_terms_above_D = 0 and elimination_faults = 0 in all 32 per-D closure records of 5ed13e; all 32 name the 20240729 library and mzd_echelonize_pluq. Product terms cannot exceed D because the budget bounds |mu| by D - size(LM) and LM is the largest monomial (a row term above D is impossible), so col_of2 = -1 cannot occur; note closure_run itself does not guard a generator of degree > D (it would silently truncate): closure_certificate does (not_applicable).", "evidence": E("outputs/guards_test.txt")}],
 "failed_attempts_to_break": [
   f"Unmutated closure.c against my reference and verifier: {unm['completed']} completed runs on {unm['distinct_instances']} instances (chained m=t=2 and t=3, matched-null, eq.(4)-shaped at D = 6 and 7; N = 9..26; memory caps from 'many tiny batches' to 'one batch'; production batch floor and a lowered floor build), {unm.get('saturation_checked', 0)} saturation checks: 0 disagreements in rank, std, LM list, verdict, saturation (the {unm.get('early_stop_partial_rank', 0)} early-stop runs excepted, see S2).",
   "Cursor bookkeeping across batch boundaries: multi-batch iterations with up to 159 batches per closure (eq.(4)-shaped D=7), boundaries inside multiplier lists, all equal to the reference.",
   f"Resume: {res_tot['tests_orig']} kill/resume tests (single, double and triple SIGKILL at {len(res_tot['distinct_iteration_multiplier_states'])} distinct (iteration, multiplier-size) states, {res_tot['kills_inside_a_multiplier_list_mi_gt_0']} of {res_tot['kills_total']} kills inside a multiplier list, resumes with a different memory cap): final rank, std, LM digest and per-iteration profile equal the uninterrupted run in {res_tot['all_fields_equal']} of {res_tot['tests_orig']}; the one exception is the early-stop partial rank (S2)."],
 "breaking_artifact": None,
 "corrected_wording_for_Q_A": ("'For the twelve records, the recorded standard-monomial count and verdict equal those of the degree-capped closure W_4 as defined in the statement. The recorded rank and leading-monomial digest equal those of W_4 for all records except those in which 1 enters the row space (five records, |V| = 0); there the closure stops at the first batch that yields 1: in four of them the stopped state is the full space (rank = columns), in n = 40 draw 0 it is not (101,931 of 102,091) and its rank and digest are batch-dependent. For these records the verdict rule does not compare with |V|; |V| = 0 was independently confirmed.'"),
}

# ============================================================== W6
R["joints"]["W6"] = {
 "verdict": "holds",
 "claim_as_attacked": "What the n=44 draw 5 and n=45 draw 0 cross-checks establish and what they do not, and that no claim is made for the unchecked instances.",
 "findings": [
  finding("W6-1", "VERIFIED", "From the logs by parsing: routine header 'mzd_echelonize' and every call labelled 'default' in all three logs against the lane records' mzd_echelonize_pluq; caps 7.0 / 10.5 against 11.0 (n=44) and 11.5 against 11.0 (n=45); the m4ri path printed in all three logs equals the m4ri_library of the lane records and names release 0.0.20240729. Batching differs: n=44 d5 check run had 2 batches in iteration 2 (293,647 + 135,243 products = 428,890 = 480,965 - 52,075, the record's iteration-2 product count); n=45 d0 check run eliminated 309,921-row matrices three times in iteration 2. The cap-7 attempt stopped 'unreached_memory_cap' at rank 125,250 after 3 eliminations, all in=0 out=0: an instrument limit, correctly not counted as a result. The logs do NOT record the hash of closure.c or of the evalcheck library; the NOTES' statement for n=45 ('built with -DECH_EVALCHECK from closure.c at 9096320e22, sha256 a7da1a1f...') is an assertion with no artifact in the package (the evalcheck .so files are not packaged), consistent with the git blob hash of 9096320e22 but unverifiable as to what was loaded.",
          E("outputs/w6_crosschecks.txt", "outputs/w6_crosschecks.json", "scripts/w6_parse_crosschecks.py")),
  finding("W6-2", "VERIFIED", "Equality by parsing, not reading: for both instances the check run's rank, standard-monomial count, verdict, basis LM SHA-256 and the complete per-iteration (rows, rank, new pivots) profile equal the lane record's (n=44 d5: 57ed1d33...5db8, profile (44,43,43),(55857,52075,52032),(480965,126961,74886),(145089,135749,8788),(143493,140853,5104),(140853,140853,0); n=45 d0: 64f3e3fa...5ead, profile (45,45,45),(63870,59603,59558),(626806,152003,92400),(171415,161305,9302),(169585,166705,5400),(166705,166705,0)).", E("outputs/w6_crosschecks.json")),
  finding("W6-3", "VERIFIED", "System identity: the 16-hex prefix printed by xcheck equals the lane record's system_sha256 and the instance JSON's stored hash; the hash recomputed from the JSON's canonical payload equals them (n=44 d5: 0ef3197688239a86..., n=45 d0: 6961f43cb0a6dc45...).", E("outputs/w6_crosschecks.json")),
  finding("W6-5", "VERIFIED", "Producer's leading-monomial hash input (closure_cert._lm_stats): sha256 over, for every basis row in row order (the reduced echelon basis: ascending leading column = size descending, then ascending bitmask), the leading monomial's bitmask as 8 bytes BIG-endian (bit i = variable index i of var_names, i.e. x1_0..x1_{k-1} are bits 0..k-1 and x2_0.. are bits k..2k-1; the constant monomial is 8 zero bytes); hex digest, lowercase. Verified by recomputing it from my reference's LM list: equal to the library's lm_sha256 on 60 of 60 completed unmutated runs (12 instances). The blind lane's canonical digest is directly comparable only if it uses the same bit-to-variable map, the same row order (size descending, then ascending bitmask) and the same 8-byte big-endian encoding of the leading monomials only (not the standard monomials); and it is NOT comparable for the n = 40 draw 0 record, whose digest belongs to an early-stopped intermediate basis (S2).",
          E("outputs/w6_table.txt", "scripts/w6_lmhash_and_table.py")),
 ],
 "per_instance_check_and_polarity_table": w6["table"],
 "table_reading": ("Exactly two instances carry a second elimination routine and the evaluation check, each at 1 zero of 4 and of 2. Ten carry only the always-on structural check (and, for the four |V|>0 sufficient records, the exact agreement std = |V|). The three insufficient verdicts are completeness-sensitive, the nine sufficient ones soundness-sensitive; of the three insufficient ones, n=45 draw 4 (|V| = 0) was not cross-checked, which the NOTES state. The five sufficient records with 1 in W have no witness and no count check; their only protections are the structural check and the fixed library."),
 "failed_attempts_to_break": ["Looked for a library, hash, cap or system that differs from the claim: none (W6-1, W6-3).", "Looked for a digest or profile that does not match: none (W6-2).", "Looked for checks overstated in the NOTES: the NOTES state the shared product code, the single zero, and that n=45 draw 4 was not cross-checked; the manifest's validity reason covers only the 'two insufficient verdicts with solutions'. Not overstated."],
 "breaking_artifact": None,
}

# ============================================================== W7
R["joints"]["W7"] = {
 "verdict": "holds",
 "claim_as_attacked": "Provenance of each .ms, the draw rule, the M4RI build, code continuity across lanes (closure.c commits d6a21306ee, a6d3b37e17, 9096320e22 and the later logging fixes), and that restarts, resumes and the pause could not have altered a record.",
 "findings": [
  finding("W7-1", "VERIFIED", "All twelve instances: my own parser of the .ms (variable line, characteristic line, comma-separated polynomials, field equations v^2+v) and the instance JSON give the same polynomial lists (ordered equality), the same canonical system hash, equal to the hash in the JSON file, to the hash of the instance regenerated by boolsys.generate from the recorded (n, m, t, k, B_mode, subspace, seed, draw), and to the lane record's system_sha256 (12/12). Note: the closure ran on the generator's in-memory equations, not on the .ms file; the .ms carries the same n(t-1) equations plus the N field equations, which the closure does not take (implicit Boolean ring).", E("outputs/w7_instances.txt", "outputs/w7_instances.json", "scripts/w7_instances.py")),
  finding("W7-2", "VERIFIED", f"Draw rule: recomputed from RUN-SEMBIN-9bb990/counts for n = 40..45 (low_degree_polynomial, B_random): first solution-free and first solution-bearing draw = the draws that ran in all six lanes (n=40: 0,1; 41: 0,4; 42: 0,1; 43: 5,0; 44: 0,5; 45: 4,0), with the recorded counts. Because the rule consumes the counts of EVERY earlier draw, I recounted all {w7c['n_compared']} draws (6 n x 10 draws) with my independent counter on instances regenerated by the repository generator: {len(w7c['mismatches'])} mismatches with the recorded counts. The rule was applied before any closure (the scheduler reads the counts file; the scheduler log lists the draws before 'start').", E("outputs/w7_drawrule.txt", "outputs/w7_allcounts.txt", "outputs/w7_allcounts.json", "scripts/w7_allcounts.py", "scripts/w7_drawrule.py")),
  finding("W7-3", "VERIFIED", f"Hunk classification and equivalence of the three lane commits. d6a21306ee: dlfcn/m4ri_library logging; structural output check ech_output_ok and lost-pivot check (fault stops the run, no change when they pass); rk<0 handling; and ONE stopping-rule hunk (found_one at the start of an iteration changed from 'rank_>0 && 1 is a pivot' to 'only on resume'), which differs only when 1 is in the span of the generators at iteration 0 or in a resumed basis; it is not a hunk of rows produced, elimination, memory, checkpoint naming or logging, and it is not exercised by the 12 instances (iteration-0 ranks 40..45, 1 enters only after a batch). a6d3b37e17: checkpoint file naming by system hash plus '&& !single_level' on the cleanup (checkpoint management). 9096320e22: batch_for memory accounting and mzd_free(B_) after the products are written (memory). 1c042d5f80: solutions_source label (logging). 5e1aa460cb: per-closure resets of resumed_/ech_faults_ (logging). "
          f"Direct test: closure.c built from each of the four git blobs (sha256 7bb7bfdd.../a499bc29.../a7da1a1f.../fb50e265..., equal to the hashes in the lanes' environment.json and the manifest) on 8 instances at 3 memory caps: {len(w7v_done)} completed (instance, cap, version) runs, differences in std, per-iteration profile, rank, LM digest from the HEAD build: {sum(1 for r in w7v_done if not r['same_as_head_modulo_early_stop'])}.", E("outputs/w7_codeversions.txt", "outputs/w7_codeversions.json", "scripts/w7_codeversions.py")),
  finding("W7-4", "VERIFIED", "Which code produced which record (environment.json against the notes, the lane progress logs and commit times): n=40 d0 ran 2026-10-02T21:35-22:15 on d6a21306ee (committed 2026-10-02 01:36, a6d3b37e17 committed 2026-10-03 00:15), but the lane's environment.json shows a499bc29 (a6d3b37e17) because the lane was relaunched at 2026-10-03T00:16 after a container restart: the NOTES disclose it. n=40 d1 started on d6a21306ee and resumed on a6d3b37e17 at iteration 4 (the launch order in progress.log is consistent). n=41..44: a6d3b37e17 (timestamps all after its commit and before 9096320e22). n=45 d0: a6d3b37e17 until the pause/kill, then 9096320e22 resumed from the D=4 checkpoint (iteration 2, row 56,453 of 59,558) - the record produced across a code change; n=45 d4: 9096320e22. The only change across those boundaries that touches the product loop is the memory accounting, which changes batch sizes, not products (W7-3, W7-5). Each lane re-runs D=2 and D=3 in every launch; the records kept are those of the final launch.", E("outputs/w7_codeversions.txt", "outputs/w8_fields_timing.txt")),
  finding("W7-5", "VERIFIED", "Resume test, replicated and extended (the producer's own test, m4ri_defect_investigation/ckpt_resume_test_*, killed an N=34 closure three times and compared PARTIAL ranks at the memory cap in both runs: neither run completed, so no standard count or digest was compared): " + json.dumps(res_tot) + " . Cross-source observation: the n=45 draw 0 record WAS resumed once (across 9096320e22), and the uninterrupted cross-check (different routine, cap, no checkpoint) reproduced its rank, std, LM digest and profile exactly.", E("outputs/scratch_results/resume.jsonl", "outputs/scratch_results/resume.log", "scripts/w7_resume.py", "scripts/run_resume_matrix.sh")),
  finding("W7-6", "VERIFIED (what the package carries) / not verifiable (what it does not)", "Build provenance of the fixed M4RI. Every 5ed13e closure record and every lane environment.json name the library by path '.../scratchpad/m4ri-20240729/lib/libm4ri-0.0.20240729.so'; the file name carries the release but NO hash of the library, no commit, no configure flags and no make check log is in the package (the NOTES say 'git; make check 15/15'). Independently: I cloned malb/m4ri, checked out release-20240729 (commit d0a1ee18511714a2c33cc0920a068c05c1f0f8fb, 2024-07-29), built with --disable-openmp and ran make check: 15 of 15 PASS (my log is in scratch_results). The producer's scratch clone resolves to the same commit and tag (git log -1 / describe in its directory, read for this purpose only). The producer's installed library hashes to ad69e178... and mine to 93fd6d83...; the .text sections differ (builds are not bit-reproducible and the producer's configure flags are not in the package), so identity of the loaded binary with a clean build of the tag is not established by the package; the check of record is behavioural (below). The manifest's environment.libm4ri_dev still reads the apt package '20200125-1build2' while groebner_engine names 20240729 (DV-2): the per-record m4ri_library field is the authoritative one (32/32 per-D records carry the 20240729 path).", E("outputs/scratch_results/m4ri_release-20240729_build_and_make_check_mine.log", "scripts/01_build_m4ri.sh", "scripts/02_build_libs.sh")),
  finding("W7-7", "VERIFIED", "My builds of count_m2.c and count_chain.c from the repository sources have the same sha256 as the manifest's libcountm2.so (4b6ac998...) and libcountchain.so (5063cf93...): the exact counters are reproducible bit-for-bit from the recorded sources.", E("scripts/02_build_libs.sh")),
 ],
 "failed_attempts_to_break": ["Looked for a .ms that is not the closure's input (none, 12/12); a draw that is not the rule's draw (none, rule and all 60 counts reproduced); a closure.c hunk that changes the rows produced (none; one stopping hunk that the lanes do not exercise); a resume that changes the final digest (none except the early-stop partial rank, which is batch-dependent whether or not a resume occurs)."],
 "weakest_item": "n=45 draw 0 (resumed across a closure.c change): resumed-run invariance holds in my tests incl. a different memory cap, and the uninterrupted cross-check equals the record.",
 "breaking_artifact": None,
}

# ============================================================== W8
dupe_pairs = w8d["pairs"]
three = [p for p in dupe_pairs if p["verdict_bearing_diff"]]
R["joints"]["W8"] = {
 "verdict": "breaks",
 "claim_as_attacked": "Raw-to-summary agreement; the declared design (run count); the 97 duplicate records of 9bb990 resolved by a rule that cannot hide a disagreement; manifest completeness; the disclosed defects exactly as disclosed; controls inventory; resource claims against timing.",
 "breaking_artifact": {
   "criterion_met": "an undisclosed process-wide (here: last-process-only) field that changes a stated value",
   "artifact": ("'wall_s' of a closure that was resumed from a checkpoint counts only the process that finished it, and the manifest's timing.workers for a lane that was relaunched counts only its last launch. Stated values affected: the 'D=4 wall s' column of the NOTES table for n=40 draw 1 (1,748 s; the D=4 closure started 2026-10-02T22:16 and finished 2026-10-03T00:45, about 8,990 s of elapsed time including the container downtime), and for n=45 draw 0 (9,626 s; D=4 first started 2026-10-03T19:34 and finished 2026-10-04T01:03, about 19,700 s elapsed with one kill and a code change); and timing.workers for closure_m2_n40 (1,757 s against 11,398 s from the first launch in progress.log) and closure_m2_n45 (22,675 s against 38,194 s from the first launch in the scheduler/progress logs, which includes the operator pause). "
                "None of this is disclosed in NOTES.md (which discloses the restarts and the two counter defects but not that wall values are post-restart only). No verdict-bearing value is affected."),
   "reproduce": "python3 scripts/w8_fields_timing.py  (outputs/w8_fields_timing.txt)", "evidence": E("outputs/w8_fields_timing.txt", "scripts/w8_fields_timing.py")},
 "findings": [
  finding("W8-1", "VERIFIED", "The 5ed13e results table: my recomputation from the six lanes' results.jsonl equals the NOTES.md table in all 12 rows x 12 columns (0 differing cells); window_table.py's output equals the NOTES rows text-for-text (12/12); results-table.json: all 36 rows equal their lane records field by field (the only extra key is '_worker', added by assemble.load); summary.json: per-cell verdict counts, standard-monomial sets, exact counts and closure_D values equal my recomputation for all six cells; n_records 36 = records in the lanes. Design: six lanes x two instances x three instruments (count, F4-declared-unreached, closure) = 36; closure records carry one per_D entry per degree reached: 10 instances x {2,3,4} and 2 instances x {2} = 32. duplicate_records_resolved 0 is true (no key repeats).", E("outputs/w8_table.txt", "outputs/w8_table.json", "scripts/w8_table.py")),
  finding("W8-2", "VERIFIED", f"Duplicates in 9bb990: assemble.load reads {w8d['records_loaded']} records from 29 lanes; {w8d['duplicated_keys']} keys repeat, {w8d['extra_records']} extra records (= the manifest's 97); by instrument: exhaustive_solution_count 32, f4_trace_msolve 36, closure_certificate 8, macaulay_single_level 2. assemble.dedupe keeps the FIRST record of a key unless the first is not 'ok' and a later one is; it compares nothing, so the rule as written CAN hide a disagreement between two completed records. I compared all 97 pairs field by field: for the 10 closure/single-level pairs the per-D core (D, status, verdict, rank, ncols, std, contains_one, solutions, LM digest, deficiency) is identical; for the exact counts 'solutions' agree in every pair (8 pairs differ only in method/enumeration fields); the kept record is the first in 92 of 97 pairs and the later one in 5. Three pairs differ in verdict-bearing/status fields, all F4 records: " + "; ".join(f"{p['key'][0][:28]} ({p['first_worker']} {p['first_status']} vs {p['later_worker']} {p['later_status']}, kept {p['kept_worker']})" for p in three) + ". These are 'declared unreached' placeholders against a completed or capped F4 run; the rule prefers the completed one. No pair disagrees in a closure or count verdict.", E("outputs/w8_duplicates.txt", "outputs/w8_duplicates.json", "scripts/w8_duplicates.py")),
  finding("W8-3", "VERIFIED", "Manifests. Neither manifest (5ed13e, 9bb990) has an inference block, and no file of either package contains requested_policy, resolved model, backend, effort, fallback or degraded fields (grep over both run directories and the lane environment.json key sets): the known gap is confirmed (AGENTS.md 'Artifact policy' requires them). They also lack the schema's 'resources' and 'artifacts' blocks, record timing only per worker (no run-level started_at/finished_at/wall_seconds) and a result block without metrics/valid/invalid_reason; the strict JSON schema schemas/run-manifest.schema.json would reject them (jsonschema is not installed here; read, not run). The repository's own validator tools/validate_ledger.py (RUN_REQUIRED_TOP = id, experiment_id, status, code, environment, inputs, timing, result, plus companion files) accepts them: it reports 122 new errors repo-wide, none naming RUN-SEMBIN-5ed13e, RUN-SEMBIN-9bb990 or EXP-SEMBIN-7e1371. Remedy named by DEC-20261004-df2986 DV-9 (additive supersession through tools/run_supersession_registry.yaml) applies.", E("outputs/scratch_results/repo_validate_ledger_output.txt")),
  finding("W8-4", "VERIFIED", "Disclosed defects exactly as disclosed: per_D[*].solutions_source reads 'f4_quotient_dimension' in every closure record (checked: all 32 per-D records; top-level solutions_source reads exhaustive_count_chain); checkpoint_resumes for n=45 draw 4 reads 1 at D=2, 3, 4 and its true value is 0 (that process resumed once for draw 0); n=40 d1 (D=4) and n=45 d0 (D=4) carry a true 1. elimination_faults is 0 everywhere. A third field of the same kind: wall_s (see the breaking artifact). dropped_terms_above_D is reset per run (closure_reset_dropped in _run) and max_rows_seen is local to closure_run: not process-wide.", E("outputs/w8_fields_timing.txt")),
  finding("W8-5", "VERIFIED", "Controls inventory: see controls_inventory. 5ed13e ran with --controls none (command lines) and summary.json controls is {}. None of the six contract controls was measured on the fixed library or the PLUQ routine in either run; the n = 40 baseline cell was measured (two draws, sufficient) but not as a control.", E("outputs/w9_classes.txt")),
  finding("W8-6", "VERIFIED", "Resource claims against timing (DV-6). Lane wall clocks in the manifest are 1,757 / 15,405 / 12,422 / 28,192 / 6,193 / 22,675 s against the advisory 5,400 s per run; the memory figure is a configured model cap (11 GiB; cross-checks 10.5 and 11.5, one attempt at 7), not a measurement: no peak RSS is recorded anywhere in the 5ed13e records (the only memory-like per-record field is max_rows_seen, a row count) and the manifest has no resources block, so 'memory alongside time' cannot be reported for this run. Time claims are understated for the two relaunched lanes (breaking artifact).", E("outputs/w8_fields_timing.txt")),
 ],
 "failed_attempts_to_break": ["Looked for a table cell that differs from its lane record: none (W8-1).", "Looked for a duplicate pair that disagrees in a closure or count verdict: none (W8-2)."],
 "corrected_wording": ("Manifest/NOTES: add that 'D=4 wall s' and timing.workers are those of the final launch only for n=40 draw 1, n=45 draw 0 and lanes closure_m2_n40 and closure_m2_n45; and that 11 GiB is a configured cap and peak memory was not recorded. "
                       "assemble.dedupe: it keeps the first record without comparing; the statement 'resolved by a rule that cannot hide a disagreement' is true of the data (checked) and not of the rule."),
}

# ============================================================== W9
R["joints"]["W9"] = {
 "verdict": "breaks",
 "claim_as_attacked": "That the 9bb990 closure and single-level records are rightly labelled invalid-or-unverified for the stated reason; that the diagnosis chain supports the stated cause without claiming more than it isolates; that exact counts are independent of M4RI; which record classes depend on M4RI; whether stopping rule 4 fired.",
 "breaking_artifact": {
   "criterion_met": "a quoted log line that does not say what the notes cite it for (here: a cited line with no log in the package)",
   "artifact": ("NOTES-deviations-and-limitations.md lines 224-241 ('Localised further: the fault is in mzd_echelonize's hand-off, not in PLE') quote '[ech 2 pluq] 199768 x 149986 rank 129376 | in=0 out=0' as the reading of mzd_echelonize_pluq on M4RI 0.0.20200125 on the identical input matrix. No log in the package contains that line with a pluq label. The only package line with these numbers is '[ech 2 default] 199768 x 149986 rank 129376 | ... in=0 out=0' in n44_default_legacy_cap3.5_m4ri-20240729_replay.log (default routine on release-20240729), which the NOTES quote separately at lines 349-351. "
                "The package's own PLUQ-on-20200125 log (n44_pluq_m4ri-20200125_evalcheck_FAILED.log) is a different, later run (elimination 2 is 288,892 x 149,986 with rank 129,383; it fails at elimination 7). The NOTES say the first PLUQ run 'was lost to a container restart after elimination 2'. The same section's conclusion is superseded in the NOTES themselves ('PLUQ is NOT a fix: it fails too'), so the effect on the final classification is nil, but the quote is not backed by an artifact."),
   "reproduce": "python3 scripts/w9_classes.py  (outputs/w9_classes.txt: 'NOT FOUND' for the pluq line at NOTES line 230; grep -rn 129376 over the package)", "evidence": E("outputs/w9_classes.txt", "scripts/w9_classes.py")},
 "findings": [
  finding("W9-1", "VERIFIED", "Quoted lines against the logs: of the 10 '[ech ...]' lines quoted in the NOTES, 9 are found in the package logs with identical rows, columns, rank, in and out (default routine on 20200125: elimination 2 = 199,768 x 149,986, rank 139,898, in=0 out=68,559, '*** ELIMINATION LEFT THE IDEAL ***'; PLUQ on 20200125: elimination 7 = 148,601 x 149,986, rank 139,204, in=0 out=66,598, then '[ckpt] pivot count 131030 != rank 139204; checkpoint NOT written', DONE std=127628 insufficient; 20240729 replay, legacy sizing, cap 3.5: elimination 2 = 199,768 x 149,986, rank 129,376, in=0 out=0; 20240729 verdict run: 22 + 17 = 39 eliminations all in=0 out=0, DONE std=2 |V|=2 sufficient); the tenth is the absent pluq line (breaking artifact). Caveats: the 'identical input matrix' of the replay is identical in dimensions and in the ranks of eliminations 0 and 1, not shown to be identical in content; the evalcheck positive control 'flags 15 violating generators at the first call' has no log in the package (I reproduced the kind at small N: W4-3).", E("outputs/w9_classes.txt")),
  finding("W9-2", "VERIFIED", "Cause: the chain supports 'unsound eliminations occur on M4RI 0.0.20200125 under both mzd_echelonize and mzd_echelonize_pluq, and do not occur on release-20240729 on the same configuration'. It does not isolate a cause inside the library, and the NOTES say so. I opened the upstream source (my clone of malb/m4ri, retrieved): commit 34b1b560e29f0c67f7e5b07d3e767c9dc4784761 (2020-05-14, Martin R. Albrecht, 'fix count for remaining number of rows in a block / fixes #74') changes only m4ri/mzd.h, in mzd_remaining_rows_in_block: it adds M->row_offset to r and removes it from the n == 0 branch; it is not in release-20200125 and is in release-20240729; 58 commits separate the releases (matches the NOTES). "
          "Further facts the NOTES do not state: those 58 commits include the 2021-08/09 refactor that removed the rows[] array and the whole multi-block storage layout ('force a single block', 'get rid of blockrows_log', 'get rid of blocks uglyness for good'; wi_t became 64-bit; also 'ple_russian: actually use a window', 'mzd_ple: actually test it!'), so in release-20240729 mzd_remaining_rows_in_block no longer exists and the regime named in the NOTES (row windows into multi-block matrices) cannot occur; hence 20240729's soundness at this scale is consistent with, but does not isolate, commit 34b1b56. "
          "A function-level test (compiled against the 20200125 headers/library, N=44 geometry: 149,986 columns, 32,768 rows per block, a window with row_offset 32,718): mzd_remaining_rows_in_block returns the right count for window rows in block 0 and over-counts by the row offset for rows in block 1 (32,918 for 32,768; 32,908 for 32,758; 32,569 for 32,419): the 20200125 function IS wrong in that regime. This shows the cited commit fixes a real defect of the kind described; it does not show that this defect produced the bad rows (no elimination was run, and an N=44 run was out of scope). Attribution remains NOT isolated, as the NOTES state; the 'candidate' wording is the most the evidence supports.",
          E("outputs/w9_remaining_rows_test_20200125.txt", "scripts/w9_remaining_rows_test.c")),
  finding("W9-3", "VERIFIED", "Exact counters share no code with the closure and none with each other beyond the idea: count_chain.c and count_m2.c have no includes beyond stdint/string, no M4RI, each defines its own gfmul; they take the field description (modulus, basis, z, B), not the Boolean system. The recorded agreement is weak in the 9bb990 package (cross_check_agrees is recorded on 4 of 269 t=2 count records; most were produced by count_m2 alone, the chain counter at t>=3), but I recounted independently: my counter works on the descended Boolean polynomials (affine-in-x2 solve per x1) and agrees with the recorded exact count on 12/12 window instances and on 60/60 draws (n = 40..45, 10 draws each); the 12 window instances also carry count_m2/count_chain agreement in the 5ed13e records. The exact counts are independent of M4RI.", E("outputs/w9_classes.txt", "outputs/w7_allcounts.txt", "outputs/w4_zeros.txt")),
  finding("W9-4", "VERIFIED", "No record of the 9bb990 package carries 'elimination' or 'm4ri_library' (those per-record fields were added after the run: 0 of the 27+2 closure, 92+10+48 single-level records). Which routine and library produced them rests on the manifest (libm4ri_dev 20200125-1build2; groebner_engine 'libm4ri 20200125 via closure.c'), on the per-worker closure.c hash (all 29 workers: fe52c567..., the git blob of commit bd66d5fa84, whose source calls mzd_echelonize(M,1) directly in both places) and on the NOTES. That chain is sufficient and verified here; it is a weaker form of provenance than the 5ed13e per-record fields.", E("outputs/w9_classes.txt")),
 ],
 "record_classes_and_m4ri_dependence": [
   {"class": "exhaustive_solution_count (291 records; count_chain.c / count_m2.c)", "uses_m4ri": False, "narrowest_label": "valid (independently recounted)"},
   {"class": "f4_trace_msolve (415 records)", "uses_m4ri": False, "narrowest_label": "not affected by the M4RI defect; almost all 'unreached_declared' or capped; the completed ones agree with the closure where both exist"},
   {"class": "closure_certificate chained (27) and matched_null (2)", "uses_m4ri": True, "narrowest_label": "(43,2,2,22) draw 0: CONTRADICTED (invalid); all others: UNVERIFIED on 0.0.20200125 with mzd_echelonize (five 'sufficient by 1 in W_D' records on empty varieties agree with the truth but came through the unsound path; four std = |V| records agree with an independent count); the nine window instances are re-measured in 5ed13e"},
   {"class": "macaulay_single_level (92 chained, 10 null, 48 eq.(4))", "uses_m4ri": True, "narrowest_label": "UNVERIFIED (no contradiction observed; the single-level product logic itself reproduces my independent Macaulay rank in 42/42 small-N runs, but the elimination library is the defective one); the 48 eq.(4) records are structurally empty blocks and do not call M4RI at D=4"},
   {"class": "controls: invalid_input, summation_polynomial_identity", "uses_m4ri": False, "narrowest_label": "valid (python only)"},
   {"class": "control known_false", "uses_m4ri": True, "narrowest_label": "unverified but trivial (closure at D=2, plus an F4 trace that agrees)"},
 ],
 "stopping_rule_4": {
   "text": "'Stop the whole route if the certificate and an affordable Groebner completion disagree anywhere, and report it as a refutation of the certificate method.'",
   "reading": ("Did not fire in the contract's sense. Its condition is a disagreement with an AFFORDABLE Groebner completion. At the contradicted cell (43,2,2,22) no F4 completion was affordable (msolve capped); the contradiction was with exact enumeration (two counters, both solutions substituted back), which is a different instrument. "
               "Where an affordable F4 completion existed the closure agreed with it: (17,3,3,6) draws 0 and 5 (F4 quotient dimension 0 and 6 = closure std 0 and 6, d_F4 = 4), and (12,6,6,2) completed in F4 with the closure unreached. The executor invoked the rule by analogy and stopped, which is a reasonable machine-protection reaction, but the NOTES' sentence 'the contract anticipates it: stopping rule 4 says...' overstates the rule's reach. "
               "What happened is an instrument-validity event: the library, not the method, was traced (W9-2), so a 'refutation of the certificate method' is the wrong reading; the right one is that the 9bb990 closure measurements are invalid or unverified as instrument outputs. Whether continued measurement under v1 is within contract is the Coordinator's decision (DV-8); this report does not make it.")},
 "run_level_label": ("'completed_invalid' for the whole run is broader than the evidence: one closure record is contradicted, the other closure and single-level records are unverified, and the exact counts, F4 traces, structural controls and the eq.(4) records are not affected. The narrowest accurate labelling is per record class (record_classes_and_m4ri_dependence). "
                      "The manifest's own validity reason already scopes it to 'the closure and single-level measurements', and says the exact counts are unaffected; the status word alone does not."),
 "failed_attempts_to_break": ["Looked for an M4RI-free class that uses M4RI: none (the classes marked False do not link libm4ri; single-level on eq.(4) never reaches M4RI because the block is empty).", "Looked for exact counters sharing code with the closure: none."],
 "corrected_wording": ("NOTES lines 224-241: mark the PLUQ-on-20200125 elimination-2 quote as 'observed on screen; log lost with the container restart' or remove it; the replay line it duplicates is the 20240729 default-routine line. "
                       "Heading 'The defect is in M4RI 0.0.20200125 and is fixed upstream' -> 'The unsound eliminations occur on 0.0.20200125 and not on release-20240729; the library is the cause traced; which upstream change is responsible is not isolated (58 commits, including removal of the multi-block layout)'. "
                       "'stopping rule 4 fired' -> 'an instrument-validity contradiction against exact enumeration was found; stopping rule 4 (which names an affordable Groebner completion) was not triggered at any cell where a completion existed'. Run label: record-class labels."),
}

# ============================================================== W10
R["joints"]["W10"] = {
 "verdict": "holds",
 "claim_as_attacked": "That the 92 hash-listed, untracked instance files can be regenerated byte-for-byte from the generator at the recorded code hashes, that every record naming them carries a system hash consistent with the list, and that no claim of Q-A or Q-B depends on a file nobody can open.",
 "findings": [
  finding("W10-1", "VERIFIED", f"Sets and hashes: {w10s['excluded_entries']} listed files = digest paths minus tracked paths (exactly), count and byte total ({w10s['sum_listed_bytes']}) equal the declared values, each listed file > 1 MiB, no tracked file under an instances/ directory exceeds 1 MiB; listed sha256 equals the digest file's value for all 92; every tracked file hashes to its digest entry except task-report.md, which is tracked but absent from artifact-digests.json (post-digest file, already classified in the 208b23 receipt as B_tracked_minus_digest with artifact-digests.json). The 92 files are present on this host and their local sha256 equals the listed value (host-specific evidence, not package evidence).", E("outputs/w10_sets.txt", "outputs/w10_sets.json", "scripts/w10_sets.py")),
  finding("W10-3", "VERIFIED", f"Regeneration of ALL 92 files (not a sample; each took 0.7-9 s): generator = the git blobs whose sha256 equal the manifest's code_sha256 for boolsys.py (55d0063a...) and eq4sys.py (d066299e...) (one version exists in history, commit bd66d5fa84; all 29 workers recorded the same hashes), parameters from the file names; the .json bytes as run_cert.measure writes them (json.dumps(..., sort_keys=True)), the .ms as boolsys.write_msolve writes it. Result: {w10a['sha256_equal']} of {w10a['files_regenerated']} regenerated files have the listed sha256 and byte size ({w10a['distinct_instances_covered']} instances). No regeneration failed, so there is no provenance defect to attribute.", E("outputs/w10_regen_all92.txt", "outputs/w10_analysis.json", "scripts/w10_regen.py", "scripts/w10_analyze.py"),
          "cd $SP/work && python3 $WS/scripts/w10_regen.py $(seq 0 91)"),
  finding("W10-2", "VERIFIED", "Records naming the systems: all 92 files belong to 48 eq.(4) control instances under light_controls (44 with both .ms and .json listed, 4 with only the .ms); the records that name them are 48 f4_trace_msolve (declared unreached; the .ms was written, no solver was run on it) and 48 macaulay_single_level records. For each, the record's system_sha256 equals the canonical hash of the REGENERATED system, and the f4 record's msolve_input_sha256 equals the listed sha256 of the .ms (48/48). No record names a hash that is not accounted for. The list carries file hashes, not system_sha256, so 'present in the list' is checked through msolve_input_sha256 (.ms) and through regeneration (.json).", E("outputs/w10_analysis.json", "outputs/w10_sets.json")),
  finding("W10-4", "VERIFIED", "Dependence: all 92 listed files are eq.(4) nearby-object control inputs (no chained-cell file is among them; the card's 'one chained-cell file' item does not apply). No closure record, no Q-A record and none of the 12 window instances rests on them. For Q-B the only statements that touch them are the nearby_object control (eq.(4) at m=3 has degree 6, the degree-4 block is empty; recorded per instance) and the 'bytes that ran' claim for the 48 single-level records; both are regenerable and now byte-checked. Nobody needs to open the files for any statement of Q-A or Q-B.", E("outputs/w10_analysis.json")),
 ],
 "failed_attempts_to_break": ["Looked for a regenerated file whose sha256 differs with the generator at the recorded hash: 0 of 92.", "Looked for a record naming a system hash that is not listed/accounted for: none.", "Looked for a claim resting on a file that is neither tracked nor regenerable: none."],
 "breaking_artifact": None,
}

# ---------------------------------------------------------------- composed sections
R["controls_inventory"] = {
 "note": "The six contract controls of EXP-SEMBIN-7e1371 v1: where each was measured, on which M4RI and routine, and whether comparable to the 5ed13e instrument (M4RI release-20240729, mzd_echelonize_pluq, structural check). RUN-SEMBIN-5ed13e ran with --controls none and summary.json controls = {} (VERIFIED).",
 "table": [
  {"control": "baseline (diagonal cells n=17 and n=40 must be sufficient; F4 trace at n=17 returns 4)", "where": "9bb990: closure_sw_n17k6 / soundness_n17k6 for (17,3,3,6) (draws 0 and 5: sufficient; F4 completed with d_F4 = 4 and quotient dimension 0 and 6 = closure std); closure_m2_n40 draw 0 for (40,2,2,20) (sufficient, 1 in W, partial rank 101931). 5ed13e: (40,2,2,20) draws 0 and 1 sufficient (measured, not run as a control).", "library_and_routine": "9bb990: M4RI 0.0.20200125, mzd_echelonize (legacy), closure.c bd66d5fa84; 5ed13e: 20240729 + PLUQ", "comparable_to_5ed13e": "n=17: no (different library/routine; a single check on 20240729 exists only in a commit message of 9096320e22, not in the package). n=40: the 5ed13e measurement is itself the cell, but not a control run."},
  {"control": "nearby_object (eq.(4) must be insufficient at every cell)", "where": "9bb990 light_controls: 48 eq.(4) instances, single-level D=3,4 and F4 declared unreached; at m=3 the generators have degree 6 > 4, so the degree-4 block is empty (rank 0). At m=2, eq.(4) is byte-identical to eq.(5) at t=2 (per NOTES).", "library_and_routine": "no M4RI call at D=4 (empty block); closure not applicable", "comparable_to_5ed13e": "structurally yes (it does not depend on the elimination), but it does not exercise the instrument: it 'passes' because the block is empty, not because a certificate returned insufficient"},
  {"control": "matched_null (must be insufficient at every k)", "where": "9bb990: null_closure (17,3,3,6) and (40,2,2,20), closure; null_single: single-level at the m=2 window and the n=17 sweep.", "library_and_routine": "M4RI 0.0.20200125, mzd_echelonize", "comparable_to_5ed13e": "no. The closure verdicts are 'undetermined' (|V| not available for a null system), which is reported honestly but does not demonstrate the required 'insufficient'; the task-report's remark that this 'does not trip the stopping rule' is correct and does not discharge the control."},
  {"control": "certificate_soundness (certificate vs affordable Groebner completion must agree)", "where": "9bb990 soundness_n12k2, n13k4, n17k6, n19k7: F4 completed with a verdict only at (17,3,3,6) draws 0 and 5 (agree) and (12,6,6,2) (closure unreached); n13k4 and n19k7: F4 capped, closure std = exact |V| (24, 15).", "library_and_routine": "M4RI 0.0.20200125, mzd_echelonize", "comparable_to_5ed13e": "no"},
  {"control": "known_false (planted degree-2 solution decided at D=2)", "where": "9bb990 controls/cells/controls.json: closure_D = 2 (expected 2), F4 d_F4 = 2 (naive 2); passed.", "library_and_routine": "closure at D=2 on 0.0.20200125", "comparable_to_5ed13e": "no; trivial at this size"},
  {"control": "invalid_input (k = 0 and t > m rejected)", "where": "9bb990 controls.json: both rejected by the generator; passed.", "library_and_routine": "python only", "comparable_to_5ed13e": "yes (no instrument involved)"},
 ],
 "not_contract_controls_but_relevant": [
  "evaluation check with a deliberately wrong witness (NOTES: 15 violating generators): no log in the package; reproduced the kind at small N (W4-3).",
  "replay on release-20240729 of the failing configuration (log present) and the N=44 verdict run on 20240729 with the evaluation check on every elimination (log present): the nearest thing to a positive control on the fixed library, one instance.",
  "summation_polynomial_identity (S_3, S_4 against the group law at n = 13, 17, 21): passed, python only."],
 "reading": "No contract control was measured on the 5ed13e instrument. The 9bb990 control measurements that used M4RI used the library the same package classifies as UNVERIFIED. Comparability of any control to 5ed13e is therefore NOT established (DV-5 confirmed, not overstated by the notes).",
}

R["corrected_wordings"] = [
 {"where": "Q-A (card)", "text": R["joints"]["W5"]["corrected_wording_for_Q_A"]},
 {"where": "NOTES.md 5ed13e, evaluation check", "text": R["joints"]["W4"]["corrected_wording"]},
 {"where": "NOTES.md 5ed13e table and manifest timing", "text": R["joints"]["W8"]["corrected_wording"]},
 {"where": "NOTES-deviations 9bb990, M4RI diagnosis and stopping rule 4", "text": R["joints"]["W9"]["corrected_wording"]},
 {"where": "NOTES.md 5ed13e, cross-check provenance", "text": "State that the evalcheck libraries used by crosscheck_n44_d5 and crosscheck_n45_d0 and their closure.c hash are not part of the package, and that the logs do not record them."},
 {"where": "manifest.yaml environment.libm4ri_dev (both runs)", "text": "Name the apt package as 'not the library that ran'; the per-record m4ri_library field is authoritative (5ed13e). For 9bb990 no per-record field exists."},
]

R["citation_provenance"] = [
 {"claim": "M4RI commit 34b1b56 (2020-05-14, 'fix count for remaining number of rows in a block', fixes #74) exists, touches only m4ri/mzd.h (mzd_remaining_rows_in_block), is in release-20240729 and not in release-20200125; 58 commits separate the two releases; the 2021 refactor removed the multi-block layout", "provenance": "retrieved", "verified_by": "this validator session (git clone https://github.com/malb/m4ri; git show, git log, git rev-list --count release-20200125..release-20240729)", "load_bearing_for": "W9"},
 {"claim": "M4RI issue #74 is titled 'A bug with mzd_ple()'", "provenance": "recalled (from the 9bb990 NOTES; the issue tracker was not opened; the commit message only says 'fixes #74')", "verified_by": None, "load_bearing_for": "nothing in this report"},
 {"claim": "release-20240729 make check 15/15", "provenance": "retrieved for MY build (my log); the producer's '15/15' is an unlogged claim in the package", "verified_by": "this validator session", "load_bearing_for": "W7-6"},
 {"claim": "Dispatch preconditions, DV-1..DV-9 and the stopping-rule text", "provenance": "internal (specification.yaml, DEC-20261004-df2986, TASK-20260917-b2bf32)", "verified_by": "read directly", "load_bearing_for": "W8, W9"},
 {"claim": "In a finite Boolean ring every ideal is the vanishing ideal of its zero set", "provenance": "recalled textbook fact, checked empirically at N=12 and N=14 (rank of I = 2^N - |V|)", "verified_by": "this validator session (scratch)", "load_bearing_for": "a suggestion in W4-7 only"},
]

R["artifact_checks"] = [
 {"check": "package artifacts, hashes and counts", "result": "5ed13e: manifest, summary, results-table, six lanes (records, instances .ms/.json, logs, LANE_COMPLETE), two cross-check directories, scheduler files present; 9bb990: 976 tracked + 92 hash-listed files, exclusion list = digest minus tracked (W10-1)."},
 {"check": "command, revision, dirty-tree, environment", "result": "5ed13e manifest code.commit 5e1aa460cb..., dirty false, code_changed_during_run true (per-lane hashes match git blobs, W7-3/W7-4); 9bb990 manifest commit 51d7e648..., dirty true, per-worker closure.c = blob of bd66d5fa84; both lack an inference block (W8-3)."},
 {"check": "seeds and instances", "result": "12/12 .ms/json/generator/record hashes agree; draw rule and 60 counts reproduced (W7-1, W7-2)."},
 {"check": "resource records", "result": "wall clock per lane present; understated for relaunched lanes; no peak memory recorded (W8-6)."},
]
R["metric_recomputations"] = [
 {"metric": "5ed13e results table (12 rows)", "result": "recomputed, 0 differing cells (W8-1)"},
 {"metric": "exact |V| for 12 window instances and 60 draws", "result": "recounted independently, 72 comparisons (12 + 60, overlapping instances counted once in the 60), 0 mismatches (W4-2, W7-2)"},
 {"metric": "cross-check equality (rank, std, verdict, LM digest, profile)", "result": "recomputed by parsing, equal (W6-2)"},
 {"metric": "closure rank / std / LM list on small instances", "result": f"{unm['completed']} unmutated runs equal an independent reference (W5)"},
]
R["control_checks"] = [{"control": "positive and negative controls of the evaluation check and of the product-completeness checks", "result": "positive control flags; necessary-only control stays clean; bulk-corruption control: every trial with at least half as many injected flips as output rows flagged (168/168), smaller corruptions pass in a fraction of trials, size dependence stated (W4-4, W4-8); mutants MA/MB/MC/MD/MI detected by reference/verifier, producer procedure flags none (W4, W5)"},
                       {"control": "contract controls inventory", "result": "see controls_inventory (none on the fixed instrument)"}]
R["heuristic_validation_checks"] = "not applicable: instrument-validity review; no heuristic distribution, pre-registered prediction or correspondence is under test in these joints (the specification's prediction is outside this card)."
R["cost_model_checks"] = "not applicable beyond DV-6 resource claims, reported in W8-6 (no unit-bearing cost table is under review)."
R["proof_architecture_checks"] = "not applicable; no proof-oriented proposal is under review. The method-ceiling/nearby-object analogue for the argument 'both elimination routines agree, hence sound' was run as a proves-too-much control: the same argument goes through on mutants that drop products (MA, MB_s32, MC, MD), where its conclusion (complete) is KNOWN FALSE; so the argument establishes at most soundness-type agreement, never completeness (W5)."

R["deviations_and_disclosures"] = [
 "Blindness: I did not open the plan file, DEC-20261004-a47503, TASK-20261004-095926 or anything under reviews/TASK-20261004-095926/. Encounters that are NOT opens: (a) a directory listing of coordination/goals/GOAL-SEMBIN-5078bc/reviews/ and of the goal directory showed names only (earlier rounds' task directories and the existence of review-plans/); (b) a listing of the shared scratchpad directory showed the names of other sessions' files (including names suggesting the Coordinator's and the blind lane's work, e.g. blind_sandbox, blind_pairs.json); I opened none of them; (c) ps output listed another session's command line (run_all_closures.sh, run_instance.py on a 5ed13e .ms file name); I did not follow it. I read no report of the sibling.",
 "Reads outside the declared input list, with reasons: (i) the producer's loaded M4RI library file (path recorded in every 5ed13e record) was hashed in place and the git metadata of the producer's m4ri clone (git log -1 / describe) was read, to check the identity of the library named by the records (W7-6); (ii) the producer's scratch directory names were listed. Nothing else in the producer's scratchpad was opened. Additionally read for the card's purposes: tools/validate_ledger.py (RUN_REQUIRED_TOP, check_run), schemas/run-manifest.schema.json, templates/research-records.md (attestation), tools/check_review_independence.py, tools/allocate_id.py (help), git history of the code directory and of the cited M4RI commits.",
 "Constraint touched: the card forbids re-running any window-scale (N >= 40) closure. To size my reference tool I ran my own reference closure (not closure.c) once on the n=45 draw 0 system at D=2 and D=3 (0.02 s and 0.65 s, ~30 MB; ranks 90 and 8,465, equal to the lane's D=2/D=3 records). These are not the D=4 closure and could not affect the blind lane's memory; I report them as a borderline action and used them for nothing in any verdict. I did not repeat them for other instances and ran no other computation at N >= 40 apart from instance generation/parsing/counting (zero counters and regeneration are not closures).",
 "The shared scratchpad path named in the task prompt already held the producer's and Coordinator's files; my own work is under .../scratchpad/v7d2fb6/ (binaries, bulk) and this write scope (scripts, outputs). The refclos binary used in the early campaigns was built before two additive edits to refclos.cpp (the MAXMU environment variable and a 'macaulay' mode); behaviour with MAXMU unset and in the other modes is unchanged.",
 "Model: the session's resolved model is recorded in the attestation block of this report; the card asks for the review-adversarial policy with fallback not allowed; no fallback was used. Session reasoning effort cannot be independently verified from inside the session and is not asserted.",
]
R["limitations"] = [
 "W5 'holds' is about closure.c's product logic over N <= 26 (and degree 6/7 at N = 12): there is no N >= 40 closure in my evidence, the final bases of the three window insufficient records are not archived, and they are too large to saturate-check here (a 166,705 x 179,447 basis is ~3.7 GB dense). The extension to window scale rests on the absence of N-dependent product logic (only batch sizing and memory accounting scale), the guard tests at N = 40..62 and the equal-code check across the lane commits. The blind lane is the independent check at scale.",
 "The five solution-free sufficient records (n=40 d0, n=41 d0, n=43 d5 at D=4; n=42 d0, n=44 d0 at D=2) have no witness: 1 in W_D at scale is protected only by the structural check and the fixed library. A reference closure at D=2 for the last two is a millisecond computation but N = 42/44, so I did not run it; the Coordinator or the blind lane can.",
 "Small-N mutants are absorbed by redundancy unless they remove almost an iteration or a structural class (dose-response); the verifier's power against a rare defect that removes a handful of products that are the only source of a pivot is not measured here (such losses did not occur in 212 block-drop runs, including all single-product positions sampled).",
 "W4-4/W4-5/W4-8 controls were run at N = 16..20; detection rates at the window depend on the witness weight and are a computed model there (no corruption was injected into any window-scale run: that is an N >= 40 closure this card forbade).",
 "The library actually loaded by the producer (hash ad69e178...) was not shown to be a clean build of the tag; behavioural evidence at scale is the producer's own cross-checks (two instances) and the n=44 20240729 verdict run.",
 "W9-2's function-level test shows a real defect in 20200125's inline function in the relevant geometry; it does not attribute the observed bad rows to it.",
]
R["how_to_reproduce"] = [
 "cd <repo>; . coordination/goals/GOAL-SEMBIN-5078bc/reviews/TASK-20261004-7d2fb6/scripts/00_env.sh   (sets WS, SP, CODE, M4RI_PREFIX, 3 GB ulimit)",
 "bash $WS/scripts/01_build_m4ri.sh  (clone malb/m4ri, checkout release-20240729, autoreconf, configure --disable-openmp, make check, install into $SP/m4ri_prefix); bash $WS/scripts/02_build_libs.sh; bash $WS/scripts/03_prodcopy.sh; g++ -O2 -std=c++17 -o $SP/work/refclos $WS/scripts/refclos.cpp; gcc -O2 -o $SP/work/vcount_ms $WS/scripts/vcount_ms.c",
 "bash $WS/scripts/04_gen_instances.sh; python3 $WS/scripts/make_mutants.py; then the campaigns as in outputs/scratch_results/*.log headers: w5_campaign.py, w5_xproc.py (see scripts/ headers), run_resume_matrix.sh, run_doseresponse*.sh, w4_controls.py, w4_bulk_scale.py, guards_test.c (gcc -w -I$SP/work/build -I$M4RI_PREFIX/include ...), w5_order_control.py, w5_singlelevel.py, w7_codeversions.py",
 "package-reading scripts (no build needed): w6_parse_crosschecks.py, w6_lmhash_and_table.py, w7_instances.py, w7_drawrule.py, w7_allcounts.py, w8_table.py, w8_duplicates.py, w8_fields_timing.py, w9_classes.py, w10_sets.py, w10_regen.py, w10_analyze.py; then bash scripts/99_collect.sh; python3 scripts/build_report.py",
]
R["external_scratch_binaries_sha256"] = binaries
R["files_sha256"] = {"note": "sha256 of every file of the write scope except this report, at report time. The scripts directory includes this report's own builder (scripts/build_report.py).", "files": files}
R["artifact_paths"] = ["coordination/goals/GOAL-SEMBIN-5078bc/reviews/TASK-20261004-7d2fb6/"]
R["verdict"] = "incomplete"
R["verdict_note"] = ("Terminal validator status of THIS task as to admissibility of the receipts: incomplete, because the report covers the seven joints W4-W10 of the card only (any other joint of the round, and the composition of verdicts, belong to other sessions and to the Coordinator) and the card forbids a whole-claim verdict. "
                      "It is not 'passed' (two joints break), not 'failed' or 'invalid' (neither break changes a verdict-bearing value), and it is not a verdict on Q-A or Q-B. The per-joint mapping in joint_verdicts is the result the card asked for.")

RA = "review_" + "attestation"
R[RA] = {
 "task_id": "TASK-20261004-7d2fb6",
 "role": "validator",
 "joints_owned": ["W4", "W5", "W6", "W7", "W8", "W9", "W10"],
 "sources_read": [
  "ledger/handoffs/TASK-20261004-7d2fb6.yaml", "agents/validator.md", "AGENTS.md", "CLAUDE.md (supplied in the session context)",
  "experiments/EXP-SEMBIN-7e1371/specification.yaml",
  "experiments/EXP-SEMBIN-7e1371/code/closure.c", "experiments/EXP-SEMBIN-7e1371/code/closure_cert.py", "experiments/EXP-SEMBIN-7e1371/code/boolsys.py", "experiments/EXP-SEMBIN-7e1371/code/eq4sys.py",
  "experiments/EXP-SEMBIN-7e1371/code/run_cert.py", "experiments/EXP-SEMBIN-7e1371/code/run_wrapper.py", "experiments/EXP-SEMBIN-7e1371/code/solcount.py", "experiments/EXP-SEMBIN-7e1371/code/count_m2.c",
  "experiments/EXP-SEMBIN-7e1371/code/count_chain.c", "experiments/EXP-SEMBIN-7e1371/code/soundness_probe.py", "experiments/EXP-SEMBIN-7e1371/code/assemble.py", "experiments/EXP-SEMBIN-7e1371/code/Makefile",
  "experiments/EXP-SEMBIN-7e1371/code/ (grep only: f4_trace.py, gf2_echelon.c; hashed only: the other files)",
  "experiments/EXP-SEMBIN-7e1371/runs/RUN-SEMBIN-5ed13e/ (NOTES.md, manifest.yaml, summary.json, results-table.json, environment.json, command.txt, closure_m2_n40..n45/{cells/results.jsonl, cells/progress.log, cells/instances/*, environment.json, command.txt, stderr.log, LANE_COMPLETE}, crosscheck_n44_d5/*, crosscheck_n45_d0/*, schedulers/{window_sched.py, window_table.py, window_sched.log})",
  "experiments/EXP-SEMBIN-7e1371/runs/RUN-SEMBIN-9bb990/ (NOTES-deviations-and-limitations.md, task-report.md, manifest.yaml, artifact-digests.json, excluded-large-instances.json, m4ri_defect_investigation/*, counts/cells/results.jsonl, controls/cells/controls.json, every lane's cells/results.jsonl and command.txt; the 92 untracked instance files were hashed, not opened)",
  "ledger/decisions/DEC-20261004-df2986.yaml (lines 100-360)", "ledger/decisions/DEC-20261004-6ac6bc.yaml (lines 1-140)", "ledger/handoffs/TASK-20260917-b2bf32.yaml",
  "ledger/handoffs/TASK-20261004-208b23.yaml (lines 1-60)", "ledger/handoffs/TASK-20261004-342564.yaml (lines 1-40)", "ledger/goals/GOAL-SEMBIN-5078bc/checkpoints/BATCH-9d649f-DEC-20261004-6ac6bc.yaml (lines 1-50)",
  "coordination/goals/GOAL-SEMBIN-5078bc/archives/TASK-20261004-208b23/snapshot-receipt.yaml (grep only)", "tools/run_supersession_registry.yaml (grep only)",
  "tools/validate_ledger.py (RUN_REQUIRED_TOP, check_run; executed read-only)", "schemas/run-manifest.schema.json", "templates/research-records.md (attestation and plan sections)", "tools/check_review_independence.py (read; not run)", "tools/allocate_id.py (help)",
  "git history of experiments/EXP-SEMBIN-7e1371/code/ (commits bd66d5fa84, d6a21306ee, a6d3b37e17, 9096320e22, 1c042d5f80, 5e1aa460cb)",
  "external: clone of https://github.com/malb/m4ri (retrieved by git), the producer's loaded libm4ri-0.0.20240729.so (hashed) and its scratch clone's git metadata (git log -1, describe)",
  "coordination/goals/GOAL-SEMBIN-5078bc/reviews/ and the scratchpad directory: LISTINGS of names only, no file opened"],
 "read_sibling_reports": False,
 "independent_session": True,
 "requested_policy": "review-adversarial",
 "resolved_model_id": "claude-sonnet-5-5",
 "fallback": {"used": False, "reason": None},
 "reasoning_effort": "not independently verifiable from inside the session; the card carries null (policy default)",
 "verdicts": {"W4": "holds", "W5": "holds", "W6": "holds", "W7": "holds", "W8": "breaks", "W9": "breaks", "W10": "holds"},
 "blindness_statement": ("The review plan file (coordination/goals/GOAL-SEMBIN-5078bc/review-plans/REVIEW-SEMBIN-20261004-a47503.yaml), DEC-20261004-a47503, ledger/handoffs/TASK-20261004-095926.yaml and the directory "
                         "coordination/goals/GOAL-SEMBIN-5078bc/reviews/TASK-20261004-095926/ were NOT opened before this report was written, and no other reviewer's report or output was read. "
                         "Encounters that were not opens, disclosed because the card asks for them: directory listings (names only) of coordination/goals/GOAL-SEMBIN-5078bc/reviews/ and of the goal directory; a listing of the shared scratchpad directory whose names include files of other sessions "
                         "(among them names that suggest the blind lane's work, for example blind_sandbox and blind_pairs.json), none opened; and a process listing that showed another session's command line (run_all_closures.sh, run_instance.py on a window .ms file), not followed. "
                         "The path of the plan file and the identifiers DEC-20261004-a47503 and TASK-20261004-095926 are on my own card, which names them as forbidden."),
 "no_second_attestation": "this block is the only attestation key under the write scope: no scratch file of the write scope contains the key name (checked by a text search of every file)",
}

class NoAlias(yaml.SafeDumper):
    def ignore_aliases(self, data): return True
text = yaml.dump(report, Dumper=NoAlias, sort_keys=False, width=10**6, allow_unicode=True, default_flow_style=False)
open(f"{WS}/validation_report.yaml", "w").write(text)
# self-checks
chk = yaml.safe_load(open(f"{WS}/validation_report.yaml"))
assert set(chk["validation_report"][RA]["verdicts"]) == {"W4", "W5", "W6", "W7", "W8", "W9", "W10"}
n_att = 0
for p in glob.glob(f"{WS}/**/*", recursive=True):
    if os.path.isfile(p) and p.endswith((".yaml", ".yml")):
        n_att += open(p).read().count(RA + ":")
n_any = sum(1 for p in glob.glob(f"{WS}/**/*", recursive=True) if os.path.isfile(p) and p != f"{WS}/validation_report.yaml" and RA.encode() in open(p, "rb").read())
print("report written:", len(text), "bytes; files hashed:", len(files), "; attestation keys in YAML files under the write scope:", n_att, "(must be 1); other files containing the key name:", n_any, "(must be 0)")
