#!/usr/bin/env python3
"""w5_campaign.py -- joint W5: unmutated closure.c and mutants versus my own reference closure and saturation verifier.

For each instance (generated by the repository generator, scratch, small N) and each library variant and each memory cap:
  * run the closure in a fresh process (w5_worker.py),
  * compare rank, standard-monomial count (independently computed by SOS-DP in refclos) and the leading-monomial LIST with
    the reference closure (refclos closure) -- which implements the card's statement literally,
  * for N <= SAT_N also write the final basis rows and run the saturation verifier (refclos saturate): every echelon vector r
    of the span and every mu with 1 <= |mu| <= D - deg(LM r) must give mu*r reducing to 0 modulo the span.
Output: one JSON line per (instance, variant, cap) in OUTFILE. SCRATCH, TASK-20261004-7d2fb6.
Usage: w5_campaign.py OUTFILE VARIANTS CAPSPEC INSTANCE...
  VARIANTS  comma list among: orig,STRESS32,MA,MB,MC,MD,MF,MG,MH  (suffix _s32 selects the lowered-threshold build of a mutant)
  CAPSPEC   comma list of cap values in GiB, or xF = F * ncols^2/8 bytes (e.g. x4,x8,x30,2.0)
  INSTANCE  file stem in $SP/work/inst (json with N, equations, V) plus optional ':D' (default 4)
"""
import sys, os, json, subprocess, hashlib
SP, WS = os.environ["SP"], os.environ["WS"]
W = f"{SP}/work"
SAT_N = int(os.environ.get("SAT_N", "20"))

def lib_path(v):
    if v == "orig": return f"{W}/build/libclosure_orig.so"
    if v == "STRESS32": return f"{W}/mut/libclosure_STRESS32.so"
    return f"{W}/mut/libclosure_{v}.so"

def sh(cmd, **kw):
    return subprocess.run(cmd, shell=True, capture_output=True, text=True, **kw)

def reference(stem, D):
    base = f"{W}/ref/{stem}.D{D}"
    os.makedirs(f"{W}/ref", exist_ok=True)
    if not os.path.exists(base + ".stats"):
        r = sh(f"{W}/refclos closure {W}/inst/{stem}.sys {D} {base}")
        assert r.returncode == 0, r.stderr
    st = dict(kv.split("=") for kv in open(base + ".stats").read().split())
    lms = [int(x) for x in open(base + ".lm").read().split()]
    return {"rank": int(st["rank"]), "std": int(st["std"]), "contains_one": int(st["contains_one"]), "products": int(st["products"]),
            "overflow": int(st["overflow_terms"]), "lm": lms, "stats": st}

def sysfile(stem):
    p = f"{W}/inst/{stem}.sys"
    if not os.path.exists(p):
        raise SystemExit(f"missing {p}; run gen_small.py first")
    return p

def main():
    out, variants, capspec = sys.argv[1], sys.argv[2].split(","), sys.argv[3].split(",")
    insts = sys.argv[4:]
    fh = open(out, "a")
    for spec in insts:
        stem, _, dd = spec.partition(":"); D = int(dd) if dd else 4
        s = json.load(open(f"{W}/inst/{stem}.json")); V = s["V"]
        sysfile(stem)
        ref = reference(stem, D)
        # statement-level verdict from the reference
        rv = ("sufficient" if ref["std"] == V else "insufficient" if ref["std"] > V else "impossible")
        from math import comb
        ncols = sum(comb(s["N"], d) for d in range(D + 1))
        # a spec 'xF' means F * ncols^2/8 bytes (the PLUQ workspace scale), expressed in GiB; a plain number is GiB
        caps = [(float(c[1:]) * ncols * ncols / 8 / 2**30 if c.startswith("x") else float(c)) for c in capspec]
        for v in variants:
            for cap in caps:
                rows_out = f"{W}/rows_{stem}_{v}_{cap}.bin" if s["N"] <= SAT_N else None
                r = sh(f"python3 {WS}/scripts/w5_worker.py {lib_path(v)} {W}/inst/{stem}.json {D} {cap} {rows_out or ''}")
                if r.returncode != 0:
                    rec = {"instance": stem, "variant": v, "cap": cap, "error": r.stderr[-300:]}
                else:
                    rec = json.loads(r.stdout.strip().splitlines()[-1])
                    rec.update({"instance": stem, "variant": v, "D": D, "N": s["N"], "V": V})
                    if rec["rc"] == 0:
                        lm = [int(x) for x in open(f"{W}/inst/{stem}.json.lm_last").read().split()] if rec["rank"] else []
                        # leading-monomial LIST of a run that stopped at 1 is the partial basis; compare only for complete runs
                        rec["ref_rank"], rec["ref_std"], rec["ref_one"], rec["ref_verdict"] = ref["rank"], ref["std"], ref["contains_one"], rv
                        rec["rank_equal"] = (rec["rank"] == ref["rank"])
                        rec["std_equal"] = (rec["std"] == ref["std"])
                        rec["lm_equal_as_set"] = (sorted(lm) == sorted(ref["lm"]))
                        rec["lm_equal_in_order"] = (lm == ref["lm"])
                        rec["lm_sha256"] = rec.get("lm_sha256")
                        myverdict = ("sufficient" if (rec["contains_one"] and V == 0) else
                                     "impossible" if rec["contains_one"] else
                                     "sufficient" if rec["std"] == V else "insufficient" if rec["std"] > V else "impossible")
                        rec["verdict_variant"] = myverdict
                        rec["verdict_equal"] = (myverdict == rv)
                        if rows_out and os.path.exists(rows_out):
                            q = sh(f"{W}/refclos saturate {W}/inst/{stem}.sys {D} {rows_out}")
                            rec["saturate"] = q.stdout.strip()
                            kv = dict(x.split("=") for x in q.stdout.split())
                            rec["saturation_violations"] = int(kv["saturation_violations"]); rec["gens_not_in_span"] = int(kv["gens_not_in_span"])
                            os.remove(rows_out)
                fh.write(json.dumps(rec) + "\n"); fh.flush()
                flag = ""
                if "error" in rec: flag = "ERROR"
                elif rec["rc"] != 0: flag = f"rc={rec['rc']}(not completed)"
                else:
                    bad = []
                    partial = rec["contains_one"] and rec["rank"] < rec["ncols"]   # 1 entered W: closure.c stops early, rank is the partial rank
                    rec["early_stop_partial_rank"] = bool(partial)
                    if not rec["rank_equal"] and not partial: bad.append("RANK")
                    if not rec["std_equal"]: bad.append("STD")
                    if not rec["lm_equal_as_set"] and not partial: bad.append("LM")
                    if not rec["verdict_equal"]: bad.append("VERDICT")
                    if rec.get("saturation_violations"): bad.append(f"SAT{rec['saturation_violations']}")
                    flag = "match" if not bad else "DIFF:" + ",".join(bad)
                print(f"{stem:34s} {v:9s} cap={cap:<7g} batches={rec.get('batches','-'):>3} rank={rec.get('rank','-')}/{rec.get('ref_rank','-')} "
                      f"std={rec.get('std','-')}/{rec.get('ref_std','-')} {flag}", flush=True)

if __name__ == "__main__":
    main()
