#!/usr/bin/env python3
"""w7_allcounts.py -- joint W7 (2) extension: the draw rule picks the first solution-free and first solution-bearing draw FROM THE EXACT COUNTS, so every earlier draw's count must be right.
Independently recount ALL 60 draws (n = 40..45, draws 0..9, low_degree_polynomial, B_random: Table 2 convention) with my own zero counter (vcount_ms, working on the Boolean polynomials of the
instance regenerated by the repository generator) and compare with RUN-SEMBIN-9bb990/counts. Writes outputs/w7_allcounts.json. About 5-15 minutes."""
import sys, os, json, subprocess, hashlib, time, collections
REPO = "/home/user/crypto-autoresearcher"; WS, SP = os.environ["WS"], os.environ["SP"]
sys.path.insert(0, os.environ["CODE"]); sys.path.insert(0, f"{REPO}/harness/macaulay_fp/fixtures")
import boolsys
SEEDS = [20260913101, 20260913102, 20260913103, 20260913104, 20260913105]
C = f"{REPO}/experiments/EXP-SEMBIN-7e1371/runs/RUN-SEMBIN-9bb990/counts/cells/results.jsonl"
recorded = {}
for l in open(C):
    r = json.loads(l)
    if r.get("instrument") == "exhaustive_solution_count" and r.get("subspace") == "low_degree_polynomial" and r.get("B_mode") == "B_random" and r.get("m") == 2:
        recorded[(r["n"], r["draw"])] = r["solutions"]
out = []; bad = []
for n, k in [(40, 20), (41, 21), (42, 21), (43, 22), (44, 22), (45, 23)]:
    for draw in range(10):
        t0 = time.time()
        inst = boolsys.generate(n, 2, 2, k, "B_random", "low_degree_polynomial", SEEDS[draw % 5], draw)
        N = inst["N"]; sysf = f"{SP}/work/cnt_{n}_{draw}.sys"
        with open(sysf, "w") as fh:
            fh.write(f"{N} {len(inst['equations'])}\n")
            for e in inst["equations"]: fh.write(f"{len(e)} " + " ".join(map(str, e)) + "\n")
        r = subprocess.run([f"{SP}/work/vcount_ms", sysf], capture_output=True, text=True)
        os.remove(sysf)
        cl = [l for l in r.stdout.splitlines() if l.startswith("COUNT")][0].split()
        mine = int(cl[1]); rec = recorded.get((n, draw))
        out.append({"n": n, "draw": draw, "mine": mine, "recorded": rec, "equal": mine == rec, "seconds": round(time.time() - t0, 1)})
        if mine != rec: bad.append(out[-1])
        print(f"n={n} draw={draw} mine={mine} recorded={rec} {'ok' if mine == rec else 'MISMATCH'} ({out[-1]['seconds']}s)", flush=True)
json.dump({"results": out, "mismatches": bad, "n_compared": len(out)}, open(f"{WS}/outputs/w7_allcounts.json", "w"), indent=1)
print("compared", len(out), "draws; mismatches:", len(bad))
