import hashlib, json, datetime
d = json.load(open('v1_rederivation_raw.json'))
def sha(p):
    return hashlib.sha256(open(p,'rb').read()).hexdigest()
L = []
w = L.append
w("# V1 BLIND RE-DERIVATION -- TASK-20260904-a7eead (EXP-PFDR-20ee58)")
w("# Written at the PHASE A / PHASE B boundary. Produced from the statement in")
w("# ledger/handoffs/TASK-20260904-a7eead.yaml review_plan.blind_rederivation")
w("# alone, with the validator's own code. No path in blind_from was read.")
w("rederivation:")
w("  task_id: TASK-20260904-a7eead")
w("  joint: 'V1 blind re-derivation of deficit(5..8) on the deciding-cell SEM instances'")
w("  experiment_id: EXP-PFDR-20ee58")
w("  hypothesis_id: H-PFDR-9aadc0")
w("  phase_a_started_utc: '2026-09-04T02:12:41Z'")
w("  phase_a_v1_run_utc: ['2026-09-04T02:14:34Z', '2026-09-04T02:14:59Z']")
w("  written_at_utc: '%s'" % datetime.datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ'))
w("  self_sha_note: >-")
w("    A file cannot contain its own sha256; the phase-boundary sha256 OF THIS")
w("    FILE is recorded in validation-report.yaml (phase_boundary.rederivation_sha256)")
w("    and was computed immediately after this file was written and before any")
w("    manifest result block or sidecar was opened. The hashes below pin the")
w("    inputs this file was generated from.")
w("  generated_from:")
for p in ('rederive_v1.py', 'v1_rederivation_raw.json', 'v1_run.log',
          'selfcheck_v1.py', 'selfcheck_v1.log'):
    w("    %s: %s" % (p, sha(p)))
w("  conventions_used:")
w("    ring: >-")
w("      R = F_p[a_{k,i} : k in {1,2,3}, i in {0,1,2}][u] / (a_{k,i}^2 - a_{k,i});")
w("      nine squarefree digit variables, u FREE (all powers allowed). Monomial")
w("      basis: (squarefree 9-bit digit mask) x u^e. Multiplication of digit")
w("      variables is the OR of masks (a^2 -> a).")
w("    grading: 'deg = (number of distinct digit variables) + (u-exponent); total-degree, non-homogeneous'")
w("    p: 4099")
w("    prime_check: 'sympy.isprime(4099) = True'")
w("    leaves: 'x_k = a_{k,0} + 2 a_{k,1} + 4 a_{k,2} (s = 3, digits base 2)'")
w("    S3_formula: >-")
w("      S_3(X1,X2,X3) = (X1 - X2)^2 X3^2 - 2((X1 + X2)(X1 X2 + A) + 2 B) X3")
w("      + (X1 X2 - A)^2 - 4 B (X1 + X2), evaluated in R.")
w("    generators: 'E1 = S_3(x1, x2, u); E2 = S_3(u, x3, x_R) with x_R a constant of F_p. u is NOT substituted.'")
w("    multipliers: 'CUMULATIVE: every monomial m of R with deg m <= D - 4, both generators; zero products dropped and counted'")
w("    columns: 'all monomials of R of total degree <= D (combinatorial count, not the reached support)'")
w("    rank: 'exact rank over F_4099 by the validator''s own prefix-incremental echelon elimination (numpy int64 carrier, modular arithmetic only, no floating point); no import of harness/macaulay_fp'")
w("    koszul: 'koszul(D) = 1 if D >= 8 else 0'")
w("    deficit: 'deficit(D) = rows(D) - rank(Mac_D) - koszul(D)'")
w("  closed_form_counts_independent_of_matrix_build:")
w("    formula_columns: 'columns(D) = sum_{j=0..min(9,D)} C(9,j) * (D - j + 1)'")
w("    formula_rows: 'rows(D) = 2 * columns(D-4) with the same formula, minus zero products'")
w("    values: {5: {columns: 825, multipliers: 11, rows: 22}, 6: {columns: 1291, multipliers: 57, rows: 114}, 7: {columns: 1793, multipliers: 187, rows: 374}, 8: {columns: 2304, multipliers: 443, rows: 886}}")
w("  instances:")
for r in d:
    pd = r['per_degree']
    vec = [pd[str(D)]['deficit'] for D in (5,6,7,8)]
    w("    - curve_seed: %d" % r['curve_seed'])
    w("      target: %d" % r['target'])
    w("      A: %d" % r['A'])
    w("      B: %d" % r['B'])
    w("      x_R: %d" % r['x_R'])
    w("      u_planted_not_substituted: %d" % r['u_planted'])
    w("      deg_E1: %d" % r['degE1'])
    w("      deg_E2: %d" % r['degE2'])
    w("      terms_E1: %d" % r['terms_E1'])
    w("      terms_E2: %d" % r['terms_E2'])
    w("      zero_product_rows: %d" % r['zero_product_rows'])
    w("      koszul_relation_exhibited_and_verified: %s" % str(r['koszul_relation_verified']).lower())
    if 'identical_generator_system_as' in r:
        w("      identical_generator_system_as: '%s'" % r['identical_generator_system_as'])
    w("      per_degree:")
    for D in (5,6,7,8):
        e = pd[str(D)]
        w("        %d: {rows: %d, columns: %d, support_columns_reached: %d, rank: %d, koszul: %d, deficit: %d}"
          % (D, e['rows'], e['columns'], e['support_columns'], e['rank'], e['koszul'], e['deficit']))
    w("      deficit_vector_D5_D8: [%d, %d, %d, %d]" % tuple(vec))
allzero = all(all(r['per_degree'][str(D)]['deficit'] == 0 for D in (5,6,7,8)) for r in d)
w("  summary:")
w("    instances_computed: %d" % len(d))
w("    all_twelve_deficit_vectors_are_0_0_0_0: %s" % str(allzero).lower())
w("    d8_rows_all: 886")
w("    d8_columns_all: 2304")
w("    d8_rank_all: 885")
w("    d8_support_columns_reached_all: 2275")
w("    zero_product_rows_all: 0")
w("    kernel_dimension_at_D8: 1")
w("    kernel_identified: >-")
w("      rows - rank = 1 at D = 8 and the explicit Koszul vector (coefficients of")
w("      E2 on the rows {m E1} minus coefficients of E1 on the rows {m E2}) is")
w("      nonzero and annihilates the matrix, verified per instance; hence the")
w("      kernel is exactly the span of the Koszul relation and deficit 0 means")
w("      'no syzygy beyond the Koszul one', not 'no rows'.")
w("  anti_artifact_self_checks:")
w("    why: 'a deficit of 0 is also what an empty or mis-sized Macaulay space returns; these checks establish the space and the instrument independently of the result'")
w("    column_space_size: 'columns(8) = 2304 from the closed form AND from enumerating the monomial basis; the two agree'")
w("    reached_support: '2275 of 2304 columns are hit by some row; the 29 unreached columns are exactly u^8, u^7, a_i u^7 (9) and the 18 digit-pairs a_i a_j u^6 that no generator supplies (max u-power of a row = 4 (multiplier) + 2 (generator) = 6; the reachable u^6 digit-pairs are the 15 pairs of (x1-x2)^2 plus the 3 pairs of x3^2)'")
w("    positive_control_own_meter: >-")
w("      Two quartics sharing a quadratic factor, F1 = h q1, F2 = h q2 with h, q1,")
w("      q2 random <= quadratics in the digits and u (seed 20260904), have the")
w("      planted non-Koszul syzygy q2 F1 - q1 F2 = 0 at multiplier degree 2. My")
w("      meter returns deficit (0, 1, 11, 56) at D = 5, 6, 7, 8 -- nonzero exactly")
w("      from the predicted degree D = 6 on. The instrument is not blind at this shape.")
w("    negative_control_own_meter: >-")
w("      Two independent random elements of degree <= 4 with dense support in the")
w("      same ring return deficit (0, 0, 0, 0) with rank 885 at D = 8, i.e. the")
w("      Koszul-only baseline, matching the twin.")
w("    scope_of_self_checks: 'these two checks bound MY instrument only; the sensitivity of the PRODUCER meter is joint R2 and is not mine'")
open('rederivation.yaml','w').write("\n".join(L) + "\n")
print("written")
